CREATE OR REPLACE VIEW INV_ITEM_MASTER_TLV AS
SELECT IIM.INVENTORY_ITEM_ID
      ,	IIM.SOB_ID
      ,	IIM.ORG_ID
      , IIM.ITEM_DIVISION_CODE
      ,	IIM.ITEM_CODE
      ,	NVL(IIMT.ITEM_DESCRIPTION, IIM.ITEM_DESCRIPTION)     ITEM_DESCRIPTION
      ,	NVL(IIMT.ITEM_SPECIFICATION, IIM.ITEM_SPECIFICATION) ITEM_SPECIFICATION
      , IIM.CUSTOMER_SITE_ID
      , IIM.CUSTOMER_REV
      , IIM.CUSTOMER_ITEM_CODE
      , IIM.CUSTOMER_ITEM_DESCRIPTION
      , IIM.SALES_PERSON_ID
      ,	ITEM_CATEGORY_CODE
      ,	ITEM_SECTION_CODE
      ,	ITEM_BRANCH_LCODE
      ,	ITEM_LAYER_LCODE
      ,	ITEM_TYPE_LCODE
      ,	ITEM_USE_LCODE
      ,	ITEM_CLASS_LCODE
      ,	SUBSTITUTE_ITEM_ID
      ,	HS_LCODE
      ,	UL_MARK_FLAG
      ,	HALOGEN_FREE_FLAG
      ,	MAKING_DATE_FLAG
      ,	OUT_PRINTING_FLAG
      ,	SMD_FLAG
      ,	KEY_PBA_FLAG
      ,	IMPEDANCE
      ,	NVL(IIMT.REMARK, IIM.REMARK)                         REMARK
      ,	OE_ORDER_FLAG
      ,	OE_DELIVERY_FLAG
      ,	PO_PURCHASING_FLAG
      ,	BOM_GENERATION_FLAG
      ,	INV_ONHAND_FLAG
      ,	INV_INVENTORY_FLAG
      ,	PRIMARY_UOM_CODE
      ,	SECONDARY_UOM_CODE
      ,	UOM_CONVERT_RATE
      ,	STORE_WAREHOUSE_CODE
      ,	STORE_INSPECTION_FLAG
      ,	ISSUE_METHOD_CODE
      ,	INV_AGING_FLAG
      ,	INV_AGING_DAYS
      ,	MAT_MAKER_ID
      , MAT_MAKER_ITEM_DESC
      ,	MAT_LAYER
      ,	MAT_WIDTH
      ,	MAT_LENGTH
      ,	MAT_THICKNESS
      ,	MAT_PI_THICKNESS
      ,	MAT_PI_TYPE_LCODE
      ,	MAT_COPPER_THICKNESS_L
      ,	MAT_COPPER_THICKNESS_R
      ,	MAT_COPPER_TYPE_LCODE
      ,	MAT_FILM_THICKNESS
      ,	MAT_FILM_TYPE_LCODE
      ,	MAT_ADHESIVE_THICKNESS
      ,	MAT_ADHESIVE_TYPE_LCODE
      ,	MAT_PO_POLICY_CODE
      ,	MAT_MIN_QTY
      ,	MAT_MAX_QTY
      ,	MAT_SAFETY_QTY
      , IIM.MAT_MIN_ORDER_QTY
      ,	EFFECTIVE_DATE_FR
      ,	EFFECTIVE_DATE_TO
      ,	ENABLED_FLAG
      ,	NVL(IIMT.ATTRIBUTE_A, IIM.ATTRIBUTE_A)                ATTRIBUTE_A
      ,	NVL(IIMT.ATTRIBUTE_B, IIM.ATTRIBUTE_B)                ATTRIBUTE_B
      ,	NVL(IIMT.ATTRIBUTE_C, IIM.ATTRIBUTE_C)                ATTRIBUTE_C
      ,	NVL(IIMT.ATTRIBUTE_D, IIM.ATTRIBUTE_D)                ATTRIBUTE_D
      ,	NVL(IIMT.ATTRIBUTE_E, IIM.ATTRIBUTE_E)                ATTRIBUTE_E
      ,	NVL(IIMT.ATTRIBUTE_F, IIM.ATTRIBUTE_F)                ATTRIBUTE_F
      ,	NVL(IIMT.ATTRIBUTE_G, IIM.ATTRIBUTE_G)                ATTRIBUTE_G
      ,	NVL(IIMT.ATTRIBUTE_H, IIM.ATTRIBUTE_H)                ATTRIBUTE_H
      ,	NVL(IIMT.ATTRIBUTE_1, IIM.ATTRIBUTE_1)                ATTRIBUTE_1
      ,	NVL(IIMT.ATTRIBUTE_2, IIM.ATTRIBUTE_2)                ATTRIBUTE_2
      ,	NVL(IIMT.ATTRIBUTE_3, IIM.ATTRIBUTE_3)                ATTRIBUTE_3
      ,	NVL(IIMT.ATTRIBUTE_4, IIM.ATTRIBUTE_4)                ATTRIBUTE_4
      ,	NVL(IIMT.ATTRIBUTE_5, IIM.ATTRIBUTE_5)                ATTRIBUTE_5
      ,	NVL(IIMT.ATTRIBUTE_6, IIM.ATTRIBUTE_6)                ATTRIBUTE_6
      ,	NVL(IIMT.ATTRIBUTE_7, IIM.ATTRIBUTE_7)                ATTRIBUTE_7
      ,	IIM.CREATION_DATE
      ,	IIM.CREATED_BY
      ,	IIM.LAST_UPDATE_DATE
      ,	IIM.LAST_UPDATED_BY
      , IIM.TEMPLATE_FLAG
      , IIM.MULTI_LEVEL_WORKING_UOM_FLAG
      , IIM.SHIP_TO_CUST_SITE_ID
      , IIM.ITEM_NET_CODE
      , IIM.ITEM_NET_REV
  FROM INV_ITEM_MASTER     IIM
     , INV_ITEM_MASTER_TL  IIMT
 WHERE IIMT.INVENTORY_ITEM_ID(+) = IIM.INVENTORY_ITEM_ID
   AND IIMT.LANG_CODE(+)         = USERENV_G.GET_TERRITORY_S_F;
