-- 반제품창고 재고실사 : PAGE SKIP => 창고, LOC 소계
CREATE OR REPLACE VIEW INV_SUB_ITEM_ONHAND_V1
AS
SELECT IIO.SOB_ID
     , IIO.ORG_ID
     , IWH.WAREHOUSE_CODE -- 창고코드
     , IWH.WAREHOUSE_NAME -- 창고명
     , IWL.LOCATION_CODE -- LOC코드
     , IWL.LOCATION_NAME --LOC명
     , IIM.ITEM_CODE -- 품목코드
     , IIM.ITEM_DESCRIPTION -- 품목명
     , IIO.UOM_CODE -- 단위
     , SUM(IIO.ONHAND_QTY) AS ONHAND_QTY -- 재고량
  FROM INV_ITEM_ONHAND    IIO
     , INV_WAREHOUSE      IWH
     , INV_WH_LOCATION    IWL
     , INV_ITEM_MASTER    IIM
     , SDM_ITEM_STRUCTURE SIS
 WHERE IIO.WAREHOUSE_ID      = IWH.WAREHOUSE_ID
   AND IIO.LOCATION_ID       = IWL.WH_LOCATION_ID
   AND IIO.INVENTORY_ITEM_ID = IIM.INVENTORY_ITEM_ID
   AND IIO.BOM_ITEM_ID       = SIS.SG_BOM_ITEM_ID
/*   AND IIO.SOB_ID            = 20
   AND IIO.ORG_ID            = 201*/
   AND IWH.SG_WIP_WAREHOUSE  = 'Y'
 GROUP BY IIO.SOB_ID
        , IIO.ORG_ID
        , IWH.WAREHOUSE_CODE
        , IWH.WAREHOUSE_NAME
        , IWL.LOCATION_CODE
        , IWL.LOCATION_NAME
        , IIM.ITEM_CODE
        , IIM.ITEM_DESCRIPTION
        , IIO.UOM_CODE
 HAVING SUM(IIO.ONHAND_QTY) <> 0
 ORDER BY IWH.WAREHOUSE_CODE
        , IWL.LOCATION_CODE
        , IIM.ITEM_CODE
