-- 자재재고실사리스트 :  집계 = > 제조사
SELECT IWH.WAREHOUSE_CODE -- 창고코드
     , IWH.WAREHOUSE_NAME -- 창고명
     , IWL.LOCATION_CODE -- LOC코드
     , IWL.LOCATION_NAME -- LOC명
     , IIC.DESCRIPTION -- 범주
     , ELE.ENTRY_DESCRIPTION AS SUMMARY_GROUP -- 중분류
     , IIS.DESCRIPTION -- 소분류
     , IIM.ITEM_CODE -- 품목코드
     , IIM.ITEM_DESCRIPTION -- 품목명
     , IMK.MAKER_CODE -- 제조사코드
     , IMK.MAKER_DESCRIPTION -- 제조사명
     , IIO.UOM_CODE -- 단위
     , SUM(IIO.ONHAND_QTY) AS ONHAND_QTY --재고량
     , NULL AS ACTUAL_QTY -- 실사량
  FROM INV_ITEM_ONHAND        IIO
     , INV_WAREHOUSE          IWH
     , INV_WH_LOCATION        IWL
     , INV_ITEM_MASTER        IIM
     , INV_ITEM_CATEGORY      IIC
     , INV_ITEM_SECTION       IIS
     , EAPP_LOOKUP_ENTRY_TLV  ELE
     , INV_ITEM_MAKER         IMK
 WHERE IIO.WAREHOUSE_ID         = IWH.WAREHOUSE_ID
   AND IIO.LOCATION_ID          = IWL.WH_LOCATION_ID
   AND IIO.INVENTORY_ITEM_ID    = IIM.INVENTORY_ITEM_ID
   AND IIM.ITEM_CATEGORY_CODE   = IIC.ITEM_CATEGORY_CODE
   AND IIM.SOB_ID               = IIC.SOB_ID
   AND IIM.ORG_ID               = IIC.ORG_ID
   AND IIM.ITEM_SECTION_CODE    = IIS.ITEM_SECTION_CODE
   AND IIM.SOB_ID               = IIS.SOB_ID
   AND IIM.ORG_ID               = IIS.ORG_ID
   AND IIS.SUMMARY_GROUP_LCODE  = ELE.ENTRY_CODE(+)
   AND IIS.SOB_ID               = ELE.SOB_ID(+)
   AND IIS.ORG_ID               = ELE.ORG_ID(+)
   AND ELE.LOOKUP_TYPE          = 'ITEM_SUMMARY_GROUP' 
   AND IIM.MAT_MAKER_ID         = IMK.MAKER_ID
   AND IIO.SOB_ID               = 20
   AND IIO.ORG_ID               = 201
   AND (IWH.MAT_MAIN_WAREHOUSE  = 'Y') -- 작업공정 현장창고
 GROUP BY IWH.WAREHOUSE_CODE
        , IWH.WAREHOUSE_NAME
        , IWL.LOCATION_CODE
        , IWL.LOCATION_NAME
        , ELE.ENTRY_CODE
        , ELE.ENTRY_DESCRIPTION
        , IMK.MAKER_CODE
        , IMK.MAKER_DESCRIPTION
        , IIC.DESCRIPTION        
        , IIS.DESCRIPTION
        , IIM.ITEM_CODE
        , IIM.ITEM_DESCRIPTION        
        , IIO.UOM_CODE
 HAVING SUM(IIO.ONHAND_QTY) <> 0
 ORDER BY IWH.WAREHOUSE_CODE
        , IWL.LOCATION_CODE
        , ELE.ENTRY_CODE
        , IMK.MAKER_CODE
        , IIM.ITEM_CODE
        , IMK.MAKER_CODE
        , IIC.DESCRIPTION        
        , IIS.DESCRIPTION
        , IIM.ITEM_CODE
