SELECT *
  FROM FI_ASSET_MASTER_CG X
 WHERE X.ASSET_CODE       = 'B000000311'
 ;
 
SELECT *
  FROM FI_ASSET_DPR_HISTORY_CG DH
 WHERE DH.ASSET_ID             = 775
 ; 
 
SELECT *
  FROM FI_ASSET_HISTORY_CG AH
 WHERE AH.ASSET_ID         = 775
 ;

-- ªË¡¶ -- 
DELETE 
  FROM FI_ASSET_HISTORY_CG AH
 WHERE AH.ASSET_ID         = 775
 ;

DELETE 
  FROM FI_ASSET_MASTER_CG X
 WHERE X.ASSET_CODE       = 'B000000311'
 ;
 
DELETE 
  FROM FI_ASSET_DPR_HISTORY_CG DH
 WHERE DH.ASSET_ID             = 775
 ; 
 

