CREATE OR REPLACE VIEW HRM_ALLOWANCE_SELF_DEV_V AS
SELECT HC.COMMON_ID AS SELF_DEV_ID
     , HC.CODE AS SELF_DEV_CODE
     , HC.CODE_NAME AS SELF_DEV_NAME
     , HC.VALUE1 AS PAY_TYPE
     , TO_NUMBER(HC.VALUE2) AS LONG_YEAR_FR
     , TO_NUMBER(HC.VALUE3) AS LONG_YEAR_TO
     , TO_NUMBER(HC.VALUE4) AS ALLOWANCE_AMOUNT 
     , HC.DEFAULT_FLAG
     , HC.SORT_NUM
     , HC.DESCRIPTION
     , HC.ENABLED_FLAG
     , HC.EFFECTIVE_DATE_FR
     , HC.EFFECTIVE_DATE_TO
     , HC.SOB_ID
     , HC.ORG_ID
  FROM HRM_COMMON_TLV HC
 WHERE HC.GROUP_CODE              = 'ALLOWANCE_SELF_DEV';
