SELECT *
  FROM FI_SLIP_LINE SL
WHERE SL.SOB_ID           = 20
;

SELECT *
  FROM FI_ACCOUNT_SET
;

SELECT *
  FROM FI_ACCOUNT_GROUP AG
WHERE AG.ACCOUNT_SET_ID         = 10
FOR UPDATE
;

SELECT *
  FROM FI_ACCOUNT_CONTROL_ITEM CI
WHERE CI.SOB_ID                = 10
FOR UPDATE
;

SELECT *
  FROM FI_ACCOUNT_CONTROL AC
WHERE AC.SOB_ID           = 10
  AND AC.ACCOUNT_SET_ID   = 10  
FOR UPDATE  
;

SELECT MAX(AG.ACCOUNT_GROUP_ID)
  FROM FI_ACCOUNT_GROUP AG
;

SELECT MAX(AC.ACCOUNT_CONTROL_ID)
  FROM FI_ACCOUNT_CONTROL AC
;

select *
  from fi_common x
where x.group_code        = 'MANAGEMENT_CODE'
  AND X.SOB_ID            = 10
--FOR UPDATE
;
