SELECT DECODE(GROUPING(SX1.SUPPLIER_CODE), 1, TO_CHAR(NULL), SX1.VAT_TYPE) AS VAT_TYPE
     , CASE
         WHEN GROUPING(SX1.VAT_TYPE) = 1 THEN EAPP_MESSAGE_G.RETURN_TEXT_F(USERENV_G.GET_TERRITORY_S_F, 'EAPP_10045', NULL)
         WHEN GROUPING(SX1.SUPPLIER_CODE) = 1 THEN EAPP_MESSAGE_G.RETURN_TEXT_F(USERENV_G.GET_TERRITORY_S_F, 'EAPP_10046', NULL)
         ELSE SX1.VAT_TYPE_NAME
       END AS VAT_TYPE_NAME
     , SX1.VAT_REASON_NAME
     , SX1.SUPPLIER_CODE
     , SX1.SUPPLIER_NAME
     , SX1.TAX_REG_NO AS TAX_REG_NO
     , SX1.VAT_ISSUE_DATE
     , SX1.SLIP_DATE
     , SUM(SX1.GL_AMOUNT) AS GL_AMOUNT
     , SUM(SX1.VAT_AMOUNT) AS VAT_AMOUNT
     , SUM(SX1.TOTAL_AMOUNT) TOTAL_AMOUNT          
     , SX1.CREDITCARD_CODE
     , SX1.CARD_NUM
     , SX1.CARD_NAME
     , SX1.CASH_RECEIPT_NUM
     , SX1.REMARK
     , NULL AS MANAGEMENT1                           -- °èÁÂ¹øÈ£ OR CODE °ª.
     , SX1.CURRENCY_CODE
     , SX1.EXCHANGE_RATE
     , SX1.GL_CURRENCY_AMOUNT
     , SX1.SLIP_NUM
     , SX1.HEADER_INTERFACE_ID           
  FROM (SELECT DECODE(VM.VAT_TYPE_AP, NULL, '2', '1') AS VAT_GUBUN
             , CASE
                 WHEN VM.VAT_TYPE_AP IS NULL THEN FI_COMMON_G.GET_ID_F('VAT_TYPE_AR', 'CODE = ''' || VM.VAT_TYPE_AR || '''', VM.SOB_ID)
                 ELSE FI_COMMON_G.GET_ID_F('VAT_TYPE_AP', 'CODE = ''' || VM.VAT_TYPE_AP || '''', VM.SOB_ID)
               END AS VAT_TYPE_ID
             , NVL(VM.VAT_TYPE_AP, VM.VAT_TYPE_AR) AS VAT_TYPE
             , CASE
                 WHEN VM.VAT_TYPE_AP IS NULL THEN FI_COMMON_G.CODE_NAME_F('VAT_TYPE_AR', VM.VAT_TYPE_AR, VM.SOB_ID)
                 ELSE FI_COMMON_G.CODE_NAME_F('VAT_TYPE_AP', VM.VAT_TYPE_AP, VM.SOB_ID)
               END AS VAT_TYPE_NAME
             , FI_COMMON_G.CODE_NAME_F('VAT_REASON', VM.VAT_REASON_CODE, VM.SOB_ID) AS VAT_REASON_NAME
             , SC.SUPP_CUST_ID AS SUPPLIER_ID
             , VM.SUPPLIER_CODE
             , SC.SUPP_CUST_NAME AS SUPPLIER_NAME
             , SC.TAX_REG_NO 
             , VM.VAT_ISSUE_DATE
             , VM.SLIP_DATE
             , NVL(VM.GL_AMOUNT, 0) AS GL_AMOUNT
             , NVL(VM.VAT_AMOUNT, 0) AS VAT_AMOUNT
             , NVL(VM.GL_AMOUNT, 0) + NVL(VM.VAT_AMOUNT, 0) AS TOTAL_AMOUNT
             , VM.CREDITCARD_CODE
             , CC.CARD_NUM
             , CC.CARD_NAME
             , VM.CASH_RECEIPT_NUM
             , VM.REMARK
             , VM.CURRENCY_CODE
             , VM.EXCHANGE_RATE
             , VM.GL_CURRENCY_AMOUNT
             , VM.SLIP_NUM
             , VM.HEADER_INTERFACE_ID
             , VM.TAX_CODE
          FROM (SELECT SL.HEADER_INTERFACE_ID
                     , SL.SOB_ID
                     , FI_SLIP_INTERFACE_G.SLIP_IF_ITEM_VALUE_F(SL.LINE_INTERFACE_ID, 'TAX_CODE', SL.SOB_ID) AS TAX_CODE
                     , FI_SLIP_INTERFACE_G.SLIP_IF_ITEM_VALUE_F(SL.LINE_INTERFACE_ID, 'VAT_TYPE_AP', SL.SOB_ID) AS VAT_TYPE_AP
                     , FI_SLIP_INTERFACE_G.SLIP_IF_ITEM_VALUE_F(SL.LINE_INTERFACE_ID, 'VAT_TYPE_AR', SL.SOB_ID) AS VAT_TYPE_AR
                     , FI_SLIP_INTERFACE_G.SLIP_IF_ITEM_VALUE_F(SL.LINE_INTERFACE_ID, 'VAT_REASON', SL.SOB_ID) AS VAT_REASON_CODE
                     , FI_SLIP_INTERFACE_G.SLIP_IF_ITEM_VALUE_F(SL.LINE_INTERFACE_ID, 'CUSTOMER', SL.SOB_ID) AS SUPPLIER_CODE
                     , TO_DATE(FI_SLIP_INTERFACE_G.SLIP_IF_ITEM_VALUE_F(SL.LINE_INTERFACE_ID, 'ISSUE_DATE', SL.SOB_ID), 'YYYY-MM-DD') AS VAT_ISSUE_DATE
                     , SL.SLIP_DATE
                     , TO_NUMBER(FI_SLIP_INTERFACE_G.SLIP_IF_ITEM_VALUE_F(SL.LINE_INTERFACE_ID, 'SUPPLY_AMOUNT', SL.SOB_ID)) AS GL_AMOUNT
                     , NVL(SL.GL_AMOUNT, 0) AS VAT_AMOUNT
                     , FI_SLIP_INTERFACE_G.SLIP_IF_ITEM_VALUE_F(SL.LINE_INTERFACE_ID, 'CREDIT_CARD', SL.SOB_ID) AS CREDITCARD_CODE
                     , FI_SLIP_INTERFACE_G.SLIP_IF_ITEM_VALUE_F(SL.LINE_INTERFACE_ID, 'CASH_RECEIPT', SL.SOB_ID) AS CASH_RECEIPT_NUM
                     , SL.REMARK
                     , SL.CURRENCY_CODE
                     , SL.EXCHANGE_RATE
                     , SL.GL_CURRENCY_AMOUNT
                     , SL.SLIP_NUM
                  FROM FI_SLIP_LINE_INTERFACE SL
                    , FI_ACCOUNT_CONTROL AC
                WHERE SL.ACCOUNT_CONTROL_ID      = AC.ACCOUNT_CONTROL_ID                  
                  AND SL.SOB_ID                  = &W_SOB_ID
                  AND SL.CONFIRM_YN              = 'N'
                  AND AC.VAT_ENABLED_FLAG        = 'Y'
                ) VM
            , FI_SUPP_CUST_V SC
            , FI_CREDIT_CARD CC
        WHERE VM.SUPPLIER_CODE            = SC.SUPP_CUST_CODE
          AND VM.SOB_ID                   = SC.SOB_ID  
          AND VM.CREDITCARD_CODE          = CC.CARD_CODE(+)
          AND VM.SOB_ID                   = CC.SOB_ID(+)
          AND VM.VAT_ISSUE_DATE           BETWEEN &W_ISSUE_DATE_FR AND &W_ISSUE_DATE_TO
       ) SX1
WHERE SX1.TAX_CODE                = &W_TAX_CODE
  AND SX1.VAT_GUBUN               = NVL(&W_VAT_CLASS, SX1.VAT_GUBUN)
  AND SX1.SUPPLIER_ID             = NVL(&W_SUPPLIER_ID, SX1.SUPPLIER_ID)
  AND SX1.VAT_TYPE_ID             = NVL(&W_VAT_TYPE_ID, SX1.VAT_TYPE_ID)
GROUP BY ROLLUP ((SX1.VAT_TYPE
     , SX1.VAT_TYPE_NAME)
     , (SX1.VAT_REASON_NAME
     , SX1.SUPPLIER_CODE
     , SX1.SUPPLIER_NAME
     , SX1.TAX_REG_NO 
     , SX1.VAT_ISSUE_DATE
     , SX1.SLIP_DATE
     , SX1.CREDITCARD_CODE
     , SX1.CARD_NUM
     , SX1.CARD_NAME
     , SX1.CASH_RECEIPT_NUM
     , SX1.REMARK
     , SX1.CURRENCY_CODE
     , SX1.EXCHANGE_RATE
     , SX1.GL_CURRENCY_AMOUNT
     , SX1.SLIP_NUM
     , SX1.HEADER_INTERFACE_ID))  
;
