CREATE OR REPLACE VIEW HRM_ALLOWANCE_HOLIDAY_V AS
SELECT HC.COMMON_ID AS ALLOWANCE_HOLIDAY_ID
     , HC.CODE AS ALLOWANCE_HOLIDAY
     , HC.CODE_NAME AS ALLOWANCE_HOLIDAY_NAME
     , HC.SYSTEM_FLAG
     , HC.CODE_LENGTH
     , HC.VALUE1 AS JOB_CATEGORY_CODE
     , TO_NUMBER(NVL(HC.VALUE2, 0)) AS START_TIME
     , TO_NUMBER(NVL(HC.VALUE3, 0)) AS END_TIME
     , TO_NUMBER(NVL(HC.VALUE4, 0)) AS ALLOWANCE_AMOUNT
     , HC.VALUE5
     , HC.VALUE6
     , HC.VALUE7
     , HC.VALUE8
     , HC.VALUE9
     , HC.VALUE10
     , HC.DEFAULT_FLAG
     , HC.SORT_NUM
     , HC.DESCRIPTION
     , HC.ENABLED_FLAG
     , HC.EFFECTIVE_DATE_FR
     , HC.EFFECTIVE_DATE_TO
     , HC.SOB_ID
     , HC.ORG_ID
  FROM HRM_COMMON_TLV HC
 WHERE HC.GROUP_CODE              = 'ALLOWANCE_HOLIDAY';
