SELECT SL.ACCOUNT_CONTROL_ID
     , SL.ACCOUNT_CODE
     , CC.CC_CODE
     , DECODE(SL.ACCOUNT_DR_CR, '1', SL.GL_AMOUNT, 0) AS DR_AMOUNT
     , DECODE(SL.ACCOUNT_DR_CR, '2', SL.GL_AMOUNT, 0) AS CR_AMOUNT
     , SL.REMARK
  FROM FI_SLIP_LINE SL
    , FI_SLIP_HEADER SH    
    , FI_ACCOUNT_CONTROL AC
    , (-- 원가코드.
      SELECT MI.SLIP_LINE_ID
           , MI.MANAGEMENT_VALUE AS CC_CODE
        FROM FI_SLIP_MANAGEMENT_ITEM MI
          , FI_MANAGEMENT_CODE_V MC
      WHERE MI.MANAGEMENT_ID            = MC.MANAGEMENT_ID
        AND MC.LOOKUP_TYPE              = 'COSTCENTER'
      ) CC
WHERE SL.SLIP_HEADER_ID           = SH.SLIP_HEADER_ID
  AND SL.ACCOUNT_CONTROL_ID       = AC.ACCOUNT_CONTROL_ID
  AND SL.SLIP_LINE_ID             = CC.SLIP_LINE_ID
  AND SH.GL_DATE                  BETWEEN &W_START_DATE AND &W_END_DATE  
  AND SL.SOB_ID                   = &W_SOB_ID
  AND SL.CONFIRM_YN               = 'Y'
  AND SH.SLIP_TYPE                <> 'CL' -- 결산전표 제외.
  AND AC.ACCOUNT_CODE             BETWEEN &W_ACCOUNT_CODE_FR AND &W_ACCOUNT_CODE_TO  
;

