INSERT INTO HRM_COMMON 
    ( COMMON_ID, GROUP_CODE, CODE, CODE_NAME
    , VALUE1, VALUE2, VALUE3, VALUE4, VALUE5, VALUE6, VALUE7, VALUE8, VALUE9, VALUE10
    , DEFAULT_FLAG
    , SORT_NUM, DESCRIPTION, ENABLED_FLAG, EFFECTIVE_DATE_FR, EFFECTIVE_DATE_TO
    , SOB_ID, ORG_ID
    , CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY)
SELECT HRM_COMMON_S1.Nextval
    , HC.GROUP_CODE
    , HC.CODE
    , HC.CODE_NAME    
    , HC.VALUE1
    , HC.VALUE2
    , HC.VALUE3
    , HC.VALUE4
    , HC.VALUE5
    , HC.VALUE6
    , HC.VALUE7
    , HC.VALUE8
    , HC.VALUE9
    , HC.VALUE10
    , HC.DEFAULT_FLAG
    , HC.SORT_NUM
    , HC.DESCRIPTION
    , HC.ENABLED_FLAG
    , HC.EFFECTIVE_DATE_FR
    , HC.EFFECTIVE_DATE_TO
    , 20 AS SOB_ID
    , 201 AS ORG_ID
    , TO_DATE('2010-11-15 15:10:01', 'YYYY-MM-DD HH24:MI:SS')
    , -1
    , TO_DATE('2010-11-15 15:10:01', 'YYYY-MM-DD HH24:MI:SS')
    , -1
FROM HRM_COMMON HC
;

SELECT HC.COMMON_ID
    , HC.GROUP_CODE
    , HC.CODE
    , HC.CODE_NAME    
    , HC.VALUE1
    , HC.VALUE2
    , HC.VALUE3
    , HC.VALUE4
    , HC.VALUE5
    , HC.VALUE6
    , HC.VALUE7
    , HC.VALUE8
    , HC.VALUE9
    , HC.VALUE10
    , HC.DEFAULT_FLAG
    , HC.SORT_NUM
    , HC.DESCRIPTION
    , HC.ENABLED_FLAG
    , HC.EFFECTIVE_DATE_FR
    , HC.EFFECTIVE_DATE_TO
    , HC.SOB_ID
    , HC.ORG_ID
    , HC.CREATION_DATE
    , HC.CREATED_BY
    , HC.LAST_UPDATE_DATE
    , HC.LAST_UPDATED_BY
FROM HRM_COMMON HC
WHERE HC.SOB_ID = 20
  AND HC.ORG_ID = 201
;
