/******************************************************************************/
/* Project      : FPCB ERP
/* Module       : HR
/* Program Name : HRD_WORK_CALENDAR_SET
/* Description  : 근무계획표 생성 기준정보.
/*
/* Reference by :
/* Program History
/*------------------------------------------------------------------------------
/*   Date       In Charge          Description
/*------------------------------------------------------------------------------
/* 07-JUN-2010  Jeon Ho Su          Initialize
/******************************************************************************/
CREATE TABLE HRD_WORK_CALENDAR_SET
( CORP_ID                         NUMBER        NOT NULL
, WORK_PERIOD                     VARCHAR2(7)   NOT NULL
, SOB_ID                          NUMBER        NOT NULL
, ORG_ID                          NUMBER        NOT NULL
, WORK_DATE_FR                    DATE          NOT NULL
, WORK_DATE_TO                    DATE          NOT NULL
, WORK_TYPE_ID                    NUMBER        NOT NULL
, WORK_DATE                       DATE          NOT NULL
, HOLY_TYPE                       VARCHAR2(4)   NOT NULL
, WEEK_DATE_FR                    DATE          NOT NULL
, WEEK_DATE_TO                    DATE          NOT NULL
, HOLIDAY_YN                      VARCHAR2(1)   DEFAULT 'N'
, DESCRIPTION                     VARCHAR2(150)
, CREATION_DATE                   DATE          NOT NULL
, CREATED_BY                      NUMBER        NOT NULL
, LAST_UPDATE_DATE                DATE          NOT NULL
, LAST_UPDATED_BY                 NUMBER        NOT NULL
) TABLESPACE FCM_TS_DATA;

-- Add comments to the columns 
COMMENT ON TABLE HRD_WORK_CALENDAR_SET IS '근무계획표 생성 기준';
COMMENT ON COLUMN HRD_WORK_CALENDAR_SET.CORP_ID IS '업체ID';
COMMENT ON COLUMN HRD_WORK_CALENDAR_SET.WORK_PERIOD IS '근무년월';
COMMENT ON COLUMN HRD_WORK_CALENDAR_SET.WORK_TYPE_ID IS '교대유형ID';
COMMENT ON COLUMN HRD_WORK_CALENDAR_SET.CREATED_METHOD IS '생성방법(A-ALL,P-PERSON,D-DEPARTMENT) ';
COMMENT ON COLUMN HRD_WORK_CALENDAR_SET.SEQ IS '순서';
COMMENT ON COLUMN HRD_WORK_CALENDAR_SET.HOLY_TYPE IS '근무타입(-1:이월수)';
COMMENT ON COLUMN HRD_WORK_CALENDAR_SET.DAY_COUNT IS '적용 일수';
COMMENT ON COLUMN HRD_WORK_CALENDAR_SET.WORK_DATE_FR IS '적용 시작일자';
COMMENT ON COLUMN HRD_WORK_CALENDAR_SET.WORK_DATE_TO IS '적용 종료일자';
COMMENT ON COLUMN HRD_WORK_CALENDAR_SET.DESCRIPTION IS '비고';
COMMENT ON COLUMN HRD_WORK_CALENDAR_SET.CREATION_DATE  IS '생성일자';
COMMENT ON COLUMN HRD_WORK_CALENDAR_SET.CREATED_BY IS '생성자';
COMMENT ON COLUMN HRD_WORK_CALENDAR_SET.LAST_UPDATE_DATE IS '최종수정일자';
COMMENT ON COLUMN HRD_WORK_CALENDAR_SET.LAST_UPDATED_BY IS '최종수정자';

-- CREATE INDEX.
CREATE UNIQUE INDEX HRD_WORK_CALENDAR_SET_U1 ON HRD_WORK_CALENDAR_SET(WORK_PERIOD, WORK_TYPE_ID, CREATED_METHOD, SEQ, SOB_ID, ORG_ID) TABLESPACE FCM_TS_IDX;
CREATE INDEX HRD_WORK_CALENDAR_SET_N1 ON HRD_WORK_CALENDAR_SET(WORK_PERIOD, WORK_TYPE_ID, SOB_ID, ORG_ID) TABLESPACE FCM_TS_IDX;
CREATE INDEX HRD_WORK_CALENDAR_SET_N2 ON HRD_WORK_CALENDAR_SET(WORK_PERIOD, WORK_TYPE_ID, CREATED_METHOD, WORK_DATE_FR, WORK_DATE_TO, SEQ, SOB_ID, ORG_ID) TABLESPACE FCM_TS_IDX;

-- ANALYZE.
ANALYZE TABLE HRD_WORK_CALENDAR_SET COMPUTE STATISTICS;
ANALYZE INDEX HRD_WORK_CALENDAR_SET_U1 COMPUTE STATISTICS;
ANALYZE INDEX HRD_WORK_CALENDAR_SET_N1 COMPUTE STATISTICS;
ANALYZE INDEX HRD_WORK_CALENDAR_SET_N2 COMPUTE STATISTICS;
