-- 근태 내역 조회.
SELECT OT.MONTH_TOTAL_ITEM
     , OT.OT_TYPE_NAME
     , 'HRD_MONTH_TOTAL_OT' AS TABLE_NAME
     , OT.OT_TYPE AS COLUMN_CODE
  FROM HRM_OT_TYPE_V OT
 WHERE OT.ENABLED_FLAG            = 'Y'
   AND OT.EFFECTIVE_DATE_FR       <= TRUNC(GET_LOCAL_DATE(OT.SOB_ID))
   AND (OT.EFFECTIVE_DATE_TO IS NULL OR OT.EFFECTIVE_DATE_TO >= TRUNC(GET_LOCAL_DATE(OT.SOB_ID)))
UNION ALL
SELECT MTI.MONTH_TOTAL_ITEM
     , MTI.MONTH_TOTAL_ITEM_NAME
     , MTI.TABLE_NAME
     , MTI.COLUMN_CODE
  FROM HRM_MONTH_TOTAL_ITEM_V MTI
 WHERE MTI.ENABLED_FLAG           = 'Y'
   AND MTI.EFFECTIVE_DATE_FR      <= TRUNC(GET_LOCAL_DATE(MTI.SOB_ID))
   AND (MTI.EFFECTIVE_DATE_TO IS NULL OR MTI.EFFECTIVE_DATE_TO >= TRUNC(GET_LOCAL_DATE(MTI.SOB_ID)))
ORDER BY MONTH_TOTAL_ITEM   
;
