SELECT SH.ATIME
     , SH.ID_SEQ
     , SH.MASTER_A
     , HDV.DEVICE_NAME
     , SH.STATE
     , SSV.SECOM_STATUS_NAME
     , SSV.CHECK_FLAG
     , SH.CONTENT_A
     , SH.A_DATE
     , SH.A_TIME
     , SH.CONTENT_A
     , SH.PERSON_NUM
     , SH.JUMIN_NUM
     , PM.PERSON_NUM
     , PM.NAME     
     
     , HDV.DEVICE_ID
     , PM.PERSON_ID
     , SSV.CHECK_FLAG
     , TO_DATE(SH.ATIME, 'YYYY-MM-DD HH24:MI:SS') AS CHECK_DATE_TIME
     , TO_DATE(SH.A_DATE, 'YYYY-MM-DD') AS CHECK_DATE
     , TO_CHAR(TO_DATE(SH.ATIME, 'YYYY-MM-DD HH24:MI:SS'), 'HH24:MI') AS CHECK_TIME
/*     , 'I' AS CREATED_FLAG
     --, NULL AS CARD_NUM
     , GET_LOCAL_DATE(PM.SOB_ID) AS CREATION_DATE
     , -1
     , GET_LOCAL_DATE(PM.SOB_ID) AS LAST_UPDATE_DATE
     , -1*/
  FROM HRD_SECOM_HISTORY SH 
    , HRM_DEVICE_V HDV
    , HRM_SECOM_STATUS_V SSV
    , HRM_PERSON_MASTER PM
 WHERE SH.MASTER_A                = HDV.SOURCE_DEVICE_CODE
   AND SH.STATE                   = SSV.SECOM_STATUS
   AND SH.JUMIN_NUM               = REPLACE(PM.REPRE_NUM, '-', '')
   AND SH.STATE                   LIKE 'W%'
;

UPDATE   hrd_secoM_history t
 SET T.A_DATE = SUBSTR(T.ATIME, 1, 8)
   , T.A_TIME = SUBSTR(T.ATIME, 9, 6)
   , T.JUMIN_NUM = CASE 
                      WHEN SUBSTR(T.CONTENT_A, 1, 1) = '0' THEN NULL
                      ELSE SUBSTR(T.CONTENT_A, 1, 13)
                    END 
;

UPDATE   hrd_secoM_history t
 SET T.CREATION_DATE = TO_DATE('2010-11-10 18:29:00', 'YYYY-MM-DD HH24:MI:SS')
   , T.CREATED_BY    = -1
;

SELECT DISTINCT X.STATE
  FROM HRD_SECOM_HISTORY X
 WHERE X.CONTENT_A LIKE '%¹é°¡¿µ%'
 ;
 
SELECT *
  FROM HRD_SECOM_HISTORY SH
 WHERE SUBSTR(SH.ATIME, 1, 8)     BETWEEN TO_CHAR(&W_START_DATE, 'YYYYMMDD') AND TO_CHAR(&W_END_DATE, 'YYYYMMDD')
   AND EXISTS ( SELECT 'X'
                  FROM HRM_SECOM_STATUS_V SSV
                 WHERE SSV.SECOM_STATUS   = SH.STATE
                   AND SSV.MODULE_TYPE    = NVL(&W_MODULE_TYPE, SSV.MODULE_TYPE)
              )
;
