SELECT DECODE(GROUPING(RR.RESERVE_YYYYMM), 1, 'Total', RR.RESERVE_YYYYMM) AS RESERVE_YYYYMM
     , DECODE(GROUPING(RR.RESERVE_YYYYMM), 1, TO_CHAR(COUNT(PM.PERSON_ID), 'FM999,999') || ' Person', PM.DISPLAY_NAME) AS DISPLAY_NAME
     , COUNT(PM.PERSON_ID) AS PERSON_COUNT
     , RR.DEPT_ID
     , HRM_DEPT_MASTER_G.DEPT_NAME_F(RR.DEPT_ID) AS DEPT_NAME
     , HRM_COMMON_G.CODE_NAME_F('EMPLOYE_TYPE', PM.EMPLOYE_TYPE, PM.SOB_ID, PM.ORG_ID) AS EMPLOYE_TYPE_NAME
     , NVL(PM.ORI_JOIN_DATE, PM.JOIN_DATE) AS JOIN_DATE
     , PM.EXPIRE_DATE
     , PM.RETIRE_DATE
     , RR.COST_CENTER_ID AS COST_CENTER_CODE
     , '' AS COST_CENTER_NAME
     , SUM(RR.PREVIOUS_RETIRE_AMOUNT) AS PREVIOUS_RETIRE_AMOUNT
     , SUM(RR.THIS_RETIRE_AMOUNT) AS THIS_RETIRE_AMOUNT
     , SUM(RR.GAP_RETIRE_AMOUNT) AS GAP_RETIRE_AMOUNT
     , RR.TOTAL_PAY_AMOUNT
     , RR.TOTAL_BONUS_AMOUNT
     , RR.YEAR_ALLOWANCE_AMOUNT
     , RR.DAY_3RD_COUNT
     , RR.DAY_AVG_AMOUNT
     , RR.LONG_YEAR
     , RR.LONG_DAY     
     , RR.RETIRE_AMOUNT
  FROM HRR_RETIRE_RESERVE RR
     , HRM_PERSON_MASTER PM
 WHERE RR.PERSON_ID               = PM.PERSON_ID
   AND RR.RESERVE_YYYYMM          = &W_STD_YYYYMM
   AND RR.CORP_ID                 = &W_CORP_ID
   AND RR.SOB_ID                  = &W_SOB_ID
   AND RR.ORG_ID                  = &W_ORG_ID
   AND RR.PERSON_ID               = NVL(&W_PERSON_ID, RR.PERSON_ID)
   AND RR.DEPT_ID                 = NVL(&W_DEPT_ID, RR.DEPT_ID)
   AND RR.PAY_GRADE_ID            = NVL(&W_PAY_GRADE_ID, RR.PAY_GRADE_ID)
GROUP BY ROLLUP((RR.RESERVE_YYYYMM
     , PM.DISPLAY_NAME
     , RR.DEPT_ID
     , HRM_DEPT_MASTER_G.DEPT_NAME_F(RR.DEPT_ID)
     , HRM_COMMON_G.CODE_NAME_F('EMPLOYE_TYPE', PM.EMPLOYE_TYPE, PM.SOB_ID, PM.ORG_ID)
     , NVL(PM.ORI_JOIN_DATE, PM.JOIN_DATE)
     , PM.EXPIRE_DATE
     , PM.RETIRE_DATE
     , RR.COST_CENTER_ID
     , ''
     , RR.TOTAL_PAY_AMOUNT
     , RR.TOTAL_BONUS_AMOUNT
     , RR.YEAR_ALLOWANCE_AMOUNT
     , RR.DAY_3RD_COUNT
     , RR.DAY_AVG_AMOUNT
     , RR.LONG_YEAR
     , RR.LONG_DAY     
     , RR.RETIRE_AMOUNT))
ORDER BY RR.DEPT_ID, PM.DISPLAY_NAME
 ;
