SELECT *
  FROM FI_AUTO_JOURNAL_HEADER JH
WHERE JH.JOB_CODE                 = '901'
;

SELECT &W_PERIOD_NAME AS PERIOD_NAME
    , JL.SOB_ID
    , JL.ORG_ID
    , LAST_DAY(TO_DATE(&W_PERIOD_NAME, 'YYYY-MM')) AS GL_DATE
    , AC.ACCOUNT_CONTROL_ID
    , AC.ACCOUNT_CODE
    , AC.ACCOUNT_DESC
    , JL.ACCOUNT_DR_CR
    , 50000000 AS GL_AMOUNT
, JL.REMARK
  FROM FI_AUTO_JOURNAL_LINE JL
    , FI_AUTO_JOURNAL_HEADER JH
    , FI_ACCOUNT_CONTROL AC
WHERE JL.JOURNAL_HEADER_ID        = JH.JOURNAL_HEADER_ID
  AND JL.ACCOUNT_CONTROL_ID       = AC.ACCOUNT_CONTROL_ID
  AND JH.JOB_CODE                 = '901'
ORDER BY JL.SEQ  
;
