SELECT AMB.ACCT_MGMT_BALANCE_ID
     , AMB.GL_DATE
     , AMB.GL_DATE_SEQ
     , AMB.SOB_ID
     , AMB.ORG_ID
     , AMB.ACCOUNT_CONTROL_ID
     , AMB.ACCOUNT_CODE
     , AMB.CURRENCY_CODE
     , AMB.ACCT_MGMT_SEQ
     , AMB.DR_SUM
     , AMB.CR_SUM
     , AMB.DR_CURR_SUM
     , AMB.CR_CURR_SUM
  FROM FI_ACCT_MGMT_BALANCE AMB
FOR UPDATE  
  
;

-- 관리항목.
SELECT MBI.ACCT_MGMT_BALANCE_ID
  FROM FI_ACCT_MGMT_BALANCE_ITEM MBI
    , FI_ACCT_MGMT_BALANCE AMB
WHERE MBI.ACCT_MGMT_BALANCE_ID = AMB.ACCT_MGMT_BALANCE_ID
  AND MBI.SOB_ID               = &W_SOB_ID
  AND AMB.GL_DATE              = &W_GL_DATE
  AND AMB.ACCOUNT_CONTROL_ID   = &W_ACCOUNT_CONTROL_ID
  AND AMB.CURRENCY_CODE        = &W_CURRENCY_CODE
  AND EXISTS( SELECT 'X'
                FROM FI_SLIP_MANAGEMENT_ITEM SMI
                  , FI_SLIP_LINE SL
              WHERE SMI.SLIP_LINE_ID      = SL.SLIP_LINE_ID
                AND SL.GL_DATE            = AMB.GL_DATE
                AND SL.ACCOUNT_CONTROL_ID = AMB.ACCOUNT_CONTROL_ID
                AND SL.CURRENCY_CODE      = AMB.CURRENCY_CODE
                AND SMI.MANAGEMENT_ID     = MBI.MANAGEMENT_ID
                AND SMI.SOB_ID            = MBI.SOB_ID
                AND SMI.MANAGEMENT_VALUE  = MBI.MANAGEMENT_VALUE
                AND SL.GL_DATE            = AMB.GL_DATE
                AND SL.SOB_ID             = AMB.SOB_ID
             )
;

SELECT *
  FROM FI_SLIP_LINE SL
    , FI_SLIP_MANAGEMENT_ITEM SMI
    , FI_MANAGEMENT_CODE_V MC
WHERE SL.SLIP_LINE_ID   = SMI.SLIP_LINE_ID
  AND SMI.MANAGEMENT_ID = MC.MANAGEMENT_ID
  AND SL.GL_DATE        = &W_GL_DATE
  AND SL.SOB_ID         = &W_SOB_ID
  AND SL.SLIP_LINE_ID   = 606
;


SELECT SL.GL_DATE
     , 1 AS GL_DATE_SEQ
     , SL.SOB_ID
     , SL.ORG_ID
     , SL.ACCOUNT_CONTROL_ID
     , SL.ACCOUNT_CODE
     , SL.CURRENCY_CODE
     , DECODE(SL.ACCOUNT_DR_CR, '1', SL.GL_AMOUNT, 0) AS DR_AMOUNT
     , DECODE(SL.ACCOUNT_DR_CR, '2', SL.GL_AMOUNT, 0) AS CR_AMOUNT
     , DECODE(SL.ACCOUNT_DR_CR, '1', SL.GL_CURRENCY_AMOUNT, 0) AS DR_CURRENCY_AMOUNT
     , DECODE(SL.ACCOUNT_DR_CR, '2', SL.GL_CURRENCY_AMOUNT, 0) AS CR_CURRENCY_AMOUNT
  FROM FI_SLIP_LINE SL
WHERE SL.SLIP_LINE_ID         = 1830
  
;

SELECT SMI.MANAGEMENT_ID
     , SMI.MANAGEMENT_CODE
     , SMI.MANAGEMENT_VALUE
     , MC.MANAGEMENT_NAME
     , SMI.*
  FROM FI_SLIP_MANAGEMENT_ITEM SMI
    , FI_MANAGEMENT_CODE_V MC
WHERE SMI.MANAGEMENT_ID       = MC.MANAGEMENT_ID
  AND SMI.SLIP_LINE_ID        = 1830
  AND MC.BALANCE_YN           = 'Y'
  AND SMI.SOB_ID               = 20
  ;
  
SELECT *
  FROM FI_MANAGEMENT_CODE_V
