SELECT *
  FROM HRM_PERSON_MASTER PM
;

-- V_SUPP_CUST_CODE : = 'S000632';
-- V_DEPT_CODE := '';
-- V_PERSON_NUM := '';

-- 판관.
SELECT MP.PAY_YYYYMM
     , MP.WAGE_TYPE
     , '5200100' AS ACCOUNT_CODE
     , SUM(MA.ALLOWANCE_AMOUNT) AS ALLOWANCE_AMOUNT
     , CC.COST_CENTER_CODE AS CC_CODE
  FROM HRM_PERSON_MASTER PM
    , HRP_MONTH_PAYMENT MP
    , HRP_MONTH_ALLOWANCE MA
    , CST_COST_CENTER CC
WHERE PM.PERSON_ID          = MP.PERSON_ID
  AND MP.MONTH_PAYMENT_ID   = MA.MONTH_PAYMENT_ID
  AND MP.PERSON_ID          = MA.PERSON_ID
  AND PM.COST_CENTER_ID     = CC.COST_CENTER_ID(+)
  AND MP.PAY_YYYYMM         = &P_PAY_YYYYMM
  AND MP.WAGE_TYPE          = &P_WAGE_TYPE  -- 급여.
  AND MP.CORP_ID            = &P_CORP_ID
  AND MP.SOB_ID             = &P_SOB_ID
  AND MP.ORG_ID             = &P_ORG_ID
  AND PM.DIR_INDIR_TYPE     = '10'  -- 판관.
  -- 중도 퇴사자 적용 여부 판단.
GROUP BY MP.PAY_YYYYMM
     , MP.WAGE_TYPE
     , CC.COST_CENTER_CODE
;

SELECT AJM.SLIP_TYPE_CD
     , AJM.JOB_CATEGORY_CD
     , AJM.SLIP_REMARKS
     , AJD.AUTO_JOURNAL_SEQ
     , AJD.ACCOUNT_CONTROL_ID
     , AJD.ACCOUNT_CODE
     , AJD.ACCOUNT_DR_CR
     , AJD.SLIP_REMARKS
  FROM FI_AUTO_JOURNAL_MST AJM
    , FI_AUTO_JOURNAL_DET AJD
WHERE AJM.SOB_ID            = AJD.SOB_ID
  AND AJM.SLIP_TYPE_CD      = AJD.SLIP_TYPE_CD
  AND AJM.JOB_CATEGORY_CD   = AJD.JOB_CATEGORY_CD
  AND AJD.SLIP_TYPE_CD      = 'PAY'
  AND AJD.JOB_CATEGORY_CD   = 'PAY01'  -- 급여.
  AND AJM.ENABLED_FLAG      = 'Y'
  AND AJD.ENABLED_FLAG      = 'Y'
ORDER BY AJD.AUTO_JOURNAL_SEQ  
;

SELECT *
  FROM FI_SUPP_CUST_V SC
WHERE SC.SUPP_CUST_NAME    LIKE 'BH%'  
;

SELECT *
  FROM FI_SUPP_CUST_V X
WHERE X.SUPP_CUST_CODE     = 'S000632'
;

SELECT *
  FROM HRM
;
