SELECT *
  FROM FI_FORM_HEADER X
WHERE X.FORM_HEADER_ID  = 13
;

SELECT *
  FROM FI_FORM_LINE X
WHERE X.FORM_HEADER_ID  = 13
;

SELECT *
  FROM FI_BALANCE_FS_GT
ORDER BY HEADER_ID, ITEM_LEVEL  
  ;

INSERT INTO FI_BALANCE_FS_GT 
( HEADER_ID
, LINE_HEADER_ID
, LINE_ID
, ITEM_LEVEL
, SOB_ID
, ORG_ID
, BEFORE_DR_AMOUNT
, BEFORE_CR_AMOUNT
, THIS_DR_AMOUNT
, THIS_CR_AMOUNT
, REMAIN_DR_AMOUNT
, REMAIN_CR_AMOUNT
)
SELECT FL.FORM_HEADER_ID
     , FL.JOIN_LINE_CONTROL_ID
     , FL.FORM_LINE_ID
     , FL.ITEM_LEVEL
     , FL.SOB_ID
     , FL.ORG_ID     
     , 0 AS BEFORE_DR_AMOUNT
     , 0 AS BEFORE_CR_AMOUNT
     , 0 AS THIS_DR_AMOUNT
     , 0 AS THIS_CR_AMOUNT
     , 0 AS REMAIN_DR_AMOUNT
     , 0 AS REMAIN_CR_AMOUNT
  FROM FI_FORM_LINE FL
    , FI_FORM_HEADER FH
WHERE FL.FORM_HEADER_ID           = FH.FORM_HEADER_ID
  AND FH.FORM_TYPE_ID             = &W_FORM_TYPE_ID
  AND FH.SOB_ID                   = &W_SOB_ID
  AND FH.LAST_LEVEL_YN            <> 'Y'  
;
  
INSERT INTO FI_BALANCE_FS_GT 
( HEADER_ID
, LINE_HEADER_ID
, LINE_ID
, ITEM_LEVEL
, SOB_ID
, ORG_ID
, BEFORE_DR_AMOUNT
, BEFORE_CR_AMOUNT
, THIS_DR_AMOUNT
, THIS_CR_AMOUNT
, REMAIN_DR_AMOUNT
, REMAIN_CR_AMOUNT
)
SELECT FL.FORM_HEADER_ID
     , FL.JOIN_LINE_CONTROL_ID
     , FL.FORM_LINE_ID
     , FL.ITEM_LEVEL
     , FL.SOB_ID
     , FL.ORG_ID     
     , NVL(SX1.BEFORE_DR_AMOUNT, 0) * NVL(FL.ITEM_SIGN, 1) AS BEFORE_DR_AMOUNT
     , NVL(SX1.BEFORE_CR_AMOUNT, 0) * NVL(FL.ITEM_SIGN, 1) AS BEFORE_CR_AMOUNT
     , NVL(SX1.THIS_DR_AMOUNT, 0) * NVL(FL.ITEM_SIGN, 1) AS THIS_DR_AMOUNT
     , NVL(SX1.THIS_CR_AMOUNT, 0) * NVL(FL.ITEM_SIGN, 1) AS THIS_CR_AMOUNT
     , NVL(SX1.REMAIN_DR_AMOUNT, 0) * NVL(FL.ITEM_SIGN, 1) AS REMAIN_DR_AMOUNT
     , NVL(SX1.REMAIN_CR_AMOUNT, 0) * NVL(FL.ITEM_SIGN, 1) AS REMAIN_CR_AMOUNT
  FROM FI_FORM_LINE FL
    , FI_FORM_HEADER FH
    , (-- 월 기초.
      SELECT DS.ACCOUNT_CONTROL_ID
           , DS.ACCOUNT_CODE
           , NVL(SUM(DS.DR_SUM), 0) AS BEFORE_DR_AMOUNT
           , NVL(SUM(DS.CR_SUM), 0) AS BEFORE_CR_AMOUNT
           , 0 AS THIS_DR_AMOUNT
           , 0 AS THIS_CR_AMOUNT
           , NVL(SUM(DECODE(AC.ACCOUNT_DR_CR, '1', NVL(DS.DR_SUM, 0) - NVL(DS.CR_SUM, 0))), 0) AS REMAIN_DR_AMOUNT                
           , NVL(SUM(DECODE(AC.ACCOUNT_DR_CR, '2', NVL(DS.CR_SUM, 0) - NVL(DS.DR_SUM, 0))), 0) AS REMAIN_CR_AMOUNT
        FROM FI_DAILY_SUM DS
          , FI_ACCOUNT_CONTROL AC
       WHERE DS.ACCOUNT_CONTROL_ID    = AC.ACCOUNT_CONTROL_ID
         AND DS.SOB_ID                = AC.SOB_ID          
         AND DS.GL_DATE               = TRUNC(&W_GL_DATE, 'MONTH')
         AND DS.GL_DATE_SEQ           = 0
         AND DS.SOB_ID                = &W_SOB_ID
      GROUP BY DS.ACCOUNT_CONTROL_ID
           , DS.ACCOUNT_CODE   
      UNION ALL
      -- 월 발생.
      SELECT DS.ACCOUNT_CONTROL_ID
           , DS.ACCOUNT_CODE
           , 0 AS BEFORE_DR_AMOUNT
           , 0 AS BEFORE_CR_AMOUNT     
           , NVL(SUM(DS.DR_SUM), 0) AS THIS_DR_AMOUNT
           , NVL(SUM(DS.CR_SUM), 0) AS THIS_CR_AMOUNT
           , NVL(SUM(DECODE(AC.ACCOUNT_DR_CR, '1', NVL(DS.DR_SUM, 0) - NVL(DS.CR_SUM, 0))), 0) AS REMAIN_DR_AMOUNT                
           , NVL(SUM(DECODE(AC.ACCOUNT_DR_CR, '2', NVL(DS.CR_SUM, 0) - NVL(DS.DR_SUM, 0))), 0) AS REMAIN_CR_AMOUNT
        FROM FI_DAILY_SUM DS
          , FI_ACCOUNT_CONTROL AC
       WHERE DS.ACCOUNT_CONTROL_ID    = AC.ACCOUNT_CONTROL_ID
         AND DS.SOB_ID                = AC.SOB_ID          
         AND DS.GL_DATE               BETWEEN TRUNC(&W_GL_DATE, 'MONTH') AND &W_GL_DATE
         AND DS.GL_DATE_SEQ           = 1
         AND DS.SOB_ID                = &W_SOB_ID
      GROUP BY DS.ACCOUNT_CONTROL_ID
           , DS.ACCOUNT_CODE   
      ) SX1
WHERE FL.FORM_HEADER_ID           = FH.FORM_HEADER_ID
  AND FL.LAST_LEVEL_YN            = 'Y'
  AND FL.JOIN_ACCOUNT_CONTROL_ID  = SX1.ACCOUNT_CONTROL_ID(+)
  AND FH.FORM_TYPE_ID             = &W_FORM_TYPE_ID
  AND FH.SOB_ID                   = &W_SOB_ID
;

SELECT TX1.FORM_HEADER_ID
     , SUM(TX1.THIS_DR_AMOUNT) OVER (PARTITION BY TX1.FORM_HEADER_ID ORDER BY TX1.FORM_HEADER_ID) AS THIS_DR_AMOUNT
  FROM (
    SELECT DISTINCT FH.FORM_HEADER_ID
         , FH.FORM_ITEM_NAME
         , FL.JOIN_FORM_HEADER_ID     
         , SX1.*
      FROM FI_FORM_HEADER FH
        , FI_FORM_LINE FL
        , (SELECT *
            FROM FI_BALANCE_FS_GT BF1
          ) SX1
    WHERE FH.FORM_HEADER_ID      = FL.FORM_HEADER_ID
      AND FH.SOB_ID              = FL.SOB_ID
      AND FL.FORM_HEADER_ID      = SX1.HEADER_ID(+)
      AND FL.SOB_ID              = SX1.SOB_ID(+)
      AND FH.FORM_TYPE_ID        = &W_FORM_TYPE_ID
      AND FH.SOB_ID              = &W_SOB_ID
    --START WITH BF.ITEM_LEVEL <= 3 
    CONNECT BY PRIOR SX1.HEADER_ID  = FL.JOIN_FORM_HEADER_ID --AND BF.ITEM_LEVEL = SX1.ITEM_LEVEL - 1
    ORDER BY 1
      ) TX1
;


SELECT DISTINCT BF.HEADER_ID
     , BF.LINE_HEADER_ID
     , BF.ITEM_LEVEL
     , BF.SOB_ID
/*     , (BF.BEFORE_DR_AMOUNT) AS BEFORE_DR_AMOUNT
     , (BF.BEFORE_CR_AMOUNT) AS BEFORE_CR_AMOUNT
     , (BF.THIS_DR_AMOUNT) AS THIS_DR_AMOUNT
     , (BF.THIS_CR_AMOUNT) AS THIS_CR_AMOUNT
     , (BF.REMAIN_DR_AMOUNT) AS REMAIN_DR_AMOUNT
     , (BF.REMAIN_CR_AMOUNT) AS REMAIN_CR_AMOUNT*/
     , SX1.*
  FROM FI_BALANCE_FS_GT BF
    , ( SELECT BF.HEADER_ID
             , BF.LINE_HEADER_ID
             , BF.ITEM_LEVEL
             , BF.SOB_ID
             , SUM(BF.BEFORE_DR_AMOUNT) AS BEFORE_DR_AMOUNT
             , SUM(BF.BEFORE_CR_AMOUNT) AS BEFORE_CR_AMOUNT
             , SUM(BF.THIS_DR_AMOUNT) AS THIS_DR_AMOUNT
             , SUM(BF.THIS_CR_AMOUNT) AS THIS_CR_AMOUNT
             , SUM(BF.REMAIN_DR_AMOUNT) AS REMAIN_DR_AMOUNT
             , SUM(BF.REMAIN_CR_AMOUNT) AS REMAIN_CR_AMOUNT
          FROM FI_BALANCE_FS_GT BF
        GROUP BY BF.HEADER_ID
             , BF.LINE_HEADER_ID
             , BF.ITEM_LEVEL
             , BF.SOB_ID
       ) SX1
WHERE BF.LINE_HEADER_ID                    = SX1.HEADER_ID
CONNECT BY PRIOR BF.HEADER_ID              = SX1.HEADER_ID
ORDER BY BF.ITEM_LEVEL
;  

SELECT BF.HEADER_ID
     , LEVEL
     , BF.LINE_HEADER_ID
--     , BF.ITEM_LEVEL
--     , BF.SOB_ID
     , BF.BEFORE_DR_AMOUNT AS BEFORE_DR_AMOUNT
     , BF.BEFORE_CR_AMOUNT AS BEFORE_CR_AMOUNT
     , BF.THIS_DR_AMOUNT AS THIS_DR_AMOUNT
     , BF.THIS_CR_AMOUNT AS THIS_CR_AMOUNT
     , BF.REMAIN_DR_AMOUNT AS REMAIN_DR_AMOUNT
     , BF.REMAIN_CR_AMOUNT AS REMAIN_CR_AMOUNT
  FROM FI_BALANCE_FS_GT BF
    , FI_BALANCE_FS_GT BF1
WHERE BF.HEADER_ID     = BF1.LINE_HEADER_ID    
--START WITH ITEM_LEVEL             = 3 
CONNECT BY PRIOR BF.HEADER_ID     = BF1.LINE_HEADER_ID
/*GROUP BY BF.HEADER_ID
     , LEVEL
     , BF.LINE_HEADER_ID*/
ORDER BY LEVEL
;

SELECT BF.HEADER_ID
--     , BF.LINE_HEADER_ID
--     , BF.ITEM_LEVEL
     , BF.SOB_ID
     , BF.BEFORE_DR_AMOUNT
     , BF.BEFORE_CR_AMOUNT
     , SUM(BF.THIS_DR_AMOUNT) OVER(ORDER BY LEVEL) AS K
     , BF.THIS_CR_AMOUNT
     , BF.REMAIN_DR_AMOUNT
     , BF.REMAIN_CR_AMOUNT
  FROM FI_BALANCE_FS_GT BF
    , FI_BALANCE_FS_GT BF1
WHERE BF.HEADER_ID     = BF1.HEADER_ID    
--START WITH ITEM_LEVEL             = 3 
CONNECT BY PRIOR BF.HEADER_ID     = BF1.LINE_HEADER_ID AND BF.ITEM_LEVEL  = BF1.ITEM_LEVEL - 1
ORDER BY BF.ITEM_LEVEL
;


SELECT BF.HEADER_ID
     , BF.LINE_HEADER_ID
     , BF.ITEM_LEVEL
     , BF.SOB_ID
     , NVL((SELECT SUM(T.BEFORE_DR_AMOUNT)
          FROM FI_BALANCE_FS_GT T
         WHERE T.HEADER_ID      = BF.LINE_HEADER_ID
         GROUP BY  T.HEADER_ID
                 , T.ITEM_LEVEL
                 , T.SOB_ID), SUM(BF.BEFORE_DR_AMOUNT)) AS BEFORE_DR_AMOUNT
     /*, SUM(BF.BEFORE_DR_AMOUNT)*/            
     , SUM(BF.BEFORE_CR_AMOUNT)
     , SUM(BF.THIS_DR_AMOUNT)
     /*, SUM(BF.THIS_CR_AMOUNT)*/
     , NVL((SELECT SUM(T.THIS_CR_AMOUNT)
          FROM FI_BALANCE_FS_GT T
         WHERE T.HEADER_ID      = BF.LINE_HEADER_ID
         GROUP BY  T.HEADER_ID
                 , T.ITEM_LEVEL
                 , T.SOB_ID), SUM(BF.THIS_CR_AMOUNT)) AS THIS_CR_AMOUNT
     , SUM(BF.REMAIN_DR_AMOUNT)
     , SUM(BF.REMAIN_CR_AMOUNT)
  FROM FI_BALANCE_FS_GT BF

GROUP BY BF.HEADER_ID
     , BF.LINE_HEADER_ID
     , BF.ITEM_LEVEL
     , BF.SOB_ID
ORDER BY BF.ITEM_LEVEL DESC
;
