select*
  from fi_customer_balance_daily
--FOR UPDATE  
;

INSERT INTO fi_customer_balance_daily
SELECT SL.GL_DATE
     , 1
     , SL.SOB_ID
     , SL.ORG_ID
     , SX1.CUSTOMER_ID
     , SL.ACCOUNT_BOOK_ID
     , SL.PERIOD_NAME
     , SL.ACCOUNT_CONTROL_ID
     , SL.ACCOUNT_CODE
     , SL.CURRENCY_CODE
     , NULL
     , NULL
     , SUM(DECODE(SL.ACCOUNT_DR_CR, '1', SL.GL_AMOUNT, 0)) AS DR_AMOUNT
     , SUM(DECODE(SL.ACCOUNT_DR_CR, '2', SL.GL_AMOUNT, 0)) AS CR_AMOUNT
     , SUM(DECODE(SL.ACCOUNT_DR_CR, '1', SL.GL_CURRENCY_AMOUNT, 0)) AS DR_CURR_AMOUNT
     , SUM(DECODE(SL.ACCOUNT_DR_CR, '2', SL.GL_CURRENCY_AMOUNT, 0)) AS CR_CURR_AMOUNT
     , TO_DATE('2011-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
     , -1
     , TO_DATE('2011-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
     , -1     
  FROM FI_SLIP_LINE SL
    , FI_ACCOUNT_CONTROL AC
    , ( SELECT SMI.SLIP_LINE_ID
             , SMI.SOB_ID
             , SMI.MANAGEMENT_VALUE
             , ( SELECT DISTINCT SC.SUPP_CUST_ID
                   FROM FI_SUPP_CUST_V SC
                 WHERE SC.SUPP_CUST_CODE  = SMI.MANAGEMENT_VALUE
                   AND SC.SOB_ID          = SMI.SOB_ID
                ) AS CUSTOMER_ID
          FROM FI_SLIP_MANAGEMENT_ITEM SMI          
            , FI_MANAGEMENT_CODE_V MC
        WHERE SMI.MANAGEMENT_ID   = MC.MANAGEMENT_ID
          AND SMI.SOB_ID          = &W_SOB_ID
          AND MC.LOOKUP_TYPE      = 'CUSTOMER'
       ) SX1
WHERE SL.ACCOUNT_CONTROL_ID     = AC.ACCOUNT_CONTROL_ID
  AND SL.SLIP_LINE_ID           = SX1.SLIP_LINE_ID
  AND SL.SOB_ID                 = AC.SOB_ID  
  AND SL.SOB_ID                 = &W_SOB_ID
  AND SL.GL_DATE                IS NOT NULL
  AND SL.CONFIRM_YN             = 'Y'
  AND AC.CUSTOMER_ENABLED_FLAG  = 'Y'
  AND SX1.CUSTOMER_ID           IS NOT NULL
GROUP BY SL.GL_DATE
     , SL.SOB_ID
     , SL.ORG_ID
     , SX1.CUSTOMER_ID
     , SL.ACCOUNT_BOOK_ID
     , SL.PERIOD_NAME
     , SL.ACCOUNT_CONTROL_ID
     , SL.ACCOUNT_CODE
     , SL.CURRENCY_CODE  
ORDER BY SL.GL_DATE, SL.ACCOUNT_CODE
