-- 자금현황.
SELECT SL.SLIP_DATE
     , SL.ACCOUNT_CONTROL_ID
     , SL.ACCOUNT_CODE
     , AC.ACCOUNT_DESC
     , SL.CURRENCY_CODE     
     , SL.REMARK
     , DECODE(SL.ACCOUNT_DR_CR, '1', SL.GL_CURRENCY_AMOUNT, 0) AS DR_CURRENCY_AMOUNT
     , DECODE(SL.ACCOUNT_DR_CR, '2', SL.GL_CURRENCY_AMOUNT, 0) AS CR_CURRENCY_AMOUNT
     , DECODE(SL.ACCOUNT_DR_CR, '1', SL.GL_AMOUNT, 0) AS DR_AMOUNT
     , DECODE(SL.ACCOUNT_DR_CR, '2', SL.GL_AMOUNT, 0) AS CR_AMOUNT
     , SL.SLIP_LINE_ID
     , FI_SLIP_G.SLIP_ITEM_VALUE_F(SL.SLIP_LINE_ID, 'CUSTOMER', SL.SOB_ID) AS CUSTOMER_CODE
     , FI_SLIP_G.SLIP_ITEM_VALUE_F(SL.SLIP_LINE_ID, 'BANK_ACCOUNT', SL.SOB_ID) AS BANK_ACCOUNT_CODE
     , FI_SLIP_G.SLIP_ITEM_VALUE_F(SL.SLIP_LINE_ID, 'LOAN_USE', SL.SOB_ID) AS LOAN_USE
     , FI_SLIP_G.SLIP_ITEM_VALUE_F(SL.SLIP_LINE_ID, 'LOAN_NUM', SL.SOB_ID) AS LOAN_NUM
  FROM FI_SLIP_LINE SL
    , FI_ACCOUNT_CONTROL AC
WHERE SL.ACCOUNT_CONTROL_ID       = AC.ACCOUNT_CONTROL_ID
--  AND AC.ACCOUNT_CODE             IN('1110100', '1110301', '1110302', '1110400', '1110401', '1110402', '1110700', '2100200', '2100301')
  AND SL.SOB_ID                   = &W_SOB_ID
  AND SL.SLIP_DATE                = &W_GL_DATE
  AND EXISTS( SELECT 'X'
                FROM FI_COMMON FC
              WHERE FC.GROUP_CODE   = 'TR_MANAGE_ACCOUNT'
                AND FC.SOB_ID       = SL.SOB_ID
                AND FC.VALUE1       = SL.ACCOUNT_CODE
            )
ORDER BY SL.ACCOUNT_CODE       
;

-- 금융채무현황.
SELECT SL.SLIP_DATE
     , SL.ACCOUNT_CONTROL_ID
     , SL.ACCOUNT_CODE
     , AC.ACCOUNT_DESC
     , SL.CURRENCY_CODE
     , BA.BANK_NAME
     , BA.BANK_ACCOUNT_NUM
     , DECODE(SL.ACCOUNT_DR_CR, '1', SL.GL_CURRENCY_AMOUNT, 0) AS DR_CURRENCY_AMOUNT
     , DECODE(SL.ACCOUNT_DR_CR, '2', SL.GL_CURRENCY_AMOUNT, 0) AS CR_CURRENCY_AMOUNT
     , DECODE(SL.ACCOUNT_DR_CR, '1', SL.GL_AMOUNT, 0) AS DR_AMOUNT
     , DECODE(SL.ACCOUNT_DR_CR, '2', SL.GL_AMOUNT, 0) AS CR_AMOUNT
  FROM FI_SLIP_LINE SL
    , ( SELECT SMI.SLIP_LINE_ID
             , FB.BANK_NAME
             , SMI.MANAGEMENT_VALUE AS BANK_ACCOUNT_CODE
             , FBA.BANK_ACCOUNT_NUM
          FROM FI_SLIP_MANAGEMENT_ITEM SMI
            , FI_BANK_ACCOUNT FBA
            , FI_BANK FB
        WHERE SMI.MANAGEMENT_VALUE  = FBA.BANK_ACCOUNT_CODE
          AND FBA.BANK_ID           = FB.BANK_ID
          AND SMI.SOB_ID          = &W_SOB_ID
          AND EXISTS( SELECT 'X'
                        FROM FI_MANAGEMENT_CODE_V MC
                      WHERE MC.MANAGEMENT_ID    = SMI.MANAGEMENT_ID
                        AND MC.SOB_ID           = SMI.SOB_ID
                        AND MC.LOOKUP_TYPE      = 'BANK_ACCOUNT'
                    )
      ) BA
    , FI_ACCOUNT_CONTROL AC
WHERE SL.ACCOUNT_CONTROL_ID       = AC.ACCOUNT_CONTROL_ID
  AND SL.SLIP_LINE_ID             = BA.SLIP_LINE_ID(+)
  AND AC.ACCOUNT_CODE             IN('2100301')
  AND SL.SOB_ID                   = &W_SOB_ID
  AND SL.SLIP_DATE                = &W_GL_DATE
ORDER BY SL.ACCOUNT_CODE       
;

-- 일일자금 입금내역.
SELECT SL.SLIP_DATE
     , SL.ACCOUNT_CONTROL_ID
     , SL.ACCOUNT_CODE
     , AC.ACCOUNT_DESC
     , SL.CURRENCY_CODE
     , BA.BANK_NAME
     , SL.REMARK
     , SUM(DECODE(SL.ACCOUNT_DR_CR, '1', SL.GL_CURRENCY_AMOUNT, 0)) AS DR_CURRENCY_AMOUNT
     , SUM(DECODE(SL.ACCOUNT_DR_CR, '1', SL.GL_AMOUNT, 0)) AS DR_AMOUNT
  FROM FI_SLIP_LINE SL
    , ( SELECT SMI.SLIP_LINE_ID
             , FB.BANK_NAME
             , SMI.MANAGEMENT_VALUE AS BANK_ACCOUNT_CODE
             , FBA.BANK_ACCOUNT_NUM
          FROM FI_SLIP_MANAGEMENT_ITEM SMI
            , FI_BANK_ACCOUNT FBA
            , FI_BANK FB
        WHERE SMI.MANAGEMENT_VALUE  = FBA.BANK_ACCOUNT_CODE
          AND FBA.BANK_ID           = FB.BANK_ID
          AND SMI.SOB_ID          = &W_SOB_ID
          AND EXISTS( SELECT 'X'
                        FROM FI_MANAGEMENT_CODE_V MC
                      WHERE MC.MANAGEMENT_ID    = SMI.MANAGEMENT_ID
                        AND MC.SOB_ID           = SMI.SOB_ID
                        AND MC.LOOKUP_TYPE      = 'BANK_ACCOUNT'
                    )
      ) BA
    , FI_ACCOUNT_CONTROL AC
WHERE SL.ACCOUNT_CONTROL_ID       = AC.ACCOUNT_CONTROL_ID
  AND SL.SLIP_LINE_ID             = BA.SLIP_LINE_ID(+)
  AND AC.ACCOUNT_CODE             IN('1110100', '1110301', '1110302', '1110400', '1110401', '1110402', '1110700', '2100200', '2100301')
  AND AC.ACCOUNT_DR_CR            = '1'
  AND SL.SOB_ID                   = &W_SOB_ID
  AND SL.SLIP_DATE                = &W_GL_DATE
GROUP BY SL.SLIP_DATE
       , SL.ACCOUNT_CONTROL_ID
       , SL.ACCOUNT_CODE
       , AC.ACCOUNT_DESC
       , SL.CURRENCY_CODE  
       , BA.BANK_NAME       
       , SL.REMARK
ORDER BY SL.ACCOUNT_CODE       
;

-- 일일자금 츨금내역.
SELECT SL.SLIP_DATE
     , SL.ACCOUNT_CONTROL_ID
     , SL.ACCOUNT_CODE
     , AC.ACCOUNT_DESC
     , SL.CURRENCY_CODE
     , BA.BANK_NAME
     , SL.REMARK
     , SUM(DECODE(SL.ACCOUNT_DR_CR, '2', SL.GL_CURRENCY_AMOUNT, 0)) AS CR_CURRENCY_AMOUNT
     , SUM(DECODE(SL.ACCOUNT_DR_CR, '2', SL.GL_AMOUNT, 0)) AS CR_AMOUNT
  FROM FI_SLIP_LINE SL
    , ( SELECT SMI.SLIP_LINE_ID
             , FB.BANK_NAME
             , SMI.MANAGEMENT_VALUE AS BANK_ACCOUNT_CODE
             , FBA.BANK_ACCOUNT_NUM
          FROM FI_SLIP_MANAGEMENT_ITEM SMI
            , FI_BANK_ACCOUNT FBA
            , FI_BANK FB
        WHERE SMI.MANAGEMENT_VALUE  = FBA.BANK_ACCOUNT_CODE
          AND FBA.BANK_ID           = FB.BANK_ID
          AND SMI.SOB_ID          = &W_SOB_ID
          AND EXISTS( SELECT 'X'
                        FROM FI_MANAGEMENT_CODE_V MC
                      WHERE MC.MANAGEMENT_ID    = SMI.MANAGEMENT_ID
                        AND MC.SOB_ID           = SMI.SOB_ID
                        AND MC.LOOKUP_TYPE      = 'BANK_ACCOUNT'
                    )
      ) BA
    , FI_ACCOUNT_CONTROL AC
WHERE SL.ACCOUNT_CONTROL_ID       = AC.ACCOUNT_CONTROL_ID
  AND SL.SLIP_LINE_ID             = BA.SLIP_LINE_ID(+)
  AND AC.ACCOUNT_CODE             IN('1110100', '1110301', '1110302', '1110400', '1110401', '1110402', '1110700', '2100200', '2100301')
  AND AC.ACCOUNT_DR_CR            = '2'
  AND SL.SOB_ID                   = &W_SOB_ID
  AND SL.SLIP_DATE                = &W_GL_DATE
GROUP BY SL.SLIP_DATE
       , SL.ACCOUNT_CONTROL_ID
       , SL.ACCOUNT_CODE
       , AC.ACCOUNT_DESC
       , SL.CURRENCY_CODE  
       , BA.BANK_NAME       
       , SL.REMARK
ORDER BY SL.ACCOUNT_CODE       
;

-- 자금이체.
SELECT SL.SLIP_DATE
     , SL.ACCOUNT_CONTROL_ID
     , SL.ACCOUNT_CODE
     , AC.ACCOUNT_DESC
     , SL.CURRENCY_CODE
     , BA.BANK_NAME
     , SL.REMARK
     , SUM(DECODE(SL.ACCOUNT_DR_CR, '1', SL.GL_CURRENCY_AMOUNT, 0)) AS DR_CURRENCY_AMOUNT
     , SUM(DECODE(SL.ACCOUNT_DR_CR, '2', SL.GL_CURRENCY_AMOUNT, 0)) AS CR_CURRENCY_AMOUNT
     , SUM(DECODE(SL.ACCOUNT_DR_CR, '1', SL.GL_AMOUNT, 0)) AS DR_AMOUNT
     , SUM(DECODE(SL.ACCOUNT_DR_CR, '2', SL.GL_AMOUNT, 0)) AS CR_AMOUNT
  FROM FI_SLIP_LINE SL
    , ( SELECT SMI.SLIP_LINE_ID
             , FB.BANK_NAME
             , SMI.MANAGEMENT_VALUE AS BANK_ACCOUNT_CODE
             , FBA.BANK_ACCOUNT_NUM
          FROM FI_SLIP_MANAGEMENT_ITEM SMI
            , FI_BANK_ACCOUNT FBA
            , FI_BANK FB
        WHERE SMI.MANAGEMENT_VALUE  = FBA.BANK_ACCOUNT_CODE
          AND FBA.BANK_ID           = FB.BANK_ID
          AND SMI.SOB_ID          = &W_SOB_ID
          AND EXISTS( SELECT 'X'
                        FROM FI_MANAGEMENT_CODE_V MC
                      WHERE MC.MANAGEMENT_ID    = SMI.MANAGEMENT_ID
                        AND MC.SOB_ID           = SMI.SOB_ID
                        AND MC.LOOKUP_TYPE      = 'BANK_ACCOUNT'
                    )
      ) BA
    , FI_ACCOUNT_CONTROL AC
WHERE SL.ACCOUNT_CONTROL_ID       = AC.ACCOUNT_CONTROL_ID
  AND SL.SLIP_LINE_ID             = BA.SLIP_LINE_ID(+)
  AND AC.ACCOUNT_CODE             IN('1110100', '1110301', '1110302', '1110400', '1110401', '1110402', '1110700', '2100200', '2100301')
  AND SL.SOB_ID                   = &W_SOB_ID
  AND SL.SLIP_DATE                = &W_GL_DATE
  AND EXISTS( SELECT 'X'
                FROM FI_SLIP_MANAGEMENT_ITEM SMI 
                  , FI_MANAGEMENT_CODE_V MC
              WHERE SMI.MANAGEMENT_ID   = MC.MANAGEMENT_ID
                AND SMI.SLIP_LINE_ID    = SL.SLIP_LINE_ID
                AND MC.LOOKUP_TYPE      = 'FUND_MOVE'
            )
GROUP BY SL.SLIP_DATE
       , SL.ACCOUNT_CONTROL_ID
       , SL.ACCOUNT_CODE
       , AC.ACCOUNT_DESC
       , SL.CURRENCY_CODE  
       , BA.BANK_NAME       
       , SL.REMARK
ORDER BY SL.ACCOUNT_CODE       
;
