SELECT FB.BANK_CODE
     , DECODE(GROUPING(FB.BANK_CODE), 1, '총합계', FB.BANK_NAME) AS BANK_NAME
     , BA.BANK_ACCOUNT_NUM
     , SUM(NVL(LM.LOAN_AMOUNT, 0)) AS LOAN_AMOUNT
     , SUM(NVL(LM.LOAN_AMOUNT, 0) - NVL(DS.BEGIN_AMOUNT, 0)) AS BEGIN_AMOUNT
     , SUM(DS.DR_AMOUNT) AS DR_AMOUNT  -- 금일상환.
     , SUM(DS.CR_AMOUNT) AS CR_AMOUNT  -- 금일차입.
     , SUM(NVL(LM.LOAN_AMOUNT, 0) - NVL(DS.BEGIN_AMOUNT, 0) - NVL(DS.DR_AMOUNT, 0) + NVL(DS.CR_AMOUNT, 0)) AS REMAIN_AMOUNT
     , TO_CHAR(LM.ISSUE_DATE, 'YYYY-MM-DD') AS ISSUE_DATE
     , TO_CHAR(LM.DUE_DATE, 'YYYY-MM-DD') AS DUE_DATE
     , TO_CHAR(LM.INTER_RATE) AS INTER_RATE
  FROM FI_TR_DAILY_SUM DS
    , FI_TR_MANAGE_ACCOUNTE_V MA
    , FI_LOAN_USE_V LU
    , FI_BANK_ACCOUNT BA
    , FI_BANK FB
    , FI_LOAN_MASTER LM
WHERE DS.ACCOUNT_CODE           = MA.ACCOUNT_CODE
  AND DS.SOB_ID                   = MA.SOB_ID
  AND DS.LOAN_USE                 = LU.LOAN_USE_CODE
  AND DS.SOB_ID                   = LU.SOB_ID
  AND DS.BANK_ACCOUNT_CODE        = BA.BANK_ACCOUNT_CODE(+)
  AND DS.SOB_ID                   = BA.SOB_ID(+)
  AND DS.BANK_CODE                = FB.BANK_CODE(+)
  AND DS.SOB_ID                   = FB.SOB_ID(+)
  AND DS.LOAN_NUM                 = LM.LOAN_NUM(+)
  AND DS.SOB_ID                   = LM.SOB_ID(+)
  AND DS.TR_TYPE                  = 'SLIP'
  AND DS.SOB_ID                   = &W_SOB_ID
  AND DS.GL_DATE                  = &W_GL_DATE
  AND MA.TR_CLASS                 = 210
  AND LU.TR_LOAN_TYPE             = '1'
GROUP BY ROLLUP((FB.BANK_CODE
     , FB.BANK_NAME
     , BA.BANK_ACCOUNT_NUM
     , LM.ISSUE_DATE
     , LM.DUE_DATE
     , LM.INTER_RATE))  
;

