SELECT AC_1.AST_CATEGORY_NAME
     , AC_2.AST_CATEGORY_NAME
     , AC_3.AST_CATEGORY_NAME
     , HRM_COMMON_G.ID_NAME_F(AM.MANAGE_DEPT_ID) AS MANAGE_DEPT
     , HRM_COMMON_G.ID_NAME_F(AM.USE_DEPT_ID) AS USE_DEPT
     , AM.*
  FROM FI_ASSET_MASTER AM
    , FI_ASSET_CATEGORY AC_3
    , FI_ASSET_CATEGORY AC_2
    , FI_ASSET_CATEGORY AC_1    
WHERE AM.AST_CATEGORY_ID          = AC_3.AST_CATEGORY_ID
  AND AC_3.UPPER_AST_CATEGORY_ID  = AC_2.AST_CATEGORY_ID
  AND AC_2.UPPER_AST_CATEGORY_ID  = AC_1.AST_CATEGORY_ID
