SELECT SSL.SLIP_HEADER_ID
    , SSL.SOB_ID
    , MAX(DECODE(SMI.MANAGEMENT_CODE, '33', SMI.MANAGEMENT_VALUE)) AS VAT_ISSUE_DATE
FROM FI_VAT_ACCOUNTS SVA
  , FI_SLIP_LINE SSL
  , FI_SLIP_MANAGEMENT_ITEM SMI
WHERE SVA.ACCOUNT_CONTROL_ID      = SSL.ACCOUNT_CONTROL_ID
  AND SVA.SOB_ID                  = SSL.SOB_ID
  AND SSL.SLIP_LINE_ID            = SMI.SLIP_LINE_ID
  AND SSL.SOB_ID                  = SMI.SOB_ID
  AND SVA.VAT_DOCUMENT_TYPE       = '2'
  AND SVA.ENABLED_FLAG            = 'Y'
  AND SVA.VAT_ENABLED_FLAG        = 'Y'
GROUP BY SSL.SLIP_HEADER_ID
    , SSL.SOB_ID
;

SELECT *
  FROM FI_MANAGEMENT_CODE_V
