SELECT TO_CHAR(SL.GL_DATE, 'YYYY-MM') AS PERIOD_NAME
    , SL.REMARK
    , SL.ACCOUNT_CODE
    , AC.ACCOUNT_DESC
    , SUM(DECODE(SL.ACCOUNT_DR_CR, '1', SL.GL_AMOUNT)) AS DR_AMOUNT
    , SUM(DECODE(SL.ACCOUNT_DR_CR, '2', SL.GL_AMOUNT)) AS CR_AMOUNT
    , D_SL.DEPT_CODE
    , D_SL.DEPT_NAME
    , C_SL.CC_CODE
    , C_SL.CC_DESC
  FROM FI_SLIP_LINE SL
    , FI_ACCOUNT_CONTROL AC
    , ( SELECT SMI.SLIP_LINE_ID
             , SMI.MANAGEMENT_VALUE AS DEPT_CODE
             , DM.DEPT_NAME
          FROM FI_SLIP_MANAGEMENT_ITEM SMI
            , FI_DEPT_MASTER DM
        WHERE SMI.MANAGEMENT_VALUE  = DM.DEPT_CODE
          AND SMI.SOB_ID            = DM.SOB_ID
          AND SMI.SOB_ID            = &W_SOB_ID
          AND EXISTS
                ( SELECT 'X'
                    FROM FI_MANAGEMENT_CODE_V MC
                  WHERE MC.MANAGEMENT_ID    = SMI.MANAGEMENT_ID
                    AND MC.SOB_ID           = SMI.SOB_ID
                    AND MC.MANAGEMENT_CODE  = '19'
                )
      ) D_SL
    , ( SELECT SMI.SLIP_LINE_ID
             , SMI.MANAGEMENT_VALUE AS CC_CODE
             , CC.COST_CENTER_DESC AS CC_DESC
          FROM FI_SLIP_MANAGEMENT_ITEM SMI
            , CST_COST_CENTER CC
        WHERE SMI.MANAGEMENT_VALUE  = CC.COST_CENTER_CODE
          AND SMI.SOB_ID            = CC.SOB_ID
          AND SMI.SOB_ID            = &W_SOB_ID
          AND EXISTS
                ( SELECT 'X'
                    FROM FI_MANAGEMENT_CODE_V MC
                  WHERE MC.MANAGEMENT_ID    = SMI.MANAGEMENT_ID
                    AND MC.SOB_ID           = SMI.SOB_ID
                    AND MC.MANAGEMENT_CODE  = '20'
                )
      ) C_SL
WHERE SL.ACCOUNT_CONTROL_ID   = AC.ACCOUNT_CONTROL_ID
  AND SL.SLIP_LINE_ID         = D_SL.SLIP_LINE_ID(+)
  AND SL.SLIP_LINE_ID         = C_SL.SLIP_LINE_ID(+)
  AND SL.SOB_ID                = &W_SOB_ID
  AND SL.GL_DATE               BETWEEN &W_GL_DATE_FR AND &W_GL_DATE_TO
  AND SL.ACCOUNT_BOOK_ID       = FI_ACCOUNT_BOOK_G.OPERATING_ACCOUNT_BOOK_F(&W_SOB_ID)
  AND SL.ACCOUNT_CODE          BETWEEN &W_ACCOUNT_CODE_FR AND &W_ACCOUNT_CODE_TO
  AND (D_SL.DEPT_CODE IS NOT NULL OR C_SL.CC_CODE IS NOT NULL)
GROUP BY TO_CHAR(SL.GL_DATE, 'YYYY-MM')
    , SL.REMARK
    , SL.ACCOUNT_CODE
    , AC.ACCOUNT_DESC
    , D_SL.DEPT_CODE
    , D_SL.DEPT_NAME
    , C_SL.CC_CODE
    , C_SL.CC_DESC  
ORDER BY SL.ACCOUNT_CODE 
      , TO_CHAR(SL.GL_DATE, 'YYYY-MM')
