SELECT SL.SLIP_LINE_ID
     , SL.SLIP_LINE_SEQ
     , SL.SLIP_HEADER_ID
     , SL.SOB_ID
     , SL.ACCOUNT_BOOK_ID
     , SL.CUSTOMER_ID
     , SCV.SUPP_CUST_NAME
     , SCV.TAX_REG_NO
     , SL.ACCOUNT_CONTROL_ID
     , SL.ACCOUNT_CODE
     , AC.ACCOUNT_DESC
     , SL.COST_CENTER_ID
     , FI_COMMON_G.COST_CENTER_CODE_F(SL.COST_CENTER_ID) AS COST_CENTER_CODE
     , FI_COMMON_G.COST_CENTER_DESC_F(SL.COST_CENTER_ID) AS COST_CENTER_DESC
     , SL.ACCOUNT_DR_CR
     , FI_COMMON_G.CODE_NAME_F('ACCOUNT_DR_CR', SL.ACCOUNT_DR_CR, SL.SOB_ID, SL.ORG_ID) AS ACCOUNT_DR_CR_NAME
     , SL.GL_AMOUNT
     , SL.CURRENCY_CODE
     , EAPP_CURRENCY_G.CURRENCY_DESC_F(SL.CURRENCY_CODE, SL.SOB_ID, SL.ORG_ID) AS CURRENCY_DESC     
     , SL.EXCHANGE_RATE
     , SL.GL_CURRENCY_AMOUNT
     , SL.BANK_ACCOUNT_ID
     , BAT.BANK_ACCOUNT_NUM
     , BAT.BANK_ACCOUNT_NAME
     , SL.MANAGEMENT1                           -- °èÁÂ¹øÈ£ OR CODE °ª.
     , NULL AS MANAGEMENT1_DESC
     , SL.MANAGEMENT2
     , NULL AS MANAGEMENT2_DESC
     , SL.REFER1
     , NULL AS REFER1_DESC
     , SL.REFER2
     , NULL AS REFER2_DESC
     , SL.REFER3
     , NULL AS REFER3_DESC
     , SL.REFER4
     , NULL AS REFER4_DESC
     , SL.REFER5
     , NULL AS REFER5_DESC
     , SL.VOUCH_CODE
     , FI_COMMON_G.CODE_NAME_F('VOUCH_CODE', SL.VOUCH_CODE, SL.SOB_ID, SL.ORG_ID) AS VOUCH_NAME
     , SL.REFER_RATE
     , SL.REFER_AMOUNT
     , SL.REFER_DATE1
     , SL.REFER_DATE2
     , SL.REMARK
  FROM FI_SLIP_LINE SL
    , FI_SUPP_CUST_V SCV
    , GL_ACCOUNT_CONTROL AC
    , FI_BANK_ACCOUNT_TLV BAT
 WHERE SL.CUSTOMER_ID             = SCV.SUPP_CUST_ID
   AND SL.ACCOUNT_CONTROL_ID      = AC.ACCOUNT_CONTROL_ID
   AND SL.BANK_ACCOUNT_ID         = BAT.BANK_ACCOUNT_ID(+)
   AND SL.SLIP_HEADER_ID          = &W_SLIP_HEADER_ID
   AND SL.SOB_ID                  = &W_SOB_ID
 ;
