/******************************************************************************/
/* Project      : FPCB ERP
/* Module       : FCM
/* Program Name : FI_AUTO_JOURNAL_LINE_LINE
/* Description  : 자동분개 정의.
/*
/* Reference by :
/* Program History
/*------------------------------------------------------------------------------
/*   Date       In Charge          Description
/*------------------------------------------------------------------------------
/* 07-JUN-2010  Jeon Ho Su          Initialize
/******************************************************************************/
CREATE TABLE FI_AUTO_JOURNAL_LINE
( JOURNAL_LINE_ID                 NUMBER        NOT NULL
, SOB_ID                          NUMBER        NOT NULL
, ORG_ID                          NUMBER        NOT NULL
, JOURNAL_HEADER_ID               NUMBER        NOT NULL 
, SEQ                             NUMBER        DEFAULT 0
, ACCOUNT_DR_CR                   VARCHAR2(1)   NOT NULL
, ACCOUNT_CONTROL_ID              NUMBER        NOT NULL
, REMARK                          VARCHAR2(150)
, PER_CONTRA_ACCOUNT_YN           CHAR(1)       DEFAULT 'N'
, DISPLAY_YN                      CHAR(1)       DEFAULT 'Y'
, ENABLED_FLAG                    CHAR(1)       DEFAULT 'Y'
, EFFECTIVE_DATE_FR               DATE          NOT NULL
, EFFECTIVE_DATE_TO               DATE          
, CREATION_DATE                   DATE          NOT NULL
, CREATED_BY                      NUMBER        NOT NULL
, LAST_UPDATE_DATE                DATE          NOT NULL
, LAST_UPDATED_BY                 NUMBER        NOT NULL
) TABLESPACE FCM_TS_DATA;

COMMENT ON TABLE APPS.FI_AUTO_JOURNAL_LINE  IS '자동분개 유형 정의-LINE';
COMMENT ON COLUMN APPS.FI_AUTO_JOURNAL_LINE.JOURNAL_LINE_ID IS '자동분개 LINE ID';
COMMENT ON COLUMN APPS.FI_AUTO_JOURNAL_LINE.SOB_ID IS '회계조직';
COMMENT ON COLUMN APPS.FI_AUTO_JOURNAL_LINE.JOURNAL_HEADER_ID IS '자동분개 HEADER ID';
COMMENT ON COLUMN APPS.FI_AUTO_JOURNAL_LINE.SEQ IS '일련번호';
COMMENT ON COLUMN APPS.FI_AUTO_JOURNAL_LINE.ACCOUNT_DR_CR IS '차대구분(1-차, 2-대)';
COMMENT ON COLUMN APPS.FI_AUTO_JOURNAL_LINE.ACCOUNT_CONTROL_ID IS '계정관리ID';
COMMENT ON COLUMN APPS.FI_AUTO_JOURNAL_LINE.REMARK IS '비고';
COMMENT ON COLUMN APPS.FI_AUTO_JOURNAL_LINE.PER_CONTRA_ACCOUNT_YN IS '상대계정 YN';
COMMENT ON COLUMN APPS.FI_AUTO_JOURNAL_LINE.DISPLAY_YN IS '화면표시 YN';
COMMENT ON COLUMN APPS.FI_AUTO_JOURNAL_LINE.ENABLED_FLAG IS '사용';
COMMENT ON COLUMN APPS.FI_AUTO_JOURNAL_LINE.EFFECTIVE_DATE_FR IS '적용 시작일자';
COMMENT ON COLUMN APPS.FI_AUTO_JOURNAL_LINE.EFFECTIVE_DATE_TO IS '적용 종료일자';
COMMENT ON COLUMN APPS.FI_AUTO_JOURNAL_LINE.CREATION_DATE IS '생성일자';
COMMENT ON COLUMN APPS.FI_AUTO_JOURNAL_LINE.CREATED_BY IS '생성자';
COMMENT ON COLUMN APPS.FI_AUTO_JOURNAL_LINE.LAST_UPDATE_DATE IS '최종수정일자';
COMMENT ON COLUMN APPS.FI_AUTO_JOURNAL_LINE.LAST_UPDATED_BY IS '최종수정자';

CREATE UNIQUE INDEX FI_AUTO_JOURNAL_LINE_PK ON 
  FI_AUTO_JOURNAL_LINE(JOURNAL_HEADER_ID, SEQ, SOB_ID)
  TABLESPACE FCM_TS_IDX
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  LOGGING
  STORAGE (
           INITIAL 64K
           MINEXTENTS 1
           MAXEXTENTS 2147483645
          );
          
ALTER TABLE FI_AUTO_JOURNAL_LINE ADD (                                  
  CONSTRAINT FI_AUTO_JOURNAL_LINE_PK PRIMARY KEY (JOURNAL_HEADER_ID, SEQ, SOB_ID)
          );                                                    

CREATE UNIQUE INDEX FI_AUTO_JOURNAL_LINE_U1 ON FI_AUTO_JOURNAL_LINE(JOURNAL_LINE_ID) TABLESPACE FCM_TS_IDX;
CREATE INDEX FI_AUTO_JOURNAL_LINE_N1 ON FI_AUTO_JOURNAL_LINE(JOURNAL_HEADER_ID) TABLESPACE FCM_TS_IDX;
CREATE INDEX FI_AUTO_JOURNAL_LINE_N2 ON FI_AUTO_JOURNAL_LINE(PER_CONTRA_ACCOUNT_YN, ENABLED_FLAG, EFFECTIVE_DATE_FR, EFFECTIVE_DATE_TO) TABLESPACE FCM_TS_IDX;
CREATE INDEX FI_AUTO_JOURNAL_LINE_N3 ON FI_AUTO_JOURNAL_LINE(DISPLAY_YN, ENABLED_FLAG, EFFECTIVE_DATE_FR, EFFECTIVE_DATE_TO) TABLESPACE FCM_TS_IDX;

-- SEQUENCE.
CREATE SEQUENCE FI_AUTO_JOURNAL_LINE_S1;

-- ANALYZE.
ANALYZE TABLE FI_AUTO_JOURNAL_LINE COMPUTE STATISTICS;
ANALYZE INDEX FI_AUTO_JOURNAL_LINE_U1 COMPUTE STATISTICS;
ANALYZE INDEX FI_AUTO_JOURNAL_LINE_N1 COMPUTE STATISTICS;
ANALYZE INDEX FI_AUTO_JOURNAL_LINE_N2 COMPUTE STATISTICS;
ANALYZE INDEX FI_AUTO_JOURNAL_LINE_N3 COMPUTE STATISTICS;

