CREATE OR REPLACE VIEW FI_ACCOUNT_TYPE_V AS
SELECT FC.COMMON_ID AS ACCOUNT_TYPE_ID
     , FC.GROUP_CODE
     , FC.CODE AS ACCOUNT_TYPE
     , FC.CODE_NAME AS ACCOUNT_TYPE_NAME
     , NVL(FC.VALUE1, 'N') AS SUPPLIER_YN
     , NVL(FC.VALUE2, 'N') AS CUSTOMER_YN
     , FC.VALUE3 AS DEPOSIT_GB
     , FC.VALUE4
     , FC.VALUE5
     , FC.VALUE6
     , FC.VALUE7
     , FC.VALUE8
     , FC.VALUE9
     , FC.VALUE10
     , FC.DEFAULT_FLAG
     , FC.SORT_NUM
     , FC.DESCRIPTION
     , FC.ENABLED_FLAG
     , FC.EFFECTIVE_DATE_FR
     , FC.EFFECTIVE_DATE_TO
     , FC.SOB_ID
     , FC.ORG_ID
  FROM FI_COMMON_TLV FC
 WHERE FC.GROUP_CODE              = 'ACCOUNT_TYPE';
