/******************************************************************************/
/* Project      : FPCB ERP
/* Module       : FCM - GL
/* Program Name : FI_ACCOUNT_CONTROL
/* Description  : 회계 계정 통제 관리
/*
/* Reference by :
/* Program History
/*------------------------------------------------------------------------------
/*   Date       In Charge          Description
/*------------------------------------------------------------------------------
/* 07-JUN-2010  Jeon Ho Su          Initialize
/******************************************************************************/
CREATE TABLE FI_ACCOUNT_CONTROL              
( ACCOUNT_CONTROL_ID    NUMBER          NOT NULL,	/* 계정관리 ID */
  SOB_ID                NUMBER          NOT NULL,
  ORG_ID                NUMBER          NOT NULL,
  ACCOUNT_CODE          VARCHAR2(20)    NOT NULL,	/* 계정코드 */
  ACCOUNT_DESC          VARCHAR2(100)   NOT NULL,	/* 계정명 */
  ACCOUNT_DESC_S        VARCHAR2(100)   ,	 /* 계정명 약어 */
  ACCOUNT_SET_ID        NUMBER          NOT NULL,	/* 계정관리ID */
  ACCOUNT_GROUP_ID      NUMBER          NOT NULL,	/* 계정그룹 ID */
  ACCOUNT_DR_CR      	  VARCHAR2(1)     NOT NULL,       /* 차대 구분 (1-차변, 2-대변) */
  ACCOUNT_GL_ID         NUMBER          ,  /* 원장관리구분 */
  ACCOUNT_FS_TYPE       VARCHAR2(10)    ,  /* 재무제표관리구분 */
  CUSTOMER_ENABLED_FLAG VARCHAR2(1)     ,  /* 거래처 잔액관리FLAG */  
  ACCOUNT_ENABLED_FLAG  VARCHAR2(1)     ,  /* 계정잔액관리FLAG */  
  BANK_ACCOUNT_FLAG     VARCHAR2(1)     ,  /* 은행계좌관리 FLAG */
  CURRENCY_ENABLED_FLAG VARCHAR2(1)     ,  /* 외화관리FLAG */  
  ACCOUNT_MICH_YN       VARCHAR2(1)     ,  /* 개별반제 미청산 계정 FLAG */
  VAT_ENABLED_FLAG      VARCHAR2(1)     ,  /* 부가세관리FLAG */
  BUDGET_ENABLED_FLAG   VARCHAR2(1)     ,  /* 예산사용FLAG */
  BUDGET_CONTROL_FLAG   VARCHAR2(1)     ,  /* 예산통제FLAG */
  BUDGET_BELONG_FLAG    VARCHAR2(1)     ,  /* 예산귀속부서FLAG */
  COST_CENTER_FLAG      VARCHAR2(1)     ,  /* 코스트센타FLAG */  
  LIQUIDATE_METHOD_TYPE VARCHAR2(10)    ,  /* 반제처리 방법 */
  ACCOUNT_CLASS_ID      NUMBER          ,  /* 계정분류ID */
  REMARK                VARCHAR2(200)   ,	 /* 계정설명 */  
  ENABLED_FLAG          VARCHAR2(1)     DEFAULT 'Y',	 /* 사용여부 */
  EFFECTIVE_DATE_FR     DATE            NOT NULL,	/* 적용 시작일자 */
  EFFECTIVE_DATE_TO     DATE            ,	 /* 적용 종료일자 */  
  CREATION_DATE         DATE            NOT NULL,	/* 생성일자 */
  CREATED_BY            NUMBER          NOT NULL,	/* 생성자 */
  LAST_UPDATE_DATE      DATE            NOT NULL,	/* 최종수정일자 */
  LAST_UPDATED_BY       NUMBER          NOT NULL 	/* 최종수정자 */
) TABLESPACE FCM_TS_DATA;

-- Add comments to the columns 
COMMENT ON TABLE FI_ACCOUNT_CONTROL IS '계정관리';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL.ACCOUNT_CONTROL_ID IS '계정관리 ID';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL.ACCOUNT_CODE IS '계정코드';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL.ACCOUNT_DESC IS '계정명';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL.ACCOUNT_DESC_S IS '계정명 약어';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL.ACCOUNT_SET_ID IS '계정관리ID';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL.ACCOUNT_GROUP_ID IS '계정그룹 ID';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL.ACCOUNT_DR_CR IS '차대구분(1-차변,2-대변)';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL.ACCOUNT_GL_ID IS '원장관리';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL.ACCOUNT_FS_TYPE IS '재무제표관리';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL.CUSTOMER_ENABLED_FLAG IS '거래처관리(Y/N)';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL.ACCOUNT_ENABLED_FLAG IS '계정잔액관리(Y/N)';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL.BANK_ACCOUNT_FLAG IS '은행계좌 관리';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL.CURRENCY_ENABLED_FLAG IS '외화관리(Y/N)';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL.ACCOUNT_MICH_YN IS '개별 반제 미청산 계정(Y/N)';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL.VAT_ENABLED_FLAG IS '부가세관리(Y/N)';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL.BUDGET_ENABLED_FLAG IS '예산사용(Y/N)';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL.BUDGET_CONTROL_FLAG IS '예산통제(Y/N)';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL.BUDGET_BELONG_FLAG IS '예산귀속부서(Y/N)';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL.COST_CENTER_FLAG IS '코스트센타FLAG';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL.LIQUIDATE_METHOD_TYPE IS '반체처리방법';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL.ACCOUNT_CLASS_ID IS '계정 분류ID';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL.REMARK IS '비고';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL.ENABLED_FLAG IS '사용여부';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL.EFFECTIVE_DATE_FR IS '적용 시작일자';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL.EFFECTIVE_DATE_TO IS '적용 종료일자';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL.CREATION_DATE  IS '생성일자';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL.CREATED_BY IS '생성자';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL.LAST_UPDATE_DATE IS '최종수정일자';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL.LAST_UPDATED_BY IS '최종수정자';

-- CREATE INDEX.
CREATE UNIQUE INDEX FI_ACCOUNT_CONTROL_U1 ON FI_ACCOUNT_CONTROL(ACCOUNT_CONTROL_ID) TABLESPACE FCM_TS_IDX;
CREATE UNIQUE INDEX FI_ACCOUNT_CONTROL_U2 ON FI_ACCOUNT_CONTROL(ACCOUNT_GROUP_ID, SOB_ID) TABLESPACE FCM_TS_IDX;
CREATE UNIQUE INDEX FI_ACCOUNT_CONTROL_U3 ON FI_ACCOUNT_CONTROL(ACCOUNT_CODE, SOB_ID, ACCOUNT_SET_ID, ACCOUNT_GROUP_ID) TABLESPACE FCM_TS_IDX;
CREATE INDEX FI_ACCOUNT_CONTROL_N1 ON FI_ACCOUNT_CONTROL(ACCOUNT_GROUP_ID, SOB_ID, EFFECTIVE_DATE_FR, EFFECTIVE_DATE_TO) TABLESPACE FCM_TS_IDX;
CREATE INDEX FI_ACCOUNT_CONTROL_N2 ON FI_ACCOUNT_CONTROL(ACCOUNT_SET_ID, SOB_ID, EFFECTIVE_DATE_FR, EFFECTIVE_DATE_TO) TABLESPACE FCM_TS_IDX;

-- SEQUENCE.
DROP SEQUENCE FI_ACCOUNT_CONTROL_S1;
CREATE SEQUENCE FI_ACCOUNT_CONTROL_S1;

-- ANALYZE.
ANALYZE TABLE FI_ACCOUNT_CONTROL COMPUTE STATISTICS;
ANALYZE INDEX FI_ACCOUNT_CONTROL_U1 COMPUTE STATISTICS;
ANALYZE INDEX FI_ACCOUNT_CONTROL_U2 COMPUTE STATISTICS;
ANALYZE INDEX FI_ACCOUNT_CONTROL_N1 COMPUTE STATISTICS;
ANALYZE INDEX FI_ACCOUNT_CONTROL_N2 COMPUTE STATISTICS;
