-- CREATE TABLE
-- 내용년수 변경에 따른 추가 -- 
CREATE TABLE FI_ASSET_HISTORY_CG
(
  HISTORY_NUM              VARCHAR2(20) NOT NULL,
  CHARGE_DATE              DATE NOT NULL,
  SOB_ID                   NUMBER NOT NULL,
  ORG_ID                   NUMBER NOT NULL,
  ASSET_ID                 NUMBER NOT NULL,
  CHARGE_ID                NUMBER NOT NULL,
  CURRENCY_CODE            VARCHAR2(10),
  EXCHANGE_RATE            NUMBER,
  AMOUNT                   NUMBER,
  CURR_AMOUNT              NUMBER,
  QTY                      NUMBER,
  DEPT_ID                  NUMBER,
  LOCATION_ID              NUMBER,
  COST_CENTER_ID           NUMBER,
  BF_AMOUNT                NUMBER,
  BF_CURR_AMOUNT           NUMBER,
  BF_QTY                   NUMBER,
  BF_DEPT_ID               NUMBER,
  BF_LOCATION_ID           NUMBER,
  BF_COST_CENTER_ID        NUMBER,
  DESCRIPTION              VARCHAR2(200),
  DPR_SUM_AMOUNT           NUMBER DEFAULT 0,
  DPR_SUM_CURR_AMOUNT      NUMBER DEFAULT 0,
  IFRS_DPR_SUM_AMOUNT      NUMBER DEFAULT 0,
  IFRS_DPR_SUM_CURR_AMOUNT NUMBER DEFAULT 0,
  DPR_SUM_DC_AMOUNT        NUMBER DEFAULT 0,
  IFRS_DPR_SUM_DC_AMOUNT   NUMBER DEFAULT 0,
  CUSTOMER_ID              NUMBER,
  TAX_ISSUE_DATE           DATE,
  DISUSE_DATE              DATE,
  REFER_SLIP_DATE          DATE,
  REFER_SLIP_LINE_ID       NUMBER,
  REFER_REMARK             VARCHAR2(200),
  ACCOUNT_CONTROL_ID       NUMBER,
  GL_DATE                  DATE,
  SLIP_LINE_ID             NUMBER,
  REMARK                   VARCHAR2(200),
  CREATION_DATE            DATE NOT NULL,
  CREATED_BY               NUMBER NOT NULL,
  LAST_UPDATE_DATE         DATE NOT NULL,
  LAST_UPDATED_BY          NUMBER NOT NULL,
  TAX_CODE                 VARCHAR2(20),
  BF_TAX_CODE              VARCHAR2(20)
)
TABLESPACE FCM_TS_DATA
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE FI_ASSET_HISTORY_CG
  IS '자산변동내역';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.HISTORY_NUM
  IS '자산변동번호';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.CHARGE_DATE
  IS '변경일자';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.SOB_ID
  IS '회사아이디';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.ORG_ID
  IS '사업부어이디';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.ASSET_ID
  IS '자산아이디';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.CHARGE_ID
  IS '변경사유아이디';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.CURRENCY_CODE
  IS '통화';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.EXCHANGE_RATE
  IS '환율';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.AMOUNT
  IS '변동후 금액';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.CURR_AMOUNT
  IS '변동후 금액(외화)';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.QTY
  IS '변동후 수량';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.DEPT_ID
  IS '관리부서';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.LOCATION_ID
  IS '변동후 자산위치아이디';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.COST_CENTER_ID
  IS '변동후 원가아이디';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.BF_AMOUNT
  IS '변동전 금액';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.BF_CURR_AMOUNT
  IS '변동전 금액(외화)';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.BF_QTY
  IS '변동전 수량';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.BF_DEPT_ID
  IS '변동전 관리부서';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.BF_LOCATION_ID
  IS '변동전 위치ID';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.BF_COST_CENTER_ID
  IS '변동전 코스트센터';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.DESCRIPTION
  IS '비고';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.DPR_SUM_AMOUNT
  IS '상각누계금액';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.DPR_SUM_CURR_AMOUNT
  IS '상각누계액(외화)';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.IFRS_DPR_SUM_AMOUNT
  IS 'IFRS 상각누계액';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.IFRS_DPR_SUM_CURR_AMOUNT
  IS 'IFRS 상각누계액(외화)';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.DPR_SUM_DC_AMOUNT
  IS '충당금 감소액';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.IFRS_DPR_SUM_DC_AMOUNT
  IS 'IFRS 충당금 감소액';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.CUSTOMER_ID
  IS '매각 거래처ID';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.TAX_ISSUE_DATE
  IS '세금계산서일자';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.DISUSE_DATE
  IS '폐기일자';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.REFER_SLIP_DATE
  IS '참고 전표일자';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.REFER_SLIP_LINE_ID
  IS '참고 전표라인ID';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.REFER_REMARK
  IS '참고 적요';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.ACCOUNT_CONTROL_ID
  IS '계정ID';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.GL_DATE
  IS '전표일자';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.SLIP_LINE_ID
  IS '전표라인ID';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.REMARK
  IS '전표 적요';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.CREATION_DATE
  IS '생성일자';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.CREATED_BY
  IS '생성자';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.LAST_UPDATE_DATE
  IS '최종수정일자';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.LAST_UPDATED_BY
  IS '최종수정자';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.TAX_CODE
  IS '사업장 코드';
COMMENT ON COLUMN FI_ASSET_HISTORY_CG.BF_TAX_CODE
  IS '변동전 사업장 코드';
-- CREATE/RECREATE INDEXES 
CREATE INDEX FI_ASSET_HISTORY_CG_N1 ON FI_ASSET_HISTORY_CG (CHARGE_DATE, SOB_ID, CHARGE_ID)
  TABLESPACE FCM_TS_IDX
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
CREATE INDEX FI_ASSET_HISTORY_CG_N2 ON FI_ASSET_HISTORY_CG (ASSET_ID)
  TABLESPACE FCM_TS_IDX
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE FI_ASSET_HISTORY_CG
  ADD CONSTRAINT FI_ASSET_HISTORY_CG_PK PRIMARY KEY (HISTORY_NUM)
  USING INDEX 
  TABLESPACE FCM_TS_IDX
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
