/******************************************************************************/
/* Project      : FPCB ERP
/* Module       : FCM
/* Program Name : FI_ASSET_CATEGORY
/* Description  : 고정자산 유형 MASTER.
/*
/* Reference by :
/* Program History
/*------------------------------------------------------------------------------
/*   Date       In Charge          Description
/*------------------------------------------------------------------------------
/* 07-JUN-2010  Jeon Ho Su          Initialize
/******************************************************************************/
CREATE TABLE FI_ASSET_CATEGORY (
  AST_CATEGORY_ID                 NUMBER          NOT NULL,
  AST_CATEGORY_CODE               VARCHAR2(10)    NOT NULL,
  AST_CATEGORY_NAME               VARCHAR2(100)   NOT NULL,
  SOB_ID                          NUMBER          NOT NULL,
  AST_CATEGROY_LEVEL              NUMBER          DEFAULT 1,
  UPPER_AST_CATEGORY_ID           NUMBER          ,
  ASSET_TYPE                      VARCHAR2(10)    ,  
  AST_ACCOUNT_CONTROL_ID          NUMBER          ,
  AST_ACCOUNT_CODE                VARCHAR2(20)    ,
  DPR_METHOD_TYPE                 VARCHAR2(10)    ,
  PROGRESS_YEAR                   NUMBER          DEFAULT 0,
  RESIDUAL_AMOUNT                 NUMBER          DEFAULT 0,
  IFRS_DPR_METHOD_TYPE            VARCHAR2(10)    ,
  IFRS_PROGRESS_YEAR              NUMBER          DEFAULT 0,  
  IFRS_RESIDUAL_AMOUNT            NUMBER          DEFAULT 0,
  REMARK                          VARCHAR2(200)   ,
  ATTRIBUTE_A                     VARCHAR2(200)   ,
  ATTRIBUTE_B                     VARCHAR2(200)   ,
  ATTRIBUTE_C                     VARCHAR2(200)   ,
  ATTRIBUTE_D                     VARCHAR2(200)   ,
  ATTRIBUTE_E                     VARCHAR2(200)   ,
  ATTRIBUTE_1                     NUMBER          ,
  ATTRIBUTE_2                     NUMBER          ,
  ATTRIBUTE_3                     NUMBER          ,
  ATTRIBUTE_4                     NUMBER          ,
  ATTRIBUTE_5                     NUMBER          ,
  ENABLED_FLAG                    CHAR(1)         DEFAULT 'Y',
  EFFECTIVE_DATE_FR               DATE            NOT NULL,
  EFFECTIVE_DATE_TO               DATE            ,
  CREATION_DATE                   DATE            NOT NULL,
  CREATED_BY                      NUMBER          NOT NULL,
  LAST_UPDATE_DATE                DATE            NOT NULL,
  LAST_UPDATED_BY                 NUMBER          NOT NULL   
)TABLESPACE FCM_TS_DATA;

COMMENT ON TABLE FI_ASSET_CATEGORY  IS '고정자산_카테고리유형';
COMMENT ON COLUMN FI_ASSET_CATEGORY.AST_CATEGORY_ID IS '고정자산_범주ID';
COMMENT ON COLUMN FI_ASSET_CATEGORY.AST_CATEGORY_CODE IS '고정자산_범주CODE';
COMMENT ON COLUMN FI_ASSET_CATEGORY.AST_CATEGORY_NAME IS '고정자산_범주명';
COMMENT ON COLUMN FI_ASSET_CATEGORY.SOB_ID IS '회계조직';
COMMENT ON COLUMN FI_ASSET_CATEGORY.AST_CATEGROY_LEVEL IS '자산 범주 레벨';
COMMENT ON COLUMN FI_ASSET_CATEGORY.UPPER_AST_CATEGORY_ID IS '상위 자산범주 ID';
COMMENT ON COLUMN FI_ASSET_CATEGORY.ASSET_TYPE IS '자산형태(1:유형자산, 2:무형자산)';
COMMENT ON COLUMN FI_ASSET_CATEGORY.AST_ACCOUNT_CONTROL_ID IS '자산계정 ID';
COMMENT ON COLUMN FI_ASSET_CATEGORY.AST_ACCOUNT_CODE IS '자산계정코드';
COMMENT ON COLUMN FI_ASSET_CATEGORY.DPR_METHOD_TYPE IS '상각구분 1:정액,2:정율';
COMMENT ON COLUMN FI_ASSET_CATEGORY.PROGRESS_YEAR IS '내용년수';
COMMENT ON COLUMN FI_ASSET_CATEGORY.RESIDUAL_AMOUNT IS '잔존가치';
COMMENT ON COLUMN FI_ASSET_CATEGORY.IFRS_DPR_METHOD_TYPE   IS  'IFRS_상각구분 1:정액,2:정율';
COMMENT ON COLUMN FI_ASSET_CATEGORY.IFRS_PROGRESS_YEAR IS 'IFRS_내용년수';
COMMENT ON COLUMN FI_ASSET_CATEGORY.IFRS_RESIDUAL_AMOUNT IS 'IFRS 잔존가치';
COMMENT ON COLUMN FI_ASSET_CATEGORY.REMARK IS '비고';
COMMENT ON COLUMN FI_ASSET_CATEGORY.ENABLED_FLAG IS '사용여부';
COMMENT ON COLUMN FI_ASSET_CATEGORY.EFFECTIVE_DATE_FR IS '적용 시작일자';
COMMENT ON COLUMN FI_ASSET_CATEGORY.EFFECTIVE_DATE_TO IS '적용 종료일자';
COMMENT ON COLUMN FI_ASSET_CATEGORY.CREATION_DATE IS '생성일자';
COMMENT ON COLUMN FI_ASSET_CATEGORY.CREATED_BY IS '생성자';
COMMENT ON COLUMN FI_ASSET_CATEGORY.LAST_UPDATE_DATE IS '최종수정일자';
COMMENT ON COLUMN FI_ASSET_CATEGORY.LAST_UPDATED_BY IS '최종수정자';

ALTER TABLE FI_ASSET_CATEGORY ADD CONSTRAINT FI_ASSET_CATEGORY_PK PRIMARY KEY (AST_CATEGORY_ID);

CREATE UNIQUE INDEX FI_ASSET_CATEGORY_U1 ON FI_ASSET_CATEGORY(AST_CATEGORY_CODE, SOB_ID, AST_CATEGROY_LEVEL) TABLESPACE FCM_TS_IDX;
CREATE INDEX FI_ASSET_CATEGORY_N1 ON FI_ASSET_CATEGORY(AST_CATEGORY_ID, SOB_ID, ENABLED_FLAG, EFFECTIVE_DATE_FR, EFFECTIVE_DATE_TO) TABLESPACE FCM_TS_IDX;
CREATE INDEX FI_ASSET_CATEGORY_N2 ON FI_ASSET_CATEGORY(AST_CATEGROY_LEVEL, SOB_ID, ENABLED_FLAG, EFFECTIVE_DATE_FR, EFFECTIVE_DATE_TO) TABLESPACE FCM_TS_IDX;
CREATE INDEX FI_ASSET_CATEGORY_N3 ON FI_ASSET_CATEGORY(UPPER_AST_CATEGORY_ID, SOB_ID) TABLESPACE FCM_TS_IDX;

-- SEQUENCE.
CREATE SEQUENCE FI_ASSET_CATEGORY_S1;

-- ANALYZE.
ANALYZE TABLE FI_ASSET_CATEGORY COMPUTE STATISTICS;
ANALYZE INDEX FI_ASSET_CATEGORY_U1 COMPUTE STATISTICS;
ANALYZE INDEX FI_ASSET_CATEGORY_N1 COMPUTE STATISTICS;
