/******************************************************************************/
/* Project      : FPCB ERP
/* Module       : FCM
/* Program Name : FI_AUTO_JOURNAL_HEADER
/* Description  : 자동분개 헤더 정의.
/*
/* Reference by :
/* Program History
/*------------------------------------------------------------------------------
/*   Date       In Charge          Description
/*------------------------------------------------------------------------------
/* 07-JUN-2010  Jeon Ho Su          Initialize
/******************************************************************************/
CREATE TABLE FI_AUTO_JOURNAL_HEADER
( JOURNAL_HEADER_ID               NUMBER        NOT NULL
, SOB_ID                          NUMBER        NOT NULL
, ORG_ID                          NUMBER        NOT NULL
, SLIP_TYPE                       VARCHAR2(10)  NOT NULL
, JOB_CATEGORY_CODE               VARCHAR2(10)  NOT NULL
, JOB_CODE                        VARCHAR2(10)  NOT NULL
, JOB_NAME                        VARCHAR2(150) NOT NULL
, JOURNAL_TAG                     VARCHAR2(100) 
, DESCRIPTION                     VARCHAR2(150)
, ENABLED_FLAG                    CHAR(1)       DEFAULT 'Y'
, EFFECTIVE_DATE_FR               DATE          NOT NULL
, EFFECTIVE_DATE_TO               DATE          
, CREATION_DATE                   DATE          NOT NULL
, CREATED_BY                      NUMBER        NOT NULL
, LAST_UPDATE_DATE                DATE          NOT NULL
, LAST_UPDATED_BY                 NUMBER        NOT NULL
) TABLESPACE FCM_TS_DATA;

COMMENT ON TABLE APPS.FI_AUTO_JOURNAL_HEADER  IS '자동분개 유형 정의-HEADER';
COMMENT ON COLUMN APPS.FI_AUTO_JOURNAL_HEADER.JOURNAL_HEADER_ID IS '자동분개 헤더 ID';
COMMENT ON COLUMN APPS.FI_AUTO_JOURNAL_HEADER.SOB_ID IS '회계조직';
COMMENT ON COLUMN APPS.FI_AUTO_JOURNAL_HEADER.SLIP_TYPE IS '전표유형';
COMMENT ON COLUMN APPS.FI_AUTO_JOURNAL_HEADER.JOB_CATEGORY_CODE IS '업무 카테고리';
COMMENT ON COLUMN APPS.FI_AUTO_JOURNAL_HEADER.JOB_CODE IS '업무코드';
COMMENT ON COLUMN APPS.FI_AUTO_JOURNAL_HEADER.JOB_NAME IS '업무유형';
COMMENT ON COLUMN APPS.FI_AUTO_JOURNAL_HEADER.JOURNAL_TAG IS '분개유형 TAG';
COMMENT ON COLUMN APPS.FI_AUTO_JOURNAL_HEADER.DESCRIPTION IS '공통 적요';
COMMENT ON COLUMN APPS.FI_AUTO_JOURNAL_HEADER.ENABLED_FLAG IS '사용';
COMMENT ON COLUMN APPS.FI_AUTO_JOURNAL_HEADER.EFFECTIVE_DATE_FR IS '적용 시작일자';
COMMENT ON COLUMN APPS.FI_AUTO_JOURNAL_HEADER.EFFECTIVE_DATE_TO IS '적용 종료일자';
COMMENT ON COLUMN APPS.FI_AUTO_JOURNAL_HEADER.CREATION_DATE IS '생성일자';
COMMENT ON COLUMN APPS.FI_AUTO_JOURNAL_HEADER.CREATED_BY IS '생성자';
COMMENT ON COLUMN APPS.FI_AUTO_JOURNAL_HEADER.LAST_UPDATE_DATE IS '최종수정일자';
COMMENT ON COLUMN APPS.FI_AUTO_JOURNAL_HEADER.LAST_UPDATED_BY IS '최종수정자';


CREATE UNIQUE INDEX FI_AUTO_JOURNAL_HEADER_PK ON 
  FI_AUTO_JOURNAL_HEADER(SLIP_TYPE, JOB_CATEGORY_CODE, JOB_CODE, SOB_ID)
  TABLESPACE FCM_TS_IDX
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  LOGGING
  STORAGE (
           INITIAL 64K
           MINEXTENTS 1
           MAXEXTENTS 2147483645
          );
          
ALTER TABLE FI_AUTO_JOURNAL_HEADER ADD (                                  
  CONSTRAINT FI_AUTO_JOURNAL_HEADER_PK PRIMARY KEY (SLIP_TYPE, JOB_CATEGORY_CODE, JOB_CODE, SOB_ID)
          );                                                    

CREATE UNIQUE INDEX FI_AUTO_JOURNAL_HEADER_U1 ON FI_AUTO_JOURNAL_HEADER(JOURNAL_HEADER_ID) TABLESPACE FCM_TS_IDX;

-- SEQUENCE.
DROP SEQUENCE FI_AUTO_JOURNAL_HEADER_S1;
CREATE SEQUENCE FI_AUTO_JOURNAL_HEADER_S1;

-- ANALYZE.
ANALYZE TABLE FI_AUTO_JOURNAL_HEADER COMPUTE STATISTICS;
ANALYZE INDEX FI_AUTO_JOURNAL_HEADER_U1 COMPUTE STATISTICS;
