-- CREATE TABLE
-- 2013-10-21 전호수 변경  
-- 변경된 자산카테고리 
CREATE TABLE FI_ASSET_CATEGORY_CG
(
  ASSET_CATEGORY_ID          NUMBER NOT NULL,
  ASSET_CATEGORY_CODE        VARCHAR2(10) NOT NULL,
  ASSET_CATEGORY_NAME        VARCHAR2(100) NOT NULL,
  SOB_ID                     NUMBER NOT NULL,
  EXPENSE_TYPE               VARCHAR2(10),
  ASSET_TYPE                 VARCHAR2(10) NOT NULL,
  DPR_METHOD_TYPE            VARCHAR2(10),
  PROGRESS_YEAR              NUMBER DEFAULT 0,
  RESIDUAL_AMOUNT            NUMBER DEFAULT 0,
  IFRS_DPR_METHOD_TYPE       VARCHAR2(10),
  IFRS_PROGRESS_YEAR         NUMBER DEFAULT 0,
  IFRS_RESIDUAL_AMOUNT       NUMBER DEFAULT 0,
  AST_ACCOUNT_CONTROL_ID     NUMBER,
  AST_ACCOUNT_CODE           VARCHAR2(20),
  DPR_ACCOUNT_CONTROL_ID     NUMBER,
  DPR_ACCOUNT_CODE           VARCHAR2(20),
  DPR_SUM_ACCOUNT_CONTROL_ID NUMBER,
  DPR_SUM_ACCOUNT_CODE       VARCHAR2(20),
  REMARK                     VARCHAR2(200),
  ATTRIBUTE_A                VARCHAR2(200),
  ATTRIBUTE_B                VARCHAR2(200),
  ATTRIBUTE_C                VARCHAR2(200),
  ATTRIBUTE_D                VARCHAR2(200),
  ATTRIBUTE_E                VARCHAR2(200),
  ATTRIBUTE_1                NUMBER,
  ATTRIBUTE_2                NUMBER,
  ATTRIBUTE_3                NUMBER,
  ATTRIBUTE_4                NUMBER,
  ATTRIBUTE_5                NUMBER,
  ENABLED_FLAG               CHAR(1) DEFAULT 'Y',
  EFFECTIVE_DATE_FR          DATE,
  EFFECTIVE_DATE_TO          DATE,
  CREATION_DATE              DATE NOT NULL,
  CREATED_BY                 NUMBER NOT NULL,
  LAST_UPDATE_DATE           DATE NOT NULL,
  LAST_UPDATED_BY            NUMBER NOT NULL
)
TABLESPACE FCM_TS_DATA
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE FI_ASSET_CATEGORY_CG
  IS '(고정)자산유형관리';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN FI_ASSET_CATEGORY_CG.ASSET_CATEGORY_ID
  IS '자산유형아이디';
COMMENT ON COLUMN FI_ASSET_CATEGORY_CG.ASSET_CATEGORY_CODE
  IS '자산유형코드';
COMMENT ON COLUMN FI_ASSET_CATEGORY_CG.ASSET_CATEGORY_NAME
  IS '자산유형명칭';
COMMENT ON COLUMN FI_ASSET_CATEGORY_CG.SOB_ID
  IS '회사아이디';
COMMENT ON COLUMN FI_ASSET_CATEGORY_CG.EXPENSE_TYPE
  IS '경비구분';
COMMENT ON COLUMN FI_ASSET_CATEGORY_CG.ASSET_TYPE
  IS '자산형태';
COMMENT ON COLUMN FI_ASSET_CATEGORY_CG.DPR_METHOD_TYPE
  IS '상각구분';
COMMENT ON COLUMN FI_ASSET_CATEGORY_CG.PROGRESS_YEAR
  IS '내용년수';
COMMENT ON COLUMN FI_ASSET_CATEGORY_CG.RESIDUAL_AMOUNT
  IS '잔존가치';
COMMENT ON COLUMN FI_ASSET_CATEGORY_CG.IFRS_DPR_METHOD_TYPE
  IS '(IFRS)감가상각방법';
COMMENT ON COLUMN FI_ASSET_CATEGORY_CG.IFRS_PROGRESS_YEAR
  IS '(IFRS)내용년수';
COMMENT ON COLUMN FI_ASSET_CATEGORY_CG.IFRS_RESIDUAL_AMOUNT
  IS '(IFRS)잔존가치';
COMMENT ON COLUMN FI_ASSET_CATEGORY_CG.AST_ACCOUNT_CONTROL_ID
  IS '자산계정 ID';
COMMENT ON COLUMN FI_ASSET_CATEGORY_CG.AST_ACCOUNT_CODE
  IS '자산계정코드';
COMMENT ON COLUMN FI_ASSET_CATEGORY_CG.DPR_ACCOUNT_CONTROL_ID
  IS '상각비 계정 ID';
COMMENT ON COLUMN FI_ASSET_CATEGORY_CG.DPR_ACCOUNT_CODE
  IS '상각비 계정코드';
COMMENT ON COLUMN FI_ASSET_CATEGORY_CG.DPR_SUM_ACCOUNT_CONTROL_ID
  IS '상각누계 계정 ID';
COMMENT ON COLUMN FI_ASSET_CATEGORY_CG.DPR_SUM_ACCOUNT_CODE
  IS '상각누계 계정코드';
COMMENT ON COLUMN FI_ASSET_CATEGORY_CG.REMARK
  IS '비고';
COMMENT ON COLUMN FI_ASSET_CATEGORY_CG.ENABLED_FLAG
  IS '사용여부';
COMMENT ON COLUMN FI_ASSET_CATEGORY_CG.EFFECTIVE_DATE_FR
  IS '적용 시작일자';
COMMENT ON COLUMN FI_ASSET_CATEGORY_CG.EFFECTIVE_DATE_TO
  IS '적용 종료일자';
COMMENT ON COLUMN FI_ASSET_CATEGORY_CG.CREATION_DATE
  IS '생성일자';
COMMENT ON COLUMN FI_ASSET_CATEGORY_CG.CREATED_BY
  IS '생성자';
COMMENT ON COLUMN FI_ASSET_CATEGORY_CG.LAST_UPDATE_DATE
  IS '최종수정일자';
COMMENT ON COLUMN FI_ASSET_CATEGORY_CG.LAST_UPDATED_BY
  IS '최종수정자';
-- CREATE/RECREATE INDEXES 
CREATE INDEX FI_ASSET_CATEGORY_CG_N1 ON FI_ASSET_CATEGORY_CG (ASSET_CATEGORY_ID, ENABLED_FLAG, EFFECTIVE_DATE_FR, EFFECTIVE_DATE_TO)
  TABLESPACE FCM_TS_IDX
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
CREATE UNIQUE INDEX FI_ASSET_CATEGORY_CG_U1 ON FI_ASSET_CATEGORY_CG (ASSET_CATEGORY_ID)
  TABLESPACE FCM_TS_IDX
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE FI_ASSET_CATEGORY_CG
  ADD CONSTRAINT FI_ASSET_CATEGORY_CG_PK PRIMARY KEY (ASSET_CATEGORY_CODE, SOB_ID)
  USING INDEX 
  TABLESPACE FCM_TS_IDX
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
