-- CREATE TABLE
-- 내용년수 변경데 따른 생성
CREATE TABLE FI_ASSET_MASTER_CG
(
  ASSET_ID                 NUMBER NOT NULL,
  ASSET_CODE               VARCHAR2(20) NOT NULL,
  ASSET_DESC               VARCHAR2(150) NOT NULL,
  SOB_ID                   NUMBER NOT NULL,
  ORG_ID                   NUMBER NOT NULL,
  EXPENSE_TYPE             VARCHAR2(10) NOT NULL,
  ASSET_CATEGORY_ID        NUMBER NOT NULL,
  SPEC                     VARCHAR2(100),
  PURPOSE                  VARCHAR2(150),
  ACQUIRE_DATE             DATE,
  REGISTER_DATE            DATE,
  LOCATION_ID              NUMBER,
  LOCATION_DESC            VARCHAR2(150),
  QTY                      NUMBER,
  UOM_CODE                 VARCHAR2(10),
  INVEST_ID                NUMBER,
  UNIT_PRICE               NUMBER,
  CURRENCY_CODE            VARCHAR2(10),
  EXCHANGE_RATE            NUMBER,
  CURR_AMOUNT              NUMBER,
  AMOUNT                   NUMBER,
  DPR_YN                   CHAR(1) DEFAULT 'N',
  DPR_METHOD_TYPE          VARCHAR2(10) NOT NULL,
  DPR_PROGRESS_YEAR        NUMBER DEFAULT 0,
  RESIDUAL_AMOUNT          NUMBER DEFAULT 0,
  DPR_STATUS_CODE          VARCHAR2(10),
  DPR_SUM_CURR_AMOUNT      NUMBER DEFAULT 0,
  DPR_SUM_AMOUNT           NUMBER DEFAULT 0,
  DPR_TOTAL_COUNT          NUMBER DEFAULT 0,
  DPR_LAST_PERIOD          VARCHAR2(7),
  IFRS_DPR_YN              CHAR(1) DEFAULT 'N',
  IFRS_DPR_METHOD_TYPE     VARCHAR2(10) NOT NULL,
  IFRS_PROGRESS_YEAR       NUMBER DEFAULT 0,
  IFRS_RESIDUAL_AMOUNT     NUMBER DEFAULT 0,
  IFRS_DPR_STATUS_CODE     VARCHAR2(10),
  IFRS_DPR_SUM_CURR_AMOUNT NUMBER DEFAULT 0,
  IFRS_DPR_SUM_AMOUNT      NUMBER DEFAULT 0,
  IFRS_DPR_TOTAL_COUNT     NUMBER DEFAULT 0,
  IFRS_DPR_LAST_PERIOD     VARCHAR2(7),
  VENDOR_ID                NUMBER,
  MANAGE_DEPT_ID           NUMBER,
  COST_CENTER_ID           NUMBER,
  ASSET_STATUS_CODE        VARCHAR2(10),
  DISUSE_DATE              DATE,
  REMARK                   VARCHAR2(200),
  SOURCE_TABLE             VARCHAR2(100),
  SOURCE_HEADER_ID         NUMBER,
  SOURCE_LINE_ID           NUMBER,
  ATTRIBUTE_A              VARCHAR2(200),
  ATTRIBUTE_B              VARCHAR2(200),
  ATTRIBUTE_C              VARCHAR2(200),
  ATTRIBUTE_D              VARCHAR2(200),
  ATTRIBUTE_E              VARCHAR2(200),
  ATTRIBUTE_1              NUMBER,
  ATTRIBUTE_2              NUMBER,
  ATTRIBUTE_3              NUMBER,
  ATTRIBUTE_4              NUMBER,
  ATTRIBUTE_5              NUMBER,
  CREATION_DATE            DATE NOT NULL,
  CREATED_BY               NUMBER NOT NULL,
  LAST_UPDATE_DATE         DATE NOT NULL,
  LAST_UPDATED_BY          NUMBER NOT NULL,
  TAX_CODE                 VARCHAR2(20)
)
TABLESPACE FCM_TS_DATA
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 448K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE FI_ASSET_MASTER_CG
  IS '자산대장';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN FI_ASSET_MASTER_CG.ASSET_ID
  IS '자산아이디';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.ASSET_CODE
  IS '자산코드';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.ASSET_DESC
  IS '자산명';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.SOB_ID
  IS '회사아이디';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.ORG_ID
  IS '사업부아이디';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.EXPENSE_TYPE
  IS '경비구분';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.ASSET_CATEGORY_ID
  IS '자산유형아이디';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.SPEC
  IS '규격';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.PURPOSE
  IS '용도';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.ACQUIRE_DATE
  IS '취득일자';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.REGISTER_DATE
  IS '등록일자';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.LOCATION_ID
  IS '자산위치';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.LOCATION_DESC
  IS '설치장소';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.QTY
  IS '수량';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.UOM_CODE
  IS '단위';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.INVEST_ID
  IS '투자ID(CIP..)';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.UNIT_PRICE
  IS '단가';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.CURRENCY_CODE
  IS '통화';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.EXCHANGE_RATE
  IS '환율';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.CURR_AMOUNT
  IS '외화금액';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.AMOUNT
  IS '취득금액';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.DPR_YN
  IS '상각여부 N:미상각,Y:상각';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.DPR_METHOD_TYPE
  IS '상각구분 1:정액,2:정율';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.DPR_PROGRESS_YEAR
  IS '내용년수';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.RESIDUAL_AMOUNT
  IS '잔존가액';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.DPR_STATUS_CODE
  IS '상각상태';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.DPR_SUM_CURR_AMOUNT
  IS '상각누계액(외화)';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.DPR_SUM_AMOUNT
  IS '상각누계액';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.DPR_TOTAL_COUNT
  IS '상각횟수';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.DPR_LAST_PERIOD
  IS '최종상각년월';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.IFRS_DPR_YN
  IS '(IFRS)상각여부 N:미상각,Y:상각';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.IFRS_DPR_METHOD_TYPE
  IS '(IFRS)감가상각방법';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.IFRS_PROGRESS_YEAR
  IS '(IFRS)내용년수';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.IFRS_RESIDUAL_AMOUNT
  IS '(IFRS)잔존가액';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.IFRS_DPR_STATUS_CODE
  IS '(IFRS)상각상태';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.IFRS_DPR_SUM_CURR_AMOUNT
  IS '(IFRS)상각누계액(외화)';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.IFRS_DPR_SUM_AMOUNT
  IS '(IFRS)상각누계액';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.IFRS_DPR_TOTAL_COUNT
  IS '(IFRS)상각횟수';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.IFRS_DPR_LAST_PERIOD
  IS '(IFRS)최종상각년월';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.VENDOR_ID
  IS '거래처아이디';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.MANAGE_DEPT_ID
  IS '관리부서아이디';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.COST_CENTER_ID
  IS '원가아이디';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.ASSET_STATUS_CODE
  IS '자산상태';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.DISUSE_DATE
  IS '폐기(매각)일자';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.REMARK
  IS '적요';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.SOURCE_TABLE
  IS 'INTERFACE 테이블';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.SOURCE_HEADER_ID
  IS 'INTERFACE HEADER ID';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.SOURCE_LINE_ID
  IS 'INTERFACE LINE ID';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.CREATION_DATE
  IS '생성일자';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.CREATED_BY
  IS '생성자';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.LAST_UPDATE_DATE
  IS '최종수정일자';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.LAST_UPDATED_BY
  IS '최종수정자';
COMMENT ON COLUMN FI_ASSET_MASTER_CG.TAX_CODE
  IS '사업장코드(공통코드:TAX_CODE)';
-- CREATE/RECREATE INDEXES 
CREATE INDEX FI_ASSET_MASTER_CG_N1 ON FI_ASSET_MASTER_CG (DPR_YN, SOB_ID)
  TABLESPACE FCM_TS_IDX
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 128K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
CREATE INDEX FI_ASSET_MASTER_CG_N2 ON FI_ASSET_MASTER_CG (IFRS_DPR_YN, SOB_ID)
  TABLESPACE FCM_TS_IDX
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 128K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
CREATE UNIQUE INDEX FI_ASSET_MASTER_CG_U1 ON FI_ASSET_MASTER_CG (ASSET_ID)
  TABLESPACE FCM_TS_IDX
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE FI_ASSET_MASTER_CG
  ADD CONSTRAINT FI_ASSET_MASTER_CG_PK PRIMARY KEY (ASSET_CODE, SOB_ID)
  USING INDEX 
  TABLESPACE FCM_TS_IDX
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 128K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
