CREATE OR REPLACE VIEW FI_ASSET_CATEGORY_V1 AS
SELECT ACT.AST_CATEGORY_ID AS AST_CATEGORY_ID
     , ACT.AST_CATEGORY_CODE AS AST_CATEGORY_CODE
     , ACT.AST_CATEGORY_NAME AS AST_CATEGORY_NAME
     , ACT.ASSET_TYPE
     , ACT.AST_ACCOUNT_CONTROL_ID
     , ACT.AST_ACCOUNT_CODE
     , ACT.DPR_METHOD_TYPE
     , ACT.PROGRESS_YEAR
     , ACT.RESIDUAL_AMOUNT
     , ACT.IFRS_DPR_METHOD_TYPE
     , ACT.IFRS_PROGRESS_YEAR
     , ACT.IFRS_RESIDUAL_AMOUNT
     , ACT.SOB_ID
     , ACL.AST_CATEGORY_ID AS AST_CLASS_ID
     , ACL.AST_CATEGORY_CODE AS AST_CLASS_CODE
     , ACL.AST_CATEGORY_NAME AS AST_CLASS_NAME
     , ACI.AST_CATEGORY_ID AS AST_ITEM_ID
     , ACI.AST_CATEGORY_CODE AS AST_ITEM_CODE
     , ACI.AST_CATEGORY_NAME AS AST_ITEM_NAME
  FROM FI_ASSET_CATEGORY ACT
    , FI_ASSET_CATEGORY ACL
    , FI_ASSET_CATEGORY ACI
WHERE ACT.AST_CATEGORY_ID   = ACL.UPPER_AST_CATEGORY_ID
  AND ACT.SOB_ID            = ACL.SOB_ID
  AND ACL.AST_CATEGORY_ID   = ACI.UPPER_AST_CATEGORY_ID
  AND ACL.SOB_ID            = ACI.SOB_ID;
