/******************************************************************************/
/* Project      : FPCB ERP
/* Module       : FCM
/* Program Name : FI_ASSET_MASTER
/* Description  : 고정자산 MASTER.
/*
/* Reference by :
/* Program History
/*------------------------------------------------------------------------------
/*   Date       In Charge          Description
/*------------------------------------------------------------------------------
/* 07-JUN-2010  Jeon Ho Su          Initialize
/******************************************************************************/
CREATE TABLE FI_ASSET_MASTER 
( ASSET_ID                        NUMBER          NOT NULL,
  ASSET_CODE                      VARCHAR2(20)    NOT NULL,
  ASSET_DESC                      VARCHAR2(150)   NOT NULL,
  SOB_ID                          NUMBER          NOT NULL,
  ORG_ID                          NUMBER          NOT NULL,
  AST_CATEGORY_ID                 NUMBER          NOT NULL,
  EXPENSE_TYPE                    VARCHAR2(10)    NOT NULL,
  ACQUIRE_DATE                    DATE            ,
  REGISTER_DATE                   DATE            ,
  QTY                             NUMBER          ,
  UOM_CODE                        VARCHAR2(10)    ,
  UNIT_PRICE                      NUMBER          ,
  CURRENCY_CODE                   VARCHAR2(10)    ,
  EXCHANGE_RATE                   NUMBER          ,  
  CURR_AMOUNT                     NUMBER          ,
  AMOUNT                          NUMBER          ,
  INVEST_ID                       NUMBER          ,
  ITEM_NAME                       VARCHAR2(200)   ,
  ITEM_SPEC                       VARCHAR2(100)   ,
  PURPOSE                         VARCHAR2(150)   ,
  LOCATION_ID                     NUMBER          ,
  INSTALL_PLACE                   VARCHAR2(150)   ,
  VENDOR_ID                       NUMBER          ,
  MANAGE_DEPT_ID                  NUMBER          ,
  USE_DEPT_ID                     NUMBER          ,
  FIRST_USER                      VARCHAR2(100)   ,
  SECOND_USER                     VARCHAR2(100)   ,
  COST_CENTER_ID                  NUMBER          ,
  HAVE_TYPE                       VARCHAR2(10)    ,
  LEASE_TYPE                      VARCHAR2(10)    ,
  TAX_DED_TYPE                    VARCHAR2(10)    ,
  ASSET_STATUS_CODE               VARCHAR2(10)    ,
  DISUSE_DATE                     DATE            ,
  REMARK                          VARCHAR2(200)   ,
  DPR_YN                          CHAR(1)         DEFAULT 'N',
  DPR_METHOD_TYPE                 VARCHAR2(10)    ,
  DPR_PROGRESS_YEAR               NUMBER          DEFAULT 0,  
  RESIDUAL_AMOUNT                 NUMBER          DEFAULT 0,
  DPR_STATUS_CODE                 VARCHAR2(10)    ,
  DPR_SUM_CURR_AMOUNT             NUMBER          DEFAULT 0,
  DPR_SUM_AMOUNT                  NUMBER          DEFAULT 0,
  DPR_TOTAL_COUNT                 NUMBER          DEFAULT 0,
  DPR_LAST_PERIOD                 VARCHAR2(7)     ,
  IFRS_DPR_YN                     CHAR(1)         DEFAULT 'N',
  IFRS_DPR_METHOD_TYPE            VARCHAR2(10)    ,
  IFRS_PROGRESS_YEAR              NUMBER          DEFAULT 0,  
  IFRS_RESIDUAL_AMOUNT            NUMBER          DEFAULT 0,
  IFRS_DPR_STATUS_CODE            VARCHAR2(10)    ,
  IFRS_DPR_SUM_CURR_AMOUNT        NUMBER          DEFAULT 0,
  IFRS_DPR_SUM_AMOUNT             NUMBER          DEFAULT 0,
  IFRS_DPR_TOTAL_COUNT            NUMBER          DEFAULT 0,
  IFRS_DPR_LAST_PERIOD            VARCHAR2(7)     ,
  SOURCE_TABLE                    VARCHAR2(100)   ,
  SOURCE_HEADER_ID                NUMBER          , 
  SOURCE_LINE_ID                  NUMBER          ,
  ATTRIBUTE_A                     VARCHAR2(200)   ,
  ATTRIBUTE_B                     VARCHAR2(200)   ,
  ATTRIBUTE_C                     VARCHAR2(200)   ,
  ATTRIBUTE_D                     VARCHAR2(200)   ,
  ATTRIBUTE_E                     VARCHAR2(200)   ,
  ATTRIBUTE_1                     NUMBER          ,
  ATTRIBUTE_2                     NUMBER          ,
  ATTRIBUTE_3                     NUMBER          ,
  ATTRIBUTE_4                     NUMBER          ,
  ATTRIBUTE_5                     NUMBER          ,  
  CREATION_DATE                   DATE            NOT NULL,
  CREATED_BY                      NUMBER          NOT NULL,
  LAST_UPDATE_DATE                DATE            NOT NULL,
  LAST_UPDATED_BY                 NUMBER          NOT NULL   
)TABLESPACE FCM_TS_DATA;

COMMENT ON TABLE FI_ASSET_MASTER  IS '고정자산 대장';
COMMENT ON COLUMN FI_ASSET_MASTER.ASSET_ID IS '고정자산 ID';
COMMENT ON COLUMN FI_ASSET_MASTER.ASSET_CODE IS '고정자산 CODE';
COMMENT ON COLUMN FI_ASSET_MASTER.ASSET_DESC IS '고정자산명';
COMMENT ON COLUMN FI_ASSET_MASTER.SOB_ID IS '회계조직';
COMMENT ON COLUMN FI_ASSET_MASTER.AST_CATEGORY_ID IS '자산카테고리ID';
COMMENT ON COLUMN FI_ASSET_MASTER.EXPENSE_TYPE IS '경비구분';
COMMENT ON COLUMN FI_ASSET_MASTER.ACQUIRE_DATE IS '취득일자';
COMMENT ON COLUMN FI_ASSET_MASTER.REGISTER_DATE IS '등록일자';
COMMENT ON COLUMN FI_ASSET_MASTER.QTY IS '수량';
COMMENT ON COLUMN FI_ASSET_MASTER.UOM_CODE IS '단위';
COMMENT ON COLUMN FI_ASSET_MASTER.UNIT_PRICE IS '단가';
COMMENT ON COLUMN FI_ASSET_MASTER.CURRENCY_CODE IS '통화';
COMMENT ON COLUMN FI_ASSET_MASTER.EXCHANGE_RATE IS '환율';
COMMENT ON COLUMN FI_ASSET_MASTER.CURR_AMOUNT IS '외화금액';
COMMENT ON COLUMN FI_ASSET_MASTER.AMOUNT IS '취득금액';
COMMENT ON COLUMN FI_ASSET_MASTER.INVEST_ID IS '투자ID(CIP..)';
COMMENT ON COLUMN FI_ASSET_MASTER.ITEM_NAME IS '품명';
COMMENT ON COLUMN FI_ASSET_MASTER.ITEM_SPEC IS '규격';
COMMENT ON COLUMN FI_ASSET_MASTER.PURPOSE IS '용도';
COMMENT ON COLUMN FI_ASSET_MASTER.LOCATION_ID IS '자산 위치';
COMMENT ON COLUMN FI_ASSET_MASTER.INSTALL_PLACE IS '설치장소';
COMMENT ON COLUMN FI_ASSET_MASTER.VENDOR_ID IS '거래처ID';
COMMENT ON COLUMN FI_ASSET_MASTER.MANAGE_DEPT_ID IS '관리부서';
COMMENT ON COLUMN FI_ASSET_MASTER.USE_DEPT_ID IS '사용부서';
COMMENT ON COLUMN FI_ASSET_MASTER.FIRST_USER IS '사용자-정';
COMMENT ON COLUMN FI_ASSET_MASTER.SECOND_USER IS '사용자-부';
COMMENT ON COLUMN FI_ASSET_MASTER.COST_CENTER_ID IS '원가ID';
COMMENT ON COLUMN FI_ASSET_MASTER.HAVE_TYPE IS '소유구분';
COMMENT ON COLUMN FI_ASSET_MASTER.LEASE_TYPE IS '리스자산 구분';
COMMENT ON COLUMN FI_ASSET_MASTER.TAX_DED_TYPE IS '세액공제 타입';
COMMENT ON COLUMN FI_ASSET_MASTER.ASSET_STATUS_CODE IS  '자산 상태';
COMMENT ON COLUMN FI_ASSET_MASTER.DISUSE_DATE IS '폐기(매각)일자';
COMMENT ON COLUMN FI_ASSET_MASTER.REMARK  IS  '적요';
COMMENT ON COLUMN FI_ASSET_MASTER.DPR_YN IS '상각여부 N:미상각,Y:상각';
COMMENT ON COLUMN FI_ASSET_MASTER.DPR_METHOD_TYPE IS '상각구분 1:정액,2:정율(DPR_METHOD_TYPE)';
COMMENT ON COLUMN FI_ASSET_MASTER.DPR_PROGRESS_YEAR IS '내용년수';
COMMENT ON COLUMN FI_ASSET_MASTER.RESIDUAL_AMOUNT IS '잔존가액';
COMMENT ON COLUMN FI_ASSET_MASTER.DPR_STATUS_CODE IS '자산상태';
COMMENT ON COLUMN FI_ASSET_MASTER.DPR_SUM_CURR_AMOUNT IS '상각누계액(외화)';
COMMENT ON COLUMN FI_ASSET_MASTER.DPR_SUM_AMOUNT IS '상각누계액';
COMMENT ON COLUMN FI_ASSET_MASTER.DPR_TOTAL_COUNT IS '상각횟수';
COMMENT ON COLUMN FI_ASSET_MASTER.DPR_LAST_PERIOD IS '최종상각년월';
COMMENT ON COLUMN FI_ASSET_MASTER.IFRS_DPR_YN IS '(IFRS)상각여부 N:미상각,Y:상각';
COMMENT ON COLUMN FI_ASSET_MASTER.IFRS_DPR_METHOD_TYPE IS '(IFRS)상각구분 1:정액,2:정율(DPR_METHOD_TYPE)';
COMMENT ON COLUMN FI_ASSET_MASTER.IFRS_PROGRESS_YEAR IS '(IFRS)내용년수';
COMMENT ON COLUMN FI_ASSET_MASTER.IFRS_RESIDUAL_AMOUNT IS '잔존가액';
COMMENT ON COLUMN FI_ASSET_MASTER.IFRS_DPR_STATUS_CODE IS '(IFRS)자산상태';
COMMENT ON COLUMN FI_ASSET_MASTER.IFRS_DPR_SUM_CURR_AMOUNT IS '(IFRS)상각누계액(외화)';
COMMENT ON COLUMN FI_ASSET_MASTER.IFRS_DPR_SUM_AMOUNT IS '(IFRS)상각누계액';
COMMENT ON COLUMN FI_ASSET_MASTER.IFRS_DPR_TOTAL_COUNT IS '(IFRS)상각횟수';
COMMENT ON COLUMN FI_ASSET_MASTER.IFRS_DPR_LAST_PERIOD IS '(IFRS)최종상각년월';
COMMENT ON COLUMN FI_ASSET_MASTER.SOURCE_TABLE IS 'INTERFACE 테이블';
COMMENT ON COLUMN FI_ASSET_MASTER.SOURCE_HEADER_ID IS 'INTERFACE HEADER ID';
COMMENT ON COLUMN FI_ASSET_MASTER.SOURCE_LINE_ID IS 'INTERFACE LINE ID';
COMMENT ON COLUMN FI_ASSET_MASTER.CREATION_DATE IS '생성일자';
COMMENT ON COLUMN FI_ASSET_MASTER.CREATED_BY IS '생성자';
COMMENT ON COLUMN FI_ASSET_MASTER.LAST_UPDATE_DATE IS '최종수정일자';
COMMENT ON COLUMN FI_ASSET_MASTER.LAST_UPDATED_BY IS '최종수정자';

-- INDEX.
ALTER TABLE FI_ASSET_MASTER ADD CONSTRAINT FI_ASSET_MASTER_PK PRIMARY KEY(ASSET_CODE, SOB_ID);

CREATE UNIQUE INDEX FI_ASSET_MASTER_U1 ON FI_ASSET_MASTER(ASSET_ID) TABLESPACE FCM_TS_IDX;
CREATE INDEX FI_ASSET_MASTER_N1 ON FI_ASSET_MASTER(ACQUIRE_DATE, SOB_ID) TABLESPACE FCM_TS_IDX;
CREATE INDEX FI_ASSET_MASTER_N2 ON FI_ASSET_MASTER(DPR_YN, SOB_ID) TABLESPACE FCM_TS_IDX;
CREATE INDEX FI_ASSET_MASTER_N3 ON FI_ASSET_MASTER(IFRS_DPR_YN, SOB_ID) TABLESPACE FCM_TS_IDX;

-- SEQUENCE.
CREATE SEQUENCE FI_ASSET_MASTER_S1;

-- ANALYZE.
ANALYZE TABLE FI_ASSET_MASTER COMPUTE STATISTICS;
ANALYZE INDEX FI_ASSET_MASTER_U1 COMPUTE STATISTICS;
ANALYZE INDEX FI_ASSET_MASTER_N1 COMPUTE STATISTICS;
ANALYZE INDEX FI_ASSET_MASTER_N2 COMPUTE STATISTICS;
ANALYZE INDEX FI_ASSET_MASTER_N3 COMPUTE STATISTICS;
