/******************************************************************************/
/* Project      : FPCB ERP
/* Module       : FCM
/* Program Name : FI_ACCOUNT_BOOK
/* Description  : 회계장부.
/*
/* Reference by :
/* Program History
/*------------------------------------------------------------------------------
/*   Date       In Charge          Description
/*------------------------------------------------------------------------------
/* 07-JUN-2010  Jeon Ho Su          Initialize
/******************************************************************************/
CREATE TABLE FI_ACCOUNT_BOOK
( ACCOUNT_BOOK_ID                 NUMBER          NOT NULL,
  SOB_ID                          NUMBER          NOT NULL,
  ACCOUNT_BOOK_CODE               VARCHAR2(50)    NOT NULL,
  ACCOUNT_BOOK_NAME               VARCHAR2(200)   ,
  ACCOUNT_BOOK_NAME_S             VARCHAR2(100)   ,
  ACCOUNT_SET_ID                  NUMBER          NOT NULL,
  FISCAL_CALENDAR_ID              NUMBER          NOT NULL,
  FUTURE_OPEN_PERIOD_COUNT        NUMBER          ,
  LATEST_OPENED_PERIOD_NAME       VARCHAR2(10)    , 
  CURRENCY_CODE                   VARCHAR2(10)    NOT NULL,
  EXCHANGE_RATE_TYPE              VARCHAR2(10)    NOT NULL,
  EXCHANGE_PROFIT_ACCOUNT_ID      NUMBER          NOT NULL,
  EXCHANGE_LOSS_ACCOUNT_ID        NUMBER          NOT NULL,
  BUDGET_CONTROL_YN               CHAR(1)         NOT NULL,
  DEPT_LEVEL                      NUMBER          NOT NULL,
  OPERATING_FLAG                  CHAR(1)         NOT NULL,
  REMARK                          VARCHAR2(250)   ,
  ATTRIBUTE_A                     VARCHAR2(250)   ,
  ATTRIBUTE_B                     VARCHAR2(250)   ,
  ATTRIBUTE_C                     VARCHAR2(250)   ,
  ATTRIBUTE_D                     VARCHAR2(250)   ,
  ATTRIBUTE_E                     VARCHAR2(250)   ,
  ATTRIBUTE_1                     NUMBER          ,
  ATTRIBUTE_2                     NUMBER          ,
  ATTRIBUTE_3                     NUMBER          ,
  ATTRIBUTE_4                     NUMBER          ,
  ATTRIBUTE_5                     NUMBER          ,
  CREATION_DATE                   DATE            NOT NULL,
  CREATED_BY                      NUMBER          NOT NULL,
  LAST_UPDATE_DATE                DATE            NOT NULL,
  LAST_UPDATED_BY                 NUMBER          NOT NULL
) TABLESPACE FCM_TS_DATA;

COMMENT ON TABLE FI_ACCOUNT_BOOK IS '회계장부';
COMMENT ON COLUMN APPS.FI_ACCOUNT_BOOK.ACCOUNT_BOOK_ID IS '회계장부 ID';
COMMENT ON COLUMN APPS.FI_ACCOUNT_BOOK.ACCOUNT_BOOK_CODE IS '회계장부코드';
COMMENT ON COLUMN APPS.FI_ACCOUNT_BOOK.ACCOUNT_BOOK_NAME IS '회계장부명';
COMMENT ON COLUMN APPS.FI_ACCOUNT_BOOK.ACCOUNT_BOOK_NAME_S IS '회계장부명(약어)';
COMMENT ON COLUMN APPS.FI_ACCOUNT_BOOK.ACCOUNT_SET_ID IS '계정코드집';
COMMENT ON COLUMN APPS.FI_ACCOUNT_BOOK.FISCAL_CALENDAR_ID IS '회계달력';
COMMENT ON COLUMN APPS.FI_ACCOUNT_BOOK.FUTURE_OPEN_PERIOD_COUNT IS '미래 사용가능 월수';
COMMENT ON COLUMN APPS.FI_ACCOUNT_BOOK.CURRENCY_CODE IS '기준 통화';
COMMENT ON COLUMN APPS.FI_ACCOUNT_BOOK.EXCHANGE_RATE_TYPE IS '기준 환율구분';
COMMENT ON COLUMN APPS.FI_ACCOUNT_BOOK.EXCHANGE_PROFIT_ACCOUNT_ID IS '환차이익 계정관리ID';
COMMENT ON COLUMN APPS.FI_ACCOUNT_BOOK.EXCHANGE_LOSS_ACCOUNT_ID IS '환차손실 계정관리ID';
COMMENT ON COLUMN APPS.FI_ACCOUNT_BOOK.BUDGET_CONTROL_YN IS '예산통제';
COMMENT ON COLUMN APPS.FI_ACCOUNT_BOOK.DEPT_LEVEL IS '부서관리 LEVEL';
COMMENT ON COLUMN APPS.FI_ACCOUNT_BOOK.OPERATING_FLAG IS '운영장부 여부';
COMMENT ON COLUMN APPS.FI_ACCOUNT_BOOK.REMARK IS '비고';
COMMENT ON COLUMN APPS.FI_ACCOUNT_BOOK.CREATION_DATE IS '생성자';
COMMENT ON COLUMN APPS.FI_ACCOUNT_BOOK.CREATED_BY IS '생성일';
COMMENT ON COLUMN APPS.FI_ACCOUNT_BOOK.LAST_UPDATE_DATE IS '수정자';
COMMENT ON COLUMN APPS.FI_ACCOUNT_BOOK.LAST_UPDATED_BY IS '수정일';

-- PRIMARY KEY
CREATE UNIQUE INDEX FI_ACCOUNT_BOOK_PK ON 
  FI_ACCOUNT_BOOK(ACCOUNT_BOOK_CODE, SOB_ID)
  TABLESPACE FCM_TS_IDX
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  LOGGING
  STORAGE (
           INITIAL 64K
           MINEXTENTS 1
           MAXEXTENTS 2147483645
          );

ALTER TABLE FI_ACCOUNT_BOOK ADD ( 
  CONSTRAINT FI_ACCOUNT_BOOK_PK PRIMARY KEY (ACCOUNT_BOOK_CODE, SOB_ID) 
        );
        
-- UNIQUE INDEX.
CREATE UNIQUE INDEX FI_ACCOUNT_BOOK_U1 ON FI_ACCOUNT_BOOK(ACCOUNT_BOOK_ID) TABLESPACE FCM_TS_IDX;
CREATE INDEX FI_ACCOUNT_BOOK_N1 ON FI_ACCOUNT_BOOK(ACCOUNT_BOOK_ID, SOB_ID, OPERATING_FLAG) TABLESPACE FCM_TS_IDX;
CREATE INDEX FI_ACCOUNT_BOOK_N2 ON FI_ACCOUNT_BOOK(SOB_ID, OPERATING_FLAG) TABLESPACE FCM_TS_IDX;

-- SEQUENCE.
DROP SEQUENCE FI_ACCOUNT_BOOK_S1;
CREATE SEQUENCE FI_ACCOUNT_BOOK_S1;

-- ANALYZE.
ANALYZE TABLE APPS.FI_ACCOUNT_BOOK COMPUTE STATISTICS;
ANALYZE INDEX FI_ACCOUNT_BOOK_PK COMPUTE STATISTICS;
ANALYZE INDEX FI_ACCOUNT_BOOK_U1 COMPUTE STATISTICS;
ANALYZE INDEX FI_ACCOUNT_BOOK_N1 COMPUTE STATISTICS;
ANALYZE INDEX FI_ACCOUNT_BOOK_N2 COMPUTE STATISTICS;
