CREATE OR REPLACE VIEW FI_BANK_ACCOUNT_TLV AS
SELECT   T.BANK_ACCOUNT_ID
      ,	 T.SOB_ID
      ,	 T.ORG_ID
      , T.BANK_ACCOUNT_CODE
      ,	 NVL(TL.BANK_ACCOUNT_NAME, T.BANK_ACCOUNT_NAME) AS BANK_ACCOUNT_NAME
      ,	 T.BANK_ID
      ,	 T.BANK_ACCOUNT_NUM
      ,	 NVL(TL.OWNER_NAME, T.OWNER_NAME) AS OWNER_NAME
      ,  T.ACCOUNT_TYPE
      ,  T.GL_CONTROL_YN
      ,  T.CURRENCY_CODE
      ,  T.LIMIT_AMOUNT
      ,  T.USE_AMOUNT
      ,	 T.ACCOUNT_OWNER_TYPE
      ,	 NVL(T.SUPPLIER_CUSTOMER_ID, -1) AS SUPPLIER_CUSTOMER_ID
      ,  NVL(TL.REMARK, T.REMARK) AS REMARK
      ,	 T.EFFECTIVE_DATE_FR
      ,	 T.EFFECTIVE_DATE_TO
      ,	 T.ENABLED_FLAG
      ,  NVL(TL.ATTRIBUTE_A, T.ATTRIBUTE_A) AS ATTRIBUTE_A
      ,  NVL(TL.ATTRIBUTE_B, T.ATTRIBUTE_B) AS ATTRIBUTE_B
      ,  NVL(TL.ATTRIBUTE_C, T.ATTRIBUTE_C) AS ATTRIBUTE_C
      ,  NVL(TL.ATTRIBUTE_D, T.ATTRIBUTE_D) AS ATTRIBUTE_D
      ,  NVL(TL.ATTRIBUTE_E, T.ATTRIBUTE_E) AS ATTRIBUTE_E
      ,  NVL(TL.ATTRIBUTE_1, T.ATTRIBUTE_1) AS ATTRIBUTE_1
      ,  NVL(TL.ATTRIBUTE_2, T.ATTRIBUTE_2) AS ATTRIBUTE_2
      ,  NVL(TL.ATTRIBUTE_3, T.ATTRIBUTE_3) AS ATTRIBUTE_3
      ,  NVL(TL.ATTRIBUTE_4, T.ATTRIBUTE_4) AS ATTRIBUTE_4
      ,  NVL(TL.ATTRIBUTE_5, T.ATTRIBUTE_5) AS ATTRIBUTE_5
      ,  T.CREATION_DATE
      ,  T.CREATED_BY
      ,  T.LAST_UPDATE_DATE
      ,  T.LAST_UPDATED_BY
   FROM FI_BANK_ACCOUNT       T
      , FI_BANK_ACCOUNT_TL    TL
  WHERE TL.BANK_ACCOUNT_ID(+) = T.BANK_ACCOUNT_ID
    AND TL.LANG_CODE(+)       = USERENV_G.GET_TERRITORY_S_F;
