CREATE OR REPLACE VIEW FI_BALANCE_ACCOUNTS_ITEM_V AS
SELECT BAI.ACCOUNT_CONTROL_ID
     , BAI.ACCOUNT_CODE
     , BAI.SOB_ID
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 1, BAI.MANAGEMENT_ID, NULL)) AS MANAGEMENT1_ID
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 1, BAI.MANAGEMENT_CODE, NULL)) AS MANAGEMENT1_CODE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 1, MC.MANAGEMENT_NAME, NULL)) AS MANAGEMENT1_DESC
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 1, BAI.BALANCE_YN, NULL)) AS BALANCE1_YN
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 1, BAI.ENABLED_FLAG, NULL)) AS ENABLED1_FLAG
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 2, BAI.MANAGEMENT_ID, NULL)) AS MANAGEMENT2_ID
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 2, BAI.MANAGEMENT_CODE, NULL)) AS MANAGEMENT2_CODE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 2, MC.MANAGEMENT_NAME, NULL)) AS MANAGEMENT2_DESC
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 2, BAI.BALANCE_YN, NULL)) AS BALANCE2_YN
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 2, BAI.ENABLED_FLAG, NULL)) AS ENABLED2_FLAG
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 3, BAI.MANAGEMENT_ID, NULL)) AS MANAGEMENT3_ID
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 3, BAI.MANAGEMENT_CODE, NULL)) AS MANAGEMENT3_CODE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 3, MC.MANAGEMENT_NAME, NULL)) AS MANAGEMENT3_DESC
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 3, BAI.BALANCE_YN, NULL)) AS BALANCE3_YN
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 3, BAI.ENABLED_FLAG, NULL)) AS ENABLED3_FLAG
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 4, BAI.MANAGEMENT_ID, NULL)) AS MANAGEMENT4_ID
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 4, BAI.MANAGEMENT_CODE, NULL)) AS MANAGEMENT4_CODE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 4, MC.MANAGEMENT_NAME, NULL)) AS MANAGEMENT4_DESC
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 4, BAI.BALANCE_YN, NULL)) AS BALANCE4_YN
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 4, BAI.ENABLED_FLAG, NULL)) AS ENABLED4_FLAG
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 5, BAI.MANAGEMENT_ID, NULL)) AS MANAGEMENT5_ID
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 5, BAI.MANAGEMENT_CODE, NULL)) AS MANAGEMENT5_CODE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 5, MC.MANAGEMENT_NAME, NULL)) AS MANAGEMENT5_DESC
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 5, BAI.BALANCE_YN, NULL)) AS BALANCE5_YN
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 5, BAI.ENABLED_FLAG, NULL)) AS ENABLED5_FLAG
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 6, BAI.MANAGEMENT_ID, NULL)) AS MANAGEMENT6_ID
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 6, BAI.MANAGEMENT_CODE, NULL)) AS MANAGEMENT6_CODE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 6, MC.MANAGEMENT_NAME, NULL)) AS MANAGEMENT6_DESC
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 6, BAI.BALANCE_YN, NULL)) AS BALANCE6_YN
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 6, BAI.ENABLED_FLAG, NULL)) AS ENABLED6_FLAG
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 7, BAI.MANAGEMENT_ID, NULL)) AS MANAGEMENT7_ID
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 7, BAI.MANAGEMENT_CODE, NULL)) AS MANAGEMENT7_CODE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 7, MC.MANAGEMENT_NAME, NULL)) AS MANAGEMENT7_DESC
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 7, BAI.BALANCE_YN, NULL)) AS BALANCE7_YN
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 7, BAI.ENABLED_FLAG, NULL)) AS ENABLED7_FLAG
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 8, BAI.MANAGEMENT_ID, NULL)) AS MANAGEMENT8_ID
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 8, BAI.MANAGEMENT_CODE, NULL)) AS MANAGEMENT8_CODE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 8, MC.MANAGEMENT_NAME, NULL)) AS MANAGEMENT8_DESC
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 8, BAI.BALANCE_YN, NULL)) AS BALANCE8_YN
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 8, BAI.ENABLED_FLAG, NULL)) AS ENABLED8_FLAG
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 9, BAI.MANAGEMENT_ID, NULL)) AS MANAGEMENT9_ID
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 9, BAI.MANAGEMENT_CODE, NULL)) AS MANAGEMENT9_CODE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 9, MC.MANAGEMENT_NAME, NULL)) AS MANAGEMENT9_DESC
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 9, BAI.BALANCE_YN, NULL)) AS BALANCE9_YN
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 9, BAI.ENABLED_FLAG, NULL)) AS ENABLED9_FLAG
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 10, BAI.MANAGEMENT_ID, NULL)) AS MANAGEMENT10_ID
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 10, BAI.MANAGEMENT_CODE, NULL)) AS MANAGEMENT10_CODE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 10, MC.MANAGEMENT_NAME, NULL)) AS MANAGEMENT10_DESC
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 10, BAI.BALANCE_YN, NULL)) AS BALANCE10_YN
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 10, BAI.ENABLED_FLAG, NULL)) AS ENABLED10_FLAG
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 11, BAI.MANAGEMENT_ID, NULL)) AS MANAGEMENT11_ID
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 11, BAI.MANAGEMENT_CODE, NULL)) AS MANAGEMENT11_CODE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 11, MC.MANAGEMENT_NAME, NULL)) AS MANAGEMENT11_DESC
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 11, BAI.BALANCE_YN, NULL)) AS BALANCE11_YN
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 11, BAI.ENABLED_FLAG, NULL)) AS ENABLED11_FLAG
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 12, BAI.MANAGEMENT_ID, NULL)) AS MANAGEMENT12_ID
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 12, BAI.MANAGEMENT_CODE, NULL)) AS MANAGEMENT12_CODE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 12, MC.MANAGEMENT_NAME, NULL)) AS MANAGEMENT12_DESC
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 12, BAI.BALANCE_YN, NULL)) AS BALANCE12_YN
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 12, BAI.ENABLED_FLAG, NULL)) AS ENABLED12_FLAG
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 13, BAI.MANAGEMENT_ID, NULL)) AS MANAGEMENT13_ID
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 13, BAI.MANAGEMENT_CODE, NULL)) AS MANAGEMENT13_CODE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 13, MC.MANAGEMENT_NAME, NULL)) AS MANAGEMENT13_DESC
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 13, BAI.BALANCE_YN, NULL)) AS BALANCE13_YN
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 13, BAI.ENABLED_FLAG, NULL)) AS ENABLED13_FLAG
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 14, BAI.MANAGEMENT_ID, NULL)) AS MANAGEMENT14_ID
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 14, BAI.MANAGEMENT_CODE, NULL)) AS MANAGEMENT14_CODE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 14, MC.MANAGEMENT_NAME, NULL)) AS MANAGEMENT14_DESC
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 14, BAI.BALANCE_YN, NULL)) AS BALANCE14_YN
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 14, BAI.ENABLED_FLAG, NULL)) AS ENABLED14_FLAG
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 15, BAI.MANAGEMENT_ID, NULL)) AS MANAGEMENT15_ID
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 15, BAI.MANAGEMENT_CODE, NULL)) AS MANAGEMENT15_CODE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 15, MC.MANAGEMENT_NAME, NULL)) AS MANAGEMENT15_DESC
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 15, BAI.BALANCE_YN, NULL)) AS BALANCE15_YN
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 15, BAI.ENABLED_FLAG, NULL)) AS ENABLED15_FLAG
  FROM FI_BALANCE_ACCOUNTS_ITEM BAI
    , FI_MANAGEMENT_CODE_V MC
WHERE BAI.MANAGEMENT_ID           = MC.MANAGEMENT_ID(+)
  AND BAI.SOB_ID                  = MC.SOB_ID(+)
GROUP BY BAI.ACCOUNT_CONTROL_ID
     , BAI.ACCOUNT_CODE
     , BAI.SOB_ID;
