/******************************************************************************/
/* Project      : FPCB ERP
/* Module       : FCM
/* Program Name : FI_BUDGET_MOVE
/* Description  : 월별 예산 전용 신청/승인 내역(HISTORY 관리).
/*
/* Reference by :
/* Program History
/*------------------------------------------------------------------------------
/*   Date       In Charge          Description
/*------------------------------------------------------------------------------
/* 07-JUN-2010  Jeon Ho Su          Initialize
/******************************************************************************/
--> CREATE TABLE.
CREATE TABLE FI_BUDGET_MOVE
( BUDGET_PERIOD                   VARCHAR2(10)  NOT NULL
, FROM_DEPT_ID                    NUMBER        NOT NULL
, FROM_ACCOUNT_CONTROL_ID         NUMBER        NOT NULL
, FROM_ACCOUNT_CODE               VARCHAR2(20)  NOT NULL
, TO_DEPT_ID                      NUMBER        NOT NULL
, TO_ACCOUNT_CONTROL_ID           NUMBER        NOT NULL
, TO_ACCOUNT_CODE                 VARCHAR2(20)  NOT NULL
, SOB_ID                          NUMBER        NOT NULL
, ORG_ID                          NUMBER        NOT NULL
, CREATE_SEQ                      NUMBER        NOT NULL
, BUDGET_PERIOD_FR                VARCHAR2(10)  NOT NULL
, BUDGET_PERIOD_TO                VARCHAR2(10)  NOT NULL
, START_DATE                      DATE          NOT NULL
, END_DATE                        DATE          NOT NULL
, SAVE_SEQ                        NUMBER        DEFAULT 1
, AMOUNT                          NUMBER        DEFAULT 0
, CAUSE_ID                        NUMBER        NOT NULL
, LAST_YN                         CHAR(1)       DEFAULT 'Y'
, APPROVED_YN                     CHAR(1)       DEFAULT 'N'
, APPROVED_DATE                   DATE
, APPROVED_PERSON_ID              NUMBER
, CONFIRMED_YN                    CHAR(1)       DEFAULT 'N'
, CONFIRMED_DATE                  DATE
, CONFIRMED_PERSON_ID             NUMBER
, CLOSED_YN                       CHAR(1)       DEFAULT 'N'
, CLOSED_DATE                     DATE
, CLOSED_PERSON_ID                NUMBER
, APPROVE_STATUS                  VARCHAR2(5)   DEFAULT 'N'
, EMAIL_STATUS                    VARCHAR2(5)
, DESCRIPTION                     VARCHAR2(100)
, REJECT_REMARK                   VARCHAR2(100)
, ATTRIBUTE_A                     VARCHAR2(100)
, ATTRIBUTE_B                     VARCHAR2(100)
, ATTRIBUTE_C                     VARCHAR2(100)
, ATTRIBUTE_D                     VARCHAR2(100)
, ATTRIBUTE_E                     VARCHAR2(100)
, ATTRIBUTE_1                     NUMBER
, ATTRIBUTE_2                     NUMBER
, ATTRIBUTE_3                     NUMBER
, ATTRIBUTE_4                     NUMBER
, ATTRIBUTE_5                     NUMBER
, CREATION_DATE                   DATE          NOT NULL
, CREATED_BY                      NUMBER        NOT NULL
, LAST_UPDATE_DATE                DATE          NOT NULL
, LAST_UPDATED_BY                 NUMBER        NOT NULL
) TABLESPACE FCM_TS_DATA;

--> COMMENT.
COMMENT ON TABLE FI_BUDGET_MOVE IS '예산 전용 관리';
COMMENT ON COLUMN FI_BUDGET_MOVE.BUDGET_PERIOD IS '예산적용년월';
COMMENT ON COLUMN FI_BUDGET_MOVE.FROM_DEPT_ID IS '현재 발의부서';
COMMENT ON COLUMN FI_BUDGET_MOVE.FROM_ACCOUNT_CONTROL_ID IS '현재 계정(세목)관리ID';
COMMENT ON COLUMN FI_BUDGET_MOVE.FROM_ACCOUNT_CODE IS '현재 계정(세목) 코드';
COMMENT ON COLUMN FI_BUDGET_MOVE.TO_DEPT_ID IS '전용 발의부서';
COMMENT ON COLUMN FI_BUDGET_MOVE.TO_ACCOUNT_CONTROL_ID IS '현재 계정(세목)관리ID';
COMMENT ON COLUMN FI_BUDGET_MOVE.TO_ACCOUNT_CODE IS '전용 계정(세목) 코드';
COMMENT ON COLUMN FI_BUDGET_MOVE.CREATE_SEQ IS '생성 일련번호';
COMMENT ON COLUMN FI_BUDGET_MOVE.BUDGET_PERIOD_FR IS '예산 적용 시작년월';
COMMENT ON COLUMN FI_BUDGET_MOVE.BUDGET_PERIOD_TO IS '예산 적용 종료년월';
COMMENT ON COLUMN FI_BUDGET_MOVE.START_DATE IS '예산 적용일자-예산적용 시작년월의 1일';
COMMENT ON COLUMN FI_BUDGET_MOVE.END_DATE IS '예산 종료일자->예산적용 종료년월의 말일';
COMMENT ON COLUMN FI_BUDGET_MOVE.SAVE_SEQ IS '수정 일련번호';
COMMENT ON COLUMN FI_BUDGET_MOVE.AMOUNT IS '전용 예산금액';
COMMENT ON COLUMN FI_BUDGET_MOVE.CAUSE_ID IS '예산전용사유(BUDGET_CAUSE)';
COMMENT ON COLUMN FI_BUDGET_MOVE.LAST_YN IS '최종자료 Y/N';
COMMENT ON COLUMN FI_BUDGET_MOVE.APPROVED_YN IS '승인여부';
COMMENT ON COLUMN FI_BUDGET_MOVE.APPROVED_DATE IS '승인일자';
COMMENT ON COLUMN FI_BUDGET_MOVE.APPROVED_PERSON_ID IS '승인 처리자';
COMMENT ON COLUMN FI_BUDGET_MOVE.CONFIRMED_YN IS '확정승인 여부';
COMMENT ON COLUMN FI_BUDGET_MOVE.CONFIRMED_DATE IS '확정승인 일자';
COMMENT ON COLUMN FI_BUDGET_MOVE.CONFIRMED_PERSON_ID IS '확정승인 처리자';
COMMENT ON COLUMN FI_BUDGET_MOVE.APPROVE_STATUS IS '최종승인상태';
COMMENT ON COLUMN FI_BUDGET_MOVE.CLOSED_YN IS '마감여부';
COMMENT ON COLUMN FI_BUDGET_MOVE.CLOSED_DATE IS '마감일자';
COMMENT ON COLUMN FI_BUDGET_MOVE.CLOSED_PERSON_ID IS '마감처리자';
COMMENT ON COLUMN FI_BUDGET_MOVE.EMAIL_STATUS IS 'EMAIL 발송여부(N-미발송,AR/BR-발송준비,AS/BS-발송완료)';

--> CREATE INDEX.
ALTER TABLE FI_BUDGET_MOVE ADD CONSTRAINT FI_BUDGET_MOVE_PK PRIMARY KEY (BUDGET_PERIOD, FROM_DEPT_ID, FROM_ACCOUNT_CONTROL_ID, TO_DEPT_ID, TO_ACCOUNT_CONTROL_ID, SOB_ID, SAVE_SEQ);

CREATE INDEX FI_BUDGET_MOVE_N1 ON FI_BUDGET_MOVE(BUDGET_PERIOD, FROM_DEPT_ID, FROM_ACCOUNT_CONTROL_ID, SOB_ID)
  TABLESPACE FCM_TS_IDX;

CREATE INDEX FI_BUDGET_MOVE_N2 ON FI_BUDGET_MOVE(BUDGET_PERIOD, TO_DEPT_ID, TO_ACCOUNT_CONTROL_ID, SOB_ID)
  TABLESPACE FCM_TS_IDX;
  
CREATE INDEX FI_BUDGET_MOVE_N3 ON FI_BUDGET_MOVE(BUDGET_PERIOD, APPROVE_STATUS, SOB_ID)
  TABLESPACE FCM_TS_IDX;

CREATE INDEX FI_BUDGET_MOVE_N4 ON FI_BUDGET_MOVE(BUDGET_PERIOD, LAST_YN, SOB_ID)
  TABLESPACE FCM_TS_IDX;
  
CREATE INDEX FI_BUDGET_MOVE_N5 ON FI_BUDGET_MOVE(BUDGET_PERIOD, EMAIL_STATUS, SOB_ID)
  TABLESPACE FCM_TS_IDX;
    
