/******************************************************************************/
/* Project      : FPCB ERP
/* Module       : FCM
/* Program Name : FI_BILL_MASTER
/* Description  : 어음 마스터.
/*
/* Reference by :
/* Program History
/*------------------------------------------------------------------------------
/*   Date       In Charge          Description
/*------------------------------------------------------------------------------
/* 07-JUN-2010  Jeon Ho Su          Initialize
/******************************************************************************/
CREATE TABLE FI_BILL_MASTER 
( BILL_NUM                        VARCHAR2(50)  NOT NULL
, SOB_ID                          NUMBER        NOT NULL
, ORG_ID                          NUMBER        NOT NULL
, BILL_TYPE                       VARCHAR2(10)  NOT NULL
, BILL_AMOUNT                     NUMBER        DEFAULT 0
, ISSUE_DATE                      DATE          NOT NULL
, DUE_DATE                        DATE          NOT NULL
, BILL_STATUS                     VARCHAR2(10)  DEFAULT '00'
, BILL_MODE                       VARCHAR2(10)  
, AREA_CODE                       VARCHAR2(10)
, ISSUE_NAME                      VARCHAR2(100)
, CUSTOMER_ID                     NUMBER        NOT NULL
, BANK_ID                         NUMBER
, RECEIPT_DEPT_ID                 NUMBER
, RECEIPT_DATE                    DATE
, KEEP_DEPT_ID                    NUMBER
, ENDORSE_NAME                    VARCHAR2(100) 
, ENDORSE_ADDRESS                 VARCHAR2(150)
, TRUST_DATE                      DATE
, TRUST_BANK_ID                   NUMBER
, BAD_DATE                        DATE
, DC_DATE                         DATE
, DC_BANK_ID                      NUMBER
, DC_REMAIN_AMOUNT                NUMBER        DEFAULT 0
, GIVE_DATE                       DATE
, MOVE_START_DATE                 DATE
, MOVE_CONFIRM_DATE               DATE
, PAYMENT_DATE                    DATE
, CANCEL_MOVE_DATE                DATE
, CANCEL_MOVE_BAD_DATE            DATE
, CANCEL_BAD_DATE                 DATE
, CANCEL_PAYMENT_DATE             DATE
, CANCEL_DC_DATE                  DATE
, CANCEL_TRUST_DATE               DATE
, CREDIT_YN                       CHAR(1)
, CREDIT_NO_REMARK                VARCHAR2(150)
, LAST_REPLACE_DATE               DATE
, SLIP_LINE_ID                    NUMBER
, CREATION_DATE                   DATE          NOT NULL
, CREATED_BY                      NUMBER        NOT NULL
, LAST_UPDATE_DATE                DATE          NOT NULL
, LAST_UPDATED_BY                 NUMBER        NOT NULL
) TABLESPACE FCM_TS_DATA ;

COMMENT ON TABLE FI_BILL_MASTER IS '어음MASTER';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.BILL_NUM IS '어음번호';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.BILL_TYPE IS '어음종류(1:지급어음,2:받을어음,3:수표)';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.BILL_AMOUNT IS '어음금액';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.ISSUE_DATE IS '발행일자';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.DUE_DATE IS '만기일자';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.BILL_STATUS IS '어음상태';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.BILL_MODE IS '자(1),타(2)구분';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.AREA_CODE IS '지역코드';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.ISSUE_NAME IS '발행인';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.CUSTOMER_ID IS '거래처ID';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.BANK_ID IS '만기은행ID';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.RECEIPT_DEPT_ID IS '입금부서';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.RECEIPT_DATE IS '입금일자';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.KEEP_DEPT_ID IS '보관부서';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.ENDORSE_NAME IS '최종 배서인';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.ENDORSE_ADDRESS IS '최종 배서인 주소';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.TRUST_DATE IS '수탁일자';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.TRUST_BANK_ID IS '수탁은행 ID';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.BAD_DATE IS '부도일자';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.DC_DATE IS '할인일자';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.DC_BANK_ID IS '할인은행ID';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.DC_REMAIN_AMOUNT IS '할인 잔액';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.GIVE_DATE IS '배서지급일자';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.MOVE_START_DATE IS '이동통보서작성일';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.MOVE_CONFIRM_DATE IS '이동통보서확인일';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.PAYMENT_DATE IS '실결제일';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.CANCEL_MOVE_DATE IS '정상이동취소일';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.CANCEL_MOVE_BAD_DATE IS '부도이동취소일';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.CANCEL_BAD_DATE IS '부도취소일';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.CANCEL_PAYMENT_DATE IS '결제취소일';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.CANCEL_DC_DATE IS '할인취소일';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.CANCEL_TRUST_DATE IS '수탁취소일';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.CREDIT_YN IS '여신제외여부';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.CREDIT_NO_REMARK IS '여신미반영시 사유';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.LAST_REPLACE_DATE IS '최종상태변경일';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.SLIP_LINE_ID IS '전표 LINE ID';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.CREATION_DATE IS '생성자';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.CREATED_BY IS '생성일';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.LAST_UPDATE_DATE IS '수정자';
COMMENT ON COLUMN APPS.FI_BILL_MASTER.LAST_UPDATED_BY IS '수정일';

CREATE UNIQUE INDEX FI_BILL_MASTER_U1 ON FI_BILL_MASTER(BILL_NUM, SOB_ID) TABLESPACE  FCM_TS_IDX;
CREATE INDEX FI_BILL_MASTER_N1 ON FI_BILL_MASTER(ISSUE_DATE, DUE_DATE, ISSUE_NAME) TABLESPACE FCM_TS_IDX;        
CREATE INDEX FI_BILL_MASTER_N2 ON FI_BILL_MASTER(SLIP_LINE_ID) TABLESPACE FCM_TS_IDX;
