CREATE OR REPLACE VIEW FI_BALANCE_STATEMENT_ITEM_V9 AS
SELECT BAI.ACCOUNT_CONTROL_ID
     , BAI.ACCOUNT_CODE
     , BAI.SOB_ID
     , BSI.CURRENCY_CODE
     , BSI.ITEM_GROUP_ID
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 1, BSI.MANAGEMENT_VALUE, ')')) AS MANAGEMENT1_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 2, BSI.MANAGEMENT_VALUE, ')')) AS MANAGEMENT2_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 3, BSI.MANAGEMENT_VALUE, ')')) AS MANAGEMENT3_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 4, BSI.MANAGEMENT_VALUE, ')')) AS MANAGEMENT4_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 5, BSI.MANAGEMENT_VALUE, ')')) AS MANAGEMENT5_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 6, BSI.MANAGEMENT_VALUE, ')')) AS MANAGEMENT6_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 7, BSI.MANAGEMENT_VALUE, ')')) AS MANAGEMENT7_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 8, BSI.MANAGEMENT_VALUE, ')')) AS MANAGEMENT8_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 9, BSI.MANAGEMENT_VALUE, ')')) AS MANAGEMENT9_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 10, BSI.MANAGEMENT_VALUE, ')')) AS MANAGEMENT10_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 11, BSI.MANAGEMENT_VALUE, ')')) AS MANAGEMENT11_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 12, BSI.MANAGEMENT_VALUE, ')')) AS MANAGEMENT12_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 13, BSI.MANAGEMENT_VALUE, ')')) AS MANAGEMENT13_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 14, BSI.MANAGEMENT_VALUE, ')')) AS MANAGEMENT14_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 15, BSI.MANAGEMENT_VALUE, ')')) AS MANAGEMENT15_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 1, DECODE(BAI.BALANCE_YN, 'Y', BSI.MANAGEMENT_VALUE, ')'), ')')) AS BALANCE1_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 2, DECODE(BAI.BALANCE_YN, 'Y', BSI.MANAGEMENT_VALUE, ')'), ')')) AS BALANCE2_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 3, DECODE(BAI.BALANCE_YN, 'Y', BSI.MANAGEMENT_VALUE, ')'), ')')) AS BALANCE3_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 4, DECODE(BAI.BALANCE_YN, 'Y', BSI.MANAGEMENT_VALUE, ')'), ')')) AS BALANCE4_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 5, DECODE(BAI.BALANCE_YN, 'Y', BSI.MANAGEMENT_VALUE, ')'), ')')) AS BALANCE5_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 6, DECODE(BAI.BALANCE_YN, 'Y', BSI.MANAGEMENT_VALUE, ')'), ')')) AS BALANCE6_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 7, DECODE(BAI.BALANCE_YN, 'Y', BSI.MANAGEMENT_VALUE, ')'), ')')) AS BALANCE7_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 8, DECODE(BAI.BALANCE_YN, 'Y', BSI.MANAGEMENT_VALUE, ')'), ')')) AS BALANCE8_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 9, DECODE(BAI.BALANCE_YN, 'Y', BSI.MANAGEMENT_VALUE, ')'), ')')) AS BALANCE9_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 10, DECODE(BAI.BALANCE_YN, 'Y', BSI.MANAGEMENT_VALUE, ')'), ')')) AS BALANCE10_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 11, DECODE(BAI.BALANCE_YN, 'Y', BSI.MANAGEMENT_VALUE, ')'), ')')) AS BALANCE11_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 12, DECODE(BAI.BALANCE_YN, 'Y', BSI.MANAGEMENT_VALUE, ')'), ')')) AS BALANCE12_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 13, DECODE(BAI.BALANCE_YN, 'Y', BSI.MANAGEMENT_VALUE, ')'), ')')) AS BALANCE13_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 14, DECODE(BAI.BALANCE_YN, 'Y', BSI.MANAGEMENT_VALUE, ')'), ')')) AS BALANCE14_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 15, DECODE(BAI.BALANCE_YN, 'Y', BSI.MANAGEMENT_VALUE, ')'), ')')) AS BALANCE15_VALUE
  FROM FI_BALANCE_STATEMENT_ITEM BSI
    , FI_BALANCE_ACCOUNTS_ITEM BAI
WHERE BSI.ACCOUNT_CONTROL_ID      = BAI.ACCOUNT_CONTROL_ID
  AND BSI.MANAGEMENT_ID           = BAI.MANAGEMENT_ID
  AND BSI.SOB_ID                  = BAI.SOB_ID
  AND BAI.ENABLED_FLAG            = 'Y'
GROUP BY BAI.ACCOUNT_CONTROL_ID
     , BAI.ACCOUNT_CODE
     , BAI.SOB_ID
     , BSI.CURRENCY_CODE
     , BSI.ITEM_GROUP_ID;
