CREATE OR REPLACE VIEW FI_BALANCE_STATEMENT_ITEM_V AS
SELECT BSI.ACCOUNT_CONTROL_ID
     , BSI.ACCOUNT_CODE
     , BSI.CURRENCY_CODE
     , BSI.ITEM_GROUP_ID
     , BSI.SOB_ID
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 1, BSI.MANAGEMENT_ID, NULL)) AS MANAGEMENT1_ID
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 1, BSI.MANAGEMENT_CODE, NULL)) AS MANAGEMENT1_CODE
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 1, BSI.MANAGEMENT_VALUE, NULL)) AS MANAGEMENT1_VALUE
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 2, BSI.MANAGEMENT_ID, NULL)) AS MANAGEMENT2_ID
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 2, BSI.MANAGEMENT_CODE, NULL)) AS MANAGEMENT2_CODE
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 2, BSI.MANAGEMENT_VALUE, NULL)) AS MANAGEMENT2_VALUE
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 3, BSI.MANAGEMENT_ID, NULL)) AS MANAGEMENT3_ID
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 3, BSI.MANAGEMENT_CODE, NULL)) AS MANAGEMENT3_CODE
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 3, BSI.MANAGEMENT_VALUE, NULL)) AS MANAGEMENT3_VALUE
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 4, BSI.MANAGEMENT_ID, NULL)) AS MANAGEMENT4_ID
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 4, BSI.MANAGEMENT_CODE, NULL)) AS MANAGEMENT4_CODE
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 4, BSI.MANAGEMENT_VALUE, NULL)) AS MANAGEMENT4_VALUE
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 5, BSI.MANAGEMENT_ID, NULL)) AS MANAGEMENT5_ID
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 5, BSI.MANAGEMENT_CODE, NULL)) AS MANAGEMENT5_CODE
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 5, BSI.MANAGEMENT_VALUE, NULL)) AS MANAGEMENT5_VALUE
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 6, BSI.MANAGEMENT_ID, NULL)) AS MANAGEMENT6_ID
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 6, BSI.MANAGEMENT_CODE, NULL)) AS MANAGEMENT6_CODE
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 6, BSI.MANAGEMENT_VALUE, NULL)) AS MANAGEMENT6_VALUE
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 7, BSI.MANAGEMENT_ID, NULL)) AS MANAGEMENT7_ID
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 7, BSI.MANAGEMENT_CODE, NULL)) AS MANAGEMENT7_CODE
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 7, BSI.MANAGEMENT_VALUE, NULL)) AS MANAGEMENT7_VALUE
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 8, BSI.MANAGEMENT_ID, NULL)) AS MANAGEMENT8_ID
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 8, BSI.MANAGEMENT_CODE, NULL)) AS MANAGEMENT8_CODE
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 8, BSI.MANAGEMENT_VALUE, NULL)) AS MANAGEMENT8_VALUE
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 9, BSI.MANAGEMENT_ID, NULL)) AS MANAGEMENT9_ID
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 9, BSI.MANAGEMENT_CODE, NULL)) AS MANAGEMENT9_CODE
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 9, BSI.MANAGEMENT_VALUE, NULL)) AS MANAGEMENT9_VALUE
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 10, BSI.MANAGEMENT_ID, NULL)) AS MANAGEMENT10_ID
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 10, BSI.MANAGEMENT_CODE, NULL)) AS MANAGEMENT10_CODE
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 10, BSI.MANAGEMENT_VALUE, NULL)) AS MANAGEMENT10_VALUE
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 11, BSI.MANAGEMENT_ID, NULL)) AS MANAGEMENT11_ID
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 11, BSI.MANAGEMENT_CODE, NULL)) AS MANAGEMENT11_CODE
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 11, BSI.MANAGEMENT_VALUE, NULL)) AS MANAGEMENT11_VALUE
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 12, BSI.MANAGEMENT_ID, NULL)) AS MANAGEMENT12_ID
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 12, BSI.MANAGEMENT_CODE, NULL)) AS MANAGEMENT12_CODE
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 12, BSI.MANAGEMENT_VALUE, NULL)) AS MANAGEMENT12_VALUE
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 13, BSI.MANAGEMENT_ID, NULL)) AS MANAGEMENT13_ID
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 13, BSI.MANAGEMENT_CODE, NULL)) AS MANAGEMENT13_CODE
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 13, BSI.MANAGEMENT_VALUE, NULL)) AS MANAGEMENT13_VALUE
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 14, BSI.MANAGEMENT_ID, NULL)) AS MANAGEMENT14_ID
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 14, BSI.MANAGEMENT_CODE, NULL)) AS MANAGEMENT14_CODE
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 14, BSI.MANAGEMENT_VALUE, NULL)) AS MANAGEMENT14_VALUE
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 15, BSI.MANAGEMENT_ID, NULL)) AS MANAGEMENT15_ID
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 15, BSI.MANAGEMENT_CODE, NULL)) AS MANAGEMENT15_CODE
     , MAX(DECODE(BSI.MANAGEMENT_SEQ, 15, BSI.MANAGEMENT_VALUE, NULL)) AS MANAGEMENT15_VALUE
  FROM FI_BALANCE_STATEMENT_ITEM BSI
GROUP BY BSI.ACCOUNT_CONTROL_ID
     , BSI.ACCOUNT_CODE
     , BSI.CURRENCY_CODE
     , BSI.ITEM_GROUP_ID
     , BSI.SOB_ID;
