/******************************************************************************/
/* Project      : FPCB ERP
/* Module       : HR
/* Program Name : FI_CREDIT_CARD
/* Description  : 신용카드 관리.
/*
/* Reference by :
/* Program History
/*------------------------------------------------------------------------------
/*   Date       In Charge          Description
/*------------------------------------------------------------------------------
/* 07-JUN-2010  Jeon Ho Su          Initialize
/******************************************************************************/
CREATE TABLE FI_CREDIT_CARD
( CARD_CODE             VARCHAR2(50)    NOT NULL,  
  SOB_ID                NUMBER          NOT NULL,
  ORG_ID                NUMBER          NOT NULL,
  CARD_NUM              VARCHAR2(30)    NOT NULL,
  CARD_NAME             VARCHAR2(100)   NOT NULL,
  CARD_ENG_NAME         VARCHAR2(100)   ,        
  CARD_TYPE_ID          NUMBER          ,
  CRAD_CORP_ID          NUMBER          NOT NULL,
  EXPIRE_PERIOD         VARCHAR2(10)    NOT NULL,
  BANK_ID               NUMBER          ,
  BANK_ACCOUNT_ID       NUMBER          ,
  LIMIT_AMOUNT          NUMBER(12,0)    DEFAULT 0,
  CURRENCY_CODE         VARCHAR2(10)    ,
  CURRENCY_LIMIT_AMOUNT NUMBER(16,4)    DEFAULT 0,
  USE_PERSON_ID         NUMBER          ,
  ISSU_DATE             DATE            ,
  DUE_DATE              DATE            ,
  CLOSE_DAY             VARCHAR2(2)     ,
  SETTLE_DAY            VARCHAR2(2)     ,
  REMARK                VARCHAR2(150)   ,
  ENABLED_FLAG          CHAR(1)         DEFAULT 'Y',
  EFFECTIVE_DATE_FR     DATE            ,
  EFFECTIVE_DATE_TO     DATE            ,
  CREATION_DATE         DATE            NOT NULL,
  CREATED_BY            NUMBER          NOT NULL,
  LAST_UPDATE_DATE      DATE            NOT NULL,
  LAST_UPDATED_BY       NUMBER          NOT NULL 
) TABLESPACE FCM_TS_DATA;

COMMENT ON TABLE  FI_CREDIT_CARD IS '신용카드MASTER';
COMMENT ON COLUMN FI_CREDIT_CARD.CARD_CODE IS '신용카드코드';
COMMENT ON COLUMN FI_CREDIT_CARD.SOB_ID IS '회사ID';
COMMENT ON COLUMN FI_CREDIT_CARD.ORG_ID IS '사업부ID';
COMMENT ON COLUMN FI_CREDIT_CARD.CARD_NUM IS '신용카드번호';
COMMENT ON COLUMN FI_CREDIT_CARD.CARD_NAME IS '신용카드명';
COMMENT ON COLUMN FI_CREDIT_CARD.CARD_ENG_NAME IS '신용카드영문';
COMMENT ON COLUMN FI_CREDIT_CARD.CARD_TYPE_ID IS '카드타입(공통코드:CREDIT_TYPE)';
COMMENT ON COLUMN FI_CREDIT_CARD.CRAD_CORP_ID IS '신용카드사(공통코드:CREDIT_CRAD_CORP)';
COMMENT ON COLUMN FI_CREDIT_CARD.EXPIRE_PERIOD IS '유효기간';
COMMENT ON COLUMN FI_CREDIT_CARD.BANK_ID IS '금융기관ID';
COMMENT ON COLUMN FI_CREDIT_CARD.BANK_ACCOUNT_ID IS '은행계좌코드 ID';
COMMENT ON COLUMN FI_CREDIT_CARD.LIMIT_AMOUNT IS '금액-한도';
COMMENT ON COLUMN FI_CREDIT_CARD.CURRENCY_CODE IS '통화';
COMMENT ON COLUMN FI_CREDIT_CARD.CURRENCY_LIMIT_AMOUNT IS '외화_한도';
COMMENT ON COLUMN FI_CREDIT_CARD.USE_PERSON_ID IS '카드 사용자ID';
COMMENT ON COLUMN FI_CREDIT_CARD.ISSU_DATE IS '사용자 지급일자';
COMMENT ON COLUMN FI_CREDIT_CARD.DUE_DATE IS '사용자 만료일자';
COMMENT ON COLUMN FI_CREDIT_CARD.CLOSE_DAY IS '결산기준일(매월 대금정산 기준일)';
COMMENT ON COLUMN FI_CREDIT_CARD.SETTLE_DAY IS '결재일(매월 정기대금 결재일)';
COMMENT ON COLUMN FI_CREDIT_CARD.REMARK IS '적요';
COMMENT ON COLUMN FI_CREDIT_CARD.ENABLED_FLAG IS '사용(Y/N)';
COMMENT ON COLUMN FI_CREDIT_CARD.CREATION_DATE IS '생성자';
COMMENT ON COLUMN FI_CREDIT_CARD.CREATED_BY IS '생성일';
COMMENT ON COLUMN FI_CREDIT_CARD.LAST_UPDATE_DATE IS '수정자';
COMMENT ON COLUMN FI_CREDIT_CARD.LAST_UPDATED_BY IS '수정일';

CREATE UNIQUE INDEX FI_CREDIT_CARD_PK ON 
  FI_CREDIT_CARD(CARD_CODE, SOB_ID)  
  TABLESPACE FCM_TS_IDX
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  LOGGING
  STORAGE (
           INITIAL 64K
           MINEXTENTS 1
           MAXEXTENTS 2147483645
          );
          
ALTER TABLE FI_CREDIT_CARD ADD ( 
  CONSTRAINT FI_CREDIT_CARD_PK PRIMARY KEY (CARD_CODE, SOB_ID)
        );

CREATE UNIQUE INDEX FI_CREDIT_CARD_U1 ON FI_CREDIT_CARD(SOB_ID, CARD_NUM) TABLESPACE FCM_TS_IDX;
