CREATE OR REPLACE VIEW FI_CLOSING_ENDING_ACCOUNT_V
AS
SELECT FC.COMMON_ID
     , FC.GROUP_CODE
     , FC.CODE AS ENDING_ACCOUNT_CODE
     , FC.CODE_NAME AS ENDING_ACCOUNT_DESC
     , FC.VALUE1
     , FC.VALUE2
     , FC.VALUE3
     , FC.VALUE4
     , FC.VALUE5
     , FC.VALUE6
     , FC.VALUE7
     , FC.VALUE8
     , FC.VALUE9
     , FC.VALUE10
     , FC.DEFAULT_FLAG
     , FC.SORT_NUM
     , FC.DESCRIPTION
     , FC.ENABLED_FLAG
     , FC.EFFECTIVE_DATE_FR
     , FC.EFFECTIVE_DATE_TO
     , FC.SOB_ID
     , FC.ORG_ID
  FROM FI_COMMON FC
WHERE FC.GROUP_CODE   = 'CLOSING_ENDING_ACCOUNT'
;
  
