/******************************************************************************/
/* Project      : FPCB ERP
/* Module       : FCM
/* Program Name : FI_CUSTOMER_BALANCE
/* Description  : 계정별 거래처별 잔액원장.
/*
/* Reference by :
/* Program History
/*------------------------------------------------------------------------------
/*   Date       In Charge          Description
/*------------------------------------------------------------------------------
/* 07-JUN-2010  Jeon Ho Su          Initialize
/******************************************************************************/
CREATE TABLE FI_CUSTOMER_BALANCE 
( PERIOD_NAME                 VARCHAR2(10)  NOT NULL,     -- 기준년월.
  SOB_ID                      NUMBER        NOT NULL,     -- 회계조직.
  ORG_ID                      NUMBER        NOT NULL,     -- 사업부ID. 
  CUSTOMER_ID                 NUMBER        NOT NULL,     -- 거래처ID.
  ACCOUNT_BOOK_ID             NUMBER        NOT NULL,     -- 회계장부 ID.
  ACCOUNT_CONTROL_ID          NUMBER        NOT NULL,     -- 계정코드ID.
  ACCOUNT_CODE                VARCHAR2(20)  NOT NULL,     -- 계정코드. 
  CURRENCY_CODE               VARCHAR2(10)  ,             -- 통화. 
  MANAGEMENT1                 VARCHAR2(50)  ,
  MANAGEMENT2                 VARCHAR2(50)  ,
  PRE_DR_AMOUNT               NUMBER(15,0)  DEFAULT 0,    -- 전월차변이월잔액.
  PRE_CR_AMOUNT               NUMBER(15,0)  DEFAULT 0,    -- 전월대변이월잔액. 
  PRE_DR_CURR_AMOUNT          NUMBER(15,0)  DEFAULT 0,    -- 전월차변이월잔액(외화).
  PRE_CR_CURR_AMOUNT          NUMBER(15,0)  DEFAULT 0,    -- 전월대변이월잔액(외화).
  THIS_DR_AMOUNT              NUMBER(15,0)  DEFAULT 0,    -- 당월차변합계.
  THIS_CR_AMOUNT              NUMBER(15,0)  DEFAULT 0,    -- 당월대변합계.
  THIS_DR_CURR_AMOUNT         NUMBER(16,4)  DEFAULT 0,    -- 당월차변합계(외화).  
  THIS_CR_CURR_AMOUNT         NUMBER(16,4)  DEFAULT 0,    -- 당월대변합계(외화).
  REMAIN_DR_AMOUNT            NUMBER(15,0)  DEFAULT 0,    -- 차변잔액.
  REMAIN_CR_AMOUNT            NUMBER(15,0)  DEFAULT 0,    -- 대변잔액.
  REMAIN_DR_CURR_AMOUNT       NUMBER(16,4)  DEFAULT 0,    -- 차변잔액(외화).
  REMAIN_CR_CURR_AMOUNT       NUMBER(16,4)  DEFAULT 0,    -- 대변잔액(외화).
  CREATION_DATE               DATE          NOT NULL,     -- 생성자.
  CREATED_BY                  NUMBER        NOT NULL,     -- 생성일.
  LAST_UPDATE_DATE            DATE          NOT NULL,     -- 수정자.
  LAST_UPDATED_BY             NUMBER        NOT NULL      -- 수정일.
) TABLESPACE FCM_TS_DATA;

COMMENT ON TABLE FI_CUSTOMER_BALANCE IS '계정별 거래처별잔액';
COMMENT ON COLUMN APPS.FI_CUSTOMER_BALANCE.PERIOD_NAME IS '회계년월';
COMMENT ON COLUMN APPS.FI_CUSTOMER_BALANCE.CUSTOMER_ID IS '거래처코드';
COMMENT ON COLUMN APPS.FI_CUSTOMER_BALANCE.ACCOUNT_BOOK_ID IS '회계장부ID';
COMMENT ON COLUMN APPS.FI_CUSTOMER_BALANCE.ACCOUNT_CONTROL_ID IS '계정통제ID';
COMMENT ON COLUMN APPS.FI_CUSTOMER_BALANCE.ACCOUNT_CODE IS '계정코드';
COMMENT ON COLUMN APPS.FI_CUSTOMER_BALANCE.CURRENCY_CODE IS '통화';

COMMENT ON COLUMN APPS.FI_CUSTOMER_BALANCE.PRE_DR_AMOUNT IS '전월차변이월금액';
COMMENT ON COLUMN APPS.FI_CUSTOMER_BALANCE.PRE_CR_AMOUNT IS '전월대변이월금액';
COMMENT ON COLUMN APPS.FI_CUSTOMER_BALANCE.PRE_DR_CURR_AMOUNT IS '전월차변이월금액(외화)';
COMMENT ON COLUMN APPS.FI_CUSTOMER_BALANCE.PRE_CR_CURR_AMOUNT IS '전월대변이월금액(외화)';

COMMENT ON COLUMN APPS.FI_CUSTOMER_BALANCE.THIS_DR_AMOUNT IS '당월차변합계';
COMMENT ON COLUMN APPS.FI_CUSTOMER_BALANCE.THIS_CR_AMOUNT IS '당월대변합계';
COMMENT ON COLUMN APPS.FI_CUSTOMER_BALANCE.THIS_DR_CURR_AMOUNT IS '당월차변합계(외화)';
COMMENT ON COLUMN APPS.FI_CUSTOMER_BALANCE.THIS_CR_CURR_AMOUNT IS '당월대변합계(외화)';

COMMENT ON COLUMN APPS.FI_CUSTOMER_BALANCE.REMAIN_DR_AMOUNT IS '당월차변잔액';
COMMENT ON COLUMN APPS.FI_CUSTOMER_BALANCE.REMAIN_CR_AMOUNT IS '당월대변잔액';
COMMENT ON COLUMN APPS.FI_CUSTOMER_BALANCE.REMAIN_DR_CURR_AMOUNT IS '당월차변잔액(외화)';
COMMENT ON COLUMN APPS.FI_CUSTOMER_BALANCE.REMAIN_CR_CURR_AMOUNT IS '당월대변잔액(외화)';

COMMENT ON COLUMN APPS.FI_CUSTOMER_BALANCE.CREATION_DATE IS '생성자';
COMMENT ON COLUMN APPS.FI_CUSTOMER_BALANCE.CREATED_BY IS '생성일';
COMMENT ON COLUMN APPS.FI_CUSTOMER_BALANCE.LAST_UPDATE_DATE IS '수정자';
COMMENT ON COLUMN APPS.FI_CUSTOMER_BALANCE.LAST_UPDATED_BY IS '수정일';

CREATE UNIQUE INDEX FI_CUSTOMER_BALANCE_PK ON 
  FI_CUSTOMER_BALANCE(PERIOD_NAME, SOB_ID, CUSTOMER_ID, ACCOUNT_BOOK_ID, ACCOUNT_CONTROL_ID, CURRENCY_CODE)
  TABLESPACE FCM_TS_IDX
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  LOGGING
  STORAGE (
           INITIAL 64K
           MINEXTENTS 1
           MAXEXTENTS 2147483645
          );

ALTER TABLE FI_CUSTOMER_BALANCE ADD ( 
  CONSTRAINT FI_CUSTOMER_BALANCE_PK PRIMARY KEY (PERIOD_NAME, SOB_ID, CUSTOMER_ID, ACCOUNT_BOOK_ID, ACCOUNT_CONTROL_ID, CURRENCY_CODE)
        );
