/******************************************************************************/
/* Project      : FPCB ERP
/* Module       : FCM - GL
/* Program Name : FI_CLOSING_ACCOUNT
/* Description  : 회계 결산 계정 관리
/*
/* Reference by :
/* Program History
/*------------------------------------------------------------------------------
/*   Date       In Charge          Description
/*------------------------------------------------------------------------------
/* 07-JUN-2010  Jeon Ho Su          Initialize
/******************************************************************************/
CREATE TABLE FI_CLOSING_ACCOUNT              
( CLOSING_ACCOUNT_ID    NUMBER          NOT NULL,
  CLOSING_GROUP         VARCHAR2(20)    NOT NULL,  /* 계정그룹 */
  ACCOUNT_CONTROL_ID    NUMBER          NOT NULL,  /* 계정관리 ID */
  ACCOUNT_CODE          VARCHAR2(20)    NOT NULL,  /* 계정코드 */
  SOB_ID                NUMBER          NOT NULL,
  ORG_ID                NUMBER          NOT NULL,
  C_ACCOUNT_CONTROL_ID  NUMBER          ,  
  CLOSING_ACCOUNT_TYPE  VARCHAR2(20)    ,          /* 결산TYPE */
  REMARK                VARCHAR2(200)   ,          /* 계정설명 */  
  CREATION_DATE         DATE            NOT NULL,  /* 생성일자 */
  CREATED_BY            NUMBER          NOT NULL,  /* 생성자 */
  LAST_UPDATE_DATE      DATE            NOT NULL,  /* 최종수정일자 */
  LAST_UPDATED_BY       NUMBER          NOT NULL   /* 최종수정자 */
) TABLESPACE FCM_TS_DATA;

-- Add comments to the columns 
COMMENT ON TABLE FI_CLOSING_ACCOUNT IS '결산계정 관리';
COMMENT ON COLUMN FI_CLOSING_ACCOUNT.CLOSING_ACCOUNT_ID IS '결산계정 ID';
COMMENT ON COLUMN FI_CLOSING_ACCOUNT.CLOSING_GROUP IS '결산계정 그룹';
COMMENT ON COLUMN FI_CLOSING_ACCOUNT.ACCOUNT_CONTROL_ID IS '계정관리 ID';
COMMENT ON COLUMN FI_CLOSING_ACCOUNT.ACCOUNT_CODE IS '계정코드';
COMMENT ON COLUMN FI_CLOSING_ACCOUNT.C_ACCOUNT_CONTROL_ID IS '상대계정 ID';
COMMENT ON COLUMN FI_CLOSING_ACCOUNT.CLOSING_ACCOUNT_TYPE IS '결산TYPE';
COMMENT ON COLUMN FI_CLOSING_ACCOUNT.REMARK IS '비고';
COMMENT ON COLUMN FI_CLOSING_ACCOUNT.CREATION_DATE  IS '생성일자';
COMMENT ON COLUMN FI_CLOSING_ACCOUNT.CREATED_BY IS '생성자';
COMMENT ON COLUMN FI_CLOSING_ACCOUNT.LAST_UPDATE_DATE IS '최종수정일자';
COMMENT ON COLUMN FI_CLOSING_ACCOUNT.LAST_UPDATED_BY IS '최종수정자';

-- CREATE INDEX.
CREATE UNIQUE INDEX FI_CLOSING_ACCOUNT_U1 ON FI_CLOSING_ACCOUNT(CLOSING_ACCOUNT_ID) TABLESPACE FCM_TS_IDX;
CREATE INDEX FI_CLOSING_ACCOUNT_N1 ON FI_CLOSING_ACCOUNT(ACCOUNT_CONTROL_ID) TABLESPACE FCM_TS_IDX;
CREATE INDEX FI_CLOSING_ACCOUNT_N2 ON FI_CLOSING_ACCOUNT(ACCOUNT_CODE, SOB_ID) TABLESPACE FCM_TS_IDX;
CREATE INDEX FI_CLOSING_ACCOUNT_N3 ON FI_CLOSING_ACCOUNT(CLOSING_GROUP, SOB_ID) TABLESPACE FCM_TS_IDX;
CREATE INDEX FI_CLOSING_ACCOUNT_N4 ON FI_CLOSING_ACCOUNT(CLOSING_ACCOUNT_TYPE, SOB_ID) TABLESPACE FCM_TS_IDX;

-- SEQUENCE;
CREATE SEQUENCE FI_CLOSING_ACCOUNT_S1;
-- ANALYZE.
ANALYZE TABLE FI_CLOSING_ACCOUNT COMPUTE STATISTICS;
ANALYZE INDEX FI_CLOSING_ACCOUNT_U1 COMPUTE STATISTICS;
ANALYZE INDEX FI_CLOSING_ACCOUNT_N1 COMPUTE STATISTICS;
ANALYZE INDEX FI_CLOSING_ACCOUNT_N2 COMPUTE STATISTICS;
ANALYZE INDEX FI_CLOSING_ACCOUNT_N3 COMPUTE STATISTICS;
ANALYZE INDEX FI_CLOSING_ACCOUNT_N4 COMPUTE STATISTICS;
