/******************************************************************************/
/* Project      : FPCB ERP
/* Module       : FCM
/* Program Name : FI_CLOSING_AUTO_JOURNAL
/* Description  : 결산 자동분개 정의.
/*
/* Reference by :
/* Program History
/*------------------------------------------------------------------------------
/*   Date       In Charge          Description
/*------------------------------------------------------------------------------
/* 07-JUN-2010  Jeon Ho Su          Initialize
/******************************************************************************/
CREATE TABLE FI_CLOSING_AUTO_JOURNAL
( JOURNAL_ID                      NUMBER        NOT NULL
, SOB_ID                          NUMBER        NOT NULL
, ORG_ID                          NUMBER        NOT NULL
, CLOSING_GROUP                   VARCHAR2(20)  NOT NULL 
, ACCOUNT_CONTROL_ID              NUMBER        NOT NULL
, ACCOUNT_CODE                    VARCHAR2(20)  NOT NULL
, ACCOUNT_DR_CR                   VARCHAR2(1)   NOT NULL
, CONTRA_ACCOUNT_FLAG             VARCHAR2(1)   DEFAULT 'N'
, REMARK                          VARCHAR2(150) 
, CREATION_DATE                   DATE          NOT NULL
, CREATED_BY                      NUMBER        NOT NULL
, LAST_UPDATE_DATE                DATE          NOT NULL
, LAST_UPDATED_BY                 NUMBER        NOT NULL
) TABLESPACE FCM_TS_DATA;

COMMENT ON TABLE APPS.FI_CLOSING_AUTO_JOURNAL  IS '결산 자동분개 유형 정의';
COMMENT ON COLUMN APPS.FI_CLOSING_AUTO_JOURNAL.JOURNAL_ID IS '결산 자동분개 ID';
COMMENT ON COLUMN APPS.FI_CLOSING_AUTO_JOURNAL.SOB_ID IS '회계조직';
COMMENT ON COLUMN APPS.FI_CLOSING_AUTO_JOURNAL.ACCOUNT_CONTROL_ID IS '계정통제ID';
COMMENT ON COLUMN APPS.FI_CLOSING_AUTO_JOURNAL.ACCOUNT_CODE IS '계정코드';
COMMENT ON COLUMN APPS.FI_CLOSING_AUTO_JOURNAL.ACCOUNT_DR_CR IS '차대구분(1-차, 2-대)';
COMMENT ON COLUMN APPS.FI_CLOSING_AUTO_JOURNAL.CONTRA_ACCOUNT_FLAG IS '대체계정여부';
COMMENT ON COLUMN APPS.FI_CLOSING_AUTO_JOURNAL.REMARK IS '비고';
COMMENT ON COLUMN APPS.FI_CLOSING_AUTO_JOURNAL.CREATION_DATE IS '생성일자';
COMMENT ON COLUMN APPS.FI_CLOSING_AUTO_JOURNAL.CREATED_BY IS '생성자';
COMMENT ON COLUMN APPS.FI_CLOSING_AUTO_JOURNAL.LAST_UPDATE_DATE IS '최종수정일자';
COMMENT ON COLUMN APPS.FI_CLOSING_AUTO_JOURNAL.LAST_UPDATED_BY IS '최종수정자';

-- INDEX.
CREATE UNIQUE INDEX FI_CLOSING_AUTO_JOURNAL_U1 ON FI_CLOSING_AUTO_JOURNAL(JOURNAL_ID) TABLESPACE FCM_TS_IDX;
CREATE INDEX FI_CLOSING_AUTO_JOURNAL_N1 ON FI_CLOSING_AUTO_JOURNAL(ACCOUNT_CONTROL_ID) TABLESPACE FCM_TS_IDX;

-- SEQUENCE.
CREATE SEQUENCE FI_CLOSING_AUTO_JOURNAL_S1;

-- ANALYZE.
ANALYZE TABLE FI_CLOSING_AUTO_JOURNAL COMPUTE STATISTICS;
ANALYZE INDEX FI_CLOSING_AUTO_JOURNAL_U1 COMPUTE STATISTICS;
ANALYZE INDEX FI_CLOSING_AUTO_JOURNAL_N1 COMPUTE STATISTICS;
