CREATE OR REPLACE VIEW FI_DEPT_MASTER_V 
AS
SELECT DM.DEPT_ID
    , DM.SOB_ID
    , DM.DEPT_CODE
    , DM.DEPT_NAME
    , DM.DEPT_NAME_S
    , DM.DEPT_LEVEL
    , DM.UPPER_DEPT_ID
    , DM.SORT_NUM
    , DM.DEPT_GROUP
    , DM.DESCRIPTION
    , DM.ENABLED_FLAG
    , DM.EFFECTIVE_DATE_FR
    , DM.EFFECTIVE_DATE_TO
  FROM FI_DEPT_MASTER DM
    , FI_ACCOUNT_BOOK AB
 WHERE DM.SOB_ID                  = AB.SOB_ID
   AND AB.OPERATING_FLAG          = 'Y'
