-- CREATE TABLE
CREATE TABLE FI_DPR_SPEC
(
  SOB_ID           NUMBER NOT NULL,
  ORG_ID           NUMBER NOT NULL,
  SLIP_LINE_ID     NUMBER NOT NULL,
  DPR_ASSET_GB_ID  NUMBER NOT NULL,
  SPEC_CONTENTS    VARCHAR2(300),
  SUP_AMOUNT       NUMBER,
  SURTAX           NUMBER,
  ASSET_CNT        NUMBER,
  CREATION_DATE    DATE NOT NULL,
  CREATED_BY       NUMBER NOT NULL,
  LAST_UPDATE_DATE DATE NOT NULL,
  LAST_UPDATED_BY  NUMBER NOT NULL
)
TABLESPACE FCM_TS_DATA
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE FI_DPR_SPEC
  IS '건물등감가상각취득명세서';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN FI_DPR_SPEC.SOB_ID
  IS '회사아이디';
COMMENT ON COLUMN FI_DPR_SPEC.ORG_ID
  IS '사업부아이디';
COMMENT ON COLUMN FI_DPR_SPEC.SLIP_LINE_ID
  IS '전표라인아이디';
COMMENT ON COLUMN FI_DPR_SPEC.DPR_ASSET_GB_ID
  IS '건물등감가상각취득명세서_자산구분';
COMMENT ON COLUMN FI_DPR_SPEC.SPEC_CONTENTS
  IS '품명및내역';
COMMENT ON COLUMN FI_DPR_SPEC.SUP_AMOUNT
  IS '공급가액';
COMMENT ON COLUMN FI_DPR_SPEC.SURTAX
  IS '부가세';
COMMENT ON COLUMN FI_DPR_SPEC.ASSET_CNT
  IS '자산건수';
COMMENT ON COLUMN FI_DPR_SPEC.CREATION_DATE
  IS '생성일';
COMMENT ON COLUMN FI_DPR_SPEC.CREATED_BY
  IS '생성자';
COMMENT ON COLUMN FI_DPR_SPEC.LAST_UPDATE_DATE
  IS '수정일';
COMMENT ON COLUMN FI_DPR_SPEC.LAST_UPDATED_BY
  IS '수정자';
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE FI_DPR_SPEC
  ADD CONSTRAINT XPKFI_DPR_SPEC PRIMARY KEY (SOB_ID, ORG_ID, SLIP_LINE_ID, DPR_ASSET_GB_ID)
  USING INDEX 
  TABLESPACE FCM_TS_DATA
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
