CREATE OR REPLACE VIEW FI_DEPT_MASTER_MAPPING_V AS
SELECT FDM.DEPT_ID
     , FDM.DEPT_CODE
     , FDM.DEPT_NAME
     , FDM.DEPT_NAME_S
     , FDM.DEPT_LEVEL
     , FDM.UPPER_DEPT_ID
     , FDM.SORT_NUM
     , FDM.DEPT_GROUP
     , FDM.DESCRIPTION
     , FDM.ENABLED_FLAG
     , FDM.EFFECTIVE_DATE_FR
     , FDM.EFFECTIVE_DATE_TO
     , HDM.HR_DEPT_ID
     , HDM.CORP_ID AS HR_CORP_ID
     , HDM.ENABLED_FLAG AS HR_ENABLED_FLAG
     , HDM.EFFECTIVE_DATE_FR AS HR_EFFECTIVE_DATE_FR
     , HDM.EFFECTIVE_DATE_TO AS HR_EFFECTIVE_DATE_TO
     , FDM.SOB_ID
  FROM FI_DEPT_MASTER FDM
    , HRM_DEPT_MAPPING HDM
WHERE FDM.DEPT_ID                 = HDM.M_DEPT_ID
  AND FDM.SOB_ID                  = HDM.SOB_ID
  AND HDM.MODULE_TYPE             = 'FCM';
