CREATE OR REPLACE VIEW FI_DEPOSIT_ACCOUNT_V AS
-- 예적금 계정.
SELECT FC.COMMON_ID 
     , FC.GROUP_CODE
     , FC.CODE AS ACCOUNT_CODE
     , FC.CODE_NAME AS ACCOUNT_NAME
     , FC.VALUE1 AS DEPOSIT_GB
     , FC.VALUE2
     , FC.VALUE3
     , FC.VALUE4
     , FC.VALUE5
     , FC.VALUE6
     , FC.VALUE7
     , FC.VALUE8
     , FC.VALUE9
     , FC.VALUE10
     , FC.DEFAULT_FLAG
     , FC.SORT_NUM
     , FC.DESCRIPTION
     , FC.ENABLED_FLAG
     , FC.EFFECTIVE_DATE_FR
     , FC.EFFECTIVE_DATE_TO
     , FC.SOB_ID
     , FC.ORG_ID
  FROM FI_COMMON_TLV FC
 WHERE FC.GROUP_CODE              = 'DEPOSIT_ACCOUNT';
