/******************************************************************************/
/* Project      : FPCB ERP
/* Module       : FCM
/* Program Name : FI_DEPOSIT_MASTER
/* Description  : 예적금 마스터.
/*
/* Reference by :
/* Program History
/*------------------------------------------------------------------------------
/*   Date       In Charge          Description
/*------------------------------------------------------------------------------
/* 07-JUN-2010  Jeon Ho Su          Initialize
/******************************************************************************/
CREATE TABLE FI_DEPOSIT_MASTER 
( BANK_ID                       NUMBER          NOT NULL, -- 금융기관ID.
  BANK_ACCOUNT_ID               NUMBER          NOT NULL, -- 은행계좌ID.
  SOB_ID                        NUMBER          NOT NULL, -- 회계조직.
  ORG_ID                        NUMBER          NOT NULL, -- 사업부ID.
  DEPOSIT_GB                    VARCHAR2(10)    NOT NULL, -- 예적금구분(DEPOSIT_GB).
  ACCOUNT_TYPE                  VARCHAR2(20)    NOT NULL, -- 예적금종류(ACCOUNT_TYPE).
  ISSUE_DATE                    DATE            NOT NULL, -- 개설일자.
  DUE_DATE                      DATE            , -- 만기일자.
  CURRENCY_CODE                 VARCHAR2(10)    , -- 통화.
  EXCHANGE_RATE                 NUMBER          , -- 환율.
  DEPOSIT_CURR_AMOUNT           NUMBER          DEFAULT 0, -- 금액_외화.
  DEPOSIT_AMOUNT                NUMBER          DEFAULT 0, -- 금액.  
  INTER_RATE                    NUMBER          , -- 이자율.
  SPREAD_RATE                   NUMBER          , -- SPREAD_RATE.
  INTER_KIND                    VARCHAR2(10)    , -- 이자종류.
  INTER_TYPE                    VARCHAR2(10)    , -- 이자유형.
  PAYMENT_PERIOD                VARCHAR2(10)    , -- 납입주기.
  PAYMENT_COUNT                 NUMBER          , -- 납입횟수.
  MONTH_CURR_AMOUNT             NUMBER          DEFAULT 0, -- 월납입금액_외화.
  MONTH_AMOUNT                  NUMBER          DEFAULT 0, -- 월납입금액. 
  TOTAL_PAYMENT_COUNT           NUMBER          , -- 총납입횟수. 
  TOTAL_CURR_AMOUNT             NUMBER          DEFAULT 0, -- 총납입금액_외화.
  TOTAL_AMOUNT                  NUMBER          DEFAULT 0, -- 총납입금액.  
  CANCEL_DATE                   DATE            , -- 해약일자.
  CANCEL_EXCHANGE_RATE          NUMBER          , -- 해약시환율. 
  CANCEL_PRIN_AMOUNT            NUMBER          , -- 해약시원금.
  CANCEL_PRIN_CURR_AMOUNT       NUMBER          , -- 해약시원금_외화.
  CANCEL_INTER_RATE             NUMBER          , -- 해약시이자율.
  CANCEL_INTER_AMOUNT           NUMBER          , -- 해약시이금액.
  CANCEL_INTER_CURR_AMOUNT      NUMBER          , -- 해약시이금액_외화.
  CANCEL_AMOUNT                 NUMBER          , -- 해약금액.
  CANCEL_CURR_AMOUNT            NUMBER          , -- 해약금액_외화.
  MORTGAGE_YN                   VARCHAR2(1)     DEFAULT 'N', -- 담보설정(Y/N).
  MORTGAGE_DATE                 DATE            , -- 담보제공일자.
  FINAL_CURR_AMOUNT             NUMBER          DEFAULT 0, -- 최종금액_외화.
  FINAL_AMOUNT                  NUMBER          DEFAULT 0, -- 최종금액.  
  TRANS_STATUS                  VARCHAR2(10)    NOT NULL, -- 거래_상태.
  COST_CENTER_ID                NUMBER          , -- 코스트(COST)센타코드.
  REMARK                        VARCHAR2(100)   , -- 적요.
  ENABLED_FLAG                  VARCHAR2(1)     DEFAULT 'Y', -- 사용(Y/N).
  CREATION_DATE                 DATE            NOT NULL, -- 생성자.
  CREATED_BY                    NUMBER          NOT NULL, -- 생성일.
  LAST_UPDATE_DATE              DATE            NOT NULL, -- 수정자.
  LAST_UPDATED_BY               NUMBER          NOT NULL  -- 수정일.
) TABLESPACE FCM_TS_DATA;

COMMENT ON TABLE FI_DEPOSIT_MASTER IS '예적금 MASTER';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.BANK_ID IS '금융기관ID';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.BANK_ACCOUNT_ID IS '은행계좌ID';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.SOB_ID IS '회사코드';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.ORG_ID IS '사업부ID';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.DEPOSIT_GB IS '예적금구분(DEPOSIT_GB)';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.ACCOUNT_TYPE IS '계좌종류(ACCOUNT_TYPE)';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.ISSUE_DATE IS '개설일자';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.DUE_DATE IS '만기일자';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.CURRENCY_CODE IS '통화';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.EXCHANGE_RATE IS '환율';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.DEPOSIT_CURR_AMOUNT IS '약정금액_외화';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.DEPOSIT_AMOUNT IS '약정금액';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.INTER_RATE IS '이자율';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.SPREAD_RATE IS 'SPREAD_RATE';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.INTER_KIND IS '이자종류';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.INTER_TYPE IS '이자유형';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.PAYMENT_PERIOD IS '납입주기';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.PAYMENT_COUNT IS '납입횟수';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.MONTH_CURR_AMOUNT IS '월납입금액_외화';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.MONTH_AMOUNT IS '월납입금액';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.TOTAL_PAYMENT_COUNT IS '총납입횟수';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.TOTAL_CURR_AMOUNT IS '총납입금액_외화';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.TOTAL_AMOUNT IS '총납입금액';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.CANCEL_DATE IS '해약일자';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.CANCEL_EXCHANGE_RATE IS '해약시환율';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.CANCEL_PRIN_AMOUNT IS '해약시원금';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.CANCEL_PRIN_CURR_AMOUNT IS '해약시원금_외화';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.CANCEL_INTER_RATE IS '해약시이자율';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.CANCEL_INTER_AMOUNT IS '해약시이금액';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.CANCEL_INTER_CURR_AMOUNT IS '해약시이금액_외화';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.CANCEL_AMOUNT IS '해약금액';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.CANCEL_CURR_AMOUNT IS '해약금액_외화';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.FINAL_CURR_AMOUNT IS '최종금액_외화';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.FINAL_AMOUNT IS '최종금액';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.TRANS_STATUS IS '거래상태(TRANS_STATUS)';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.COST_CENTER_ID IS '코스트(COST)센타코드';
COMMENT ON COLUMN APPS.FI_DEPOSIT_MASTER.REMARK IS '적요';
COMMENT ON COLUMN APPS.FI_BANK_ACCOUNT.ENABLED_FLAG IS '사용(Y/N)';
COMMENT ON COLUMN APPS.FI_BANK_ACCOUNT.CREATION_DATE IS '생성자';
COMMENT ON COLUMN APPS.FI_BANK_ACCOUNT.CREATED_BY IS '생성일';
COMMENT ON COLUMN APPS.FI_BANK_ACCOUNT.LAST_UPDATE_DATE IS '수정자';
COMMENT ON COLUMN APPS.FI_BANK_ACCOUNT.LAST_UPDATED_BY IS '수정일';

CREATE UNIQUE INDEX FI_DEPOSIT_MASTER_PK ON 
  FI_DEPOSIT_MASTER( BANK_ID, BANK_ACCOUNT_ID, SOB_ID )
  TABLESPACE FCM_TS_IDX
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  LOGGING
  STORAGE (
           INITIAL 64K
           MINEXTENTS 1
           MAXEXTENTS 2147483645
          );

ALTER TABLE FI_DEPOSIT_MASTER ADD ( 
  CONSTRAINT FI_DEPOSIT_MASTER_PK PRIMARY KEY ( BANK_ID, BANK_ACCOUNT_ID, SOB_ID )
        );
