CREATE OR REPLACE VIEW FI_FORM_TYPE_V AS
SELECT FC.COMMON_ID AS FORM_TYPE_ID
     , FC.GROUP_CODE
     , FC.CODE AS FORM_TYPE
     , FC.CODE_NAME AS FORM_TYPE_NAME
     , TO_NUMBER(FC.VALUE1) AS CONTROL_LEVEL
     , FC.VALUE2 AS ACCOUNT_BOOK_CODE
     , FC.VALUE3
     , FC.VALUE4
     , FC.VALUE5
     , FC.VALUE6
     , FC.VALUE7
     , FC.VALUE8
     , FC.VALUE9
     , FC.VALUE10
     , FC.DEFAULT_FLAG
     , FC.SORT_NUM
     , FC.DESCRIPTION
     , FC.ENABLED_FLAG
     , FC.EFFECTIVE_DATE_FR
     , FC.EFFECTIVE_DATE_TO
     , FC.SOB_ID
     , FC.ORG_ID
  FROM FI_COMMON_TLV FC
 WHERE FC.GROUP_CODE              = 'FORM_TYPE';
