CREATE OR REPLACE VIEW FI_LOAN_USE_V AS
SELECT FC.COMMON_ID AS LOAN_USE_ID
     , FC.GROUP_CODE
     , FC.CODE AS LOAN_USE_CODE
     , FC.CODE_NAME AS LOAN_USE_NAME
     , FC.VALUE1 AS LOAN_KIND_CODE
     , FC.VALUE2 AS TR_CLASS_CODE
     , FC.VALUE3
     , FC.VALUE4
     , FC.VALUE5
     , FC.VALUE6
     , FC.VALUE7
     , FC.VALUE8
     , FC.VALUE9
     , FC.VALUE10
     , FC.DEFAULT_FLAG
     , FC.SORT_NUM
     , FC.DESCRIPTION
     , FC.ENABLED_FLAG
     , FC.EFFECTIVE_DATE_FR
     , FC.EFFECTIVE_DATE_TO
     , FC.SOB_ID
     , FC.ORG_ID
  FROM FI_COMMON_TLV FC
 WHERE FC.GROUP_CODE              = 'LOAN_USE';
