CREATE OR REPLACE VIEW FI_MANAGEMENT_CODE_V AS
SELECT FC.COMMON_ID AS MANAGEMENT_ID
     , FC.GROUP_CODE
     , FC.CODE AS MANAGEMENT_CODE
     , FC.CODE_NAME AS MANAGEMENT_NAME
     , NVL(FC.VALUE1, 'N') AS DR_LOOKUP_YN
     , NVL(FC.VALUE2, 'N') AS CR_LOOKUP_YN
     , FC.VALUE3 AS LOOKUP_TYPE
     , NVL(FC.VALUE4, 'VARCHAR2') AS DATA_TYPE
     , NVL(FC.VALUE5, 'N') AS VAT_YN
     , NVL(FC.VALUE6, 'N') AS BALANCE_YN
     , FC.VALUE7
     , FC.VALUE8
     , FC.VALUE9
     , FC.VALUE10
     , FC.DEFAULT_FLAG
     , FC.SORT_NUM
     , FC.DESCRIPTION
     , FC.ENABLED_FLAG
     , FC.EFFECTIVE_DATE_FR
     , FC.EFFECTIVE_DATE_TO
     , FC.SOB_ID
     , FC.ORG_ID
  FROM FI_COMMON_TLV FC
 WHERE FC.GROUP_CODE              = 'MANAGEMENT_CODE';
