CREATE OR REPLACE VIEW FI_ROUND_TYPE_V AS
SELECT FC.COMMON_ID AS ROUND_TYPE_ID
     , FC.GROUP_CODE
     , FC.CODE AS ROUND_TYPE
     , FC.CODE_NAME AS ROUND_TYPE_NAME
     , FC.VALUE1 AS ROUNDING_RULE
     , TO_NUMBER(FC.VALUE2) AS DECIMAL_POINT
     , FC.VALUE3
     , FC.VALUE4
     , FC.VALUE5
     , FC.VALUE6
     , FC.VALUE7
     , FC.VALUE8
     , FC.VALUE9
     , FC.VALUE10
     , FC.DEFAULT_FLAG
     , FC.SORT_NUM
     , FC.DESCRIPTION
     , FC.ENABLED_FLAG
     , FC.EFFECTIVE_DATE_FR
     , FC.EFFECTIVE_DATE_TO
     , FC.SOB_ID
     , FC.ORG_ID
  FROM FI_COMMON_TLV FC
 WHERE FC.GROUP_CODE              = 'ROUND_TYPE';
