CREATE OR REPLACE VIEW FI_SLIP_MANAGEMENT_ITEM_V1
AS
SELECT SMI.SLIP_LINE_ID
     , SMI.SLIP_DATE
     , SMI.SLIP_NUM
     , SMI.SLIP_LINE_SEQ
     , SMI.SLIP_HEADER_ID
     , SMI.SOB_ID
     , SMI.MANAGEMENT_SEQ
     , SMI.MANAGEMENT_ID
     , SMI.MANAGEMENT_CODE
     , SMI.MANAGEMENT_VALUE
     , MC.DR_LOOKUP_YN
     , MC.CR_LOOKUP_YN
     , MC.LOOKUP_TYPE
     , MC.DATA_TYPE
     , MC.VAT_YN
     , MC.BALANCE_YN
  FROM FI_SLIP_MANAGEMENT_ITEM SMI
    , FI_MANAGEMENT_CODE_V MC
WHERE SMI.MANAGEMENT_ID           = MC.MANAGEMENT_ID
  AND SMI.SOB_ID                  = MC.SOB_ID
;
