/******************************************************************************/
/* PROJECT      : FPCB ERP
/* MODULE       : FI
/* PROGRAM NAME : FI_SURTAX_CARD
/* DESCRIPTION  : 일반과세자 부가가치세 신고서.
/* REFERENCE BY : 회계 법인 정보 관리.
/* PROGRAM HISTORY
/*------------------------------------------------------------------------------
/*   DATE       IN CHARGE          DESCRIPTION
/*------------------------------------------------------------------------------
/* 07-JUN-2010  JEON HO SU          INITIALIZE
/******************************************************************************/
-- CREATE TABLE
CREATE TABLE FI_SURTAX_CARD
(
  SOB_ID                      NUMBER NOT NULL,
  ORG_ID                      NUMBER NOT NULL,
  TAX_CODE                    VARCHAR2(10) NOT NULL,
  VAT_MNG_SERIAL              NUMBER NOT NULL,
  SPEC_SERIAL                 NUMBER NOT NULL,
  VAT_MAKE_GB                 VARCHAR2(50),
  GUBUN_1                     VARCHAR2(1),
  GUBUN_2                     VARCHAR2(1),
  GUBUN_3                     VARCHAR2(1),
  GUBUN_4                     VARCHAR2(1),
  TITLE_1_1                   DATE,
  TITLE_1_2                   DATE,
  TITLE_2                     VARCHAR2(50),
  TITLE_3                     VARCHAR2(50),
  TITLE_4                     VARCHAR2(30),
  TITLE_5                     VARCHAR2(30),
  TITLE_6                     VARCHAR2(30),
  TITLE_7                     VARCHAR2(30),
  TITLE_8                     VARCHAR2(30),
  TITLE_9                     VARCHAR2(100),
  TITLE_10                    VARCHAR2(50),
  TITLE_11                    VARCHAR2(50),
  TITLE_12                    VARCHAR2(50),
  TITLE_13                    VARCHAR2(30),
  TITLE_14                    DATE,
  TITLE_15                    VARCHAR2(30),
  TITLE_16                    VARCHAR2(50),
  COL1_1                      NUMBER,
  COL1_2                      NUMBER,
  COL2_1                      NUMBER,
  COL2_2                      NUMBER,
  COL3_1                      NUMBER,
  COL3_2                      NUMBER,
  COL4_1                      NUMBER,
  COL4_2                      NUMBER,
  COL5_1                      NUMBER,
  COL6_1                      NUMBER,
  COL7_1                      NUMBER,
  COL7_2                      NUMBER,
  COL8_2                      NUMBER,
  COL9_1                      NUMBER,
  COL9_2                      NUMBER,
  COL10_1                     NUMBER,
  COL10_2                     NUMBER,
  COL11_1                     NUMBER,
  COL11_2                     NUMBER,
  COL12_1                     NUMBER,
  COL12_2                     NUMBER,
  COL13_1                     NUMBER,
  COL13_2                     NUMBER,
  COL14_1                     NUMBER,
  COL14_2                     NUMBER,
  COL15_1                     NUMBER,
  COL15_2                     NUMBER,
  COL16_1                     NUMBER,
  COL16_2                     NUMBER,
  COL17_1                     NUMBER,
  COL17_2                     NUMBER,
  COL_DA                      NUMBER,
  COL18_2                     NUMBER,
  COL19_2                     NUMBER,
  COL20_2                     NUMBER,
  COL21_2                     NUMBER,
  COL22_2                     NUMBER,
  COL23_2                     NUMBER,
  COL24_2                     NUMBER,
  COL25                       NUMBER,
  DEAL_BANK                   VARCHAR2(50),
  DEAL_BANK_CD                VARCHAR2(20),
  DEAL_BRANCH                 VARCHAR2(50),
  DEAL_BRANCH_ID              NUMBER,
  ACC_NO                      VARCHAR2(50),
  CLOSURE_DATE                DATE,
  CLOSURE_REASON              VARCHAR2(100),
  COL26_1                     VARCHAR2(50),
  COL26_2                     VARCHAR2(50),
  COL26_3                     NUMBER,
  COL27_1                     VARCHAR2(50),
  COL27_2                     VARCHAR2(50),
  COL27_3                     NUMBER,
  COL28_1                     VARCHAR2(50),
  COL28_2                     VARCHAR2(50),
  COL28_3                     NUMBER,
  COL29_1                     VARCHAR2(50),
  COL29_2                     VARCHAR2(50),
  COL29_3                     NUMBER,
  COL30                       NUMBER,
  COL31_1                     NUMBER,
  COL31_2                     NUMBER,
  COL32_1                     NUMBER,
  COL32_2                     NUMBER,
  COL33_1                     NUMBER,
  COL34_1                     NUMBER,
  COL35_1                     NUMBER,
  COL35_2                     NUMBER,
  COL36_1                     NUMBER,
  COL36_2                     NUMBER,
  COL37_1                     NUMBER,
  COL37_2                     NUMBER,
  COL38_1                     NUMBER,
  COL38_2                     NUMBER,
  COL39_1                     NUMBER,
  COL39_2                     NUMBER,
  COL40_1                     NUMBER,
  COL40_2                     NUMBER,
  COL41_1                     NUMBER,
  COL41_2                     NUMBER,
  COL42_1                     NUMBER,
  COL42_2                     NUMBER,
  COL43_1                     NUMBER,
  COL43_2                     NUMBER,
  COL44_2                     NUMBER,
  COL45_2                     NUMBER,
  COL46_2                     NUMBER,
  COL47_1                     NUMBER,
  COL47_2                     NUMBER,
  COL48_1                     NUMBER,
  COL48_2                     NUMBER,
  COL49_1                     NUMBER,
  COL49_2                     NUMBER,
  COL50_1                     NUMBER,
  COL50_2                     NUMBER,
  COL51_1                     NUMBER,
  COL51_2                     NUMBER,
  COL52_2                     NUMBER,
  COL53_2                     NUMBER,
  COL54_2                     NUMBER,
  COL55_2                     NUMBER,
  COL56_2                     NUMBER,
  COL57_2                     NUMBER,
  COL58_1                     NUMBER,
  COL58_2                     NUMBER,
  COL59_1                     NUMBER,
  COL59_2                     NUMBER,
  COL60_1                     NUMBER,
  COL60_2                     NUMBER,
  COL61_1                     NUMBER,
  COL61_2                     NUMBER,
  COL62_1                     NUMBER,
  COL62_2                     NUMBER,
  COL63_1                     NUMBER,
  COL63_2                     NUMBER,
  COL64_1                     NUMBER,
  COL64_2                     NUMBER,
  COL65_1                     NUMBER,
  COL65_2                     NUMBER,
  COL66_1                     NUMBER,
  COL66_2                     NUMBER,
  COL67_1                     NUMBER,
  COL67_2                     NUMBER,
  COL68_2                     NUMBER,
  COL69_1                     VARCHAR2(50),
  COL69_2                     VARCHAR2(50),
  COL69_3                     NUMBER,
  COL70_1                     VARCHAR2(50),
  COL70_2                     VARCHAR2(50),
  COL70_3                     NUMBER,
  COL71_1                     VARCHAR2(50),
  COL71_2                     VARCHAR2(50),
  COL71_3                     NUMBER,
  COL72                       NUMBER,
  COL73                       NUMBER,
  COL74                       NUMBER,
  HOMETAX_USERID              VARCHAR2(20),
  VAT_PRESENTER_GB            NUMBER(1),
  VAT_LEVIER_GB               VARCHAR2(1),
  VAT_REFUND_GB               VARCHAR2(1),
  E_FILE_SURTAX_YN            VARCHAR2(1),
  E_FILE_ZERO_YN              VARCHAR2(1),
  E_FILE_REAL_ESTATE_YN       VARCHAR2(1),
  E_FILE_BLD_YN               VARCHAR2(1),
  E_FILE_NO_DEDUCTION_YN      VARCHAR2(1),
  E_FILE_SUM_VAT_YN           VARCHAR2(1),
  E_FILE_SUM_CALC_YN          VARCHAR2(1),
  E_FILE_EXPORT_YN            VARCHAR2(1),
  E_FILE_GET_YN               VARCHAR2(1),
  CREATION_DATE               DATE NOT NULL,
  CREATED_BY                  NUMBER NOT NULL,
  LAST_UPDATE_DATE            DATE NOT NULL,
  LAST_UPDATED_BY             NUMBER NOT NULL,
  E_FILE_TAX_PUB_YN           VARCHAR2(1),
  E_FILE_DOMESTIC_LC_YN       VARCHAR2(1),
  R_ORIGIN_PLACE_AMT          NUMBER DEFAULT 0,
  R_ORIGIN_PLACE_VAT          NUMBER DEFAULT 0,
  A_TAX_RECEIVE_DELAY_AMT     NUMBER DEFAULT 0,
  A_TAX_RECEIVE_DELAY_VAT     NUMBER DEFAULT 0,
  A_TAX_INV_SUM_BAD_AMT_1     NUMBER DEFAULT 0,
  A_TAX_INV_SUM_BAD_VAT_1     NUMBER DEFAULT 0,
  A_REPORT_BAD_AMT_1          NUMBER DEFAULT 0,
  A_REPORT_BAD_VAT_1          NUMBER DEFAULT 0,
  A_REPORT_BAD_AMT_2          NUMBER DEFAULT 0,
  A_REPORT_BAD_VAT_2          NUMBER DEFAULT 0,
  A_REPORT_BAD_AMT_3          NUMBER DEFAULT 0,
  A_REPORT_BAD_VAT_3          NUMBER DEFAULT 0,
  A_REPORT_BAD_AMT_4          NUMBER DEFAULT 0,
  A_REPORT_BAD_VAT_4          NUMBER DEFAULT 0,
  A_REALTY_LEASE_UNREPORT_AMT NUMBER DEFAULT 0,
  A_REALTY_LEASE_UNREPORT_VAT NUMBER DEFAULT 0,
  MODIFY_DEGREE               NUMBER,
  MODIFY_DESC                 VARCHAR2(300),
  CLOSED_FLAG                 VARCHAR2(2) DEFAULT 'N',
  LAST_FLAG                   VARCHAR2(2) DEFAULT 'N'
)
TABLESPACE FCM_TS_DATA
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
  
-- 2014.1기 예정 추가 
ALTER TABLE FI_SURTAX_CARD ADD COL26_4                    VARCHAR2(200);
ALTER TABLE FI_SURTAX_CARD ADD COL27_4                    VARCHAR2(200);
ALTER TABLE FI_SURTAX_CARD ADD COL28_4                    VARCHAR2(200);
ALTER TABLE FI_SURTAX_CARD ADD COL29_4                    VARCHAR2(200);

ALTER TABLE FI_SURTAX_CARD ADD PROXY_PAY_TAX_AMT          NUMBER DEFAULT 0;
ALTER TABLE FI_SURTAX_CARD ADD PROXY_PAY_TAX_VAT          NUMBER DEFAULT 0;
ALTER TABLE FI_SURTAX_CARD ADD SPECIAL_PAY_TAX_AMT        NUMBER DEFAULT 0;
ALTER TABLE FI_SURTAX_CARD ADD SPECIAL_PAY_TAX_VAT        NUMBER DEFAULT 0;
ALTER TABLE FI_SURTAX_CARD ADD E_FORE_TOUR_REFUND_AMT     NUMBER DEFAULT 0;
ALTER TABLE FI_SURTAX_CARD ADD E_FORE_TOUR_REFUND_VAT     NUMBER DEFAULT 0;   
ALTER TABLE FI_SURTAX_CARD ADD A_MISS_DEAL_ACCOUNT_AMT    NUMBER DEFAULT 0;
ALTER TABLE FI_SURTAX_CARD ADD A_MISS_DEAL_ACCOUNT_VAT    NUMBER DEFAULT 0;
ALTER TABLE FI_SURTAX_CARD ADD A_DELAY_PAYMENT_AMT        NUMBER DEFAULT 0;
ALTER TABLE FI_SURTAX_CARD ADD A_DELAY_PAYMENT_VAT        NUMBER DEFAULT 0;

COMMENT ON COLUMN FI_SURTAX_CARD.COL26_4 IS '2014.04.01-과세표준 생산요소1';
COMMENT ON COLUMN FI_SURTAX_CARD.COL27_4 IS '2014.04.01-과세표준 생산요소2';
COMMENT ON COLUMN FI_SURTAX_CARD.COL28_4 IS '2014.04.01-과세표준 생산요소3';
COMMENT ON COLUMN FI_SURTAX_CARD.COL29_4 IS '2014.04.01-과세표준 생산요소4';
COMMENT ON COLUMN FI_SURTAX_CARD.PROXY_PAY_TAX_AMT IS '2014.04.01-사업양수자의 대리납부 기납부세액';
COMMENT ON COLUMN FI_SURTAX_CARD.PROXY_PAY_TAX_VAT IS '2014.04.01-사업양수자의 대리납부 기납부세액';
COMMENT ON COLUMN FI_SURTAX_CARD.SPECIAL_PAY_TAX_AMT IS '2014.04.01-매입자납부특례 기납부세액';
COMMENT ON COLUMN FI_SURTAX_CARD.SPECIAL_PAY_TAX_VAT IS '2014.04.01-매입자납부특례 기납부세액';
COMMENT ON COLUMN FI_SURTAX_CARD.E_FORE_TOUR_REFUND_AMT IS '2014.04.01-그밖의 공제매입세액 : 외국인 관광객에 대한 환급세액(AMT-금액, VAT-세액)';
COMMENT ON COLUMN FI_SURTAX_CARD.E_FORE_TOUR_REFUND_VAT IS '2014.04.01-그밖의 공제매입세액 : 외국인 관광객에 대한 환급세액';
COMMENT ON COLUMN FI_SURTAX_CARD.A_MISS_DEAL_ACCOUNT_AMT IS '2014.04.01-가산세명세 : 매입자 납부특례 거래계좌 미사용(AMT-금액, VAT-세액)';
COMMENT ON COLUMN FI_SURTAX_CARD.A_MISS_DEAL_ACCOUNT_VAT IS '2014.04.01-가산세명세 : 매입자 납부특례 거래계좌 미사용';
COMMENT ON COLUMN FI_SURTAX_CARD.A_DELAY_PAYMENT_AMT IS '2014.04.01-가산세명세 : 매입자 납부특례 거래계좌 지연입금(AMT-금액, VAT-세액)';
COMMENT ON COLUMN FI_SURTAX_CARD.A_DELAY_PAYMENT_VAT IS '2014.04.01-가산세명세 : 매입자 납부특례 거래계좌 지연입금';



-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE FI_SURTAX_CARD IS '부가세신고서';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN FI_SURTAX_CARD.SOB_ID IS '회사아이디';
COMMENT ON COLUMN FI_SURTAX_CARD.ORG_ID IS '사업부아이디';
COMMENT ON COLUMN FI_SURTAX_CARD.TAX_CODE IS '사업장아이디';
COMMENT ON COLUMN FI_SURTAX_CARD.VAT_MNG_SERIAL IS '부가세신고기간구분번호';
COMMENT ON COLUMN FI_SURTAX_CARD.SPEC_SERIAL IS '일련번호';
COMMENT ON COLUMN FI_SURTAX_CARD.VAT_MAKE_GB IS '신고구분(01-정기신고, 02-수정신고)';
COMMENT ON COLUMN FI_SURTAX_CARD.GUBUN_1 IS '신고서구분_예정';
COMMENT ON COLUMN FI_SURTAX_CARD.GUBUN_2 IS '신고서구분_확정';
COMMENT ON COLUMN FI_SURTAX_CARD.GUBUN_3 IS '신고서구분_기한후과세표준';
COMMENT ON COLUMN FI_SURTAX_CARD.GUBUN_4 IS '신고서구분_영세율등조기환급';
COMMENT ON COLUMN FI_SURTAX_CARD.TITLE_1_1 IS '신고기간_시작';
COMMENT ON COLUMN FI_SURTAX_CARD.TITLE_1_2 IS '신고기간_종료';
COMMENT ON COLUMN FI_SURTAX_CARD.TITLE_2 IS '상호';
COMMENT ON COLUMN FI_SURTAX_CARD.TITLE_3 IS '성명';
COMMENT ON COLUMN FI_SURTAX_CARD.TITLE_4 IS '사업자등록번호';
COMMENT ON COLUMN FI_SURTAX_CARD.TITLE_5 IS '법인등록번호';
COMMENT ON COLUMN FI_SURTAX_CARD.TITLE_6 IS '사업장전화';
COMMENT ON COLUMN FI_SURTAX_CARD.TITLE_7 IS '주소지전화';
COMMENT ON COLUMN FI_SURTAX_CARD.TITLE_8 IS '휴대전화';
COMMENT ON COLUMN FI_SURTAX_CARD.TITLE_9 IS '사업장주소';
COMMENT ON COLUMN FI_SURTAX_CARD.TITLE_10 IS '전자우편주소';
COMMENT ON COLUMN FI_SURTAX_CARD.TITLE_11 IS '업태';
COMMENT ON COLUMN FI_SURTAX_CARD.TITLE_12 IS '종목';
COMMENT ON COLUMN FI_SURTAX_CARD.TITLE_13 IS '업종코드';
COMMENT ON COLUMN FI_SURTAX_CARD.TITLE_14 IS '작성일자';
COMMENT ON COLUMN FI_SURTAX_CARD.TITLE_15 IS '신고인';
COMMENT ON COLUMN FI_SURTAX_CARD.TITLE_16 IS '세무서';
COMMENT ON COLUMN FI_SURTAX_CARD.COL1_1 IS '과세_세금계산서발급분_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL1_2 IS '과세_세금계산서발급분_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL2_1 IS '과세_매입자발행세금계산서_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL2_2 IS '과세_매입자발행세금계산서_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL3_1 IS '과세_신용카드_현금영수증발행분_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL3_2 IS '과세_신용카드_현금영수증발행분_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL4_1 IS '과세_기타_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL4_2 IS '과세_기타_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL5_1 IS '영세율_세금계산서발급분_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL6_1 IS '양세율_기타_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL7_1 IS '예정신고누락분_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL7_2 IS '예정신고누락분_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL8_2 IS '대손세액가감_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL9_1 IS '합계_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL9_2 IS '합계_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL10_1 IS '매입_일반매입_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL10_2 IS '매입_일반매입_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL11_1 IS '매입_고정자산매입_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL11_2 IS '매입_고장자산매입_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL12_1 IS '매입_예정신고누락분_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL12_2 IS '매입_예정신고누락분_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL13_1 IS '매입_매입자발행세금계산서_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL13_2 IS '매입_매입자발행세금계산서_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL14_1 IS '매입_기타공제매입세액_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL14_2 IS '매입_기타공제매입세액_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL15_1 IS '매입_합계_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL15_2 IS '매입_합계_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL16_1 IS '매입_공제받지못할매입세액_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL16_2 IS '매입_공제받지못할매입세액_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL17_1 IS '매입_차감계_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL17_2 IS '매입_차감계_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL_DA IS '납부세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL18_2 IS '기타경감공제세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL19_2 IS '신용카드매출전표등발행공제등';
COMMENT ON COLUMN FI_SURTAX_CARD.COL20_2 IS '경감공제_합계';
COMMENT ON COLUMN FI_SURTAX_CARD.COL21_2 IS '예정신고미환급세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL22_2 IS '예정고지세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL23_2 IS '금지금_매입자_납부특례_기납부세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL24_2 IS '가산세액계';
COMMENT ON COLUMN FI_SURTAX_CARD.COL25 IS '차가감하여납부할세액';
COMMENT ON COLUMN FI_SURTAX_CARD.DEAL_BANK IS '거래은행';
COMMENT ON COLUMN FI_SURTAX_CARD.DEAL_BANK_CD IS '거래은행코드';
COMMENT ON COLUMN FI_SURTAX_CARD.DEAL_BRANCH IS '거래지점';
COMMENT ON COLUMN FI_SURTAX_CARD.DEAL_BRANCH_ID IS '거래지점코드';
COMMENT ON COLUMN FI_SURTAX_CARD.ACC_NO IS '계좌번호';
COMMENT ON COLUMN FI_SURTAX_CARD.CLOSURE_DATE IS '폐업일';
COMMENT ON COLUMN FI_SURTAX_CARD.CLOSURE_REASON IS '폐업사유';
COMMENT ON COLUMN FI_SURTAX_CARD.COL26_1 IS '과세표준_업태1';
COMMENT ON COLUMN FI_SURTAX_CARD.COL26_2 IS '과세표준_종목1';
COMMENT ON COLUMN FI_SURTAX_CARD.COL26_3 IS '과세표준_금액1';
COMMENT ON COLUMN FI_SURTAX_CARD.COL27_1 IS '과세표준_업태2';
COMMENT ON COLUMN FI_SURTAX_CARD.COL27_2 IS '과세표준_종목2';
COMMENT ON COLUMN FI_SURTAX_CARD.COL27_3 IS '과세표준_금액2';
COMMENT ON COLUMN FI_SURTAX_CARD.COL28_1 IS '과세표준_업태3';
COMMENT ON COLUMN FI_SURTAX_CARD.COL28_2 IS '과세표준_종목3';
COMMENT ON COLUMN FI_SURTAX_CARD.COL28_3 IS '과세표준_금액3';
COMMENT ON COLUMN FI_SURTAX_CARD.COL29_1 IS '과세표준_업태4';
COMMENT ON COLUMN FI_SURTAX_CARD.COL29_2 IS '과세표준_종목4';
COMMENT ON COLUMN FI_SURTAX_CARD.COL29_3 IS '과세표준_금액4';
COMMENT ON COLUMN FI_SURTAX_CARD.COL30 IS '과세표준_합계';
COMMENT ON COLUMN FI_SURTAX_CARD.COL31_1 IS '예정신고_매출_과세_세금계산서_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL31_2 IS '예정신고_매출_과세_세금계산서_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL32_1 IS '예정신고_매출_과세_기타_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL32_2 IS '예정신고_매출_과세_기타_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL33_1 IS '예정신고_매출_영세율_세금계산서';
COMMENT ON COLUMN FI_SURTAX_CARD.COL34_1 IS '예정신고_매출_영세율_기타';
COMMENT ON COLUMN FI_SURTAX_CARD.COL35_1 IS '예정신고_매출_합계_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL35_2 IS '예정신고_매출_합계_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL36_1 IS '예정신고_매입_세금계산서_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL36_2 IS '예정신고_매입_세금계산서_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL37_1 IS '예정신고_매입_기타공제매입세액_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL37_2 IS '예정신고_매입_기타공제매입세액_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL38_1 IS '예정신고_매입_합계_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL38_2 IS '예정신고_매입_합계_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL39_1 IS '기타공제_신용카드_일반매입_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL39_2 IS '기타공제_신용카드_일반매입_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL40_1 IS '기타공제_신용카드_고정자산매입_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL40_2 IS '기타공제_신용카드_고정자산매입_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL41_1 IS '기타공제_의제매입세액_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL41_2 IS '기타공제_의제매입세액_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL42_1 IS '기타공제_재활용폐자원등매입세액_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL42_2 IS '기타공제_재활용폐자원등매입세액_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL43_1 IS '기타공제_고금의제매입세액_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL43_2 IS '기타공제_고금의제매입세액_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL44_2 IS '기타공제_과세사업전환매입세액_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL45_2 IS '기타공제_재고매입세액_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL46_2 IS '기타공제_변제대손세액_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL47_1 IS '기타공제_합계_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL47_2 IS '기타공제_헙계_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL48_1 IS '공제받지못할매입세액_공제받지못할_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL48_2 IS '공제받지못할매입세액_공제받지못할_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL49_1 IS '공제받지못할매입세액_공통매입세액면세_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL49_2 IS '공제받지못할매입세액_공통매입세액면세_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL50_1 IS '공제받지못할매입세액_대손처분받은세액_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL50_2 IS '공제받지못할매입세액_대손처분받은세액_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL51_1 IS '공제받지못할매입세액_합계_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL51_2 IS '공제받지못할매입세액_합계_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL52_2 IS '기탁경감공제세액_전자신고세액공제_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL53_2 IS '기타경감공제세액_전자세금계산서발급세액공제_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL54_2 IS '기타경감공제세액_택시운송사업자경감세액_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL55_2 IS '기타경감공제세액_현금영수증사업자세액공제_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL56_2 IS '기타경감공제세액_기타_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL57_2 IS '기타경감공제세액_합계_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL58_1 IS '가산세명세_사업자미등록등_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL58_2 IS '가산세명세_사업자미등록등_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL59_1 IS '가산세명세_지연발급등_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL59_2 IS '가산세명세_지연발급등_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL60_1 IS '가산세명세_미발급등_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL60_2 IS '가산세명세_미발급등_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL61_1 IS '가산세명세_다음달15일이후_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL61_2 IS '가산세명세_다음달15일이후_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL62_1 IS '가산세명세_과세기간다음달15일이후_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL62_2 IS '가산세명세_과세기간다음달15일이후_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL63_1 IS '가산세명세_세금계산서합계표제출불성실_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL63_2 IS '가산세명세_세금계산서합계표제출불성실_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL64_1 IS '가산세명세_신고불성실_금액(합계)';
COMMENT ON COLUMN FI_SURTAX_CARD.COL64_2 IS '가산세명세_신고불성실_세액(합계)';
COMMENT ON COLUMN FI_SURTAX_CARD.COL65_1 IS '가산세명세_납부불성싱_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL65_2 IS '가산세명세_납부불성실_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL66_1 IS '가산세명세_영세율과세표준신고불성실_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL66_2 IS '가산세명세_영세율과세표준신고불성실_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL67_1 IS '가산세명세_현금매출명세서미제출등_금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL67_2 IS '가산세명세_현금매출명세서미제출등_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL68_2 IS '가산세명세_합계_세액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL69_1 IS '면세사업수입금액_업태1';
COMMENT ON COLUMN FI_SURTAX_CARD.COL69_2 IS '면세사업수입금액_종목1';
COMMENT ON COLUMN FI_SURTAX_CARD.COL69_3 IS '면세사업수입금액_금액1';
COMMENT ON COLUMN FI_SURTAX_CARD.COL70_1 IS '면세사업수입금액_업태2';
COMMENT ON COLUMN FI_SURTAX_CARD.COL70_2 IS '면세사업수입금액_종목2';
COMMENT ON COLUMN FI_SURTAX_CARD.COL70_3 IS '면세사업수입금액_금액2';
COMMENT ON COLUMN FI_SURTAX_CARD.COL71_1 IS '면세사업수입금액_업태3';
COMMENT ON COLUMN FI_SURTAX_CARD.COL71_2 IS '면세사업수입금액_종목3';
COMMENT ON COLUMN FI_SURTAX_CARD.COL71_3 IS '면세사업수입금액_금액3';
COMMENT ON COLUMN FI_SURTAX_CARD.COL72 IS '면세사업수입금액_합계';
COMMENT ON COLUMN FI_SURTAX_CARD.COL73 IS '계산서발급금액';
COMMENT ON COLUMN FI_SURTAX_CARD.COL74 IS '계산서수취금액';
COMMENT ON COLUMN FI_SURTAX_CARD.HOMETAX_USERID IS '홈택스_사용자아이디';
COMMENT ON COLUMN FI_SURTAX_CARD.VAT_PRESENTER_GB IS '제출자구분';
COMMENT ON COLUMN FI_SURTAX_CARD.VAT_LEVIER_GB IS '일반과세자구분';
COMMENT ON COLUMN FI_SURTAX_CARD.VAT_REFUND_GB IS '환급구분';
COMMENT ON COLUMN FI_SURTAX_CARD.E_FILE_SURTAX_YN IS '전자신고파일생성대상여부_부가세신고서';
COMMENT ON COLUMN FI_SURTAX_CARD.E_FILE_ZERO_YN IS '전자신고파일생성대상여부_영세율첨부서류제출명세서';
COMMENT ON COLUMN FI_SURTAX_CARD.E_FILE_REAL_ESTATE_YN IS '전자신고파일생성대상여부_부동산임대공급가액명세서';
COMMENT ON COLUMN FI_SURTAX_CARD.E_FILE_BLD_YN IS '전자신고파일생성대상여부_건물등감가상각자산취득명세서';
COMMENT ON COLUMN FI_SURTAX_CARD.E_FILE_NO_DEDUCTION_YN IS '전자신고파일생성대상여부_공제받지못할매입세액명세서';
COMMENT ON COLUMN FI_SURTAX_CARD.E_FILE_SUM_VAT_YN IS '전자시고파일생성대상여부_세금계산서합계표';
COMMENT ON COLUMN FI_SURTAX_CARD.E_FILE_SUM_CALC_YN IS '전자신고파일생성대상여부_계산서합계표';
COMMENT ON COLUMN FI_SURTAX_CARD.E_FILE_EXPORT_YN IS '전자신고파일생성대상여부_수출실적명세서';
COMMENT ON COLUMN FI_SURTAX_CARD.E_FILE_GET_YN IS '전자신고파일생성대상여부_신용카드매출전표등수취명세서';
COMMENT ON COLUMN FI_SURTAX_CARD.CREATION_DATE IS '생성일';
COMMENT ON COLUMN FI_SURTAX_CARD.CREATED_BY IS '생성자';
COMMENT ON COLUMN FI_SURTAX_CARD.LAST_UPDATE_DATE IS '수정일';
COMMENT ON COLUMN FI_SURTAX_CARD.LAST_UPDATED_BY IS '수정자';
COMMENT ON COLUMN FI_SURTAX_CARD.E_FILE_TAX_PUB_YN IS '전자신고파일생성대상여부_전자세금계산서발급세액공제신고서';
COMMENT ON COLUMN FI_SURTAX_CARD.E_FILE_DOMESTIC_LC_YN IS '전자신고파일생성대상여부_내국신용장구매확인서전자발급명세서';
COMMENT ON COLUMN FI_SURTAX_CARD.R_ORIGIN_PLACE_AMT IS '경감공제세액 - 원산지확인서 발급공제금액(AMT-금액, VAT-세액)';
COMMENT ON COLUMN FI_SURTAX_CARD.R_ORIGIN_PLACE_VAT IS '경감공제세액 - 원산지확인서 발급공제금액(AMT-금액, VAT-세액)';
COMMENT ON COLUMN FI_SURTAX_CARD.A_TAX_RECEIVE_DELAY_AMT IS '가산세명세 - 세금계산서 지연수취(AMT-금액, VAT-세액)';
COMMENT ON COLUMN FI_SURTAX_CARD.A_TAX_RECEIVE_DELAY_VAT IS '가산세명세 - 세금계산서 지연수취(AMT-금액, VAT-세액)';
COMMENT ON COLUMN FI_SURTAX_CARD.A_TAX_INV_SUM_BAD_AMT_1 IS '가산세명세 - 세금계산서 합계표 지연제출AMT-금액, VAT-세액)';
COMMENT ON COLUMN FI_SURTAX_CARD.A_TAX_INV_SUM_BAD_VAT_1 IS '가산세명세 - 세금계산서 합계표 지연제출(AMT-금액, VAT-세액)';
COMMENT ON COLUMN FI_SURTAX_CARD.A_REPORT_BAD_AMT_1 IS '가산세명세 - 신고불성실(AMT-금액, VAT-세액)-무신고(일반)';
COMMENT ON COLUMN FI_SURTAX_CARD.A_REPORT_BAD_VAT_1 IS '가산세명세 - 신고불성실(AMT-금액, VAT-세액)-무신고(일반)';
COMMENT ON COLUMN FI_SURTAX_CARD.A_REPORT_BAD_AMT_2 IS '가산세명세 - 신고불성실(AMT-금액, VAT-세액)-무신고(부당)';
COMMENT ON COLUMN FI_SURTAX_CARD.A_REPORT_BAD_VAT_2 IS '가산세명세 - 신고불성실(AMT-금액, VAT-세액)-무신고(부당)';
COMMENT ON COLUMN FI_SURTAX_CARD.A_REPORT_BAD_AMT_3 IS '가산세명세 - 신고불성실(AMT-금액, VAT-세액)-과소/초과 환급신고(일반)';
COMMENT ON COLUMN FI_SURTAX_CARD.A_REPORT_BAD_VAT_3 IS '가산세명세 - 신고불성실(AMT-금액, VAT-세액)-과소/초과 환급신고(일반)';
COMMENT ON COLUMN FI_SURTAX_CARD.A_REPORT_BAD_AMT_4 IS '가산세명세 - 신고불성실(AMT-금액, VAT-세액)-과소/초과 환급신고(부당)';
COMMENT ON COLUMN FI_SURTAX_CARD.A_REPORT_BAD_VAT_4 IS '가산세명세 - 신고불성실(AMT-금액, VAT-세액)-과소/초과 환급신고(부당)';
COMMENT ON COLUMN FI_SURTAX_CARD.A_REALTY_LEASE_UNREPORT_AMT IS '가산세명세 - 부동산임대공급가액명세서 불성실(AMT-금액, VAT-세액)';
COMMENT ON COLUMN FI_SURTAX_CARD.A_REALTY_LEASE_UNREPORT_VAT IS '가산세명세 - 부동산임대공급가액명세서 불성실(AMT-금액, VAT-세액)';
COMMENT ON COLUMN FI_SURTAX_CARD.MODIFY_DEGREE IS '수정신고 차수';
COMMENT ON COLUMN FI_SURTAX_CARD.MODIFY_DESC IS '수정사유';
COMMENT ON COLUMN FI_SURTAX_CARD.CLOSED_FLAG IS '마감구분(신고서 마감 처리시 마감 FLAG 업데이트 실시 : 마감된 후에 수정신고서 작성시 수정신고 차수 증가)';
COMMENT ON COLUMN FI_SURTAX_CARD.LAST_FLAG IS '최종구분(신고별)';

-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE FI_SURTAX_CARD
  ADD CONSTRAINT FI_SURTAX_CARD_PK PRIMARY KEY (SOB_ID, ORG_ID, TAX_CODE, VAT_MNG_SERIAL, SPEC_SERIAL)
  USING INDEX 
  TABLESPACE FCM_TS_DATA
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );

