CREATE OR REPLACE VIEW FI_SLIP_MGMT_BANK_ACCOUNT_V AS
SELECT SMI.SLIP_LINE_ID
     , SMI.SOB_ID
     , SMI.MANAGEMENT_VALUE AS BANK_ACCOUNT_CODE
     , BA.BANK_ACCOUNT_ID
     , BA.BANK_ACCOUNT_NAME
     , BA.BANK_ACCOUNT_NUM
     , BA.BANK_ID
  FROM FI_SLIP_MANAGEMENT_ITEM SMI
    , FI_MANAGEMENT_CODE_V MC
    , FI_BANK_ACCOUNT BA
WHERE SMI.MANAGEMENT_CODE         = MC.MANAGEMENT_CODE
  AND SMI.SOB_ID                  = MC.SOB_ID
  AND SMI.MANAGEMENT_VALUE        = BA.BANK_ACCOUNT_CODE
  AND SMI.SOB_ID                  = BA.SOB_ID
  AND MC.LOOKUP_TYPE              = 'BANK_ACCOUNT';
