CREATE OR REPLACE VIEW FI_SUPP_CUST_V AS
SELECT CST.CUST_SITE_ID AS SUPP_CUST_ID
     , CST.CUST_SITE_CODE AS SUPP_CUST_CODE
     , NVL(CST.CUST_SITE_SHORT_NAME, CST.CUST_SITE_FULL_NAME) AS SUPP_CUST_NAME
     , CST.TAX_REG_NO
     , CST.COUNTRY_CODE
     , 'C' AS SUPP_CUST_TYPE
     , FI_COMMON_G.CODE_NAME_F('SUPP_CUST_TYPE', 'C', CST.SOB_ID) AS SUPP_CUST_TYPE_NAME
     , CST.PRESIDENT_NAME AS PRESIDENT_NAME
     , CST.ADDRESS_1
     , CST.ADDRESS_2
     , CST.BUSINESS_TYPE_LCODE AS BUSINESS_TYPE
     , CASE UPPER(CST.BUSINESS_TYPE_LCODE) 
         WHEN 'INDIVIDUAL' THEN 'I'
         WHEN 'PERSON' THEN 'P'
         ELSE 'C'           
       END AS BUSINESS_TYPE_S
     , CST.BUSINESS_CONDITION
     , CST.BUSINESS_ITEM
     , CST.SOB_ID
     , CST.ORG_ID
     , CST.ENABLED_FLAG AS ENABLED_FLAG
     , CST.EFFECTIVE_DATE_FR AS EFFECTIVE_DATE_FR
     , CST.EFFECTIVE_DATE_TO AS EFFECTIVE_DATE_TO
  FROM AR_CUSTOMER_SITE_TLV CST
---
UNION ALL
---
SELECT ASU.SUPPLIER_ID AS SUPP_CUST_ID
     , ASU.SUPPLIER_CODE AS SUPP_CUST_CODE
     , NVL(ASU.SUPPLIER_SHORT_NAME, ASU.SUPPLIER_FULL_NAME) AS SUPP_CUST_NAME
     , ASU.TAX_REG_NO
     , ASU.COUNTRY_CODE
     , 'S' AS SUPP_CUST_TYPE
     , FI_COMMON_G.CODE_NAME_F('SUPP_CUST_TYPE', 'S', ASU.SOB_ID) AS SUPP_CUST_TYPE_NAME
     , ASU.PRESIDENT_NAME AS PRESIDENT_NAME
     , ASU.ADDRESS_1
     , ASU.ADDRESS_2
     , ASU.BUSINESS_TYPE_LCODE AS BUSINESS_TYPE
     , CASE UPPER(ASU.BUSINESS_TYPE_LCODE) 
         WHEN 'INDIVIDUAL' THEN 'I'
         WHEN 'PERSON' THEN 'P'
         ELSE 'C'           
       END AS BUSINESS_TYPE_S
     , ASU.BUSINESS_CONDITION
     , ASU.BUSINESS_ITEM
     , ASU.SOB_ID
     , ASU.ORG_ID
     , ASU.ENABLED_FLAG AS ENABLED_FLAG
     , ASU.EFFECTIVE_DATE_FR AS EFFECTIVE_DATE_FR
     , ASU.EFFECTIVE_DATE_TO AS EFFECTIVE_DATE_TO
  FROM AP_SUPPLIER_TLV ASU;
