CREATE OR REPLACE VIEW FI_SLIP_MANAGEMENT_ITEM_V8 AS
SELECT BAI.ACCOUNT_CONTROL_ID
     , BAI.ACCOUNT_CODE
     , BAI.SOB_ID
     , SL.CURRENCY_CODE
     , SL.SLIP_LINE_ID
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 1, SMI.MANAGEMENT_VALUE, ')')) AS MANAGEMENT1_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 2, SMI.MANAGEMENT_VALUE, ')')) AS MANAGEMENT2_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 3, SMI.MANAGEMENT_VALUE, ')')) AS MANAGEMENT3_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 4, SMI.MANAGEMENT_VALUE, ')')) AS MANAGEMENT4_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 5, SMI.MANAGEMENT_VALUE, ')')) AS MANAGEMENT5_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 6, SMI.MANAGEMENT_VALUE, ')')) AS MANAGEMENT6_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 7, SMI.MANAGEMENT_VALUE, ')')) AS MANAGEMENT7_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 8, SMI.MANAGEMENT_VALUE, ')')) AS MANAGEMENT8_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 9, SMI.MANAGEMENT_VALUE, ')')) AS MANAGEMENT9_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 10, SMI.MANAGEMENT_VALUE, ')')) AS MANAGEMENT10_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 11, SMI.MANAGEMENT_VALUE, ')')) AS MANAGEMENT11_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 12, SMI.MANAGEMENT_VALUE, ')')) AS MANAGEMENT12_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 13, SMI.MANAGEMENT_VALUE, ')')) AS MANAGEMENT13_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 14, SMI.MANAGEMENT_VALUE, ')')) AS MANAGEMENT14_VALUE
     , MAX(DECODE(BAI.MANAGEMENT_SEQ, 15, SMI.MANAGEMENT_VALUE, ')')) AS MANAGEMENT15_VALUE
  FROM FI_SLIP_LINE SL
    , FI_BALANCE_ACCOUNTS_ITEM BAI
    , FI_SLIP_MANAGEMENT_ITEM SMI
WHERE SL.ACCOUNT_CONTROL_ID       = BAI.ACCOUNT_CONTROL_ID
  AND SL.SOB_ID                   = BAI.SOB_ID
  AND SL.SLIP_LINE_ID             = SMI.SLIP_LINE_ID
  AND SL.SOB_ID                   = SMI.SOB_ID
  AND SMI.MANAGEMENT_ID           = BAI.MANAGEMENT_ID
  AND SMI.SOB_ID                  = BAI.SOB_ID
  AND BAI.ENABLED_FLAG            = 'Y'
  AND SL.CONFIRM_YN               = 'Y'
GROUP BY BAI.ACCOUNT_CONTROL_ID
     , BAI.ACCOUNT_CODE
     , BAI.SOB_ID
     , SL.CURRENCY_CODE
     , SL.SLIP_LINE_ID;
