CREATE OR REPLACE VIEW FI_SLIP_MGMT_VENDOR_V AS
SELECT SMI.SLIP_LINE_ID
     , SMI.SOB_ID
     , SMI.MANAGEMENT_VALUE AS CUSTOMER_CODE
     , SC.SUPP_CUST_NAME AS CUSTOMER_NAME
     , SC.TAX_REG_NO
     , SC.SUPP_CUST_ID
  FROM FI_SLIP_MANAGEMENT_ITEM SMI
    , FI_MANAGEMENT_CODE_V MC
    , FI_SUPP_CUST_V SC
WHERE SMI.MANAGEMENT_CODE         = MC.MANAGEMENT_CODE
  AND SMI.SOB_ID                  = MC.SOB_ID
  AND SMI.MANAGEMENT_VALUE        = SC.SUPP_CUST_CODE
  AND SMI.SOB_ID                  = SC.SOB_ID
  AND MC.LOOKUP_TYPE              = 'CUSTOMER';
