CREATE OR REPLACE VIEW FI_SLIP_TYPE_V AS
SELECT FC.COMMON_ID AS SLIP_TYPE_ID
     , FC.GROUP_CODE
     , FC.CODE AS SLIP_TYPE
     , FC.CODE_NAME AS SLIP_TYPE_NAME
     , FC.VALUE1 AS SLIP_TYPE_CLASS
     , FC.VALUE2 AS DOCUMENT_TYPE
     , FC.VALUE3
     , FC.VALUE4
     , FC.VALUE5
     , FC.VALUE6
     , FC.VALUE7
     , FC.VALUE8
     , FC.VALUE9
     , FC.VALUE10
     , FC.DEFAULT_FLAG
     , FC.SORT_NUM
     , FC.DESCRIPTION
     , FC.ENABLED_FLAG
     , FC.EFFECTIVE_DATE_FR
     , FC.EFFECTIVE_DATE_TO
     , FC.SOB_ID
     , FC.ORG_ID
  FROM FI_COMMON_TLV FC
 WHERE FC.GROUP_CODE              = 'SLIP_TYPE';
