/******************************************************************************/
/* Project      : FPCB ERP
/* Module       : FCM
/* Program Name : FI_SLIP_MANAGEMENT_ITEM
/* Description  : 회계전표 관리항목 내역.
/*
/* Reference by :
/* Program History
/*------------------------------------------------------------------------------
/*   Date       In Charge          Description
/*------------------------------------------------------------------------------
/* 07-JUN-2010  Jeon Ho Su          Initialize
/******************************************************************************/
CREATE TABLE FI_SLIP_MANAGEMENT_ITEM
( SLIP_LINE_ID                    NUMBER          NOT NULL,
  SLIP_DATE                       DATE            NOT NULL,
  SLIP_NUM                        VARCHAR2(30)    NOT NULL,
  SLIP_LINE_SEQ                   NUMBER          NOT NULL,
  SLIP_HEADER_ID                  NUMBER          NOT NULL,
  SOB_ID                          NUMBER          NOT NULL,
  MANAGEMENT_SEQ                  NUMBER          DEFAULT 1,
  MANAGEMENT_ID                   NUMBER          NOT NULL,
  MANAGEMENT_CODE                 VARCHAR2(70)    NOT NULL,
  MANAGEMENT_VALUE                VARCHAR2(100)   ,
  MANAGEMENT_VALUE_NUMBER         NUMBER          ,
  MANAGEMENT_VALUE_DATE           DATE            ,
  ATTRIBUTE_A                     VARCHAR2(250)   ,
  ATTRIBUTE_B                     VARCHAR2(250)   ,
  ATTRIBUTE_C                     VARCHAR2(250)   ,
  ATTRIBUTE_D                     VARCHAR2(250)   ,
  ATTRIBUTE_E                     VARCHAR2(250)   ,
  ATTRIBUTE_1                     NUMBER          ,
  ATTRIBUTE_2                     NUMBER          ,
  ATTRIBUTE_3                     NUMBER          ,
  ATTRIBUTE_4                     NUMBER          ,
  ATTRIBUTE_5                     NUMBER          ,
  CREATION_DATE                   DATE            NOT NULL,
  CREATED_BY                      NUMBER          NOT NULL,
  LAST_UPDATE_DATE                DATE            NOT NULL,
  LAST_UPDATED_BY                 NUMBER          NOT NULL
) TABLESPACE FCM_TS_DATA;

COMMENT ON TABLE FI_SLIP_MANAGEMENT_ITEM IS '전표 관리항목 내역';
COMMENT ON COLUMN APPS.FI_SLIP_MANAGEMENT_ITEM.SLIP_LINE_ID IS '전표 라인 ID';
COMMENT ON COLUMN APPS.FI_SLIP_MANAGEMENT_ITEM.SLIP_DATE IS '기표일자';
COMMENT ON COLUMN APPS.FI_SLIP_MANAGEMENT_ITEM.SLIP_NUM IS '기표번호';
COMMENT ON COLUMN APPS.FI_SLIP_MANAGEMENT_ITEM.SLIP_LINE_SEQ IS '전표 라인 순서';
COMMENT ON COLUMN APPS.FI_SLIP_MANAGEMENT_ITEM.SLIP_HEADER_ID IS '전표 HEADER ID';
COMMENT ON COLUMN APPS.FI_SLIP_MANAGEMENT_ITEM.MANAGEMENT_SEQ IS '관리항목 순서';
COMMENT ON COLUMN APPS.FI_SLIP_MANAGEMENT_ITEM.MANAGEMENT_ID IS '관리항목 ID';
COMMENT ON COLUMN APPS.FI_SLIP_MANAGEMENT_ITEM.MANAGEMENT_CODE IS '관리항목 코드';
COMMENT ON COLUMN APPS.FI_SLIP_MANAGEMENT_ITEM.MANAGEMENT_VALUE IS '관리항목내역(값)';
COMMENT ON COLUMN APPS.FI_SLIP_MANAGEMENT_ITEM.MANAGEMENT_VALUE_NUMBER IS '관리항목 내역 중 NUMBER 변환 값';
COMMENT ON COLUMN APPS.FI_SLIP_MANAGEMENT_ITEM.MANAGEMENT_VALUE_DATE IS '관리항목 내역 중 DATE형 변환 값';
COMMENT ON COLUMN APPS.FI_SLIP_MANAGEMENT_ITEM.CREATION_DATE IS '생성자';
COMMENT ON COLUMN APPS.FI_SLIP_MANAGEMENT_ITEM.CREATED_BY IS '생성일';
COMMENT ON COLUMN APPS.FI_SLIP_MANAGEMENT_ITEM.LAST_UPDATE_DATE IS '수정자';
COMMENT ON COLUMN APPS.FI_SLIP_MANAGEMENT_ITEM.LAST_UPDATED_BY IS '수정일';

-- PRIMARY KEY
ALTER TABLE FI_SLIP_MANAGEMENT_ITEM ADD ( 
  CONSTRAINT FI_SLIP_MANAGEMENT_ITEM_PK PRIMARY KEY (SLIP_LINE_ID, MANAGEMENT_SEQ, SOB_ID) 
        );
        
-- UNIQUE INDEX.
CREATE INDEX FI_SLIP_MANAGEMENT_ITEM_N1 ON FI_SLIP_MANAGEMENT_ITEM(MANAGEMENT_ID) TABLESPACE FCM_TS_IDX;
CREATE INDEX FI_SLIP_MANAGEMENT_ITEM_N2 ON FI_SLIP_MANAGEMENT_ITEM(MANAGEMENT_CODE, SOB_ID) TABLESPACE FCM_TS_IDX;
CREATE INDEX FI_SLIP_MANAGEMENT_ITEM_N3 ON FI_SLIP_MANAGEMENT_ITEM(SOB_ID, MANAGEMENT_VALUE) TABLESPACE FCM_TS_IDX;

-- ANALYZE.
ANALYZE TABLE FI_SLIP_MANAGEMENT_ITEM COMPUTE STATISTICS;
ANALYZE INDEX FI_SLIP_MANAGEMENT_ITEM_PK COMPUTE STATISTICS;
ANALYZE INDEX FI_SLIP_MANAGEMENT_ITEM_N1 COMPUTE STATISTICS;
ANALYZE INDEX FI_SLIP_MANAGEMENT_ITEM_N2 COMPUTE STATISTICS;
ANALYZE INDEX FI_SLIP_MANAGEMENT_ITEM_N3 COMPUTE STATISTICS;
