/******************************************************************************/
/* Project      : FPCB ERP
/* Module       : FCM - GL
/* Program Name : GL_ACCOUNT_CONTROL_ITEM_ITEM
/* Description  : 회계 계정코드 관리항목.
/*
/* Reference by :
/* Program History
/*------------------------------------------------------------------------------
/*   Date       In Charge          Description
/*------------------------------------------------------------------------------
/* 07-JUN-2010  Jeon Ho Su          Initialize
/******************************************************************************/
CREATE TABLE GL_ACCOUNT_CONTROL_ITEM              
( ACCOUNT_CONTROL_ID    NUMBER          NOT NULL,  /* 계정관리 ID */
  ACCOUNT_CODE          VARCHAR2(20)    NOT NULL,  /* 계정코드 */
  SOB_ID                NUMBER          NOT NULL,  /* 회계조직 */
  ORG_ID                NUMBER          NOT NULL,  /* 사업부ID */
  ACCOUNT_DR_CR         VARCHAR2(1)     NOT NULL,  /* 차대 구분 (1-차변, 2-대변) */
  MANAGEMENT_ID         NUMBER          NOT NULL,  /* 관리항목 ID */
  MANAGEMENT_SEQ        NUMBER          ,  /* 관리항목 순번 */
  MANAGEMENT_FLAG       VARCHAR2(1)     ,  /* 계정관리 항목 필수 FLAG */
  BALANCE_FLAG          VARCHAR2(1)     ,  /* 잔액 관리 FLAG */
  ENABLED_FLAG          VARCHAR2(1)     DEFAULT 'Y',   /* 사용여부 */
  EFFECTIVE_DATE_FR     DATE            NOT NULL,  /* 적용 시작일자 */
  EFFECTIVE_DATE_TO     DATE            ,   /* 적용 종료일자 */  
  CREATION_DATE         DATE            NOT NULL,  /* 생성일자 */
  CREATED_BY            NUMBER          NOT NULL,  /* 생성자 */
  LAST_UPDATE_DATE      DATE            NOT NULL,  /* 최종수정일자 */
  LAST_UPDATED_BY       NUMBER          NOT NULL   /* 최종수정자 */
) TABLESPACE FCM_TS_DATA;

-- Add comments to the columns 
COMMENT ON TABLE GL_ACCOUNT_CONTROL_ITEM IS '계정통제';
COMMENT ON COLUMN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_CONTROL_ID IS '계정관리 ID';
COMMENT ON COLUMN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_CODE IS '계정코드';
COMMENT ON COLUMN GL_ACCOUNT_CONTROL_ITEM.SOB_ID IS '회계조직';
COMMENT ON COLUMN GL_ACCOUNT_CONTROL_ITEM.ORG_ID IS '사업부ID';
COMMENT ON COLUMN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_DR_CR IS '차대구분(1-차변,2-대변)';
COMMENT ON COLUMN GL_ACCOUNT_CONTROL_ITEM.MANAGEMENT_ID IS '관리항목ID(공통코드)';
COMMENT ON COLUMN GL_ACCOUNT_CONTROL_ITEM.MANAGEMENT_SEQ IS '관리항목 순번';
COMMENT ON COLUMN GL_ACCOUNT_CONTROL_ITEM.MANAGEMENT_FLAG IS '관리항목 필수FLAG';
COMMENT ON COLUMN GL_ACCOUNT_CONTROL_ITEM.BALANCE_FLAG IS '잔액관리FLAG';
COMMENT ON COLUMN GL_ACCOUNT_CONTROL_ITEM.ENABLED_FLAG IS '사용여부';
COMMENT ON COLUMN GL_ACCOUNT_CONTROL_ITEM.EFFECTIVE_DATE_FR IS '적용 시작일자';
COMMENT ON COLUMN GL_ACCOUNT_CONTROL_ITEM.EFFECTIVE_DATE_TO IS '적용 종료일자';
COMMENT ON COLUMN GL_ACCOUNT_CONTROL_ITEM.CREATION_DATE  IS '생성일자';
COMMENT ON COLUMN GL_ACCOUNT_CONTROL_ITEM.CREATED_BY IS '생성자';
COMMENT ON COLUMN GL_ACCOUNT_CONTROL_ITEM.LAST_UPDATE_DATE IS '최종수정일자';
COMMENT ON COLUMN GL_ACCOUNT_CONTROL_ITEM.LAST_UPDATED_BY IS '최종수정자';

-- CREATE INDEX.
CREATE UNIQUE INDEX GL_ACCOUNT_CONTROL_ITEM_U1 ON GL_ACCOUNT_CONTROL_ITEM(ACCOUNT_CONTROL_ID) TABLESPACE FCM_TS_IDX;
CREATE INDEX GL_ACCOUNT_CONTROL_ITEM_N1 ON GL_ACCOUNT_CONTROL_ITEM(SOB_ID, ORG_ID, ACCOUNT_CODE, ENABLED_FLAG, EFFECTIVE_DATE_FR, EFFECTIVE_DATE_TO) TABLESPACE FCM_TS_IDX;

-- ANALYZE.
ANALYZE TABLE GL_ACCOUNT_CONTROL_ITEM COMPUTE STATISTICS;
ANALYZE INDEX GL_ACCOUNT_CONTROL_ITEM_U1 COMPUTE STATISTICS;
ANALYZE INDEX GL_ACCOUNT_CONTROL_ITEM_N1 COMPUTE STATISTICS;
