/******************************************************************************/
/* Project      : FPCB ERP
/* Module       : FCM - GL
/* Program Name : FI_ACCOUNT_CONTROL_ITEM
/* Description  : 회계 계정코드 관리항목.
/*
/* Reference by :
/* Program History
/*------------------------------------------------------------------------------
/*   Date       In Charge          Description
/*------------------------------------------------------------------------------
/* 07-JUN-2010  Jeon Ho Su          Initialize
/******************************************************************************/
CREATE TABLE FI_ACCOUNT_CONTROL_ITEM              
( ACCOUNT_CONTROL_ID    NUMBER           NOT NULL,	/* 계정관리 ID */
  ACCOUNT_CODE          VARCHAR2(20)     NOT NULL,	/* 계정코드 */
  SOB_ID                NUMBER           NOT NULL,	/* 회계조직 */
  ORG_ID                NUMBER           NOT NULL,	/* 사업부ID */
  MANAGEMENT1_ID        NUMBER           ,	/* 잔액관리항목코드1 */
  MANAGEMENT2_ID        NUMBER           ,	/* 잔액관리항목코드2 */
  REFER1_ID             NUMBER           ,	/* 참고항목코드1 */
  REFER2_ID             NUMBER           ,	/* 참고항목코드2 */
  REFER3_ID             NUMBER           ,	/* 참고항목코드3 */
  REFER4_ID             NUMBER           ,	/* 참고항목코드4 */
  REFER5_ID             NUMBER           ,	/* 참고항목코드5 */
  REFER6_ID             NUMBER           ,	/* 참고항목코드6 */
  REFER7_ID             NUMBER           ,	/* 참고항목코드7 */
  REFER8_ID             NUMBER           ,	/* 참고항목코드8 */
  REFER9_ID             NUMBER           ,  /* 참고항목코드9 */
  REFER_RATE_ID         NUMBER           ,  /* 관리율코드 */
  REFER_AMOUNT_ID       NUMBER           ,  /* 관리금액코드 */
  REFER_DATE1_ID        NUMBER           ,  /* 관리일자코드1 */
  REFER_DATE2_ID        NUMBER           ,  /* 관리일자코드2 */
  VOUCH_ID              NUMBER           ,	/* 증빙서류 ID */  
  MANAGEMENT1_YN        VARCHAR2(1)      DEFAULT 'N',  /* 잔액관리항목필수여부 */
  MANAGEMENT2_YN        VARCHAR2(1)      DEFAULT 'N',  /* 잔액관리항목필수여부 */  
  REFER1_YN             VARCHAR2(1)      DEFAULT 'N',  /* 참고항목필수여부1 */
  REFER2_YN             VARCHAR2(1)      DEFAULT 'N',  /* 참고항목필수여부2 */
  REFER3_YN             VARCHAR2(1)      DEFAULT 'N',  /* 참고항목필수여부3 */
  REFER4_YN             VARCHAR2(1)      DEFAULT 'N',  /* 참고항목필수여부4 */
  REFER5_YN             VARCHAR2(1)      DEFAULT 'N',  /* 참고항목필수여부5 */
  REFER6_YN             VARCHAR2(1)      DEFAULT 'N',  /* 참고항목필수여부6 */
  REFER7_YN             VARCHAR2(1)      DEFAULT 'N',  /* 참고항목필수여부7 */
  REFER8_YN             VARCHAR2(1)      DEFAULT 'N',  /* 참고항목필수여부8 */
  REFER9_YN             VARCHAR2(1)      DEFAULT 'N',  /* 참고항목필수여부9 */
  REFER_RATE_YN         VARCHAR2(1)      DEFAULT 'N',  /* 관리율필수여부 */  
  REFER_AMOUNT_YN       VARCHAR2(1)      DEFAULT 'N',  /* 관리금액필수여부 */
  REFER_DATE1_YN        VARCHAR2(1)      DEFAULT 'N',  /* 관리일자필수여부1 */
  REFER_DATE2_YN        VARCHAR2(1)      DEFAULT 'N',  /* 관리일자필수여부2 */
  VOUCH_YN              VARCHAR2(1)      DEFAULT 'N',	/* 증빙유무여부 */  
  CREATION_DATE         DATE             NOT NULL,  /* 생성일자 */
  CREATED_BY            NUMBER           NOT NULL,  /* 생성자 */
  LAST_UPDATE_DATE      DATE             NOT NULL,  /* 최종수정일자 */
  LAST_UPDATED_BY       NUMBER           NOT NULL   /* 최종수정자 */
) TABLESPACE FCM_TS_DATA;

COMMENT ON TABLE FI_ACCOUNT_CONTROL_ITEM IS '회계 계정코드 관리항목';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.ACCOUNT_CONTROL_ID IS '계정관리 ID';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.ACCOUNT_CODE IS '계정코드';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.SOB_ID IS '회계조직';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.ORG_ID IS '사업부ID';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.MANAGEMENT1_ID IS '잔액관리항목ID1';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.MANAGEMENT2_ID IS '잔액관리항목ID2';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.REFER1_ID IS '참고항목ID1';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.REFER2_ID IS '참고항목ID2';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.REFER3_ID IS '참고항목ID3';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.REFER4_ID IS '참고항목ID4';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.REFER5_ID IS '참고항목ID5';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.REFER6_ID IS '참고항목ID6';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.REFER7_ID IS '참고항목ID7';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.REFER8_ID IS '참고항목ID8';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.REFER9_ID IS '참고항목ID9';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.REFER_RATE_ID IS '관리율ID';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.REFER_AMOUNT_ID IS '관리금액ID';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.REFER_DATE1_ID IS '관리일자ID1';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.REFER_DATE2_ID IS '관리일자ID2';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.VOUCH_ID IS '증빙서류ID';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.MANAGEMENT1_YN IS '잔액관리항목필수여부';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.MANAGEMENT2_YN IS '잔액관리항목필수여부';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.REFER1_YN IS '참고항목필수여부1';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.REFER2_YN IS '참고항목필수여부2';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.REFER3_YN IS '참고항목필수여부3';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.REFER4_YN IS '참고항목필수여부4';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.REFER5_YN IS '참고항목필수여부5';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.REFER6_YN IS '참고항목필수여부6';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.REFER7_YN IS '참고항목필수여부7';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.REFER8_YN IS '참고항목필수여부8';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.REFER9_YN IS '참고항목필수여부9';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.REFER_RATE_YN IS '관리율필수여부';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.REFER_AMOUNT_YN IS '관리금액필수여부';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.REFER_DATE1_YN IS '관리일자필수여부1';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.REFER_DATE2_YN IS '관리일자필수여부2';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.VOUCH_YN IS '증빙서류필수여부';

COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.CREATION_DATE IS '생성일자';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.CREATED_BY IS '생성자';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.LAST_UPDATE_DATE IS '최종수정일자';
COMMENT ON COLUMN FI_ACCOUNT_CONTROL_ITEM.LAST_UPDATED_BY IS '최종수정자';


CREATE UNIQUE INDEX FI_ACCOUNT_CONTROL_ITEM_U1 ON 
  FI_ACCOUNT_CONTROL_ITEM(ACCOUNT_CONTROL_ID, SOB_ID)
  TABLESPACE FCM_TS_IDX
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  LOGGING
  STORAGE (
           INITIAL 64K
           MINEXTENTS 1
           MAXEXTENTS 2147483645
          );

ALTER TABLE FI_ACCOUNT_CONTROL_ITEM
  ADD CONSTRAINT FI_ACCOUNT_CONTROL_ITEM_PK PRIMARY KEY (ACCOUNT_CONTROL_ID, SOB_ID);
  
CREATE INDEX FI_ACCOUNT_CONTROL_ITEM_N1 ON 
  FI_ACCOUNT_CONTROL_ITEM(ACCOUNT_CODE, SOB_ID)
  TABLESPACE FCM_TS_IDX
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  LOGGING
  STORAGE (
           INITIAL 64K
           MINEXTENTS 1
           MAXEXTENTS 2147483645
          );

-- ANALYZE.
ANALYZE TABLE FI_ACCOUNT_CONTROL_ITEM COMPUTE STATISTICS;
ANALYZE INDEX FI_ACCOUNT_CONTROL_ITEM_U1 COMPUTE STATISTICS;
ANALYZE INDEX FI_ACCOUNT_CONTROL_ITEM_N1 COMPUTE STATISTICS;
