CREATE OR REPLACE VIEW GL_PERIOD_TYPE_V AS
SELECT LET.LOOKUP_ENTRY_ID
     , LET.LOOKUP_TYPE_ID
     , LET.LOOKUP_MODULE
     , LET.LOOKUP_TYPE
     , LET.ENTRY_CODE AS PERIOD_TYPE
     , LET.ENTRY_DESCRIPTION AS PERIOD_TYPE_NAME
     , TO_NUMBER(LET.SEGMENT1) AS NUMBER_PER_FISCAL_YEAR
     , LET.SEGMENT2
     , LET.SEGMENT3
     , LET.SEGMENT4
     , LET.SEGMENT5
     , LET.DEFAULT_FLAG
     , LET.SORT_NO
     , LET.SOB_ID
     , LET.ORG_ID
     , LET.EFFECTIVE_DATE_FR
     , LET.EFFECTIVE_DATE_TO
     , LET.ENABLED_FLAG
  FROM EAPP_LOOKUP_ENTRY_TLV LET
 WHERE LET.LOOKUP_TYPE            = 'GL_PERIOD_TYPE';
