/******************************************************************************/
/* Project      : FPCB ERP
/* Module       : QM 
/* Program Name : QM_NCR_ISSUE
/* Description  : 품질 부적합 관리  
/*
/* Reference by :
/* Program History
/*------------------------------------------------------------------------------
/*   Date       In Charge          Description
/*------------------------------------------------------------------------------
/* 07-JUN-2010  Jeon Ho Su          Initialize
/******************************************************************************/
CREATE TABLE QM_NCR_ISSUE              
( NCR_ISSUE_ID                    NUMBER          NOT NULL,
  SOB_ID                          NUMBER          NOT NULL, 
  ORG_ID                          NUMBER          NOT NULL,
  NCR_ISSUE_NO                    VARCHAR2(30)    NOT NULL, 
  WORKCENTER_ID                   NUMBER          NOT NULL,
  OP_CLASS_ID                     NUMBER          ,
  OP_TYPE_ID                      NUMBER          ,
  OPERATION_ID                    NUMBER          ,
  INVENTORY_ITEM_ID               NUMBER          NOT NULL,
  BOM_ITEM_ID                     NUMBER          ,
  ISSUE_DATE                      DATE            NOT NULL,
  CAUSE_WORKCENTER_ID             NUMBER          ,
  CAUSE_OP_CLASS_ID               NUMBER          ,
  CAUSE_OP_TYPE_ID                NUMBER          ,
  CAUSE_OPERATION_ID              NUMBER          ,  
  WORKING_UOM                     VARCHAR2(10)    ,
  WORK_UOM_QTY                    NUMBER          DEFAULT 0,
  REJECT_UOM_QTY                  NUMBER          DEFAULT 0, 
  PROBLEM_CLASS                   VARCHAR2(30)    ,  
  REJECT_DIVISION_CODE            VARCHAR2(30)    ,  
  REJECT_TYPE_ID                  NUMBER          ,  
  PROBLEM_LEVEL_CODE              VARCHAR2(30)    ,  
  ISSUE_COMMENT                   VARCHAR2(4000)  ,  
  ISSUE_DESCRIPTION               VARCHAR2(500)   ,  
  NCR_STATUS                      VARCHAR2(50)    DEFAULT 'ENTER' NOT NULL,  
  ISSUE_APPR_FLAG                 VARCHAR2(1)     DEFAULT 'N' NOT NULL,    
  ISSUE_APPR_DATE                 DATE            ,  
  ISSUE_APPR_USER_ID              NUMBER          ,  
  ISSUE_RETURN_FLAG               VARCHAR2(1)     DEFAULT 'N' NOT NULL,  
  ISSUE_RETURN_DATE               DATE            ,  
  ISSUE_RETURN_USER_ID            NUMBER          ,  
  ISSUE_RETURN_DESC               VARCHAR2(500)   ,  
  ATTRIBUTE_A                     VARCHAR2(200)   ,
  ATTRIBUTE_B                     VARCHAR2(200)   ,
  ATTRIBUTE_C                     VARCHAR2(200)   ,
  ATTRIBUTE_D                     VARCHAR2(200)   ,
  ATTRIBUTE_E                     VARCHAR2(200)   ,
  ATTRIBUTE_1                     NUMBER          ,
  ATTRIBUTE_2                     NUMBER          ,
  ATTRIBUTE_3                     NUMBER          ,
  ATTRIBUTE_4                     NUMBER          ,
  ATTRIBUTE_5                     NUMBER          ,
  CREATION_DATE                   DATE            NOT NULL,
  CREATED_BY                      NUMBER          NOT NULL,
  LAST_UPDATE_DATE                DATE            NOT NULL,
  LAST_UPDATED_BY                 NUMBER          NOT NULL, 
  
  RCP_FLAG                        VARCHAR2(1)     DEFAULT 'N' NOT NULL,
  RCP_DATE                        DATE            ,
  RCP_USER_ID                     NUMBER          ,
  RCP_SITUATION                   VARCHAR2(4000)  ,
  RCP_TEMP_MEASURES               VARCHAR2(4000)  ,
  RCP_RELATED_MEASURES            VARCHAR2(4000)  ,
  NCR_PROGRESS_FLAG               VARCHAR2(1)     DEFAULT 'N' NOT NULL,
  NCR_SEPARATOR_FLAG              VARCHAR2(1)     DEFAULT 'N' NOT NULL,
  NCR_MODIFY_FLAG                 VARCHAR2(1)     DEFAULT 'N' NOT NULL,
  NCR_REWORK_FLAG                 VARCHAR2(1)     DEFAULT 'N' NOT NULL,
  NCR_SCRAP_FLAG                  VARCHAR2(1)     DEFAULT 'N' NOT NULL,
  NCR_CLAIM_FLAG                  VARCHAR2(1)     DEFAULT 'N' NOT NULL,
  NCR_CONCESSION_FLAG             VARCHAR2(1)     DEFAULT 'N' NOT NULL,
  NCR_ETC_FLAG                    VARCHAR2(1)     DEFAULT 'N' NOT NULL,
  NCR_ETC_DESC                    VARCHAR2(500)   ,
  MEASURES_REQ_FLAG               VARCHAR2(1)     DEFAULT 'N' NOT NULL,
  MEASURES_CHARGE_ID              NUMBER          ,
  MEASURES_REPLY_DATE             DATE            ,
  
  FIX_CAUSE_WORKCENTER_ID         NUMBER          ,
  FIX_CAUSE_OP_CLASS_ID           NUMBER          ,
  FIX_CAUSE_OP_TYPE_ID            NUMBER          ,
  FIX_CAUSE_OPERATION_ID          NUMBER          ,  
  
  RCP_REVIEW_FLAG                 VARCHAR2(1)     DEFAULT 'N' NOT NULL,
  RCP_REVIEW_DATE                 DATE            ,
  RCP_REVIEW_USER_ID              NUMBER          ,
  RCP_APPROVAL_FLAG               VARCHAR2(1)     DEFAULT 'N' NOT NULL,
  RCP_APPROVAL_DATE               DATE            ,
  RCP_APPROVAL_USER_ID            NUMBER          ,
  RCP_CONFIRM_FLAG                VARCHAR2(1)     DEFAULT 'N' NOT NULL,
  RCP_CONFIRM_DATE                DATE            ,
  RCP_CONFIRM_USER_ID             NUMBER          ,
  RCP_RETURN_FLAG                 VARCHAR2(1)     DEFAULT 'N' NOT NULL,
  RCP_RETURN_DATE                 DATE            ,
  RCP_RETURN_USER_ID              NUMBER    
) TABLESPACE MFG_TS_DATA;

-- Add comments to the columns 
COMMENT ON TABLE QM_NCR_ISSUE IS '품질 부적합 발행';
COMMENT ON COLUMN QM_NCR_ISSUE.NCR_ISSUE_ID IS '부적합 발행 ID';
COMMENT ON COLUMN QM_NCR_ISSUE.NCR_ISSUE_NO IS '부적합 발행 번호';
COMMENT ON COLUMN QM_NCR_ISSUE.WORKCENTER_ID IS '발견 작업장 ID';
COMMENT ON COLUMN QM_NCR_ISSUE.OP_CLASS_ID IS '발견 대공정 ID';
COMMENT ON COLUMN QM_NCR_ISSUE.OP_TYPE_ID IS '발견 중공정 ID';
COMMENT ON COLUMN QM_NCR_ISSUE.OPERATION_ID IS '발견 공정 ID';
COMMENT ON COLUMN QM_NCR_ISSUE.INVENTORY_ITEM_ID IS '모델 ID';
COMMENT ON COLUMN QM_NCR_ISSUE.BOM_ITEM_ID IS '내부 모델 ID';
COMMENT ON COLUMN QM_NCR_ISSUE.ISSUE_DATE IS '부적합 발행일자';
COMMENT ON COLUMN QM_NCR_ISSUE.CAUSE_WORKCENTER_ID IS '원인 작업장 ID';
COMMENT ON COLUMN QM_NCR_ISSUE.CAUSE_OP_CLASS_ID IS '원인 대공정 ID';
COMMENT ON COLUMN QM_NCR_ISSUE.CAUSE_OP_TYPE_ID IS '원인 중공정 ID';
COMMENT ON COLUMN QM_NCR_ISSUE.CAUSE_OPERATION_ID IS '원인 공정 ID';
COMMENT ON COLUMN QM_NCR_ISSUE.WORKING_UOM IS '작업 UOM';
COMMENT ON COLUMN QM_NCR_ISSUE.WORK_UOM_QTY IS '작업 UOM 작업수량';
COMMENT ON COLUMN QM_NCR_ISSUE.REJECT_UOM_QTY IS '작업 UOM 부적합수량';
COMMENT ON COLUMN QM_NCR_ISSUE.PROBLEM_CLASS IS '문제구분';
COMMENT ON COLUMN QM_NCR_ISSUE.REJECT_DIVISION_CODE IS '부적합 구분 코드';
COMMENT ON COLUMN QM_NCR_ISSUE.REJECT_TYPE_ID IS '불량 항목 ID';
COMMENT ON COLUMN QM_NCR_ISSUE.PROBLEM_LEVEL_CODE IS '문제 난이도';
COMMENT ON COLUMN QM_NCR_ISSUE.ISSUE_COMMENT IS '부적합 내용';
COMMENT ON COLUMN QM_NCR_ISSUE.ISSUE_DESCRIPTION IS '부적합 발행 비고';
COMMENT ON COLUMN QM_NCR_ISSUE.NCR_STATUS IS '부적합 상태';
COMMENT ON COLUMN QM_NCR_ISSUE.ISSUE_APPR_FLAG IS '현업 승인 여부';
COMMENT ON COLUMN QM_NCR_ISSUE.ISSUE_APPR_DATE IS '현업 승인 일시';
COMMENT ON COLUMN QM_NCR_ISSUE.ISSUE_APPR_USER_ID IS '현업 승인 처리자';
COMMENT ON COLUMN QM_NCR_ISSUE.ISSUE_RETURN_FLAG IS '현업 반려구분';
COMMENT ON COLUMN QM_NCR_ISSUE.ISSUE_RETURN_DATE IS '현업 반려 일시';
COMMENT ON COLUMN QM_NCR_ISSUE.ISSUE_RETURN_USER_ID IS '현업 반려 처리자';
COMMENT ON COLUMN QM_NCR_ISSUE.ISSUE_RETURN_DESC IS '현업 반려 사유';
COMMENT ON COLUMN QM_NCR_ISSUE.CREATION_DATE  IS '생성일자';
COMMENT ON COLUMN QM_NCR_ISSUE.CREATED_BY IS '생성자';
COMMENT ON COLUMN QM_NCR_ISSUE.LAST_UPDATE_DATE IS '최종수정일자';
COMMENT ON COLUMN QM_NCR_ISSUE.LAST_UPDATED_BY IS '최종수정자';
COMMENT ON COLUMN QM_NCR_ISSUE.RCP_FLAG IS '접수여부';
COMMENT ON COLUMN QM_NCR_ISSUE.RCP_DATE IS '접수일시';
COMMENT ON COLUMN QM_NCR_ISSUE.RCP_USER_ID IS '접수 처리자';
COMMENT ON COLUMN QM_NCR_ISSUE.RCP_SITUATION IS '접수-현상';
COMMENT ON COLUMN QM_NCR_ISSUE.RCP_TEMP_MEASURES IS '접수-임시 대책(조치사항)';
COMMENT ON COLUMN QM_NCR_ISSUE.RCP_RELATED_MEASURES IS '접수-재발 및 기타관련조치';
COMMENT ON COLUMN QM_NCR_ISSUE.NCR_PROGRESS_FLAG IS '처리기준-진행';
COMMENT ON COLUMN QM_NCR_ISSUE.NCR_SEPARATOR_FLAG IS '처리기준-선별';
COMMENT ON COLUMN QM_NCR_ISSUE.NCR_MODIFY_FLAG IS '처리기준-수정';
COMMENT ON COLUMN QM_NCR_ISSUE.NCR_REWORK_FLAG IS '처리기준-재작업';
COMMENT ON COLUMN QM_NCR_ISSUE.NCR_SCRAP_FLAG IS '처리기준-폐기';
COMMENT ON COLUMN QM_NCR_ISSUE.NCR_CLAIM_FLAG IS '처리기준-CLAIM';
COMMENT ON COLUMN QM_NCR_ISSUE.NCR_CONCESSION_FLAG IS '처리기준-특채';
COMMENT ON COLUMN QM_NCR_ISSUE.NCR_ETC_FLAG IS '처리기준-기타';
COMMENT ON COLUMN QM_NCR_ISSUE.NCR_ETC_DESC IS '처리기준-기타사유';
COMMENT ON COLUMN QM_NCR_ISSUE.MEASURES_REQ_FLAG IS '대책 요청구분';
COMMENT ON COLUMN QM_NCR_ISSUE.MEASURES_CHARGE_ID IS '대책 등록 담당자(공정)';
COMMENT ON COLUMN QM_NCR_ISSUE.MEASURES_REPLY_DATE IS '대책 회신일';
COMMENT ON COLUMN QM_NCR_ISSUE.RCP_REVIEW_FLAG IS '검토 여부';
COMMENT ON COLUMN QM_NCR_ISSUE.RCP_REVIEW_DATE IS '검토 일시';
COMMENT ON COLUMN QM_NCR_ISSUE.RCP_REVIEW_USER_ID IS '검토 처리자';
COMMENT ON COLUMN QM_NCR_ISSUE.RCP_APPROVAL_FLAG IS '승인여부';
COMMENT ON COLUMN QM_NCR_ISSUE.RCP_APPROVAL_DATE IS '승인일시';
COMMENT ON COLUMN QM_NCR_ISSUE.RCP_APPROVAL_USER_ID IS '승인 처리자';
COMMENT ON COLUMN QM_NCR_ISSUE.RCP_CONFIRM_FLAG IS '확정 승인여부';
COMMENT ON COLUMN QM_NCR_ISSUE.RCP_CONFIRM_DATE IS '확정 승인 일시';
COMMENT ON COLUMN QM_NCR_ISSUE.RCP_CONFIRM_USER_ID IS '확정 승인 처리자 ID';
COMMENT ON COLUMN QM_NCR_ISSUE.RCP_RETURN_FLAG IS '접수 반려 여부';
COMMENT ON COLUMN QM_NCR_ISSUE.RCP_RETURN_DATE IS '접수 반려 일시';
COMMENT ON COLUMN QM_NCR_ISSUE.RCP_RETURN_USER_ID IS '접수 반려 처리자';
                
  
-- CREATE INDEX.
ALTER TABLE QM_NCR_ISSUE ADD CONSTRAINTS QM_NCR_ISSUE_PK PRIMARY KEY(SOB_ID, ORG_ID, NCR_ISSUE_NO) USING INDEX TABLESPACE MFG_TS_IDX;

CREATE UNIQUE INDEX QM_NCR_ISSUE_U1 ON QM_NCR_ISSUE(NCR_ISSUE_ID) TABLESPACE MFG_TS_IDX;

CREATE INDEX QM_NCR_ISSUE_N1 ON QM_NCR_ISSUE(SOB_ID, ORG_ID, ISSUE_DATE, WORKCENTER_ID) TABLESPACE MFG_TS_IDX;
CREATE INDEX QM_NCR_ISSUE_N2 ON QM_NCR_ISSUE(SOB_ID, ORG_ID, TRUNC(ISSUE_DATE)) TABLESPACE MFG_TS_IDX;

-- SEQUENCE.
CREATE SEQUENCE QM_NCR_ISSUE_S1;

-- ANALYZE.
ANALYZE TABLE QM_NCR_ISSUE COMPUTE STATISTICS;
ANALYZE INDEX QM_NCR_ISSUE_PK COMPUTE STATISTICS;
ANALYZE INDEX QM_NCR_ISSUE_U1 COMPUTE STATISTICS;
ANALYZE INDEX QM_NCR_ISSUE_N1 COMPUTE STATISTICS;
