SELECT BB.HEADER_CODE
     , BB.HEADER_NAME
     , CASE
         WHEN BB.THIS_L_AMOUNT < 0 THEN 
           CASE 
             WHEN FH.MINUS_SIGN_DISPLAY = '()' THEN '(' || TO_CHAR(ABS(BB.THIS_L_AMOUNT), 'FM999,999,999,999') || ')' 
             ELSE FH.MINUS_SIGN_DISPLAY || TO_CHAR(ABS(BB.THIS_L_AMOUNT), 'FM999,999,999,999')
           END
         ELSE TO_CHAR(ABS(BB.THIS_L_AMOUNT), 'FM999,999,999,999')
       END AS THIS_L_AMOUNT
     , CASE
         WHEN BB.THIS_L_AMOUNT < 0 THEN 
           CASE 
             WHEN FH.MINUS_SIGN_DISPLAY = '()' THEN '(' || TO_CHAR(ABS(BB.PREV_L_AMOUNT), 'FM999,999,999,999') || ')' 
             ELSE FH.MINUS_SIGN_DISPLAY || TO_CHAR(ABS(BB.PREV_L_AMOUNT), 'FM999,999,999,999')
           END
         ELSE TO_CHAR(ABS(BB.PREV_L_AMOUNT), 'FM999,999,999,999')
       END AS PREV_L_AMOUNT
     , CASE
         WHEN BB.THIS_L_AMOUNT < 0 THEN 
           CASE 
             WHEN FH.MINUS_SIGN_DISPLAY = '()' THEN '(' || TO_CHAR(ABS(NVL(BB.THIS_L_AMOUNT, 0) - NVL(BB.PREV_L_AMOUNT, 0)), 'FM999,999,999,999') || ')' 
             ELSE FH.MINUS_SIGN_DISPLAY || TO_CHAR(ABS(NVL(BB.THIS_L_AMOUNT, 0) - NVL(BB.PREV_L_AMOUNT, 0)), 'FM999,999,999,999')
           END
         ELSE TO_CHAR(ABS(NVL(BB.THIS_L_AMOUNT, 0) - NVL(BB.PREV_L_AMOUNT, 0)), 'FM999,999,999,999')
       END AS CHANGE_AMOUNT
     , FH.FORM_ITEM_TYPE
     , FH.FORM_ITEM_CLASS
  FROM FI_BALANCE_BS BB
    , FI_FORM_HEADER FH
WHERE BB.HEADER_ID                = FH.FORM_HEADER_ID
ORDER BY BB.SORT_SEQ
;
