SELECT SL.SLIP_LINE_ID
     , SL.SLIP_LINE_SEQ
     , SL.GL_NUM
     , AC.ACCOUNT_CODE
     , AC.ACCOUNT_DESC
     , SL.GL_DATE
     , SL.MANAGEMENT1
     , FI_ACCOUNT_CONTROL_ITEM_G.CONTROL_ITEM_DESC_F(SL.ACCOUNT_CONTROL_ID, SL.ACCOUNT_DR_CR, 'MANAGEMENT1_ID', SL.MANAGEMENT1, SL.SOB_ID) AS MANAGEMENT1_DESC
     , SL.MANAGEMENT2
     , SL.REFER1
     , SL.REFER2
     , SL.REFER3
  FROM FI_SLIP_LINE SL
    , FI_ACCOUNT_CONTROL AC
WHERE SL.ACCOUNT_CONTROL_ID  = AC.ACCOUNT_CONTROL_ID
  AND SL.SOB_ID              = AC.SOB_ID
  AND SL.GL_DATE             BETWEEN &W_START_DATE AND &W_END_DATE
  AND SL.SOB_ID              = 20
  AND EXISTS 
        ( SELECT 'X'
            FROM FI_SLIP_LINE FSL
              , FI_ACCOUNT_CONTROL FAC
          WHERE FSL.ACCOUNT_CONTROL_ID  = FAC.ACCOUNT_CONTROL_ID
            AND FSL.SOB_ID              = FAC.SOB_ID
            AND FSL.SLIP_HEADER_ID   = SL.SLIP_HEADER_ID
            AND FSL.SOB_ID           = SL.SOB_ID
            AND FAC.ACCOUNT_CODE = '2112211'
            AND FSL.GL_DATE             BETWEEN &W_START_DATE AND &W_END_DATE
            AND FSL.SOB_ID              = 20
        )
ORDER BY SL.GL_NUM, SL.SLIP_LINE_SEQ        
;
