CREATE OR REPLACE VIEW EAPP_CALENDAR_YYYYMM_V AS
SELECT CY.YEAR_STRING || '-' || CM.MONTH_STRING AS YYYYMM
FROM EAPP_CALENDAR_YEAR CY
  , EAPP_CALENDAR_MONTH CM
WHERE CM.LANG_CODE                                      = USERENV_G.GET_TERRITORY_S_F;
