CREATE OR REPLACE VIEW EAPP_USER_PERSON_V AS
SELECT EU.USER_ID
     , EU.USER_NO
     , EU.DESCRIPTION
     , PM.PERSON_ID
     , PM.NAME
     , PM.PERSON_NUM
     , PM.CORP_ID
     , PM.OPERATING_UNIT_ID
     , PM.DEPT_ID
     , PM.EMPLOYE_TYPE
     , PM.SOB_ID
     , PM.ORG_ID
     , TRUNC(EU.EFFECTIVE_DATE_FR) AS EFFECTIVE_DATE_FR
     , TRUNC(EU.EFFECTIVE_DATE_TO) AS EFFECTIVE_DATE_TO
     , EU.ENABLED_FLAG
  FROM EAPP_USER EU
    , HRM_PERSON_MASTER PM
WHERE EU.PERSON_ID              = PM.PERSON_ID;
