CREATE OR REPLACE VIEW FI_BUDGET_MANAGER_V
AS
SELECT FC.COMMON_ID AS BUDGET_MANAGER_ID
    , PM.PERSON_ID
    , FC.CODE AS PERSON_NUM
    , FC.CODE_NAME AS NAME
    , FC.VALUE1
    , FC.VALUE2
    , FC.VALUE3
    , FC.VALUE4
    , FC.VALUE5
    , FC.VALUE6
    , FC.VALUE7
    , FC.VALUE8
    , FC.VALUE9
    , FC.VALUE10
    , FC.DEFAULT_FLAG
    , FC.SORT_NUM
    , FC.DESCRIPTION
    , FC.ENABLED_FLAG
    , FC.EFFECTIVE_DATE_FR
    , FC.EFFECTIVE_DATE_TO
    , FC.SOB_ID
    , FC.ORG_ID
  FROM FI_COMMON FC
    , HRM_PERSON_MASTER PM
WHERE FC.CODE                 = PM.PERSON_NUM
  AND FC.SOB_ID               = PM.SOB_ID
  AND FC.ORG_ID               = PM.ORG_ID
  AND FC.GROUP_CODE           = 'BUDGET_MANAGER'
;
