/******************************************************************************/
/* PROJECT      : FPCB ERP
/* MODULE       : HR
/* PROGRAM NAME : HRA_YEAR_ADJUSTMENT
/* DESCRIPTION  : 연말정산 내역..
/*
/* REFERENCE BY :
/* PROGRAM HISTORY
/*------------------------------------------------------------------------------
/*   DATE       IN CHARGE          DESCRIPTION
/*------------------------------------------------------------------------------
/* 07-JUN-2010  JEON HO SU          INITIALIZE
/******************************************************************************/
CREATE TABLE HRA_YEAR_ADJUSTMENT
( CORP_ID                           NUMBER        NOT NULL,
  YEAR_YYYY                         VARCHAR2(4)   NOT NULL,
  PERSON_ID                         NUMBER        NOT NULL,
  SOB_ID                            NUMBER        NOT NULL,
  ORG_ID                            NUMBER        NOT NULL,
  SUBMIT_DATE                       DATE          NOT NULL,
  ADJUST_DATE_FR                    DATE          NOT NULL,
  ADJUST_DATE_TO                    DATE          NOT NULL,
  PAY_TYPE                          VARCHAR2(10)  NOT NULL,
  AVG_PAY_AMT                       NUMBER,
  NOW_PAY_TOT_AMT                   NUMBER,
  NOW_BONUS_TOT_AMT                 NUMBER,
  NOW_ADD_BONUS_AMT                 NUMBER,
  NOW_STOCK_BENE_AMT                NUMBER,               
  PRE_PAY_TOT_AMT                   NUMBER,               
  PRE_BONUS_TOT_AMT                 NUMBER,               
  PRE_ADD_BONUS_AMT                 NUMBER,               
  PRE_STOCK_BENE_AMT                NUMBER,               
  INCOME_OUTSIDE_AMT                NUMBER,               
  NONTAX_OUTSIDE_AMT                NUMBER,               
  NONTAX_OT_AMT                     NUMBER,               
  NONTAX_RESEA_AMT                  NUMBER,               
  NONTAX_ETC_AMT                    NUMBER,               
  INCOME_TOT_AMT                    NUMBER,               
  INCOME_DED_AMT                    NUMBER,               
  PER_DED_AMT                       NUMBER,               
  SPOUSE_DED_AMT                    NUMBER,               
  SUPP_DED_COUNT                    NUMBER,               
  SUPP_DED_AMT                      NUMBER,               
  OLD_DED_COUNT                     NUMBER(2),            
  OLD_DED_AMT                       NUMBER,               
  OLD_DED_COUNT1                    NUMBER(2),            
  OLD_DED_AMT1                      NUMBER,               
  DEFORM_DED_COUNT                  NUMBER(2),            
  DEFORM_DED_AMT                    NUMBER,               
  WOMAN_DED_AMT                     NUMBER,               
  CHILD_DED_COUNT                   NUMBER(2),            
  CHILD_DED_AMT                     NUMBER,               
  PER_ADD_DED_AMT                   NUMBER,               
  MANY_CHILD_DED_COUNT              NUMBER(2),            
  MANY_CHILD_DED_AMT                NUMBER,               
  ANNU_INSUR_AMT                    NUMBER,               
  NATI_ANNU_AMT                     NUMBER,               
  RETR_ANNU_AMT                     NUMBER,               
  MEDIC_INSUR_AMT                   NUMBER,               
  HIRE_INSUR_AMT                    NUMBER,               
  GUAR_INSUR_AMT                    NUMBER,               
  DEFORM_INSUR_AMT                  NUMBER,               
  MEDIC_AMT                         NUMBER,               
  EDUCATION_AMT                     NUMBER,               
  HOUSE_FUND_AMT                    NUMBER,               
  DONAT_AMT                         NUMBER,               
  MARRY_ETC_AMT                     NUMBER,               
  STAND_DED_AMT                     NUMBER,               
  SUBT_DED_AMT                      NUMBER,               
  PERS_ANNU_BANK_AMT                NUMBER,               
  ANNU_BANK_AMT                     NUMBER,               
  INVES_AMT                         NUMBER,               
  FORE_INCOME_AMT                   NUMBER,               
  CREDIT_AMT                        NUMBER,               
  EMPL_STOCK_AMT                    NUMBER,               
  TAX_STD_AMT                       NUMBER,               
  COMP_TAX_AMT                      NUMBER,               
  TAX_REDU_IN_LAW_AMT               NUMBER,               
  TAX_REDU_SP_LAW_AMT               NUMBER,               
  TAX_DED_INCOME_AMT                NUMBER,               
  TAX_DED_TAXGROUP_AMT              NUMBER,               
  TAX_DED_HOUSE_DEBT_AMT            NUMBER,               
  TAX_DED_LONG_STOCK_AMT            NUMBER,               
  TAX_DED_DONAT_POLI_AMT            NUMBER,               
  TAX_DED_OUTSIDE_PAY_AMT           NUMBER,               
  FIX_IN_TAX_AMT                    NUMBER,               
  FIX_LOCAL_TAX_AMT                 NUMBER,               
  FIX_SP_TAX_AMT                    NUMBER,               
  PRE_IN_TAX_AMT                    NUMBER,               
  PRE_LOCAL_TAX_AMT                 NUMBER,               
  PRE_SP_TAX_AMT                    NUMBER,               
  SUBT_IN_TAX_AMT                   NUMBER,               
  SUBT_LOCAL_TAX_AMT                NUMBER,               
  SUBT_SP_TAX_AMT                   NUMBER,               
  CREATION_DATE                     DATE          NOT NULL,                 
  CREATED_BY                        NUMBER        NOT NULL,               
  LAST_UPDATE_DATE                  DATE          NOT NULL,                 
  LAST_UPDATED_BY                   NUMBER        NOT NULL,               
  TRANS_YN                          VARCHAR2(2)   DEFAULT 'N',          
  TRANS_PAY_YYYYMM                  VARCHAR2(7),
  TRANS_WAGE_TYPE                   VARCHAR2(10),
  TRANS_DATE                        DATE,                 
  TRANS_PERSON_ID                   NUMBER,               
  NONTAX_BIRTH_AMT                  NUMBER,               
  NONTAX_FOREIGNER_AMT              NUMBER,               
  BIRTH_DED_COUNT                   NUMBER,               
  BIRTH_DED_AMT                     NUMBER,               
  HOUSE_INTER_AMT                   NUMBER,               
  LONG_HOUSE_PROF_AMT               NUMBER,               
  HOUSE_SAVE_AMT                    NUMBER,               
  SMALL_CORPOR_DED_AMT              NUMBER,               
  LONG_STOCK_SAVING_AMT             NUMBER,               
  NONTAX_SCH_EDU_AMT                NUMBER,               
  NONTAX_MEMBER_AMT                 NUMBER,               
  NONTAX_GUARD_AMT                  NUMBER,               
  NONTAX_CHILD_AMT                  NUMBER,               
  NONTAX_HIGH_SCH_AMT               NUMBER,               
  NONTAX_SPECIAL_AMT                NUMBER,               
  NONTAX_RESEARCH_AMT               NUMBER,               
  NONTAX_COMPANY_AMT                NUMBER,               
  NONTAX_COVER_AMT                  NUMBER,               
  NONTAX_WILD_AMT                   NUMBER,               
  NONTAX_DISASTER_AMT               NUMBER,               
  NONTAX_OUTS_GOVER_AMT             NUMBER,               
  NONTAX_OUTS_ARMY_AMT              NUMBER,               
  NONTAX_OUTS_WORK_1                NUMBER,               
  NONTAX_OUTS_WORK_2                NUMBER,               
  NONTAX_STOCK_BENE_AMT             NUMBER,               
  NONTAX_FOR_ENG_AMT                NUMBER,               
  NONTAX_EMPL_STOCK_AMT             NUMBER,               
  NONTAX_EMPL_BENE_AMT_1            NUMBER,               
  NONTAX_EMPL_BENE_AMT_2            NUMBER,               
  NONTAX_HOUSE_SUBSIDY_AMT          NUMBER,               
  NONTAX_SEA_RESOURCE_AMT           NUMBER,               
  HIRE_KEEP_EMPLOY_AMT              NUMBER,               
  HOUSE_APP_DEPOSIT_AMT             NUMBER,               
  HOUSE_MONTHLY_AMT        					NUMBER,               
  DONAT_DED_ALL            					NUMBER,               
  DONAT_DED_50             					NUMBER,               
  DONAT_DED_30             					NUMBER,               
  DONAT_DED_RELIGION_10    					NUMBER,               
  DONAT_DED_10             					NUMBER,               
  DONAT_NEXT_ALL           					NUMBER,               
  DONAT_NEXT_50            					NUMBER,               
  DONAT_NEXT_30            					NUMBER,               
  DONAT_NEXT_RELIGION_10   					NUMBER,               
  DONAT_NEXT_10            					NUMBER  
) TABLESPACE FCM_TS_DATA;

--> COMMET 설정 
COMMENT ON TABLE HRA_YEAR_ADJUSTMENT IS '연말정산 내역';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.CORP_ID IS '업체ID';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.YEAR_YYYY IS '정산년도';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.PERSON_ID IS '사원ID';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.SUBMIT_DATE IS '제출일자';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.ADJUST_DATE_FR IS '정산 시작일자';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.ADJUST_DATE_TO IS '정산 종료일자';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.PAY_TYPE IS '급여코드(1.월급, 2.일급, 3.연봉, 4.시급)';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.AVG_PAY_AMT IS '월평균급여';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NOW_PAY_TOT_AMT IS '현-급여합계';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NOW_BONUS_TOT_AMT IS '현-상여합계';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NOW_ADD_BONUS_AMT IS '현-인정상여합계';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NOW_STOCK_BENE_AMT IS '현-주식매수선택권행사이익';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.PRE_PAY_TOT_AMT IS '종전-급여합계';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.PRE_BONUS_TOT_AMT IS '종전-상여합계';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.PRE_ADD_BONUS_AMT IS '종전-인정상여합계';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.PRE_STOCK_BENE_AMT IS '종전-주식매수선택권행사이익';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.INCOME_OUTSIDE_AMT IS '과세 국외소득';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NONTAX_OUTSIDE_AMT IS '비과세 국외소득';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NONTAX_OT_AMT IS '비과세 야간근로';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NONTAX_RESEA_AMT IS '비과세 연구활동비(2009년 폐지)';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NONTAX_ETC_AMT IS '비과세 기타';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.INCOME_TOT_AMT IS '총근로소득합계-비과세제외한 금액';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.INCOME_DED_AMT IS '근로소득공제';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.PER_DED_AMT IS '본인 공제';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.SPOUSE_DED_AMT IS '배우자 공제';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.SUPP_DED_COUNT IS '부양가족수';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.SUPP_DED_AMT IS '부양가족 금액';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.OLD_DED_COUNT IS '경로우대 65세 이상 인원수';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.OLD_DED_AMT IS '경로우대 65세 이상 금액';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.OLD_DED_COUNT1 IS '경로우대 70세 이상 인원수';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.OLD_DED_AMT1 IS '경로우대 70세 이상 금액';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.DEFORM_DED_COUNT IS '장애인수';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.DEFORM_DED_AMT IS '장애인 금액';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.WOMAN_DED_AMT IS '부녀세대 금액';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.CHILD_DED_COUNT IS '자녀양육 인원수';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.CHILD_DED_AMT IS '자녀양육비';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.PER_ADD_DED_AMT IS '소수공제추가공제';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.MANY_CHILD_DED_COUNT IS '다자녀 공제 인원수';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.MANY_CHILD_DED_AMT IS '다자녀 공제 금액';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.ANNU_INSUR_AMT IS '보험료(공무원, 군인연금..등)';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NATI_ANNU_AMT IS '국민연금';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.RETR_ANNU_AMT IS '퇴직연금';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.MEDIC_INSUR_AMT IS '건강보험료';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.HIRE_INSUR_AMT IS '고용보험료';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.GUAR_INSUR_AMT IS '보장보험료';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.DEFORM_INSUR_AMT IS '장애보험료';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.MEDIC_AMT IS '의료비';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.EDUCATION_AMT IS '교육비';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.HOUSE_FUND_AMT IS '주택자금(주택임차차입금상환액 + 장기주택저당차입금 + 주택마련저축액)';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.DONAT_AMT IS '기부금';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.MARRY_ETC_AMT IS '혼인장례이사비';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.STAND_DED_AMT IS '표준공제';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.SUBT_DED_AMT IS '차감소득공제액';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.PERS_ANNU_BANK_AMT IS '개인연금저축';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.ANNU_BANK_AMT IS '연금저축';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.INVES_AMT IS '투자조합출자';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.FORE_INCOME_AMT IS '외국근로자소득';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.CREDIT_AMT IS '신용직불현금';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.EMPL_STOCK_AMT IS '우리사주조합출자';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.TAX_STD_AMT IS '종합세액 과세표준';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.COMP_TAX_AMT IS '산출세액';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.TAX_REDU_IN_LAW_AMT IS '세감-소득세법';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.TAX_REDU_SP_LAW_AMT IS '세감-조세특례제한법';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.TAX_DED_INCOME_AMT IS '세공-근로소득';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.TAX_DED_TAXGROUP_AMT IS '세공-납세조합';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.TAX_DED_HOUSE_DEBT_AMT IS '세공-주택차입금';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.TAX_DED_LONG_STOCK_AMT IS '세공-장기증권저축';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.TAX_DED_DONAT_POLI_AMT IS '세공-정치기부금';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.TAX_DED_OUTSIDE_PAY_AMT IS '세공-외국납부';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.FIX_IN_TAX_AMT IS '결정세액-소득세';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.FIX_LOCAL_TAX_AMT IS '결정세액-주민세';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.FIX_SP_TAX_AMT IS '결정세액-농특세';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.PRE_IN_TAX_AMT IS '기납부-소득세';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.PRE_LOCAL_TAX_AMT IS '기납부-주민세';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.PRE_SP_TAX_AMT IS '기납부-농특세';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.SUBT_IN_TAX_AMT IS '차감-소득세';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.SUBT_LOCAL_TAX_AMT IS '차감-주민세';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.SUBT_SP_TAX_AMT IS '차감-농특세';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.TRANS_YN IS '전송구분';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.TRANS_PAY_YYYYMM IS '전송급여년월';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.TRANS_WAGE_TYPE IS '전송급상여 구분';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.TRANS_DATE IS '급여전송일자';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.TRANS_PERSON_ID IS '급여전송자';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NONTAX_BIRTH_AMT IS '비과세 출생/보육수당';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NONTAX_FOREIGNER_AMT IS '비과세 외국인 근로자';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.BIRTH_DED_COUNT IS '출생/입양자수';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.BIRTH_DED_AMT IS '출생/입양자 공제금액';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.HOUSE_INTER_AMT IS '주택임차차입금원리금상환액';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.LONG_HOUSE_PROF_AMT IS '장기주책저당차입금이자상환액';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.HOUSE_SAVE_AMT IS '주택마련저축공제액';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.SMALL_CORPOR_DED_AMT IS '소기업/소상공인공제부금 소득공제액';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.LONG_STOCK_SAVING_AMT IS '장기주식형저축소득공제';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NONTAX_SCH_EDU_AMT IS '비과세-학자금';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NONTAX_MEMBER_AMT IS '비과세-무보수위원수당';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NONTAX_GUARD_AMT IS '비과세-경호/승선수당';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NONTAX_CHILD_AMT IS '비과세-유아/초중등_연구보조/활동비';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NONTAX_HIGH_SCH_AMT IS '비과세-고등교육_연구보조/활동비';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NONTAX_SPECIAL_AMT IS '비과세-특정연구기관육성법_연구보조/활동비';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NONTAX_RESEARCH_AMT IS '비과세-연구기관_연구보조/활동비';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NONTAX_COMPANY_AMT IS '비과세-기업연구소_연구보조/활동비';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NONTAX_COVER_AMT IS '비과세-취재수당';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NONTAX_WILD_AMT IS '비과세-벽지수당';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NONTAX_DISASTER_AMT IS '비과세-재해관련급여';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NONTAX_OUTS_GOVER_AMT IS '비과세-외국정부등근무자';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NONTAX_OUTS_ARMY_AMT IS '비과세-외국주둔군인등';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NONTAX_OUTS_WORK_1 IS '비과세-국외근로(100만원)';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NONTAX_OUTS_WORK_2 IS '비과세-국외근로(150만원)';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NONTAX_STOCK_BENE_AMT IS '비과세-주식매수선택권';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NONTAX_FOR_ENG_AMT IS '비과세-외국인기술자';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NONTAX_EMPL_STOCK_AMT IS '비과세-우리사주조합배정';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NONTAX_EMPL_BENE_AMT_1 IS '비과세-우리사주조합인출금(50%)';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NONTAX_EMPL_BENE_AMT_2 IS '비과세-우리사주조합인출금(75%)';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NONTAX_HOUSE_SUBSIDY_AMT IS '비과세-주택자금보조금';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.NONTAX_SEA_RESOURCE_AMT IS '비과세-해저광물자원개발';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.HIRE_KEEP_EMPLOY_AMT IS '고용유지중소기업근로자소득공제';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.HOUSE_APP_DEPOSIT_AMT IS '주택청약종합저축 불입액 소득공제';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.HOUSE_MONTHLY_AMT IS '월세소득공제액';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.DONAT_DED_ALL IS '기부금전액공제액(법정기부금)';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.DONAT_DED_50 IS '기부금50%소득공제액(특례기부금)';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.DONAT_DED_30 IS '기부금30%소득공제액(우리사주)';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.DONAT_DED_RELIGION_10 IS '기부금10%소득공제액(종교단체지정기부금)';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.DONAT_DED_10 IS '기부금10%소득공제액(비종교단체지정기부금)';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.DONAT_NEXT_ALL IS '기부금전액_이월액(법정기부금)';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.DONAT_NEXT_50 IS '기부금50%소득_이월액(특례기부금)';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.DONAT_NEXT_30 IS '기부금30%소득_이월액(우리사주)';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.DONAT_NEXT_RELIGION_10 IS '기부금10%소득_이월액(종교단체지정기부금)';
COMMENT ON COLUMN HRA_YEAR_ADJUSTMENT.DONAT_NEXT_10 IS '기부금10%소득_이월액(비종교단체지정기부금)';

--> 인덱스 생성.                                                                                                                           
CREATE UNIQUE INDEX HRA_YEAR_ADJUSTMENT_U1 ON HRA_YEAR_ADJUSTMENT(CORP_ID, YEAR_YYYY, PERSON_ID, SOB_ID, ORG_ID) TABLESPACE FCM_TS_IDX;
CREATE INDEX HRA_YEAR_ADJUSTMENT_N1 ON HRA_YEAR_ADJUSTMENT(YEAR_YYYY, SOB_ID, ORG_ID) TABLESPACE FCM_TS_IDX;

--> ANALYZE TABLE/INDEX;
ANALYZE TABLE HRA_YEAR_ADJUSTMENT COMPUTE STATISTICS;
ANALYZE INDEX HRA_YEAR_ADJUSTMENT_U1 COMPUTE STATISTICS;
ANALYZE INDEX HRA_YEAR_ADJUSTMENT_N1 COMPUTE STATISTICS;
