/******************************************************************************/
/* Project      : FPCB ERP
/* Module       : HR
/* Program Name : HRA_INCOME_TAX_STANDARD
/* Description  : 연말정산 처리 기준.
/*
/* Reference by :
/* Program History
/*------------------------------------------------------------------------------
/*   Date       In Charge          Description
/*------------------------------------------------------------------------------
/* 07-JUN-2010  Jeon Ho Su          Initialize
/******************************************************************************/
CREATE TABLE HRA_INCOME_TAX_STANDARD
( NATION_CODE                       VARCHAR2(8) NOT NULL,       
  YEAR_YYYY                         VARCHAR2(4) NOT NULL,       
  SOB_ID                            NUMBER NOT NULL,
  ORG_ID                            NUMBER NOT NULL,              
  DRIVE_DED_LMT                     NUMBER DEFAULT 0,             
  RESE_DED_LMT                      NUMBER DEFAULT 0,             
  REPORTER_DED_AMT                  NUMBER DEFAULT 0,             
  FOREIGN_INCOME_RATE               NUMBER DEFAULT 0, 
  FOREIGN_INCOME_DED_AMT            NUMBER DEFAULT 0,            
  MONTH_PAY_STD                     NUMBER DEFAULT 0,             
  OT_DED_LMT                        NUMBER DEFAULT 0,             
  FOOD_DED_LMT                      NUMBER DEFAULT 0,             
  BABY_DED_LMT                      NUMBER DEFAULT 0,             
  INCOME_DED_A                      NUMBER DEFAULT 0,             
  INCOME_DED_RATE_A                 NUMBER DEFAULT 0,             
  INCOME_DED_AMT_A                  NUMBER DEFAULT 0,             
  INCOME_CALCU_BAS_A                NUMBER DEFAULT 0,             
  INCOME_DED_B                      NUMBER DEFAULT 0,             
  INCOME_DED_RATE_B                 NUMBER DEFAULT 0,             
  INCOME_DED_AMT_B                  NUMBER DEFAULT 0,             
  INCOME_CALCU_BAS_B                NUMBER DEFAULT 0,             
  INCOME_DED_C                      NUMBER DEFAULT 0,             
  INCOME_DED_RATE_C                 NUMBER DEFAULT 0,             
  INCOME_DED_AMT_C                  NUMBER DEFAULT 0,             
  INCOME_CALCU_BAS_C                NUMBER DEFAULT 0,             
  INCOME_DED_D                      NUMBER DEFAULT 0,             
  INCOME_DED_RATE_D                 NUMBER DEFAULT 0,             
  INCOME_DED_AMT_D                  NUMBER DEFAULT 0,             
  INCOME_CALCU_BAS_D                NUMBER DEFAULT 0,             
  INCOME_DED_LMT                    NUMBER DEFAULT 0,             
  INCOME_DED_RATE_LMT               NUMBER DEFAULT 0,             
  INCOME_DED_AMT_LMT                NUMBER DEFAULT 0,             
  INCOME_CALCU_BAS_LMT              NUMBER DEFAULT 0,             
  PERSON_DED_AMT                    NUMBER DEFAULT 0,             
  SPOUSE_DED_AMT                    NUMBER DEFAULT 0,             
  SUPPORT_DED_AMT                   NUMBER DEFAULT 0,             
  OLD_AGED_DED_AMT                  NUMBER DEFAULT 0,             
  OLD_AGED_DED1_AMT                 NUMBER DEFAULT 0,             
  DEFORM_DED_AMT                    NUMBER DEFAULT 0,             
  WOMAN_DED_AMT                     NUMBER DEFAULT 0,             
  BRING_CHILD_DED_AMT               NUMBER DEFAULT 0,             
  BIRTH_DED_AMT                     NUMBER DEFAULT 0,             
  MANY_CHILD_DED_CNT                NUMBER DEFAULT 0,             
  MANY_CHILD_DED_BAS_AMT            NUMBER DEFAULT 0,             
  MANY_CHILD_DED_ADD_AMT            NUMBER DEFAULT 0,             
  ANCESTOR_MAN_AGE                  NUMBER DEFAULT 0,             
  ANCESTOR_WOMAN_AGE                NUMBER DEFAULT 0,             
  DESCENDANT_MAN_AGE                NUMBER DEFAULT 0,             
  DESCENDANT_WOMAN_AGE              NUMBER DEFAULT 0,             
  OLD_DED_AGE                       NUMBER DEFAULT 0,             
  OLD_DED_AGE1                      NUMBER DEFAULT 0,             
  CHILDREN_DED_AGE                  NUMBER DEFAULT 0,             
  BIRTH_DED_AGE                     NUMBER DEFAULT 0,             
  MANY_CHILD_DED_AGE                NUMBER DEFAULT 0,             
  SIBLING_DED_AGE                   NUMBER DEFAULT 0,
  SIBLING_DED_AGE1                  NUMBER DEFAULT 0,
  FOSTER_CHILD_DED_AGE              NUMBER DEFAULT 0,
  ETC_INSUR_LMT                     NUMBER DEFAULT 0,             
  DEFORM_INSUR_LMT                  NUMBER DEFAULT 0,             
  MEDIC_DED_STD                     NUMBER DEFAULT 0,             
  MEDIC_DED_LMT                     NUMBER DEFAULT 0,             
  PER_EDU                           NUMBER DEFAULT 0,             
  KIND_EDU                          NUMBER DEFAULT 0,             
  STUD_EDU                          NUMBER DEFAULT 0,             
  UNIV_EDU                          NUMBER DEFAULT 0,             
  HOUSE_AMT_RATE                    NUMBER DEFAULT 0,             
  HOUSE_INTER_RATE                  NUMBER DEFAULT 0,             
  HOUSE_AMT_LMT                     NUMBER DEFAULT 0,             
  LONG_HOUSE_PROF_LMT               NUMBER DEFAULT 0,             
  HOUSE_TOTAL_LMT                   NUMBER DEFAULT 0,             
  LONG_HOUSE_PROF_LMT_1             NUMBER DEFAULT 0,             
  HOUSE_TOTAL_LMT_1                 NUMBER DEFAULT 0,             
  LONG_HOUSE_PROF_LMT_2             NUMBER DEFAULT 0,             
  HOUSE_TOTAL_LMT_2                 NUMBER DEFAULT 0,             
  LEGAL_GIFT_RATE                   NUMBER DEFAULT 0,             
  ASS_GIFT_RATE1                    NUMBER DEFAULT 0,             
  ASS_GIFT_RATE2                    NUMBER DEFAULT 0,             
  ASS_GIFT_RATE3                    NUMBER DEFAULT 0,             
  ASS_GIFT_RATE3_1                  NUMBER DEFAULT 0,             
  MARRY_DED_STD                     NUMBER DEFAULT 0,             
  MARRY_DED                         NUMBER DEFAULT 0,             
  FUNE_DED_STD                      NUMBER DEFAULT 0,             
  FUNE_DED                          NUMBER DEFAULT 0,             
  MOVE_DED_STD                      NUMBER DEFAULT 0,             
  MOVE_DED                          NUMBER DEFAULT 0,             
  SP_DED_STD                        NUMBER DEFAULT 0,             
  SP_DED_AMT                        NUMBER DEFAULT 0,             
  PRIV_PENS_RATE                    NUMBER DEFAULT 0,             
  PRIV_PENS_LMT                     NUMBER DEFAULT 0,             
  PENS_DED_RATE                     NUMBER DEFAULT 0,             
  PENS_DED_LMT                      NUMBER DEFAULT 0,             
  RETR_PENS_LMT                     NUMBER DEFAULT 0,             
  INVEST_RATE1                      NUMBER DEFAULT 0,             
  INVEST_LMT_RATE1                  NUMBER DEFAULT 0,             
  INVEST_RATE2                      NUMBER DEFAULT 0,             
  INVEST_LMT_RATE2                  NUMBER DEFAULT 0,             
  CARD_BAS_RATE                     NUMBER DEFAULT 0,             
  CARD_DED_RATE                     NUMBER DEFAULT 0,             
  CARD_DIRECT_RATE                  NUMBER,                     
  CARD_DED_LMT                      NUMBER DEFAULT 0,             
  CARD_DED_LMT_RATE                 NUMBER DEFAULT 0,             
  CHECK_CARD_DED_RATE               NUMBER DEFAULT 0,
  CASH_BAS_RATE                     NUMBER DEFAULT 0,             
  CASH_DED_RATE                     NUMBER DEFAULT 0,             
  CASH_DIRECT_RATE                  NUMBER,                     
  CASH_DED_LMT                      NUMBER DEFAULT 0,             
  CASH_DED_LMT_RATE                 NUMBER DEFAULT 0,             
  CARDCASH_DED_LMT                  NUMBER DEFAULT 0,             
  CARDCASH_DED_LMT_RATE             NUMBER DEFAULT 0,             
  STOCK_LMT                         NUMBER DEFAULT 0,             
  SMALL_CORPOR_DED_LMT              NUMBER DEFAULT 0,             
  LONG_STOCK_SAVING_RATE_1          NUMBER DEFAULT 0,             
  LONG_STOCK_SAVING_LMT_1           NUMBER DEFAULT 0,             
  LONG_STOCK_SAVING_RATE_2          NUMBER DEFAULT 0,             
  LONG_STOCK_SAVING_LMT_2           NUMBER DEFAULT 0,             
  LONG_STOCK_SAVING_RATE_3          NUMBER DEFAULT 0,             
  LONG_STOCK_SAVING_LMT_3           NUMBER DEFAULT 0,             
  IN_TAX_BASE                       NUMBER DEFAULT 0,
  IN_TAX_STD_A                      NUMBER DEFAULT 0,             
  IN_TAX_RATE_A                     NUMBER DEFAULT 0,             
  IN_TAX_STD_B                      NUMBER DEFAULT 0,             
  IN_TAX_RATE_B                     NUMBER DEFAULT 0,             
  IN_TAX_BASE_B                     NUMBER DEFAULT 0,             
  IN_TAX_STD_C                      NUMBER DEFAULT 0,             
  IN_TAX_RATE_C                     NUMBER DEFAULT 0,             
  IN_TAX_BASE_C                     NUMBER DEFAULT 0,             
  IN_TAX_LMT                        NUMBER DEFAULT 0,             
  POLI_GIFT_MAX                     NUMBER DEFAULT 0,             
  POLI_GIFT_RATE                    NUMBER DEFAULT 0,             
  POLI_GIFT_RATE1                   NUMBER DEFAULT 0,             
  TAX_ASSO_RATE                     NUMBER DEFAULT 0,             
  HOUSE_DEBT_BEN_RATE               NUMBER DEFAULT 0,             
  HOUSE_APP_DEPOSIT_RATE            NUMBER DEFAULT 0,
  HOUSE_APP_DEPOSIT_LMT             NUMBER DEFAULT 0,
  HOUSE_MONTHLY_STD                 NUMBER DEFAULT 0,
  HOUSE_MONTHLY_RATE                NUMBER DEFAULT 0,
  LOW_HOUSE_ADD_RATE                NUMBER DEFAULT 0,
  SP_TAX_RATE                       NUMBER DEFAULT 0,             
  FOREIGN_TAX_DED                   NUMBER DEFAULT 0,             
  LOCAL_TAX_RATE                    NUMBER DEFAULT 0,             
  DESCRIPTION                       VARCHAR2(100),              
  ATTRIBUTE1                        VARCHAR2(100),              
  ATTRIBUTE2                        VARCHAR2(100),              
  ATTRIBUTE3                        VARCHAR2(100),              
  ATTRIBUTE4                        VARCHAR2(100),              
  ATTRIBUTE5                        VARCHAR2(100),              
  CREATION_DATE                     DATE NOT NULL,                
  CREATED_BY                        NUMBER NOT NULL,              
  LAST_UPDATE_DATE                  DATE NOT NULL,                
  LAST_UPDATED_BY                   NUMBER NOT NULL               
) TABLESPACE FCM_TS_DATA;

-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.NATION_CODE IS '국가코드';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.YEAR_YYYY IS '적용년도';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.DRIVE_DED_LMT IS '자가운전보조금';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.RESE_DED_LMT IS '연구보조비';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.REPORTER_DED_AMT IS '취재수당';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.FOREIGN_INCOME_RATE IS '외국인근로자소득한도';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.FOREIGN_INCOME_DED_AMT IS '국외근로소득';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.MONTH_PAY_STD IS '야간근로수당 적용 급여 기준';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.OT_DED_LMT IS '야간근로수당 한도';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.FOOD_DED_LMT IS '식대한도';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.BABY_DED_LMT IS '보육수당 한도';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.INCOME_DED_A IS '근로소득공제 A';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.INCOME_DED_RATE_A IS '근로소득공제율 A';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.INCOME_DED_AMT_A IS '근로소득공제금액 A';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.INCOME_CALCU_BAS_A IS '근로소득 기본금액 A';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.INCOME_DED_B IS '근로소득공제 B';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.INCOME_DED_RATE_B IS '근로소득공제율 B';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.INCOME_DED_AMT_B IS '근로소득공제금액 B';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.INCOME_CALCU_BAS_B IS '근로소득 기본금액 B';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.INCOME_DED_C IS '근로소득공제 C';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.INCOME_DED_RATE_C IS '근로소득공제율 C';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.INCOME_DED_AMT_C IS '근로소득공제금액 C';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.INCOME_CALCU_BAS_C IS '근로소득 기본금액 C';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.INCOME_DED_D IS '근로소득공제 D';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.INCOME_DED_RATE_D IS '근로소득공제율 D';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.INCOME_DED_AMT_D IS '근로소득공제금액 D';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.INCOME_CALCU_BAS_D IS '근로소득 기본금액 D';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.INCOME_DED_LMT IS '근로소득공제 한도';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.INCOME_DED_RATE_LMT IS '근로소득공제율 한도';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.INCOME_DED_AMT_LMT IS '근로소득공제금액 한도';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.INCOME_CALCU_BAS_LMT IS '근로소득 기본금액 한도';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.PERSON_DED_AMT IS '기-본인';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.SPOUSE_DED_AMT IS '기-배우자';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.SUPPORT_DED_AMT IS '기-부양가족';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.OLD_AGED_DED_AMT IS '추-경로우대(65~69)';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.OLD_AGED_DED1_AMT IS '추-경로우대(70~)';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.DEFORM_DED_AMT IS '추-장애자';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.WOMAN_DED_AMT IS '추-부녀세대';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.BRING_CHILD_DED_AMT IS '추-자녀양육';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.BIRTH_DED_AMT IS '출산/입양';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.MANY_CHILD_DED_CNT IS '다자녀추가-인원기준';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.MANY_CHILD_DED_BAS_AMT IS '다자녀추가-기본금액';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.MANY_CHILD_DED_ADD_AMT IS '다자녀추가-인당금액';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.ANCESTOR_MAN_AGE IS '직계존속 남자 공제나이';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.ANCESTOR_WOMAN_AGE IS '직계존속 여자 공제나이';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.DESCENDANT_MAN_AGE IS '직계비속 남자 공제나이';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.DESCENDANT_WOMAN_AGE IS '직계비속 여자 공제나이';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.OLD_DED_AGE IS '경로우대1';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.OLD_DED_AGE1 IS '경로우대2';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.CHILDREN_DED_AGE IS '자녀양육비 공제 나이';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.BIRTH_DED_AGE IS '출생 공제나이';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.MANY_CHILD_DED_AGE IS '다자녀추가공제 나이';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.SIBLING_DED_AGE IS '형제자매 공제 나이';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.SIBLING_DED_AGE1 IS '형제자매 공제 나이1';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.FOSTER_CHILD_DED_AGE IS '위탁아동 공제나이';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.ETC_INSUR_LMT IS '기타보장성보험';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.DEFORM_INSUR_LMT IS '기타장애자보험';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.MEDIC_DED_STD IS '의료비-기준 RATE';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.MEDIC_DED_LMT IS '의료비-한도';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.PER_EDU IS '교-본인';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.KIND_EDU IS '교-취학전아동';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.STUD_EDU IS '교-초중고교';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.UNIV_EDU IS '교-대학교';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.HOUSE_AMT_RATE IS '주택마련저축불입액';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.HOUSE_INTER_RATE IS '주택임차차입금 이자상환액';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.HOUSE_AMT_LMT IS '주택마련주택임차차임금 한도';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.LONG_HOUSE_PROF_LMT IS '장기주택저당차입금 이자상환액';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.HOUSE_TOTAL_LMT IS '주택자금 총공제한도';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.LONG_HOUSE_PROF_LMT_1 IS '장기주택저당차입금 이자상환액(1000만)';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.HOUSE_TOTAL_LMT_1 IS '주택자금 총공제한도(1000만)';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.LONG_HOUSE_PROF_LMT_2 IS '장기주택저당차입금 이자상환액(1500만)';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.HOUSE_TOTAL_LMT_2 IS '주택자금 총공제한도(1500만)';  
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.LEGAL_GIFT_RATE IS '법정기부금';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.ASS_GIFT_RATE1 IS '특례기부금';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.ASS_GIFT_RATE2 IS '지정기부금(30%)';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.ASS_GIFT_RATE3 IS '지정기부금(10%)';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.ASS_GIFT_RATE3_1 IS '지정기분금 공제 추가1';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.MARRY_DED_STD IS '혼인 공제기준';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.MARRY_DED IS '혼인 공제액';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.FUNE_DED_STD IS '장례 공제기준';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.FUNE_DED IS '장례 공제액';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.MOVE_DED_STD IS '이사 공제기준';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.MOVE_DED IS '이상 공제액';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.SP_DED_STD IS '표준공제 기준액';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.SP_DED_AMT IS '표준공제금액';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.PRIV_PENS_RATE IS '개인 연금';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.PRIV_PENS_LMT IS '개인 연금한도';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.PENS_DED_RATE IS '연금저축 비율';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.PENS_DED_LMT IS '연금저축 한도';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.RETR_PENS_LMT IS '퇴직연금 한도';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.INVEST_RATE1 IS '투자조합출자1(2006년 이전)';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.INVEST_LMT_RATE1 IS '투자조합출자한도1';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.INVEST_RATE2 IS '투자조합출자2(2007이후)';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.INVEST_LMT_RATE2 IS '투자조합출자한도2';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.CARD_BAS_RATE IS '신용카드 최저 사용한도 비율';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.CARD_DED_RATE IS '신용카드 공제비율';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.CARD_DED_LMT IS '신용카드 공제한도1';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.CARD_DED_LMT_RATE IS '신용카드 공제한도-총급여에 대한 비율';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.CARD_BAS_RATE IS '신용카드 최저 사용한도 비율';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.CARD_DED_RATE IS '신용카드 공제비율';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.CARD_DED_LMT IS '신용카드 공제한도1';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.CARD_DED_LMT_RATE IS '신용카드 공제한도-총급여에 대한 비율';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.CHECK_CARD_DED_RATE IS '체크카드 공제비율';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.CASH_BAS_RATE IS '현금영수증 최저 사용한도 비율';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.CASH_DED_RATE IS '현금영수증 공제비율';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.CASH_DED_LMT IS '현금영수증 공제한도1';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.CASH_DED_LMT_RATE IS '현금영수증 공제한도-총급여에 대한 비율';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.CARDCASH_DED_LMT IS '신용카드현금영수증 공제한도1';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.CARDCASH_DED_LMT_RATE IS '신용카드현금영수증 공제한도-총급여에 대한 비율';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.STOCK_LMT IS '우리사주출자한도';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.SMALL_CORPOR_DED_LMT IS '소기업 소득공제 한도';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.LONG_STOCK_SAVING_RATE_1 IS '장기주식형저축 비율1';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.LONG_STOCK_SAVING_LMT_1 IS '장기주식형저축 한도1';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.LONG_STOCK_SAVING_RATE_2 IS '장기주식형저축 비율2';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.LONG_STOCK_SAVING_LMT_2 IS '장기주식형저축 한도2';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.LONG_STOCK_SAVING_RATE_3 IS '장기주식형저축 비율3';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.LONG_STOCK_SAVING_LMT_3 IS '장기주식형저축 한도3';  
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.IN_TAX_BASE IS '근로소득기본공제금';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.IN_TAX_STD_A IS '근로소득세액공제 한도1';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.IN_TAX_RATE_A IS '근로소득세액공제 한도 비율1';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.IN_TAX_STD_B IS '근로소득세액공제 한도2';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.IN_TAX_RATE_B IS '근로소득세액공제 한도 비율2';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.IN_TAX_BASE_B IS '근로소득세액공제기본 금액2';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.IN_TAX_STD_C IS '근로소득세액공제 한도3';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.IN_TAX_RATE_C IS '근로소득세액공제 한도 비율3';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.IN_TAX_BASE_C IS '근로소득세액공제기본 금액3';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.IN_TAX_LMT IS '근로소득세액공제 한도';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.POLI_GIFT_MAX IS '정치기부금한도';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.POLI_GIFT_RATE IS '정치기부금 비율';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.POLI_GIFT_RATE1 IS '정치기부금 비율1';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.TAX_ASSO_RATE IS '납세조합';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.HOUSE_DEBT_BEN_RATE IS '주택자금차입금이자세액공제';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.HOUSE_APP_DEPOSIT_RATE IS '주택청약종합저축공제율';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.HOUSE_APP_DEPOSIT_LMT IS '주택청약종합저축공제한도';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.HOUSE_MONTHLY_STD IS '저소득근로자 월세소득 기준';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.HOUSE_MONTHLY_RATE IS '저소득근로자 월세소득공제';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.LOW_HOUSE_ADD_RATE IS '저소득근로자 주택임차차입금원리금상황액 소득공제';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.SP_TAX_RATE IS '농특세 적용 비율';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.FOREIGN_TAX_DED IS '외국납부세액공제';
COMMENT ON COLUMN HRA_INCOME_TAX_STANDARD.LOCAL_TAX_RATE IS '소득세 비율';
 
-- CREATE/RECREATE INDEXES 
CREATE UNIQUE INDEX HRA_INCOME_TAX_STANDARD_U1 ON HRA_INCOME_TAX_STANDARD(NATION_CODE, YEAR_YYYY, SOB_ID, ORG_ID) TABLESPACE FCM_TS_IDX;

-- ANALYZE TABLE / INDEX;
ANALYZE TABLE HRA_INCOME_TAX_STANDARD COMPUTE STATISTICS;
ANALYZE INDEX HRA_INCOME_TAX_STANDARD_U1 COMPUTE STATISTICS;
