CREATE OR REPLACE VIEW HRA_DONATION_INFO_V AS
SELECT
      DI.DONATION_INFO_ID
    , DI.YEAR_YYYY
    , DI.PERSON_ID
    , DI.SOB_ID
    , DI.ORG_ID
    , DI.DONA_TYPE
    , DI.FAMILY_NAME
    , CASE
        WHEN DI.REPRE_NUM IS NULL THEN NULL
        ELSE DECRYPT_F(DI.REPRE_NUM)
      END AS REPRE_NUM
    , DI.RELATION_CODE
    , DI.CORP_NAME
    , DI.CORP_TAX_REG_NO
    , DI.DONA_DATE
    , DI.SUB_DESCRIPTION
    , DI.DONA_COUNT
    , DI.DONA_AMT
    , DI.DONA_BILL_NUM
    , DI.DESCRIPTION
    , DI.WEB_CLOSED_FLAG
    , DI.WEB_CLOSED_DATE
    , DI.WEB_CLOSED_PERSON_ID
    , DI.RECEIPT_FLAG
    , DI.RECEIPT_DATE
    , DI.RECEIPT_USER_ID
    , DI.CLOSED_FLAG
    , DI.CLOSED_DATE
    , DI.CLOSED_USER_ID
    , DI.ATTRIBUTE_A
    , DI.ATTRIBUTE_B
    , DI.ATTRIBUTE_C
    , DI.ATTRIBUTE_D
    , DI.ATTRIBUTE_E
    , DI.ATTRIBUTE_1
    , DI.ATTRIBUTE_2
    , DI.ATTRIBUTE_3
    , DI.ATTRIBUTE_4
    , DI.ATTRIBUTE_5
    , DI.CREATION_DATE
    , DI.CREATED_BY
    , DI.LAST_UPDATE_DATE
    , DI.LAST_UPDATED_BY
  FROM HRA_DONATION_INFO DI;
