CREATE OR REPLACE VIEW HRD_MONTH_TOTAL_DUTY_V AS
SELECT MTD.MONTH_TOTAL_ID
     , MTD.PERSON_ID
     , MTD.DUTY_TYPE
     , MTD.DUTY_YYYYMM
     , MTD.WORK_CORP_ID
     , MTD.CORP_ID
     , MTD.SOB_ID
     , MTD.ORG_ID
     , SUM(DECODE(DC.DUTY_CODE, '00', MTD.DUTY_COUNT, 0)) AS DUTY_00     -- Ãâ±Ù.
     , SUM(DECODE(DC.DUTY_CODE, '11', MTD.DUTY_COUNT, 0)) AS DUTY_11     -- °á±Ù.
     , SUM(DECODE(DC.DUTY_CODE, '12', MTD.DUTY_COUNT, 0)) AS DUTY_12     -- ±³À°.
     , SUM(DECODE(DC.DUTY_CODE, '13', MTD.DUTY_COUNT, 0)) AS DUTY_13     -- ÈÆ·Ã.
     , SUM(DECODE(DC.DUTY_CODE, '18', MTD.DUTY_COUNT, 0)) AS DUTY_18     -- ÃâÀå.
     , SUM(DECODE(DC.DUTY_CODE, '19', MTD.DUTY_COUNT, 0)) AS DUTY_19     -- °æÁ¶ÈÞ°¡.
     , SUM(DECODE(DC.DUTY_CODE, '20', MTD.DUTY_COUNT, 0)) AS DUTY_20     -- ³âÂ÷.
     , SUM(DECODE(DC.DUTY_CODE, '21', MTD.DUTY_COUNT, 0)) AS DUTY_21     -- ¹Ý³âÂ÷.
     , SUM(DECODE(DC.DUTY_CODE, '22', MTD.DUTY_COUNT, 0)) AS DUTY_22     -- º¸°ÇÈÞ°¡.
     , SUM(DECODE(DC.DUTY_CODE, '23', MTD.DUTY_COUNT, 0)) AS DUTY_23     -- ¿¬ÁßÈÞ°¡.
     , SUM(DECODE(DC.DUTY_CODE, '30', MTD.DUTY_COUNT, 0)) AS DUTY_30     -- °ø»ó.
     , SUM(DECODE(DC.DUTY_CODE, '31', MTD.DUTY_COUNT, 0)) AS DUTY_31     -- º´°¡.
     , 0 AS DUTY_32 
     , SUM(DECODE(DC.DUTY_CODE, '54', MTD.DUTY_COUNT, 0)) AS DUTY_54     -- ¹«±ÞÈÞ°¡.
     , SUM(DECODE(DC.DUTY_CODE, '55', MTD.DUTY_COUNT, 0)) AS DUTY_55     -- À¯±ÞÈÞ°¡.
     , SUM(DECODE(DC.DUTY_CODE, '56', MTD.DUTY_COUNT, 0)) AS DUTY_56     -- Æ¯º°À¯±Þ.
     , SUM(DECODE(DC.DUTY_CODE, '77', MTD.DUTY_COUNT, 0)) AS DUTY_77     -- »êÈÞ_À¯±Þ.
     , SUM(DECODE(DC.DUTY_CODE, '78', MTD.DUTY_COUNT, 0)) AS DUTY_78     -- »êÈÞ_¹«±Þ.
     , SUM(DECODE(DC.DUTY_CODE, '94', MTD.DUTY_COUNT, 0)) AS DUTY_94     -- »êÀç.
     , SUM(DECODE(DC.DUTY_CODE, '95', MTD.DUTY_COUNT, 0)) AS DUTY_95     -- ÈÞÁ÷_¹«±Þ.
     , SUM(DECODE(DC.DUTY_CODE, '96', MTD.DUTY_COUNT, 0)) AS DUTY_96     -- ÈÞÁ÷_À¯±Þ.
     , SUM(DECODE(DC.DUTY_CODE, '97', MTD.DUTY_COUNT, 0)) AS DUTY_97     -- À°¾ÆÈÞÁ÷.
     , SUM(DECODE(DC.DUTY_CODE, '98', MTD.DUTY_COUNT, 0)) AS DUTY_98     -- °ø°¡.
     , SUM(CASE WHEN DC.DUTY_CODE IN('77', '78', '95', '96', '97') THEN MTD.DUTY_COUNT ELSE 0 END) AS DUTY_TIME_OFF    -- ÈÞÁ÷/»êÈÞ/À°¾ÆÈÞÁ÷.
     , SUM(DECODE(DC.NON_PAY_DAY_FLAG, 'Y', MTD.DUTY_COUNT, 0)) AS UNPAID_COUNT  -- ¹«±ÞÀÏ¼ö.
  FROM HRD_MONTH_TOTAL_DUTY MTD
    , HRM_DUTY_CODE_V DC
WHERE MTD.DUTY_ID               = DC.DUTY_ID
  AND MTD.SOB_ID                = DC.SOB_ID
  AND MTD.ORG_ID                = DC.ORG_ID
GROUP BY MTD.MONTH_TOTAL_ID
     , MTD.PERSON_ID
     , MTD.DUTY_TYPE
     , MTD.DUTY_YYYYMM
     , MTD.WORK_CORP_ID
     , MTD.CORP_ID
     , MTD.SOB_ID
     , MTD.ORG_ID;
