CREATE OR REPLACE VIEW HRD_DAY_INTERFACE_V1 AS
SELECT /*+ INDEX(HRD_DAY_INTERFACE HRD_DAY_INTERFACE_U1) */
       DI.PERSON_ID
     , DI.WORK_DATE
     , DI.WORK_CORP_ID
     , DI.CORP_ID
     , DI.DEPT_ID
     , DI.POST_ID
     , DI.JOB_CATEGORY_ID
     , NVL(DI.WORK_TYPE_ID, WC.WORK_TYPE_ID) AS WORK_TYPE_ID
     , NVL(WC.C_DUTY_ID1, NVL(WC.C_DUTY_ID, DI.DUTY_ID)) DUTY_ID
     , NVL(WC.HOLY_TYPE, DI.HOLY_TYPE) AS HOLY_TYPE
     , DI.OPEN_TIME
     , DI.CLOSE_TIME
     , DI.OPEN_TIME1
     , DI.CLOSE_TIME1
     , NVL(OT.LEAVE_TIME, 0) AS LEAVE_TIME
     , NVL(OT.LATE_TIME, 0) AS LATE_TIME
     , NVL(OT.REST_TIME, 0) AS REST_TIME
     , NVL(OT.OVER_TIME, 0) AS OVER_TIME
     , NVL(OT.HOLIDAY_TIME, 0) AS HOLIDAY_TIME
     , NVL(OT.NIGHT_TIME, 0) AS NIGHT_TIME
     , NVL(OT.NIGHT_BONUS_TIME, 0) AS NIGHT_BONUS_TIME
     , DI.NEXT_DAY_YN
     , DI.LEAVE_ID
     , DI.LEAVE_TIME_CODE
     , DI.MODIFY_YN
     , DI.MODIFY_IN_YN
     , DI.MODIFY_OUT_YN
     , CASE
         WHEN DI.MODIFY_YN = 'Y' THEN 'Y'
         WHEN DI.MODIFY_IN_YN = 'Y' THEN 'Y'
         WHEN DI.MODIFY_OUT_YN = 'Y' THEN 'Y'
         ELSE 'N'
       END MODIFY_FLAG
     , DI.APPROVED_YN
     , DI.APPROVED_DATE
     , DI.APPROVED_PERSON_ID
     , DI.CONFIRMED_YN
     , DI.CONFIRMED_DATE
     , DI.CONFIRMED_PERSON_ID
     , DI.APPROVE_STATUS
     , NVL(DI.TRANS_YN, 'N') AS TRANS_YN
     , DI.TRANS_DATE
     , DI.TRANS_PERSON_ID
     , DI.DESCRIPTION
     , DI.SOB_ID
     , DI.ORG_ID
     , DI.CREATED_BY
     , DI.LAST_UPDATE_DATE
     , DI.LAST_UPDATED_BY
     , WC.OPEN_TIME AS PLAN_OPEN_TIME
     , WC.CLOSE_TIME AS PLAN_CLOSE_TIME
     , WC.BEFORE_OT_START
     , WC.BEFORE_OT_END
     , WC.AFTER_OT_START
     , WC.AFTER_OT_END
     , WC.BREAKFAST_YN
     , WC.LUNCH_YN
     , WC.DINNER_YN
     , WC.MIDNIGHT_YN
     , WC.DANGJIK_YN
     , NVL(WC.ALL_NIGHT_YN, DI.ALL_NIGHT_YN) AS ALL_NIGHT_YN
     , WC.ATTRIBUTE5 AS WORK_TYPE_GROUP
     , WC.OPEN_TIME AS PL_OPEN_TIME
     , WC.CLOSE_TIME AS PL_CLOSE_TIME
     , WC.BEFORE_OT_START AS PL_BEFORE_OT_START
     , WC.BEFORE_OT_END AS PL_BEFORE_OT_END
     , WC.AFTER_OT_START AS PL_AFTER_OT_START
     , WC.AFTER_OT_END AS PL_AFTER_OT_END
     , WC.BREAKFAST_YN AS PL_BREAKFAST_YN
     , WC.LUNCH_YN AS PL_LUNCH_YN
     , WC.DINNER_YN AS PL_DINNER_YN
     , WC.MIDNIGHT_YN AS PL_MIDNIGHT_YN
FROM HRD_DAY_INTERFACE DI
  , HRD_WORK_CALENDAR WC
  , (-- 일근태 잔업 계산 내역.
      SELECT DIO.PERSON_ID
           , DIO.WORK_DATE
           , DIO.CORP_ID
           , DIO.SOB_ID
           , DIO.ORG_ID
           , SUM(DECODE(DIO.OT_TYPE, '11', DIO.OT_TIME, 0)) AS LEAVE_TIME
           , SUM(DECODE(DIO.OT_TYPE, '12', DIO.OT_TIME, 0)) AS LATE_TIME
           , SUM(DECODE(DIO.OT_TYPE, '13', DIO.OT_TIME, 0)) AS REST_TIME
           , SUM(DECODE(DIO.OT_TYPE, '14', DIO.OT_TIME, 0)) AS OVER_TIME
           , SUM(DECODE(DIO.OT_TYPE, '15', DIO.OT_TIME, 0)) AS HOLIDAY_TIME
           , SUM(DECODE(DIO.OT_TYPE, '16', DIO.OT_TIME, 0)) AS NIGHT_TIME
           , SUM(DECODE(DIO.OT_TYPE, '17', DIO.OT_TIME, 0)) AS NIGHT_BONUS_TIME
        FROM HRD_DAY_INTERFACE_OT DIO
      GROUP BY DIO.PERSON_ID
           , DIO.WORK_DATE
           , DIO.CORP_ID
           , DIO.SOB_ID
           , DIO.ORG_ID
       ) OT
WHERE DI.PERSON_ID                          = WC.PERSON_ID(+)
  AND DI.WORK_DATE                          = WC.WORK_DATE(+)
  AND DI.CORP_ID                            = WC.CORP_ID(+)
  AND DI.SOB_ID                             = WC.SOB_ID(+)
  AND DI.ORG_ID                             = WC.ORG_ID(+)
  AND DI.PERSON_ID                          = OT.PERSON_ID(+)
  AND DI.WORK_DATE                          = OT.WORK_DATE(+)
  AND DI.SOB_ID                             = OT.SOB_ID(+)
  AND DI.ORG_ID                             = OT.ORG_ID(+);
