CREATE OR REPLACE VIEW HRD_PERIOD_TOTAL_DUTY_V AS
SELECT MTD.PERSON_ID
     , MTD.SOB_ID
     , MTD.ORG_ID
     , SUM(DECODE(DC.DUTY_CODE, '00', MTD.DUTY_COUNT, 0)) AS DUTY_00     -- 출근.
     , SUM(DECODE(DC.DUTY_CODE, '11', MTD.DUTY_COUNT, 0)) AS DUTY_11     -- 결근.
     , SUM(DECODE(DC.DUTY_CODE, '12', MTD.DUTY_COUNT, 0)) AS DUTY_12     -- 교육.
     , SUM(DECODE(DC.DUTY_CODE, '13', MTD.DUTY_COUNT, 0)) AS DUTY_13     -- 훈련.
     , SUM(DECODE(DC.DUTY_CODE, '18', MTD.DUTY_COUNT, 0)) AS DUTY_18     -- 출장.
     , SUM(DECODE(DC.DUTY_CODE, '19', MTD.DUTY_COUNT, 0)) AS DUTY_19     -- 경조휴가.
     , SUM(DECODE(DC.DUTY_CODE, '20', MTD.DUTY_COUNT, 0)) AS DUTY_20     -- 년차.
     , SUM(DECODE(DC.DUTY_CODE, '21', MTD.DUTY_COUNT, 0)) AS DUTY_21     -- 반년차.
     , SUM(DECODE(DC.DUTY_CODE, '22', MTD.DUTY_COUNT, 0)) AS DUTY_22     -- 보건휴가.
     , SUM(DECODE(DC.DUTY_CODE, '23', MTD.DUTY_COUNT, 0)) AS DUTY_23     -- 연중휴가.
     , SUM(DECODE(DC.DUTY_CODE, '30', MTD.DUTY_COUNT, 0)) AS DUTY_30     -- 공상.
     , SUM(DECODE(DC.DUTY_CODE, '31', MTD.DUTY_COUNT, 0)) AS DUTY_31     -- 병가.
     , SUM(DECODE(DC.DUTY_CODE, '54', MTD.DUTY_COUNT, 0)) AS DUTY_54     -- 무급휴가.
     , SUM(DECODE(DC.DUTY_CODE, '55', MTD.DUTY_COUNT, 0)) AS DUTY_55     -- 유급휴가.
     , SUM(DECODE(DC.DUTY_CODE, '56', MTD.DUTY_COUNT, 0)) AS DUTY_56     -- 특별유급.
     , SUM(DECODE(DC.DUTY_CODE, '77', MTD.DUTY_COUNT, 0)) AS DUTY_77     -- 산휴_유급.
     , SUM(DECODE(DC.DUTY_CODE, '78', MTD.DUTY_COUNT, 0)) AS DUTY_78     -- 산휴_무급.
     , SUM(DECODE(DC.DUTY_CODE, '94', MTD.DUTY_COUNT, 0)) AS DUTY_94     -- 산재.
     , SUM(DECODE(DC.DUTY_CODE, '95', MTD.DUTY_COUNT, 0)) AS DUTY_95     -- 휴직_무급.
     , SUM(DECODE(DC.DUTY_CODE, '96', MTD.DUTY_COUNT, 0)) AS DUTY_96     -- 휴직_유급.
     , SUM(DECODE(DC.DUTY_CODE, '97', MTD.DUTY_COUNT, 0)) AS DUTY_97     -- 육아휴직.
     , SUM(DECODE(DC.DUTY_CODE, '98', MTD.DUTY_COUNT, 0)) AS DUTY_98     -- 공가.
     , SUM(DECODE(DC.NON_PAY_DAY_FLAG, 'Y', MTD.DUTY_COUNT, 0)) AS UNPAID_COUNT  -- 무급일수.
  FROM HRD_PERIOD_TOTAL_DUTY_GT MTD
    , HRM_DUTY_CODE_V DC
WHERE MTD.DUTY_ID               = DC.DUTY_ID
  AND MTD.SOB_ID                = DC.SOB_ID
  AND MTD.ORG_ID                = DC.ORG_ID
GROUP BY MTD.PERSON_ID
       , MTD.SOB_ID
       , MTD.ORG_ID;
