CREATE OR REPLACE VIEW HRD_DAY_LEAVE_V AS
SELECT DL.DAY_LEAVE_ID
     , DL.PERSON_ID
     , DL.WORK_DATE
     , DL.WORK_CORP_ID
     , DL.CORP_ID
     , DL.DEPT_ID
     , DL.POST_ID
     , DL.JOB_CATEGORY_ID
     , NVL(WC.C_DUTY_ID1, NVL(WC.C_DUTY_ID, DL.DUTY_ID)) AS DUTY_ID
     , NVL(WC.HOLY_TYPE, DL.HOLY_TYPE) AS HOLY_TYPE
     , DL.OPEN_TIME
     , DL.CLOSE_TIME
     , DL.OPEN_TIME1
     , DL.CLOSE_TIME1
     , DL.NEXT_DAY_YN
     , NVL(WC.DANGJIK_YN, DL.DANGJIK_YN) AS DANGJIK_YN
     , NVL(WC.ALL_NIGHT_YN, DL.ALL_NIGHT_YN) AS ALL_NIGHT_YN
     , DL.HOLIDAY_CHECK
     , DL.CLOSED_YN
     , DL.CLOSED_DATE
     , DL.CLOSED_PERSON_ID
     , DL.ATTRIBUTE1
     , DL.ATTRIBUTE2
     , DL.ATTRIBUTE3
     , DL.ATTRIBUTE4
     , DL.ATTRIBUTE5
     , DL.ATTRIBUTE6
     , DL.ATTRIBUTE7
     , DL.ATTRIBUTE8
     , DL.ATTRIBUTE9
     , DL.ATTRIBUTE10 AS DAY_WORK_TYPE_GROUP
     , DL.SOB_ID
     , DL.ORG_ID
     , WC.WORK_TYPE_ID
     , WC.ATTRIBUTE5 AS WORK_TYPE_GROUP
     , WC.OPEN_TIME AS PL_OPEN_TIME
     , WC.CLOSE_TIME AS PL_CLOSE_TIME
     , WC.BEFORE_OT_START AS PL_BEFORE_OT_START
     , WC.BEFORE_OT_END AS PL_BEFORE_OT_END
     , WC.AFTER_OT_START AS PL_AFTER_OT_START
     , WC.AFTER_OT_END AS PL_AFTER_OT_END
     , WC.LUNCH_YN AS PL_LUNCH_YN
     , WC.DINNER_YN AS PL_DINNER_YN
     , WC.MIDNIGHT_YN AS PL_MIDNIGHT_YN
  FROM HRD_DAY_LEAVE DL
     , HRD_WORK_CALENDAR WC
WHERE DL.WORK_DATE              = WC.WORK_DATE(+)
  AND DL.PERSON_ID              = WC.PERSON_ID(+)
  AND DL.SOB_ID                 = WC.SOB_ID(+)
  AND DL.ORG_ID                 = WC.ORG_ID(+);
