CREATE OR REPLACE VIEW HRM_DONATION_TYPE_V AS
SELECT HC.COMMON_ID AS DONATION_TYPE_ID
     , HC.CODE AS DONATION_TYPE
     , HC.CODE_NAME AS DONATION_TYPE_NAME
     , NVL(TO_NUMBER(HC.VALUE1), 0) AS AVAILABLE_YEAR
     , HC.VALUE2
     , HC.VALUE3
     , HC.VALUE4
     , HC.VALUE5
     , HC.VALUE6
     , HC.VALUE7
     , HC.VALUE8
     , HC.VALUE9
     , HC.VALUE10
     , HC.SORT_NUM
     , HC.DESCRIPTION
     , HC.ENABLED_FLAG
     , HC.EFFECTIVE_DATE_FR
     , HC.EFFECTIVE_DATE_TO
     , HC.SOB_ID
     , HC.ORG_ID
FROM HRM_COMMON_TLV HC
WHERE HC.GROUP_CODE               = 'DONATION_TYPE';
