CREATE OR REPLACE VIEW HRM_HOLIDAY_TYPE_V AS
SELECT HC.COMMON_ID AS HOLIDAY_TYPE_ID
     , HC.CODE AS HOLIDAY_TYPE
     , HC.CODE_NAME AS HOLIDAY_TYPE_NAME
     , HC.VALUE1 AS DUTY_CODE
     , HC.VALUE2 AS STD_JOIN_DATE
     , HC.VALUE3 AS MONTH_DAY_TYPE
     , TO_NUMBER(HC.VALUE4) AS MIN_PERIOD_NUM
     , TO_NUMBER(HC.VALUE5) AS BASE_CREATION_NUM
     , TO_NUMBER(HC.VALUE6) AS LIMIT_CREATION_NUM
     , HC.VALUE7
     , HC.VALUE8
		 , HC.VALUE9
		 , HC.VALUE10
		 , HC.SORT_NUM
		 , HC.DESCRIPTION
		 , HC.ENABLED_FLAG
		 , HC.EFFECTIVE_DATE_FR
		 , HC.EFFECTIVE_DATE_TO
		 , HC.SOB_ID
		 , HC.ORG_ID 
FROM HRM_COMMON_TLV HC
WHERE HC.GROUP_CODE                     = 'HOLIDAY_TYPE';
