CREATE OR REPLACE VIEW HRM_REST_TIME_V AS
SELECT HC.COMMON_ID AS REST_ID
     , HC.CODE AS REST_CODE
     , HC.CODE_NAME AS REST_TIME_NAME
     , HC.VALUE1 AS JOB_CATEGORY_CODE
     , HC.VALUE2 AS REST_TYPE
     , TO_NUMBER(HC.VALUE3) AS START_ADD_DAY
     , HC.VALUE4 AS START_TIME
     , TO_NUMBER(HC.VALUE5) AS END_ADD_DAY
     , HC.VALUE6 AS END_TIME
     , TO_NUMBER(HC.VALUE7) AS REST_DED_TIME
     , HC.VALUE8
		 , HC.VALUE9
		 , HC.VALUE10
		 , HC.DEFAULT_FLAG
		 , HC.SORT_NUM
		 , HC.DESCRIPTION
		 , HC.ENABLED_FLAG
		 , HC.EFFECTIVE_DATE_FR
		 , HC.EFFECTIVE_DATE_TO
		 , HC.SOB_ID
		 , HC.ORG_ID  
FROM HRM_COMMON_TLV HC
WHERE HC.GROUP_CODE                     = 'REST_TIME';
