CREATE OR REPLACE VIEW HRM_PAYMENT_SET_V AS
SELECT HC.COMMON_ID
     , HC.CODE AS PAYMENT_SET_CODE
     , HC.CODE_NAME AS PAYMENT_SET_NAME
     , HC.VALUE1 AS COLUMN_CODE
     , HC.VALUE2 AS DEFAULT_VALUE
     , HC.VALUE3 AS CAL_START_DATE
     , HC.VALUE4 AS CAL_START_TABLE
     , HC.VALUE5 AS CAL_END_DATE
     , HC.VALUE6 AS CAL_END_TABLE
     , HC.VALUE7
     , HC.VALUE8
     , HC.VALUE9
     , HC.VALUE10
     , HC.DEFAULT_FLAG
     , HC.SORT_NUM
     , HC.DESCRIPTION
     , HC.ENABLED_FLAG
     , HC.EFFECTIVE_DATE_FR
     , HC.EFFECTIVE_DATE_TO
     , HC.SOB_ID
     , HC.ORG_ID
  FROM HRM_COMMON HC
 WHERE HC.GROUP_CODE              = 'PAYMENT_SET';
