CREATE OR REPLACE VIEW HRM_LEAVE_CAL_STD_V AS
SELECT HC.COMMON_ID
     , HC.GROUP_CODE
		 , HC.CODE AS JOB_CATEGORY_CODE
		 , HC.CODE_NAME AS JOB_CATEGORY_NAME
		 , HC.VALUE1 AS OT_YN
		 , HC.VALUE2 AS NIGHT_YN
		 , HC.VALUE3 AS REST_TIME_YN
		 , HC.VALUE4 AS HOLIDAY_YN
		 , HC.VALUE5 AS NIGHT_BONUS_YN
		 , HC.VALUE6 AS FOOD_TIME_DED
		 , HC.VALUE7 AS REST_TIME_DED
     , HC.VALUE8
		 , HC.VALUE9
		 , HC.VALUE10
     , HC.DEFAULT_FLAG
		 , HC.SORT_NUM
		 , HC.DESCRIPTION
		 , HC.ENABLED_FLAG
		 , HC.EFFECTIVE_DATE_FR
		 , HC.EFFECTIVE_DATE_TO
		 , HC.SOB_ID
		 , HC.ORG_ID 
  FROM HRM_COMMON_TLV HC
 WHERE HC.GROUP_CODE             = 'LEAVE_CAL';
