CREATE OR REPLACE VIEW HRM_SECOM_STATUS_V AS
SELECT HC.COMMON_ID AS SECOM_STATUS_ID
     , HC.CODE AS SECOM_STATUS
     , HC.CODE_NAME AS SECOM_STATUS_NAME
     , HC.VALUE1 AS CHECK_FLAG
     , HC.VALUE2
     , HC.VALUE3 AS MODULE_TYPE
     , HC.VALUE4
     , HC.VALUE5
     , HC.VALUE6
     , HC.VALUE7
     , HC.VALUE8
     , HC.VALUE9
     , HC.VALUE10
     , HC.DEFAULT_FLAG
     , HC.SORT_NUM
     , HC.DESCRIPTION
     , HC.ENABLED_FLAG
     , HC.EFFECTIVE_DATE_FR
     , HC.EFFECTIVE_DATE_TO
     , HC.SOB_ID
     , HC.ORG_ID
  FROM HRM_COMMON_TLV HC
 WHERE HC.GROUP_CODE              = 'SECOM_STATUS';
