CREATE OR REPLACE VIEW HRM_HISTORY_V AS
SELECT HH.HISTORY_HEADER_ID
     , HH.HISTORY_NUM
		 , HH.CORP_ID
		 , HH.DESCRIPTION AS HEADER_DESCRIPTION
		 , HH.SOB_ID
		 , HH.ORG_ID
		 , HL.HISTORY_LINE_ID
		 , HL.PERSON_ID
		 , HL.CHARGE_DATE
		 , HL.CHARGE_ID
		 , HL.RETIRE_ID
		 , HL.OPERATING_UNIT_ID
		 , HL.DEPT_ID
		 , HL.JOB_CLASS_ID
		 , HL.JOB_ID
		 , HL.POST_ID
		 , HL.OCPT_ID
		 , HL.ABIL_ID
		 , HL.PAY_GRADE_ID
		 , HL.JOB_CATEGORY_ID
		 , HL.FLOOR_ID
		 , HL.PRE_OPERATING_UNIT_ID
		 , HL.PRE_DEPT_ID
		 , HL.PRE_JOB_CLASS_ID
		 , HL.PRE_JOB_ID
		 , HL.PRE_POST_ID
		 , HL.PRE_OCPT_ID
		 , HL.PRE_ABIL_ID
		 , HL.PRE_PAY_GRADE_ID
		 , HL.PRE_JOB_CATEGORY_ID
		 , HL.PRE_FLOOR_ID
		 , HL.PRINT_YN
		 , HL.DESCRIPTION AS LINE_DESCRIPTION
  FROM HRM_HISTORY_HEADER HH
	  , HRM_HISTORY_LINE HL
WHERE HH.HISTORY_HEADER_ID      = HL.HISTORY_HEADER_ID;
