CREATE OR REPLACE VIEW HRM_PAYMENT_TERM_V AS
SELECT HC.COMMON_ID PAYMENT_TERM_ID
     , HC.CODE AS PAYMENT_TERM_CODE
     , HC.CODE_NAME AS PAYMENT_TERM_NAME
     , HC.VALUE1 AS WAGE_TYPE
     , HC.VALUE2 AS PAY_TYPE
     , HC.VALUE3 AS START_DAY
     , TO_NUMBER(HC.VALUE4) AS START_ADD_DAY
     , TO_NUMBER(HC.VALUE5) AS START_ADD_MONTH
     , HC.VALUE6 AS END_DAY
     , TO_NUMBER(HC.VALUE7) AS END_ADD_DAY
     , TO_NUMBER(HC.VALUE8) AS END_ADD_MONTH
     , HC.VALUE9
     , HC.VALUE10
     , HC.DEFAULT_FLAG
     , HC.SORT_NUM
     , HC.DESCRIPTION
     , HC.ENABLED_FLAG
     , HC.EFFECTIVE_DATE_FR
     , HC.EFFECTIVE_DATE_TO
     , HC.SOB_ID
     , HC.ORG_ID
  FROM HRM_COMMON HC
 WHERE HC.GROUP_CODE              = 'PAYMENT_TERM';
