CREATE OR REPLACE VIEW HRM_PAYMENT_CONFIG_V
AS
SELECT HC.COMMON_ID AS PAYMENT_CONFIG_ID
    , HC.GROUP_CODE AS PAYMENT_CONFIG_GROUP
    , HC.CODE AS PAYMENT_CONFIG
    , HC.CODE_NAME AS PAYMENT_CONFIG_NAME
    , HC.VALUE1 AS WAGE_TYPE
    , HC.VALUE2 AS STD_DAY
    , TO_NUMBER(HC.VALUE3) AS STD_ADD_MONTH
    , TO_NUMBER(HC.VALUE4) AS STD_ADD_DAY
    , HC.VALUE5 AS END_DAY
    , TO_NUMBER(HC.VALUE6) AS END_ADD_MONTH
    , TO_NUMBER(HC.VALUE7) AS END_ADD_DAY
    , NVL(HC.VALUE8, '-') AS JOB_CATEGORY_CODE
    , HC.VALUE9
    , HC.VALUE10
    , HC.DEFAULT_FLAG
    , HC.SORT_NUM
    , HC.DESCRIPTION
    , HC.ENABLED_FLAG
    , HC.EFFECTIVE_DATE_FR
    , HC.EFFECTIVE_DATE_TO
    , HC.SOB_ID
    , HC.ORG_ID
  FROM HRM_COMMON_TLV HC
 WHERE HC.GROUP_CODE              = 'PAYMENT_CONFIG';
