CREATE OR REPLACE VIEW HRM_DEPT_MASTER_V AS
SELECT DM_1.DEPT_ID AS DEPT_1ST_ID
    , DM_1.DEPT_CODE AS DEPT_1ST_CODE
    , DM_1.DEPT_NAME AS DEPT_1ST_DESC
    , DM_2.DEPT_ID AS DEPT_2ND_ID
    , DM_2.DEPT_CODE AS DEPT_2ND_CODE
    , DM_2.DEPT_NAME AS DEPT_2ND_DESC
    , DM_3.DEPT_ID AS DEPT_3TH_ID
    , DM_3.DEPT_CODE AS DEPT_3TH_CODE
    , DM_3.DEPT_NAME AS DEPT_3TH_DESC
    , DM.DEPT_ID
    , DM.DEPT_CODE
    , DM.DEPT_NAME AS DEPT_DESC
    , DM.DEPT_SORT_NUM
    , DM.T_O
    , DM.DEPT_GROUP
    , DM.VALUER_1
    , DM.VALUER_2
    , DM.DESCRIPTION
    , DM.USABLE
    , DM.START_DATE
    , DM.END_DATE
    , DM.SOB_ID
    , DM.ORG_ID
  FROM HRM_DEPT_MASTER DM
    , HRM_DEPT_MASTER DM_3
    , HRM_DEPT_MASTER DM_2
    , HRM_DEPT_MASTER DM_1
WHERE DM.UPPER_DEPT_ID      = DM_3.DEPT_ID
  AND DM_3.UPPER_DEPT_ID    = DM_2.DEPT_ID
  AND DM_2.UPPER_DEPT_ID    = DM_1.DEPT_ID
  AND DM.DEPT_LEVEL         = 4
  AND DM_3.DEPT_LEVEL       = 3
  AND DM_2.DEPT_LEVEL       = 2
  AND DM_1.DEPT_LEVEL       = 1;
