CREATE OR REPLACE VIEW HRM_PAY_CALCULATE_PERIOD_V AS
SELECT HC.COMMON_ID AS PAY_CALCULATE_ID
     , HC.GROUP_CODE AS PAY_CALCULATE_GROUP
     , HC.CODE AS PAY_CALCULATE_CODE
     , HC.CODE_NAME AS PAY_CALCULATE_NAME
     , HC.VALUE1 AS WAGE_TYPE
     , HC.VALUE2 AS START_DAY
     , HC.VALUE3 AS START_ADD_MONTH
     , HC.VALUE4 AS START_ADD_DAY
     , HC.VALUE5 AS END_DAY
     , HC.VALUE6 AS END_ADD_MONTH
     , HC.VALUE7 AS END_ADD_DAY
     , HC.VALUE8 AS JOB_CATEGORY_CODE
     , HC.VALUE9
     , HC.VALUE10
     , HC.DEFAULT_FLAG
     , HC.SORT_NUM
     , HC.DESCRIPTION
     , HC.ENABLED_FLAG
     , HC.EFFECTIVE_DATE_FR
     , HC.EFFECTIVE_DATE_TO
     , HC.SOB_ID
     , HC.ORG_ID
  FROM HRM_COMMON HC
 WHERE HC.GROUP_CODE              = 'PAYMENT_CONFIG'
   AND HC.CODE                    IN('10', '20')
;
