CREATE OR REPLACE VIEW HRM_YEAR_RELATION_V AS
SELECT HC.COMMON_ID AS YEAR_RELATION_ID
     , HC.CODE AS YEAR_RELATION_CODE
     , HC.CODE_NAME AS YEAR_RELATION_NAME
     , HC.VALUE1 AS FAMILY_ALLOWANCE_YN
     , HC.VALUE2 AS FAMILY_ALLOWANCE_AMOUNT
     , HC.VALUE3 AS DONATION_DED_YN
     , HC.VALUE4
     , HC.VALUE5
     , HC.VALUE6
     , HC.VALUE7
     , HC.VALUE8
		 , HC.VALUE9
		 , HC.VALUE10
		 , HC.DEFAULT_FLAG
		 , HC.SORT_NUM
		 , HC.DESCRIPTION
		 , HC.ENABLED_FLAG
		 , HC.EFFECTIVE_DATE_FR
		 , HC.EFFECTIVE_DATE_TO
		 , HC.SOB_ID
		 , HC.ORG_ID
FROM HRM_COMMON_TLV HC
WHERE HC.GROUP_CODE               = 'YEAR_RELATION';
