CREATE OR REPLACE VIEW HRM_OT_TYPE_GW_V AS
SELECT HC.COMMON_ID AS OT_TYPE_ID
     , HC.CODE AS OT_TYPE_CODE
     , HC.CODE_NAME AS OT_TYPE_NAME
     , TO_NUMBER(REPLACE(HC.VALUE1, ',', ''), 'FM999999.99', 'NLS_NUMERIC_CHARACTERS=.,') AS STD_OT_TIME
     , HC.VALUE2 AS ALLOWANCE_CODE
     , TO_NUMBER(REPLACE(HC.VALUE3, ',', ''), 'FM9999999999999', 'NLS_NUMERIC_CHARACTERS=.,') AS POST_510  -- 사원
     , TO_NUMBER(REPLACE(HC.VALUE4, ',', ''), 'FM9999999999999', 'NLS_NUMERIC_CHARACTERS=.,') AS POST_430  -- 계장/주임
     , TO_NUMBER(REPLACE(HC.VALUE5, ',', ''), 'FM9999999999999', 'NLS_NUMERIC_CHARACTERS=.,') AS POST_410  -- 대리
     , TO_NUMBER(REPLACE(HC.VALUE6, ',', ''), 'FM9999999999999', 'NLS_NUMERIC_CHARACTERS=.,') AS POST_330  -- 과장
     , TO_NUMBER(REPLACE(HC.VALUE7, ',', ''), 'FM9999999999999', 'NLS_NUMERIC_CHARACTERS=.,') AS POST_320  -- 차장
     , TO_NUMBER(REPLACE(HC.VALUE8, ',', ''), 'FM9999999999999', 'NLS_NUMERIC_CHARACTERS=.,') AS POST_310  -- 부장
     , HC.VALUE9
     , HC.VALUE10
     , HC.SORT_NUM
     , HC.DESCRIPTION
     , HC.ENABLED_FLAG
     , HC.EFFECTIVE_DATE_FR
     , HC.EFFECTIVE_DATE_TO
     , HC.SOB_ID
     , HC.ORG_ID
FROM HRM_COMMON_TLV HC
WHERE HC.GROUP_CODE                     = 'OT_TYPE_GW';
