CREATE OR REPLACE VIEW HRM_DATE_ITEM_V AS
SELECT HC.COMMON_ID AS DATE_ITEM_ID
     , HC.CODE AS DATE_ITEM_CODE
     , HC.CODE_NAME AS DATE_ITEM_NAME
     , HC.VALUE1 AS DATE_COLUMN
     , HC.VALUE2
     , HC.VALUE3
     , HC.VALUE4
     , HC.VALUE5
     , HC.VALUE6
     , HC.VALUE7
     , HC.VALUE8
     , HC.VALUE9
     , HC.VALUE10
     , HC.SORT_NUM
     , HC.DESCRIPTION
     , HC.ENABLED_FLAG
     , HC.EFFECTIVE_DATE_FR
     , HC.EFFECTIVE_DATE_TO
     , HC.SOB_ID
     , HC.ORG_ID
FROM HRM_COMMON_TLV HC
WHERE HC.GROUP_CODE                     = 'DATE_ITEM';
