CREATE OR REPLACE VIEW HRM_TAX_RATE_V AS
SELECT HC.COMMON_ID AS TAX_TYPE_ID
     , HC.CODE AS TAX_TYPE
     , HC.CODE_NAME AS TAX_TYPE_NAME
     , TO_NUMBER(NVL(HC.VALUE1, 0)) AS TAX_RATE
     , HC.VALUE2
     , HC.VALUE3
     , HC.VALUE4
     , HC.VALUE5
     , HC.VALUE6
     , HC.VALUE7
     , HC.VALUE8
		 , HC.VALUE9
		 , HC.VALUE10
		 , HC.DEFAULT_FLAG
		 , HC.SORT_NUM
		 , HC.DESCRIPTION
		 , HC.ENABLED_FLAG
		 , HC.EFFECTIVE_DATE_FR
		 , HC.EFFECTIVE_DATE_TO
		 , HC.SOB_ID
		 , HC.ORG_ID
  FROM HRM_COMMON_TLV HC
WHERE HC.GROUP_CODE             = 'TAX_RATE';
