CREATE OR REPLACE VIEW HRM_WORK_IO_TIME_V AS
SELECT HC.VALUE1 AS WORK_TYPE
    , HC.VALUE2 AS HOLY_TYPE
    , HC.VALUE3 AS I_TIME
    , HC.VALUE4 AS I_ADD_DAYS
    , HC.VALUE5 AS O_TIME
    , HC.VALUE6 AS O_ADD_DAYS
    , HC.VALUE7 AS JOB_CATEGORY_CODE
    , HC.VALUE8
    , HC.VALUE9
    , HC.VALUE10
    , HC.DEFAULT_FLAG
    , HC.SORT_NUM
    , HC.DESCRIPTION
    , HC.ENABLED_FLAG
    , HC.EFFECTIVE_DATE_FR
    , HC.EFFECTIVE_DATE_TO
    , HC.SOB_ID
    , HC.ORG_ID
  FROM HRM_COMMON_TLV HC
 WHERE HC.GROUP_CODE = 'WORK_IO_TIME'
;
