CREATE OR REPLACE VIEW HRM_DUTY_PERIOD_TIME_V AS
SELECT HC.COMMON_ID
     , HC.CODE
		 , HC.CODE_NAME
		 , HC.VALUE1 AS WORK_TYPE
		 , HC.VALUE2 AS HOLY_TYPE
		 , HC.VALUE3 AS START_YN
		 , HC.VALUE4 AS END_YN
		 , HC.VALUE5 AS PERIOD_TIME
		 , HC.VALUE6
		 , HC.VALUE7
     , HC.VALUE8
     , HC.VALUE9
     , HC.VALUE10
		 , HC.DESCRIPTION
		 , HC.SORT_NUM
		 , HC.ENABLED_FLAG
		 , HC.EFFECTIVE_DATE_FR
		 , HC.EFFECTIVE_DATE_TO
		 , HC.SOB_ID
		 , HC.ORG_ID
  FROM HRM_COMMON_TLV HC
 WHERE HC.GROUP_CODE            = 'DUTY_PERIOD_TIME';
