CREATE OR REPLACE VIEW HRM_FAMILY_V AS
SELECT
      HF.FAMILY_ID
		, HF.PERSON_ID
		, HF.FAMILY_NAME
		, HF.RELATION_ID
		, CASE
		    WHEN HF.REPRE_NUM IS NULL THEN NULL
				ELSE DECRYPT_F(HF.REPRE_NUM)
		  END AS REPRE_NUM
		, HF.BIRTHDAY
		, HF.BIRTHDAY_TYPE
		, HF.COMPANY_NAME
		, HF.POST_NAME
		, HF.END_SCH_ID
		, HF.LIVE_YN
		, HF.MARRY_YN
		, HF.DEFORM_YN
    , TO_CHAR(NULL) AS DISABILITY_CODE 
		, HF.PAY_YN
		, HF.TAX_YN
		, HF.DESCRIPTION
		, HF.ATTRIBUTE1
		, HF.ATTRIBUTE2
		, HF.ATTRIBUTE3
		, HF.ATTRIBUTE4
		, HF.ATTRIBUTE5
		, HF.CREATION_DATE
		, HF.CREATED_BY
		, HF.LAST_UPDATE_DATE
		, HF.LAST_UPDATED_BY
  FROM HRM_FAMILY HF;
