CREATE OR REPLACE VIEW HRM_DUTY_CODE_V AS
SELECT HC.COMMON_ID AS DUTY_ID
     , HC.CODE AS DUTY_CODE
     , HC.CODE_NAME AS DUTY_NAME
     , NVL(HC.VALUE1, 'N') AS PAY_DAY_FLAG
     , NVL(HC.VALUE2, 'N') AS NON_PAY_DAY_FLAG
     , TO_NUMBER(REPLACE(HC.VALUE3, ',', ''), '999D9999', 'NLS_NUMERIC_CHARACTERS=.,') AS APPLY_DAY
     , HC.VALUE4 AS HOLIDAY_MANAGE_DUTY_GROUP
     , NVL(HC.VALUE5, 'N') AS WORK_YN
     , NVL(HC.VALUE6, 'N') AS DAY_LEAVE_CONTROL_YN
     , NVL(HC.VALUE7, 'N') AS ATTEND_FLAG
     , NVL(HC.VALUE8, 'N') AS TIME_YN
     , HC.VALUE9
     , NVL(HC.VALUE10, 'N') AS RETIRE_DED_3RD_YN
		 , HC.SORT_NUM
		 , HC.DESCRIPTION
		 , HC.ENABLED_FLAG
		 , HC.EFFECTIVE_DATE_FR
		 , HC.EFFECTIVE_DATE_TO
		 , HC.SOB_ID
		 , HC.ORG_ID
FROM HRM_COMMON_TLV HC
WHERE HC.GROUP_CODE                     = 'DUTY';
