CREATE OR REPLACE VIEW HRM_DUTY_GW_CODE_V AS
SELECT HC.COMMON_ID AS DUTY_GW_ID
     , HC.CODE AS DUTY_GW_CODE
     , HC.CODE_NAME AS DUTY_GW_NAME
     , HC.VALUE1 AS DUTY_CODE
     , HC.VALUE2 AS OT_TYPE_GW
     , HC.VALUE3
     , HC.VALUE4
     , HC.VALUE5
     , HC.VALUE6
     , HC.VALUE7
     , HC.VALUE8
     , HC.VALUE9
     , HC.VALUE10
     , HC.SORT_NUM
     , HC.DESCRIPTION
     , HC.ENABLED_FLAG
     , HC.EFFECTIVE_DATE_FR
     , HC.EFFECTIVE_DATE_TO
     , HC.SOB_ID
     , HC.ORG_ID
FROM HRM_COMMON_TLV HC
WHERE HC.GROUP_CODE                     = 'DUTY_GW';
