CREATE OR REPLACE VIEW HRM_NUMBER_LEVEL_V AS
SELECT HC.COMMON_ID AS NUMBER_LEVEL_ID
     , HC.GROUP_CODE
     , HC.CODE AS NUMBER_LEVEL_TYPE
     , TO_NUMBER(HC.CODE_NAME) AS NUMBER_LEVEL_NAME
     , HC.VALUE1
     , HC.VALUE2
     , HC.VALUE3
     , HC.VALUE4
     , HC.VALUE5
     , HC.VALUE6
     , HC.VALUE7
     , HC.VALUE8
     , HC.VALUE9
     , HC.VALUE10
     , NVL(HC.DEFAULT_FLAG, 'N') AS DEFAULT_FLAG
     , NVL(HC.SORT_NUM, 0) AS SORT_NUM
     , HC.DESCRIPTION
     , HC.ENABLED_FLAG
     , HC.EFFECTIVE_DATE_FR
     , HC.EFFECTIVE_DATE_TO
     , HC.SOB_ID
     , HC.ORG_ID
  FROM HRM_COMMON_TLV HC
 WHERE HC.GROUP_CODE            = 'NUMBER_LEVEL_TYPE';
