CREATE OR REPLACE VIEW HRM_PAY_STANDARD_DATE_V
AS
SELECT HC.COMMON_ID AS STANDARD_DATE_ID
     , HC.GROUP_CODE AS STANDARD_DATE_GROUP
     , HC.CODE AS STANDARD_DATE_CODE
     , HC.CODE_NAME AS STANDARD_DATE_NAME
     , HC.VALUE1 AS WAGE_TYPE
     , HC.VALUE2 AS STANDARD_DAY
     , HC.VALUE3 AS STANDARD_ADD_MONTH
     , HC.VALUE4 AS STANDARD_ADD_DAY
     , HC.VALUE5 
     , HC.VALUE6 
     , HC.VALUE7 
     , HC.VALUE8 AS JOB_CATEGORY_CODE
     , HC.VALUE9
     , HC.VALUE10
     , HC.DEFAULT_FLAG
     , HC.SORT_NUM
     , HC.DESCRIPTION
     , HC.ENABLED_FLAG
     , HC.EFFECTIVE_DATE_FR
     , HC.EFFECTIVE_DATE_TO
     , HC.SOB_ID
     , HC.ORG_ID
  FROM HRM_COMMON HC
 WHERE HC.GROUP_CODE              = 'PAYMENT_CONFIG'
   AND HC.CODE                    = '70'
;
