CREATE OR REPLACE VIEW HRM_CHARGE_CODE_V AS
SELECT HC.COMMON_ID
     , HC.CODE
		 , HC.CODE_NAME
		 , NVL(HC.VALUE1, 'N') AS RETIRE_YN
		 , NVL(HC.VALUE2, 'N') AS NEWCOMER_YN
		 , NVL(HC.VALUE3, NULL) AS EMPLOYE_TYPE
		 , NVL(HC.VALUE4, 'N') AS PROMOTION_FLAG
		 , HC.VALUE5
		 , HC.VALUE6
		 , HC.VALUE7
     , HC.VALUE8
		 , HC.VALUE9
		 , HC.VALUE10
		 , HC.DEFAULT_FLAG
		 , HC.SORT_NUM
		 , HC.DESCRIPTION
		 , HC.ENABLED_FLAG
		 , HC.EFFECTIVE_DATE_FR
		 , HC.EFFECTIVE_DATE_TO
		 , HC.SOB_ID
		 , HC.ORG_ID
FROM HRM_COMMON_TLV HC
WHERE HC.GROUP_CODE                               = 'CHARGE';
