CREATE OR REPLACE VIEW HRM_PERSON_CC_V AS
SELECT PM.PERSON_ID
		, PM.PERSON_NUM
		, PM.NAME
		, PM.CORP_ID
		, PM.DEPT_ID
		, DM.DEPT_NAME
		, PM.EMPLOYE_TYPE
		, PM.FLOOR_ID
		, DECODE(PM.FLOOR_ID, NULL, 'N', 'Y') FLOOR_MAPPING_YN
		, PM.COST_CENTER_ID CC_ID
		, DECODE(PM.COST_CENTER_ID, NULL, 'N', 'Y') CC_MAPPING_YN
		, PM.ORI_JOIN_DATE
		, PM.JOIN_DATE
		, PM.RETIRE_DATE
		, PM.SOB_ID
		, PM.ORG_ID
FROM HRM_PERSON_MASTER PM
  , HRM_CORP_MASTER CM
	, HRM_DEPT_MASTER DM
WHERE PM.CORP_ID                                = CM.CORP_ID
  AND PM.DEPT_ID                                = DM.DEPT_ID
;
