CREATE OR REPLACE VIEW HRM_PERSON_MASTER_V9 AS
SELECT PM.PERSON_ID
     , PM.PERSON_NUM
     , PM.NAME
		 , HH.HISTORY_HEADER_ID
		 , HH.HISTORY_NUM
		 , HH.CHARGE_DATE
		 , HH.CHARGE_ID
		 , HL.HISTORY_LINE_ID
     , PM.CORP_ID
     , NVL(HL.DEPT_ID, PM.DEPT_ID) AS DEPT_ID
     , PM.WORK_TYPE_ID
     , NVL(HL.POST_ID, PM.POST_ID) AS POST_ID
     , NVL(HL.PAY_GRADE_ID, PM.PAY_GRADE_ID) AS PAY_GRADE_ID
     , PM.ORI_JOIN_DATE
     , PM.JOIN_DATE
     , PM.RETIRE_DATE
     , PM.EMPLOYE_TYPE
     , NVL(HL.JOB_CATEGORY_ID, PM.JOB_CATEGORY_ID) AS JOB_CATEGORY_ID
     , NVL(HL.FLOOR_ID, PM.FLOOR_ID) AS FLOOR_ID
     , PM.CORP_TYPE
     , PM.SOB_ID
     , PM.ORG_ID
     , PM.DISPLAY_NAME
FROM HRM_PERSON_MASTER PM
  , HRM_HISTORY_HEADER HH
	, HRM_HISTORY_LINE HL
WHERE PM.CORP_ID                           = HH.CORP_ID
  AND PM.SOB_ID                            = HH.SOB_ID
	AND PM.ORG_ID                            = HH.ORG_ID
	AND HH.HISTORY_HEADER_ID                 = HL.HISTORY_HEADER_ID;
