CREATE OR REPLACE VIEW HRM_DUTY_TERM_V AS
SELECT HC.COMMON_ID AS DUTY_TERM_ID
    , HC.GROUP_CODE AS DUTY_TERM_GROUP
    , HC.CODE AS DUTY_TERM
    , HC.CODE_NAME AS DUTY_TERM_NAME
    , HC.VALUE1 AS DUTY_TERM_TYPE
    , HC.VALUE2 AS START_DAY
    , TO_NUMBER(HC.VALUE3) AS START_ADD_MONTH
    , TO_NUMBER(HC.VALUE4) AS START_ADD_DAY
    , HC.VALUE5 AS END_DAY
    , TO_NUMBER(HC.VALUE6) AS END_ADD_MONTH
    , TO_NUMBER(HC.VALUE7) AS END_ADD_DAY
    , NVL(HC.VALUE8, '-') AS JOB_CATEGORY_CODE
    , HC.VALUE9
    , HC.VALUE10
    , HC.DEFAULT_FLAG
    , HC.SORT_NUM
    , HC.DESCRIPTION
    , HC.ENABLED_FLAG
    , HC.EFFECTIVE_DATE_FR
    , HC.EFFECTIVE_DATE_TO
    , HC.SOB_ID
    , HC.ORG_ID
  FROM HRM_COMMON_TLV HC
 WHERE HC.GROUP_CODE              = 'DUTY_TERM';
