CREATE OR REPLACE VIEW HRM_INSUR_RATE_V AS
SELECT HC.COMMON_ID AS INSUR_RATE_ID
     , HC.GROUP_CODE
     , HC.CODE AS INSUR_RATE_CODE
     , HC.CODE_NAME AS INSUR_NAME
     , HC.VALUE1 AS INSUR_TYPE
     , TO_NUMBER(NVL(HC.VALUE2, 0)) AS INSUR_RATE 
     , TO_NUMBER(NVL(HC.VALUE3, 0)) AS REDUCE_RATE
     , HC.VALUE4
     , HC.VALUE5
     , HC.VALUE6
     , HC.VALUE7
     , HC.VALUE8
     , HC.VALUE9
     , HC.VALUE10
     , NVL(HC.DEFAULT_FLAG, 'N') AS DEFAULT_FLAG
     , NVL(HC.SORT_NUM, 0) AS SORT_NUM
     , HC.DESCRIPTION
     , HC.ENABLED_FLAG
     , HC.EFFECTIVE_DATE_FR
     , HC.EFFECTIVE_DATE_TO
     , HC.SOB_ID
     , HC.ORG_ID
  FROM HRM_COMMON_TLV HC
 WHERE HC.GROUP_CODE            = 'INSUR_RATE';

-- COMMENT.
COMMENT ON COLUMN HRM_INSUR_RATE_V.INSUR_RATE IS '보험율(%)';
COMMENT ON COLUMN HRM_INSUR_RATE_V.REDUCE_RATE IS '경감율(%)';
