CREATE OR REPLACE VIEW HRM_OT_TYPE_ALLOWANCE_V AS
SELECT OT.OT_TYPE_ID
     , OT.OT_TYPE
     , OT.OT_TYPE_NAME
     , OT.SYSTEM_FLAG
     , OT.CODE_LENGTH
     , OT.OT_COLUMN
     , OT.MONTH_TOTAL_ITEM
     , HA_10.ALLOWANCE_ID AS ALLOWANCE_10_ID
     , OT.ALLOWANCE_10_CODE
     , OT.ALLOWANCE_RATE_10 AS ALLOWANCE_RATE_10
     , HA_20.ALLOWANCE_ID AS ALLOWANCE_20_ID
     , OT.ALLOWANCE_20_CODE
     , OT.ALLOWANCE_RATE_20 AS ALLOWANCE_RATE_20
     , OT.VALUE7
     , OT.VALUE8
     , OT.VALUE9
     , OT.VALUE10
     , OT.DEFAULT_FLAG
     , OT.SORT_NUM
     , OT.DESCRIPTION
     , OT.ENABLED_FLAG
     , OT.EFFECTIVE_DATE_FR
     , OT.EFFECTIVE_DATE_TO
     , OT.SOB_ID
     , OT.ORG_ID
  FROM HRM_OT_TYPE_V OT
    , HRM_ALLOWANCE_V HA_10
    , HRM_ALLOWANCE_V HA_20
 WHERE OT.ALLOWANCE_10_CODE             = HA_10.ALLOWANCE_CODE
   AND OT.SOB_ID                        = HA_10.SOB_ID
   AND OT.ORG_ID                        = HA_10.ORG_ID
   AND OT.ALLOWANCE_20_CODE             = HA_20.ALLOWANCE_CODE
   AND OT.SOB_ID                        = HA_20.SOB_ID
   AND OT.ORG_ID                        = HA_20.ORG_ID
;
