CREATE OR REPLACE VIEW HRM_OT_STD_TIME_V AS
SELECT HC.COMMON_ID
     , HC.GROUP_CODE
		 , HC.CODE
		 , HC.CODE_NAME
		 , HC.VALUE1 AS WORK_TYPE
		 , HC.VALUE2 AS HOLY_TYPE
		 , HC.VALUE3 AS OT_STD_TYPE
		 , TO_NUMBER(HC.VALUE4) AS START_ADD_DAY
		 , HC.VALUE5 AS START_TIME
		 , TO_NUMBER(HC.VALUE6) AS END_ADD_DAY
		 , HC.VALUE7 AS END_TIME
     , HC.VALUE8
     , HC.VALUE9
     , HC.VALUE10
     , HC.DEFAULT_FLAG
		 , HC.SORT_NUM
		 , HC.DESCRIPTION
		 , HC.ENABLED_FLAG
		 , HC.EFFECTIVE_DATE_FR
		 , HC.EFFECTIVE_DATE_TO
		 , HC.SOB_ID
		 , HC.ORG_ID     
  FROM HRM_COMMON_TLV HC
 WHERE HC.GROUP_CODE                    = 'OT_STD_TIME';
