CREATE OR REPLACE VIEW HRM_WORK_PLAN_STD_V AS
SELECT HC.COMMON_ID AS WORK_PLAN_ID
     , HC.GROUP_CODE
     , HC.CODE AS WORK_PLAN_CODE
     , HC.CODE_NAME AS WORK_PLAN_NAME
     , HC.VALUE1 AS WORK_TYPE_GROUP
     , HC.VALUE2 AS HOLY_TYPE
     , TO_NUMBER(HC.VALUE3) AS DAY_COUNT
     , HC.VALUE4
     , HC.VALUE5
     , HC.VALUE6
     , HC.VALUE7
     , HC.VALUE8
     , HC.VALUE9
     , HC.VALUE10
     , HC.DEFAULT_FLAG
     , HC.SORT_NUM
     , HC.DESCRIPTION
     , HC.ENABLED_FLAG
     , HC.EFFECTIVE_DATE_FR
     , HC.EFFECTIVE_DATE_TO
     , HC.SOB_ID
     , HC.ORG_ID
  FROM HRM_COMMON_TLV HC
WHERE HC.GROUP_CODE             = 'WORK_PLAN_STD';
