CREATE OR REPLACE VIEW HRP_MONTH_DEDUCTION_V AS
SELECT MD.PERSON_ID
     , MD.PAY_YYYYMM
     , MD.WAGE_TYPE
     , MD.CORP_ID
     , SUM(DECODE(HD.DEDUCTION_CODE, 'D01', MD.DEDUCTION_AMOUNT, 0)) AS D01
     , SUM(DECODE(HD.DEDUCTION_CODE, 'D02', MD.DEDUCTION_AMOUNT, 0)) AS D02
     , SUM(DECODE(HD.DEDUCTION_CODE, 'D03', MD.DEDUCTION_AMOUNT, 0)) AS D03
     , SUM(DECODE(HD.DEDUCTION_CODE, 'D04', MD.DEDUCTION_AMOUNT, 0)) AS D04
     , SUM(DECODE(HD.DEDUCTION_CODE, 'D05', MD.DEDUCTION_AMOUNT, 0)) AS D05
     , SUM(DECODE(HD.DEDUCTION_CODE, 'D06', MD.DEDUCTION_AMOUNT, 0)) AS D06
     , SUM(DECODE(HD.DEDUCTION_CODE, 'D07', MD.DEDUCTION_AMOUNT, 0)) AS D07
     , SUM(DECODE(HD.DEDUCTION_CODE, 'D08', MD.DEDUCTION_AMOUNT, 0)) AS D08
     , SUM(DECODE(HD.DEDUCTION_CODE, 'D09', MD.DEDUCTION_AMOUNT, 0)) AS D09
     , SUM(DECODE(HD.DEDUCTION_CODE, 'D10', MD.DEDUCTION_AMOUNT, 0)) AS D10
     , SUM(DECODE(HD.DEDUCTION_CODE, 'D11', MD.DEDUCTION_AMOUNT, 0)) AS D11
     , SUM(DECODE(HD.DEDUCTION_CODE, 'D12', MD.DEDUCTION_AMOUNT, 0)) AS D12
     , SUM(DECODE(HD.DEDUCTION_CODE, 'D13', MD.DEDUCTION_AMOUNT, 0)) AS D13
     , SUM(DECODE(HD.DEDUCTION_CODE, 'D14', MD.DEDUCTION_AMOUNT, 0)) AS D14
     , SUM(DECODE(HD.DEDUCTION_CODE, 'D15', MD.DEDUCTION_AMOUNT, 0)) AS D15
     , SUM(DECODE(HD.DEDUCTION_CODE, 'D16', MD.DEDUCTION_AMOUNT, 0)) AS D16
     , SUM(DECODE(HD.DEDUCTION_CODE, 'D17', MD.DEDUCTION_AMOUNT, 0)) AS D17
     , SUM(DECODE(HD.DEDUCTION_CODE, 'D18', MD.DEDUCTION_AMOUNT, 0)) AS D18
     , SUM(DECODE(HD.DEDUCTION_CODE, 'D19', MD.DEDUCTION_AMOUNT, 0)) AS D19
     , SUM(DECODE(HD.DEDUCTION_CODE, 'D20', MD.DEDUCTION_AMOUNT, 0)) AS D20
     , SUM(DECODE(HD.DEDUCTION_CODE, 'D21', MD.DEDUCTION_AMOUNT, 0)) AS D21
     , SUM(DECODE(HD.DEDUCTION_CODE, 'D22', MD.DEDUCTION_AMOUNT, 0)) AS D22
     , SUM(DECODE(HD.DEDUCTION_CODE, 'D23', MD.DEDUCTION_AMOUNT, 0)) AS D23
     , SUM(DECODE(HD.DEDUCTION_CODE, 'D24', MD.DEDUCTION_AMOUNT, 0)) AS D24
     , SUM(DECODE(HD.DEDUCTION_CODE, 'D25', MD.DEDUCTION_AMOUNT, 0)) AS D25
     , SUM(DECODE(HD.DEDUCTION_CODE, 'D26', MD.DEDUCTION_AMOUNT, 0)) AS D26
     , SUM(DECODE(HD.DEDUCTION_CODE, 'D27', MD.DEDUCTION_AMOUNT, 0)) AS D27
     , SUM(DECODE(HD.DEDUCTION_CODE, 'D28', MD.DEDUCTION_AMOUNT, 0)) AS D28
     , SUM(DECODE(HD.DEDUCTION_CODE, 'D29', MD.DEDUCTION_AMOUNT, 0)) AS D29
     , MD.MONTH_PAYMENT_ID
     , MD.SOB_ID
     , MD.ORG_ID
  FROM HRP_MONTH_DEDUCTION MD
     , HRM_DEDUCTION_V HD
 WHERE MD.DEDUCTION_ID            = HD.DEDUCTION_ID
GROUP BY MD.PERSON_ID
     , MD.PAY_YYYYMM
     , MD.WAGE_TYPE
     , MD.CORP_ID
     , MD.MONTH_PAYMENT_ID
     , MD.SOB_ID
     , MD.ORG_ID;
