-- CREATE TABLE
CREATE TABLE HRP_MONTH_PAYMENT_TEMP
(
  PAY_YYYYMM        VARCHAR2(7) NOT NULL,
  WAGE_TYPE         VARCHAR2(5) NOT NULL,
  WAGE_TYPE_NAME    VARCHAR2(100),
  DEPT_NAME         VARCHAR2(100),
  POST_NAME         VARCHAR2(100),
  PERSON_ID         NUMBER,
  PERSON_NUM        VARCHAR2(50) NOT NULL,
  NAME              VARCHAR2(100) NOT NULL,
  PAY_TYPE          VARCHAR2(10),
  PAY_TYPE_NAME     VARCHAR2(100),
  TOT_SUPPLY_AMOUNT NUMBER,
  TOT_DED_AMOUNT    NUMBER,
  REAL_AMOUNT       NUMBER,
  A01               NUMBER,
  A02               NUMBER,
  A03               NUMBER,
  A04               NUMBER,
  A06               NUMBER,
  A07               NUMBER,
  A08               NUMBER,
  A09               NUMBER,
  A10               NUMBER,
  A11               NUMBER,
  A12               NUMBER,
  A13               NUMBER,
  A14               NUMBER,
  A17               NUMBER,
  A18               NUMBER,
  A22               NUMBER,
  A25               NUMBER,
  A32               NUMBER,
  A33               NUMBER,
  A34               NUMBER,
  A35               NUMBER,
  A36               NUMBER,
  A37               NUMBER,
  A38               NUMBER,
  A39               NUMBER,
  D01               NUMBER,
  D02               NUMBER,
  D03               NUMBER,
  D04               NUMBER,
  D05               NUMBER,
  D07               NUMBER,
  D08               NUMBER,
  D09               NUMBER,
  D14               NUMBER,
  D15               NUMBER,
  D16               NUMBER,
  D17               NUMBER,
  D18               NUMBER,
  D19               NUMBER,
  D20               NUMBER,
  D21               NUMBER,
  D22               NUMBER,
  D23               NUMBER,
  D24               NUMBER,
  D25               NUMBER
)
TABLESPACE FCM_TS_DATA;
