/******************************************************************************/
/* Project      : FPCB ERP
/* Module       : HR
/* Program Name : HRR_RETIRE_ADJUSTMENT
/* Description  : 퇴직 및 중도 정산.
/*
/* Reference by :
/* Program History
/*------------------------------------------------------------------------------
/*   Date       In Charge          Description
/*------------------------------------------------------------------------------
/* 07-JUN-2010  Jeon Ho Su          Initialize
/******************************************************************************/
CREATE TABLE HRR_RETIRE_ADJUSTMENT              
( ADJUSTMENT_ID                   NUMBER        NOT NULL,
  ADJUSTMENT_TYPE                 VARCHAR2(2)   NOT NULL,
  ADJUSTMENT_YYYY                 VARCHAR2(4)   NOT NULL,
  PERSON_ID                       NUMBER        NOT NULL,
  CORP_ID                         NUMBER        NOT NULL,
  RETIRE_DATE_FR                  DATE          NOT NULL,
  RETIRE_DATE_TO                  DATE          NOT NULL,
  /* -- TABLE 분리 - HRR_RETIRE_ADJUSTMENT_PAYMENT --
  PAY_YYYYMM1                     VARCHAR2(7),
  PAY_AMOUNT1                     NUMBER DEFAULT 0,
  PAY_YYYYMM2                     VARCHAR2(7),
  PAY_AMOUNT2                     NUMBER DEFAULT 0,
  PAY_YYYYMM3                     VARCHAR2(7),
  PAY_AMOUNT3                     NUMBER DEFAULT 0,
  PAY_YYYYMM4                     VARCHAR2(7),
  PAY_AMOUNT4                     NUMBER DEFAULT 0,
  BONUS_YYYYMM1                   VARCHAR2(7),
  BONUS_AMOUNT1                   NUMBER DEFAULT 0,
  BONUS_YYYYMM2                   VARCHAR2(7),
  BONUS_AMOUNT2                   NUMBER DEFAULT 0,
  BONUS_YYYYMM3                   VARCHAR2(7),
  BONUS_AMOUNT3                   NUMBER DEFAULT 0,
  BONUS_YYYYMM4                   VARCHAR2(7),
  BONUS_AMOUNT4                   NUMBER DEFAULT 0,
  BONUS_YYYYMM5                   VARCHAR2(7),
  BONUS_AMOUNT5                   NUMBER DEFAULT 0,
  BONUS_YYYYMM6                   VARCHAR2(7),
  BONUS_AMOUNT6                   NUMBER DEFAULT 0,
  BONUS_YYYYMM7                   VARCHAR2(7),
  BONUS_AMOUNT7                   NUMBER DEFAULT 0,*/
  TOTAL_PAY_AMOUNT                NUMBER        DEFAULT 0,
  TOTAL_BONUS_AMOUNT              NUMBER        DEFAULT 0,
  YEAR_ALLOWANCE_AMOUNT           NUMBER        DEFAULT 0,
  LONG_YEAR                       NUMBER        DEFAULT 0,
  LONG_MONTH                      NUMBER        DEFAULT 0,
  LONG_DAY                        NUMBER        DEFAULT 0,
  DAY_3RD_COUNT                   NUMBER        DEFAULT 0,
  DAY_AVG_AMOUNT                  NUMBER        DEFAULT 0,
  DED_DAY                         NUMBER        DEFAULT 0,
  DED_DAY_DESCRIPTION             VARCHAR2(150) ,
  RETIRE_AMOUNT                   NUMBER        DEFAULT 0,
  GLORY_AMOUNT                    NUMBER        DEFAULT 0,
  GLORY_DESCRIPTION               VARCHAR2(150) ,
  ETC_SUPP_AMOUNT                 NUMBER        DEFAULT 0,
  ETC_SUPP_DESCRIPTION            VARCHAR2(150) ,
  RETIRE_TOTAL_AMOUNT             NUMBER        DEFAULT 0,
  INCOME_DED_AMOUNT               NUMBER        DEFAULT 0,
  LONG_DED_AMOUNT                 NUMBER        DEFAULT 0,
  TAX_STD_AMOUNT                  NUMBER        DEFAULT 0,
  AVG_TAX_STD_AMOUNT              NUMBER        DEFAULT 0,
  AVG_COMP_TAX_AMOUNT             NUMBER        DEFAULT 0,
  COMP_TAX_AMOUNT                 NUMBER        DEFAULT 0,
  TAX_DED_AMOUNT                  NUMBER        DEFAULT 0,
  INCOME_TAX_AMOUNT               NUMBER        DEFAULT 0,
  RESIDENT_TAX_AMOUNT             NUMBER        DEFAULT 0,
  SP_TAX_AMOUNT                   NUMBER        DEFAULT 0,
  RETIRE_CVS_AMOUNT               NUMBER        DEFAULT 0,
  ETC_DED_AMOUNT                  NUMBER        DEFAULT 0,
  ETC_DED_DESCRIPTION             VARCHAR2(150) ,
  REAL_AMOUNT                     NUMBER        DEFAULT 0,
  H_RETIRE_DATE_FR                DATE          ,
  H_RETIRE_DATE_TO                DATE          ,
  HONORARY_AMOUNT                 NUMBER        DEFAULT 0,
  HONORARY_DESCRIPTION            VARCHAR2(150) ,
  H_LONG_YEAR                     NUMBER        DEFAULT 0,
  H_LONG_MONTH                    NUMBER        DEFAULT 0,
  H_LONG_DAY                      NUMBER        DEFAULT 0,
  H_INCOME_DED_AMOUNT             NUMBER        DEFAULT 0,
  H_LONG_DED_AMOUNT               NUMBER        DEFAULT 0,
  H_TAX_STD_AMOUNT                NUMBER        DEFAULT 0,
  H_AVG_TAX_STD_AMOUNT            NUMBER        DEFAULT 0,
  H_AVG_COMP_TAX_AMOUNT           NUMBER        DEFAULT 0,
  H_COMP_TAX_AMOUNT               NUMBER        DEFAULT 0,
  H_TAX_DED_AMOUNT                NUMBER        DEFAULT 0,
  H_INCOME_TAX_AMOUNT             NUMBER        DEFAULT 0,
  H_RESIDENT_TAX_AMOUNT           NUMBER        DEFAULT 0,
  H_SP_TAX_AMOUNT                 NUMBER        DEFAULT 0,  
  H_REAL_AMOUNT                   NUMBER        DEFAULT 0,
  REAL_TOTAL_AMOUNT               NUMBER        DEFAULT 0,
  COST_CENTER_ID                  NUMBER        ,
  CLOSED_YN                       CHAR(1)       DEFAULT 'N',
  CLOSED_DATE                     DATE          ,
  CLOSED_PERSON_ID                NUMBER        ,
  INTERFACE_YN                    CHAR(1)       DEFAULT 'N',
  INTERFACE_LINK_ID               NUMBER        ,
  INTERFACE_DATE                  DATE          ,
  INTERFACE_PERSON_ID             NUMBER        ,
  DESCRIPTION                     VARCHAR2(100) ,
  ATTRIBUTE1                      VARCHAR2(100) ,
  ATTRIBUTE2                      VARCHAR2(100) ,
  ATTRIBUTE3                      VARCHAR2(100) ,
  ATTRIBUTE4                      VARCHAR2(100) ,
  ATTRIBUTE5                      VARCHAR2(100) ,
  SOB_ID                          NUMBER        NOT NULL,
  ORG_ID                          NUMBER        NOT NULL,
  CREATION_DATE                   DATE          NOT NULL,
  CREATED_BY                      NUMBER        NOT NULL,
  LAST_UPDATE_DATE                DATE          NOT NULL,
  LAST_UPDATED_BY                 NUMBER        NOT NULL
) TABLESPACE FCM_TS_DATA;

-- Add comments to the columns 
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.ADJUSTMENT_ID IS '퇴직정산ID';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.ADJUSTMENT_TYPE IS '정산구분(R-퇴직금, M-중도정산)';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.ADJUSTMENT_YYYY IS '정산년도';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.PERSON_ID IS '사원 ID';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.CORP_ID IS '업체ID';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.RETIRE_DATE_FR IS '정산 시작일자';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.RETIRE_DATE_FR IS '정산 종료일자';
/* -- TABLE 분리 - HRR_RETIRE_ADJUSTMENT_PAYMENT --
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.PAY_YYYYMM1 IS '급여년월1';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.PAY_AMOUNT1 IS '급여액1';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.PAY_YYYYMM2 IS '급여년월2';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.PAY_AMOUNT2 IS '급여액2';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.PAY_YYYYMM3 IS '급여년월3';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.PAY_AMOUNT3 IS '급여액3';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.PAY_YYYYMM4 IS '급여년월4';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.PAY_AMOUNT4 IS '급여액4';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.BONUS_YYYYMM1 IS '상여년월1';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.BONUS_AMOUNT1 IS '상여액1';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.BONUS_YYYYMM2 IS '상여년월2';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.BONUS_AMOUNT2 IS '상여액2';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.BONUS_YYYYMM3 IS '상여년월3';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.BONUS_AMOUNT3 IS '상여액3';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.BONUS_YYYYMM4 IS '상여년월4';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.BONUS_AMOUNT4 IS '상여액4';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.BONUS_YYYYMM5 IS '상여년월5';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.BONUS_AMOUNT5 IS '상여액5';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.BONUS_YYYYMM6 IS '상여년월6';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.BONUS_AMOUNT6 IS '상여액6';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.BONUS_YYYYMM7 IS '상여년월7';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.BONUS_AMOUNT7 IS '상여액7';*/
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.TOTAL_PAY_AMOUNT IS '총급여액(기준월수에 대한)';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.TOTAL_BONUS_AMOUNT IS '총상여액(기준월수에 대한)';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.YEAR_ALLOWANCE_AMOUNT IS '년차수당(기준월수에 대한)';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.LONG_YEAR IS '근속년수';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.LONG_MONTH IS '근속월수';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.LONG_DAY IS '근속일수';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.DAY_3RD_COUNT IS '3개월 일수';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.DAY_AVG_AMOUNT IS '일평균금액';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.DED_DAY IS '공제일수';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.DED_DAY_DESCRIPTION IS '공제사유';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.RETIRE_AMOUNT IS '퇴직금';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.GLORY_AMOUNT IS '위로금';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.GLORY_DESCRIPTION IS '위로금 사유';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.ETC_SUPP_AMOUNT IS '기타지급';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.ETC_SUPP_DESCRIPTION IS '기타지급사유';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.RETIRE_TOTAL_AMOUNT IS '총퇴직금';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.INCOME_DED_AMOUNT IS '소득공제금액';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.LONG_DED_AMOUNT IS '근속공제금액';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.TAX_STD_AMOUNT IS '과세표준';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.AVG_TAX_STD_AMOUNT IS '년과세표준';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.AVG_COMP_TAX_AMOUNT IS '년산출세액';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.COMP_TAX_AMOUNT IS '산출세액';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.TAX_DED_AMOUNT IS '소득세액공제';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.INCOME_TAX_AMOUNT IS '소득세액';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.RESIDENT_TAX_AMOUNT IS '주민세';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.SP_TAX_AMOUNT IS '농특세';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.RETIRE_CVS_AMOUNT IS '퇴직전환금';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.ETC_DED_AMOUNT IS '기타공제금액';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.ETC_DED_DESCRIPTION IS '기타공제 사유';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.REAL_AMOUNT IS '실지급액';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.H_RETIRE_DATE_FR IS '명예퇴직 정산 시작일자';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.H_RETIRE_DATE_FR IS '명예퇴직 정산 종료일자';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.HONORARY_AMOUNT IS '명예퇴직금';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.HONORARY_DESCRIPTION IS '명예퇴직 사유';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.H_LONG_YEAR IS '명퇴 근속년수';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.H_LONG_MONTH IS '명퇴 근속월수';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.H_LONG_DAY IS '명퇴 근속일수';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.H_INCOME_DED_AMOUNT IS '명예퇴직 소득공제금액';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.H_LONG_DED_AMOUNT IS '명예퇴직 근속공제금액';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.H_TAX_STD_AMOUNT IS '명예퇴직 과세표준';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.H_AVG_TAX_STD_AMOUNT IS '명예퇴직 년과세표준';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.H_AVG_COMP_TAX_AMOUNT IS '명예퇴직 년산출세액';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.H_COMP_TAX_AMOUNT IS '명예퇴직 산출세액';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.H_TAX_DED_AMOUNT IS '명예퇴직 소득세액공제';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.H_INCOME_TAX_AMOUNT IS '명예퇴직 소득세액';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.H_RESIDENT_TAX_AMOUNT IS '명예퇴직 주민세';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.H_SP_TAX_AMOUNT IS '명예퇴직 농특세';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.H_REAL_AMOUNT IS '명예퇴직 실지급액';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.REAL_TOTAL_AMOUNT IS '총 실지급액';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.COST_CENTER_ID IS '원가코드ID';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.CLOSED_YN IS '지급여부';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.CLOSED_DATE IS '지급일자';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.CLOSED_PERSON_ID IS '지급처리자';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.DESCRIPTION IS '비고';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.CREATION_DATE  IS '생성일자';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.CREATED_BY IS '생성자';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.LAST_UPDATE_DATE IS '최종수정일자';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT.LAST_UPDATED_BY IS '최종수정자';

-- CREATE INDEX.
CREATE UNIQUE INDEX HRR_RETIRE_ADJUSTMENT_U1 ON HRR_RETIRE_ADJUSTMENT(ADJUSTMENT_ID) TABLESPACE FCM_TS_IDX;
CREATE UNIQUE INDEX HRR_RETIRE_ADJUSTMENT_U2 ON HRR_RETIRE_ADJUSTMENT(ADJUSTMENT_TYPE, PERSON_ID, CORP_ID, RETIRE_DATE_FR, RETIRE_DATE_TO, SOB_ID, ORG_ID) TABLESPACE FCM_TS_IDX;

-- SEQUENCE.
DROP SEQUENCE HRR_RETIRE_ADJUSTMENT_S1;
CREATE SEQUENCE HRR_RETIRE_ADJUSTMENT_S1;

-- ANALYZE.
ANALYZE TABLE HRR_RETIRE_ADJUSTMENT COMPUTE STATISTICS;
ANALYZE INDEX HRR_RETIRE_ADJUSTMENT_U1 COMPUTE STATISTICS;
ANALYZE INDEX HRR_RETIRE_ADJUSTMENT_U2 COMPUTE STATISTICS;
