/******************************************************************************/
/* Project      : FPCB ERP
/* Module       : HR
/* Program Name : HRR_RETIRE_ADJUSTMENT_PAYMENT
/* Description  : 퇴직정산 급상여 지급내역(총합계).
/*
/* Reference by :
/* Program History
/*------------------------------------------------------------------------------
/*   Date       In Charge          Description
/*------------------------------------------------------------------------------
/* 07-JUN-2010  Jeon Ho Su          Initialize
/******************************************************************************/
CREATE TABLE HRR_RETIRE_ADJUSTMENT_PAYMENT              
( ADJUSTMENT_ID                   NUMBER        NOT NULL,
  PAY_YYYYMM                      VARCHAR2(7)   NOT NULL,
  WAGE_TYPE                       VARCHAR2(5)   NOT NULL,
  TOTAL_AMOUNT                    NUMBER        DEFAULT 0,
  START_DATE                      DATE          ,
  END_DATE                        DATE          ,
  MODIFY_YN                       VARCHAR2(1)   DEFAULT 'N',
  MODIFY_DATE                     DATE          ,
  MODIFY_PERSON_ID                NUMBER        ,
  PERSON_ID                       NUMBER        ,
  CORP_ID                         NUMBER        ,  
  SOB_ID                          NUMBER        NOT NULL,
  ORG_ID                          NUMBER        NOT NULL,
  CREATION_DATE                   DATE          NOT NULL,
  CREATED_BY                      NUMBER        NOT NULL,
  LAST_UPDATE_DATE                DATE          NOT NULL,
  LAST_UPDATED_BY                 NUMBER        NOT NULL
) TABLESPACE FCM_TS_DATA;

-- Add comments to the columns 
COMMENT ON TABLE HRR_RETIRE_ADJUSTMENT_PAYMENT IS '퇴직정산 급상여 총지급내역';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT_PAYMENT.ADJUSTMENT_ID IS '퇴직정산ID';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT_PAYMENT.PAY_YYYYMM IS '적용 급상여 년월';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT_PAYMENT.WAGE_TYPE IS '급상여 구분';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT_PAYMENT.TOTAL_AMOUNT IS '총금액';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT_PAYMENT.START_DATE IS '적용 시작일자';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT_PAYMENT.END_DATE IS '적용 종료일자';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT_PAYMENT.MODIFY_YN IS '수정 YN';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT_PAYMENT.MODIFY_DATE IS '수정일자';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT_PAYMENT.MODIFY_PERSON_ID IS '수정 작업자';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT_PAYMENT.PERSON_ID IS '사원ID';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT_PAYMENT.CORP_ID IS '업체ID';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT_PAYMENT.CREATION_DATE  IS '생성일자';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT_PAYMENT.CREATED_BY IS '생성자';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT_PAYMENT.LAST_UPDATE_DATE IS '최종수정일자';
COMMENT ON COLUMN HRR_RETIRE_ADJUSTMENT_PAYMENT.LAST_UPDATED_BY IS '최종수정자';

-- CREATE INDEX.
CREATE UNIQUE INDEX HRR_RETIRE_ADJUST_PAY_U1 ON HRR_RETIRE_ADJUSTMENT_PAYMENT(ADJUSTMENT_ID, PAY_YYYYMM, WAGE_TYPE) TABLESPACE FCM_TS_IDX;
CREATE INDEX HRR_RETIRE_ADJUST_PAY_N1 ON HRR_RETIRE_ADJUSTMENT_PAYMENT(ADJUSTMENT_ID, WAGE_TYPE) TABLESPACE FCM_TS_IDX;
-- ANALYZE.
ANALYZE TABLE HRR_RETIRE_ADJUSTMENT_PAYMENT COMPUTE STATISTICS;
ANALYZE INDEX HRR_RETIRE_ADJUST_PAY_U1 COMPUTE STATISTICS;
ANALYZE INDEX HRR_RETIRE_ADJUST_PAY_N1 COMPUTE STATISTICS;
