CREATE OR REPLACE VIEW HRR_RETIREMENT_PENSION_V AS
SELECT HRP.RETIREMENT_PENSION_ID
     , HRP.PERSON_ID
     , HRP.SOB_ID
     , HRP.ORG_ID
     , HRP.SIGN_UP_DATE
     , HRP.YEAR_BANK_ID
     , YB.BANK_NAME AS CORP_NAME
     , YB.TAX_REG_NUM AS TAX_REG_NUM
     , HRP.ACCOUNT_NUM
     , HRP.ISSUE_DATE
     , HRP.DUE_DATE
     , HRP.DESCRIPTION
  FROM HRR_RETIREMENT_PENSION HRP
    , ( SELECT HC.COMMON_ID AS BANK_ID
             , HC.CODE AS BANK_CODE
             , HC.CODE_NAME AS BANK_NAME
             , HC.VALUE1 AS TAX_REG_NUM
          FROM HRM_COMMON HC
         WHERE HC.GROUP_CODE  = 'YEAR_BANK'
      ) YB
  WHERE HRP.YEAR_BANK_ID        = YB.BANK_ID;
