CREATE OR REPLACE VIEW HRT_MONTH_ALLOWANCE_V AS
SELECT MA.PERSON_ID
     , MA.PAY_YYYYMM
     , MA.WAGE_TYPE
     , MA.CORP_ID
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A01', MA.ALLOWANCE_AMOUNT, 0)) AS A01
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A02', MA.ALLOWANCE_AMOUNT, 0)) AS A02
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A03', MA.ALLOWANCE_AMOUNT, 0)) AS A03
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A04', MA.ALLOWANCE_AMOUNT, 0)) AS A04
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A05', MA.ALLOWANCE_AMOUNT, 0)) AS A05
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A06', MA.ALLOWANCE_AMOUNT, 0)) AS A06
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A07', MA.ALLOWANCE_AMOUNT, 0)) AS A07
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A08', MA.ALLOWANCE_AMOUNT, 0)) AS A08
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A09', MA.ALLOWANCE_AMOUNT, 0)) AS A09
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A10', MA.ALLOWANCE_AMOUNT, 0)) AS A10
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A11', MA.ALLOWANCE_AMOUNT, 0)) AS A11
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A12', MA.ALLOWANCE_AMOUNT, 0)) AS A12
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A13', MA.ALLOWANCE_AMOUNT, 0)) AS A13
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A14', MA.ALLOWANCE_AMOUNT, 0)) AS A14
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A15', MA.ALLOWANCE_AMOUNT, 0)) AS A15
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A16', MA.ALLOWANCE_AMOUNT, 0)) AS A16
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A17', MA.ALLOWANCE_AMOUNT, 0)) AS A17
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A18', MA.ALLOWANCE_AMOUNT, 0)) AS A18
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A19', MA.ALLOWANCE_AMOUNT, 0)) AS A19
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A20', MA.ALLOWANCE_AMOUNT, 0)) AS A20
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A21', MA.ALLOWANCE_AMOUNT, 0)) AS A21
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A22', MA.ALLOWANCE_AMOUNT, 0)) AS A22
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A23', MA.ALLOWANCE_AMOUNT, 0)) AS A23
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A24', MA.ALLOWANCE_AMOUNT, 0)) AS A24
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A25', MA.ALLOWANCE_AMOUNT, 0)) AS A25
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A26', MA.ALLOWANCE_AMOUNT, 0)) AS A26
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A27', MA.ALLOWANCE_AMOUNT, 0)) AS A27
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A28', MA.ALLOWANCE_AMOUNT, 0)) AS A28
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A29', MA.ALLOWANCE_AMOUNT, 0)) AS A29
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A30', MA.ALLOWANCE_AMOUNT, 0)) AS A30
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A31', MA.ALLOWANCE_AMOUNT, 0)) AS A31
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A32', MA.ALLOWANCE_AMOUNT, 0)) AS A32
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A33', MA.ALLOWANCE_AMOUNT, 0)) AS A33
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A34', MA.ALLOWANCE_AMOUNT, 0)) AS A34
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A35', MA.ALLOWANCE_AMOUNT, 0)) AS A35
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A36', MA.ALLOWANCE_AMOUNT, 0)) AS A36
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A37', MA.ALLOWANCE_AMOUNT, 0)) AS A37
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A38', MA.ALLOWANCE_AMOUNT, 0)) AS A38
     , SUM(DECODE(HA.ALLOWANCE_CODE, 'A39', MA.ALLOWANCE_AMOUNT, 0)) AS A39
     , SUM(DECODE(HA.GENERAL_PAY_YN, 'Y', MA.ALLOWANCE_AMOUNT, 0)) AS GENERAL_PAY_AMOUNT
     , SUM(DECODE(HA.TAX_FREE, 'OT', MA.ALLOWANCE_AMOUNT, 0)) AS TAX_FREE_OT
     , SUM(DECODE(HA.TAX_FREE, 'ETC', MA.ALLOWANCE_AMOUNT, 0)) AS TAX_FREE_ETC
     , MA.MONTH_PAYMENT_ID
     , MA.SOB_ID
     , MA.ORG_ID
  FROM HRT_MONTH_ALLOWANCE MA
     , HRM_ALLOWANCE_V HA
 WHERE MA.ALLOWANCE_ID            = HA.ALLOWANCE_ID
GROUP BY MA.PERSON_ID
     , MA.PAY_YYYYMM
     , MA.WAGE_TYPE
     , MA.CORP_ID
     , MA.MONTH_PAYMENT_ID
     , MA.SOB_ID
     , MA.ORG_ID;
