/******************************************************************************/
/* Project      : FPCB ERP
/* Module       : HR
/* Program Name : HRT_MONTH_PAYMENT
/* Description  : 월급상여 내역 관리
/*
/* Reference by :
/* Program History
/*------------------------------------------------------------------------------
/*   Date       In Charge          Description
/*------------------------------------------------------------------------------
/* 07-JUN-2010  Jeon Ho Su          Initialize
/******************************************************************************/
CREATE TABLE HRT_MONTH_PAYMENT              
( MONTH_PAYMENT_ID                NUMBER          NOT NULL,
  PERSON_ID                       NUMBER          NOT NULL,
  PAY_YYYYMM                      VARCHAR2(7)     NOT NULL,
  WAGE_TYPE                       VARCHAR2(5)     NOT NULL,
  CORP_ID                         NUMBER          NOT NULL,
  DEPT_ID                         NUMBER          ,
  POST_ID                         NUMBER          ,
  OCPT_ID                         NUMBER          ,
  ABIL_ID                         NUMBER          ,
  JOB_CATEGORY_ID                 NUMBER          ,
  PAY_TYPE                        VARCHAR2(2)     NOT NULL,
  PAY_GRADE_ID                    NUMBER          ,
  GRADE_STEP                      NUMBER          ,
  COST_CENTER_ID                  NUMBER          ,
  DIR_INDIR_TYPE                  VARCHAR2(2)     ,
  EMPLOYE_TYPE                    VARCHAR2(1)     ,
  EXCEPT_TYPE                     VARCHAR2(1)     ,
  HIRE_INSUR_YN                   VARCHAR2(1)     ,
  SUPPLY_DATE                     DATE            ,
  STANDARD_DATE                   DATE            ,
  LONG_YEAR                       NUMBER          DEFAULT 0,
  LONG_MONTH                      NUMBER          DEFAULT 0,
  GENERAL_HOURLY_AMOUNT           NUMBER          DEFAULT 0,
  PAY_DAY                         NUMBER          DEFAULT 0,
  PAY_RATE                        NUMBER          DEFAULT 100,  
  DED_PERSON_COUNT                NUMBER          DEFAULT 0,
  PAY_AMOUNT                      NUMBER          DEFAULT 0,
  DED_PAY_AMOUNT                  NUMBER          DEFAULT 0,
  BONUS_AMOUNT                    NUMBER          DEFAULT 0,
  DED_BONUS_AMOUNT                NUMBER          DEFAULT 0,
  TOT_SUPPLY_AMOUNT               NUMBER          DEFAULT 0,
  TOT_DED_AMOUNT                  NUMBER          DEFAULT 0,
  NATIONAL_PENSION                NUMBER          DEFAULT 0,
  HEALTH_INSUR                    NUMBER          DEFAULT 0,
  UNEMPLOYMENT_INSUR              NUMBER          DEFAULT 0,
  SAFETY_INSUR                    NUMBER          DEFAULT 0,  
  BENEFIT_AMOUNT                  NUMBER          DEFAULT 0,  
  REAL_AMOUNT                     NUMBER          DEFAULT 0,
  CLOSED_YN                       VARCHAR2(2)     DEFAULT 'N',
  CLOSED_PERSON_ID                NUMBER          ,
  CLOSED_DATE                     DATE            ,
  INTERFACE_YN                    VARCHAR2(2)     DEFAULT 'N',
  INTERFACE_HEADER_ID             NUMBER          ,
  INTERFACE_NUM                   VARCHAR2(30)    ,
  INTERFACE_PERSON_ID             NUMBER          ,
  INTERFACE_DATE                  DATE            ,
  DESCRIPTION                     VARCHAR2(100)   ,
  ATTRIBUTE1                      VARCHAR2(100)   ,
  ATTRIBUTE2                      VARCHAR2(100)   ,
  ATTRIBUTE3                      VARCHAR2(100)   ,
  ATTRIBUTE4                      VARCHAR2(100)   ,
  ATTRIBUTE5                      VARCHAR2(100)   ,
  SOB_ID                          NUMBER          NOT NULL,
  ORG_ID                          NUMBER          NOT NULL,
  CREATION_DATE                   DATE            NOT NULL,
  CREATED_BY                      NUMBER          NOT NULL,
  LAST_UPDATE_DATE                DATE            NOT NULL,
  LAST_UPDATED_BY                 NUMBER          NOT NULL
) TABLESPACE FCM_TS_DATA;

-- Add comments to the columns 
COMMENT ON TABLE HRT_MONTH_PAYMENT IS '급상여내역';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.MONTH_PAYMENT_ID IS '월급여내역 ID';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.PERSON_ID IS '사원ID';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.PAY_YYYYMM IS '급상여 년월';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.WAGE_TYPE IS '급상여 구분';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.CORP_ID IS '업체ID';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.DEPT_ID IS '부서코드';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.POST_ID IS '직위코드';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.OCPT_ID IS '직무코드';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.ABIL_ID IS '직책코드';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.JOB_CATEGORY_ID IS '직구분';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.PAY_TYPE IS '급여제 구분';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.PAY_GRADE_ID IS '직급 ID';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.GRADE_STEP IS '호봉';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.COST_CENTER_ID IS '원가 ID';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.DIR_INDIR_TYPE IS '직간접 구분';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.EMPLOYE_TYPE IS '재직구분';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.EXCEPT_TYPE IS '입(I)/퇴사(R)등으로 예외처리';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.HIRE_INSUR_YN IS '고용보험 Y/N';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.SUPPLY_DATE IS '지급일자';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.STANDARD_DATE IS '기준일자';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.LONG_MONTH IS '근속년수';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.GENERAL_HOURLY_AMOUNT IS '통상시급';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.PAY_DAY IS '급상여일수';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.PAY_RATE IS '지급율';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.DED_PERSON_COUNT IS '부양가족 공제인원수';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.PAY_AMOUNT IS '급여 지급액';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.DED_PAY_AMOUNT IS '급여 공제액';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.BONUS_AMOUNT IS '상여 지급액';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.DED_BONUS_AMOUNT IS '상여 공제액';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.TOT_SUPPLY_AMOUNT IS '총지급액';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.TOT_DED_AMOUNT IS '총공제액';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.NATIONAL_PENSION IS '국민연금';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.HEALTH_INSUR IS '건강보험';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.UNEMPLOYMENT_INSUR IS '고용보험';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.SAFETY_INSUR IS '산재보험';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.BENEFIT_AMOUNT IS '기업이윤';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.REAL_AMOUNT IS '실지급액';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.CLOSED_YN IS '마감구분';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.CLOSED_PERSON_ID IS '마감처리자';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.CLOSED_DATE IS '마감일시';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.INTERFACE_YN IS '전송여부';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.INTERFACE_HEADER_ID IS '전송(전표) 헤더 ID';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.INTERFACE_NUM IS '전송(전표)번호';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.INTERFACE_PERSON_ID IS'전송처리자';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.INTERFACE_DATE IS '전송일시';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.DESCRIPTION IS '비고';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.CREATION_DATE  IS '생성일자';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.CREATED_BY IS '생성자';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.LAST_UPDATE_DATE IS '최종수정일자';
COMMENT ON COLUMN HRT_MONTH_PAYMENT.LAST_UPDATED_BY IS '최종수정자';

-- Primary Key.
ALTER TABLE HRT_MONTH_PAYMENT ADD CONSTRAINTS HRT_MONTH_PAYMENT_PK PRIMARY KEY(PAY_YYYYMM, WAGE_TYPE, PERSON_ID, CORP_ID, SOB_ID, ORG_ID);
-- CREATE INDEX.
CREATE UNIQUE INDEX HRT_MONTH_PAYMENT_U1 ON HRT_MONTH_PAYMENT(MONTH_PAYMENT_ID) TABLESPACE FCM_TS_IDX;

-- SEQUENCE.
CREATE SEQUENCE HRT_MONTH_PAYMENT_S1;

-- ANALYZE.
ANALYZE TABLE HRT_MONTH_PAYMENT COMPUTE STATISTICS;
ANALYZE INDEX HRT_MONTH_PAYMENT_U1 COMPUTE STATISTICS;
