/******************************************************************************/
/* Project      : FPCB ERP
/* Module       : HR
/* Program Name : HRW_WITHHOLDING_HEADER
/* Description  : 원천징수이행상황신고서-헤더.
/*
/* Reference by :
/* Program History
/*------------------------------------------------------------------------------
/*   Date       In Charge          Description
/*------------------------------------------------------------------------------
/* 07-JUN-2010  Jeon Ho Su          Initialize
/******************************************************************************/
CREATE TABLE HRW_WITHHOLDING_HEADER
( WITHHOLDING_HEADER_ID           NUMBER          NOT NULL,
  WITHHOLDING_NO                  VARCHAR2(20)    NOT NULL,
  CORP_ID                         NUMBER          NOT NULL,
  SOB_ID                          NUMBER          NOT NULL,
  ORG_ID                          NUMBER          NOT NULL,
  WITHHOLDING_TYPE                VARCHAR2(10)    NOT NULL,
  STD_YYYYMM                      VARCHAR2(8)     NOT NULL,
  PAY_YYYYMM                      VARCHAR2(8)     NOT NULL,
  INCOME_DISPOSED_YN              VARCHAR2(2)     ,
  SUBMIT_DATE                     DATE            ,
  PRE_WITHHOLDING_NO              VARCHAR2(20)    ,
  SOURCE_WITHHOLDING_NO           VARCHAR2(20)    ,
  CLOSED_YN                       VARCHAR2(2)     ,
  CLOSED_DATE                     DATE            ,
  CLOSED_PERSON_ID                NUMBER          ,
  DESCRIPTION                     VARCHAR2(100)   ,
  ATTRIBUTE_1                     NUMBER          ,
  ATTRIBUTE_2                     NUMBER          ,
  ATTRIBUTE_3                     NUMBER          ,
  ATTRIBUTE_4                     NUMBER          ,
  ATTRIBUTE_5                     NUMBER          ,
  ATTRIBUTE_A                     NUMBER          ,
  ATTRIBUTE_B                     VARCHAR2(100)   ,
  ATTRIBUTE_C                     VARCHAR2(100)   ,
  ATTRIBUTE_D                     VARCHAR2(100)   ,
  ATTRIBUTE_E                     VARCHAR2(100)   ,
  CREATION_DATE                   DATE            NOT NULL,
  CREATED_BY                      NUMBER          NOT NULL,
  LAST_UPDATE_DATE                DATE            NOT NULL,
  LAST_UPDATED_BY                 NUMBER          NOT NULL
) TABLESPACE FCM_TS_DATA;

-- Add comments to the columns 
COMMENT ON TABLE HRW_WITHHOLDING_HEADER IS '원천징수이행상황신고서-헤더';
COMMENT ON COLUMN HRW_WITHHOLDING_HEADER.WITHHOLDING_HEADER_ID IS '헤더 ID';
COMMENT ON COLUMN HRW_WITHHOLDING_HEADER.WITHHOLDING_NO IS '문서번호';
COMMENT ON COLUMN HRW_WITHHOLDING_HEADER.CORP_ID IS '업체ID';
COMMENT ON COLUMN HRW_WITHHOLDING_HEADER.WITHHOLDING_TYPE IS '신고구분';
COMMENT ON COLUMN HRW_WITHHOLDING_HEADER.STD_YYYYMM IS '귀속년월';
COMMENT ON COLUMN HRW_WITHHOLDING_HEADER.PAY_YYYYMM IS '지급년월';
COMMENT ON COLUMN HRW_WITHHOLDING_HEADER.INCOME_DISPOSED_YN IS '소득처분여부';
COMMENT ON COLUMN HRW_WITHHOLDING_HEADER.SUBMIT_DATE IS '제출일자';
COMMENT ON COLUMN HRW_WITHHOLDING_HEADER.PRE_WITHHOLDING_NO IS '전월문서';
COMMENT ON COLUMN HRW_WITHHOLDING_HEADER.SOURCE_WITHHOLDING_NO IS '수정전문서번호';
COMMENT ON COLUMN HRW_WITHHOLDING_HEADER.DESCRIPTION IS '비고';
COMMENT ON COLUMN HRW_WITHHOLDING_HEADER.CLOSED_YN IS '마감여부';
COMMENT ON COLUMN HRW_WITHHOLDING_HEADER.CLOSED_DATE IS '마감일시';
COMMENT ON COLUMN HRW_WITHHOLDING_HEADER.CLOSED_PERSON_ID IS '마감 처리자';
COMMENT ON COLUMN HRW_WITHHOLDING_HEADER.CREATION_DATE  IS '생성일자';
COMMENT ON COLUMN HRW_WITHHOLDING_HEADER.CREATED_BY IS '생성자';
COMMENT ON COLUMN HRW_WITHHOLDING_HEADER.LAST_UPDATE_DATE IS '최종수정일자';
COMMENT ON COLUMN HRW_WITHHOLDING_HEADER.LAST_UPDATED_BY IS '최종수정자';

-- PK.
ALTER TABLE HRW_WITHHOLDING_HEADER ADD CONSTRAINTS HRW_WITHHOLDING_HEADER_PK PRIMARY KEY(WITHHOLDING_NO, SOB_ID, ORG_ID);
CREATE UNIQUE INDEX HRW_WITHHOLDING_HEADER_U1 ON HRW_WITHHOLDING_HEADER(WITHHOLDING_HEADER_ID) TABLESPACE FCM_TS_IDX;

CREATE INDEX HRW_WITHHOLDING_HEADER_N1 ON HRW_WITHHOLDING_HEADER(TO_CHAR(SUBMIT_DATE, 'YYYY'), SOB_ID, ORG_ID) TABLESPACE FCM_TS_IDX;
-- SEQUENCE
CREATE SEQUENCE HRW_WITHHOLDING_HEADER_S1;
-- ANALYZE.
ANALYZE TABLE HRW_WITHHOLDING_HEADER COMPUTE STATISTICS;
ANALYZE INDEX HRW_WITHHOLDING_HEADER_U1 COMPUTE STATISTICS;
