CREATE OR REPLACE PACKAGE GL_ACCOUNT_CONTROL_ITEM_G
AS

-- 회계 계정통제관리 조회.
  PROCEDURE SELECT_ACCOUNT_CONTROL_ITEM
            ( P_CURSOR               OUT TYPES.TCURSOR
            , W_ACCOUNT_CONTROL_ID   IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_CONTROL_ID%TYPE
            , W_ACCOUNT_DR_CR        IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_DR_CR%TYPE
            );

-- 회계 계정통제관리 삽입.
  PROCEDURE INSERT_ACCOUNT_CONTROL_ITEM
            ( P_ACCOUNT_CONTROL_ID IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_CONTROL_ID%TYPE
            , P_ACCOUNT_CODE       IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_CODE%TYPE
            , P_SOB_ID             IN GL_ACCOUNT_CONTROL_ITEM.SOB_ID%TYPE
            , P_ORG_ID             IN GL_ACCOUNT_CONTROL_ITEM.ORG_ID%TYPE
            , P_ACCOUNT_DR_CR      IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_DR_CR%TYPE
            , P_MANAGEMENT1_ID     IN GL_ACCOUNT_CONTROL_ITEM.MANAGEMENT1_ID%TYPE
            , P_MANAGEMENT2_ID     IN GL_ACCOUNT_CONTROL_ITEM.MANAGEMENT2_ID%TYPE
            , P_REFER1_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER1_ID%TYPE
            , P_REFER2_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER2_ID%TYPE
            , P_REFER3_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER3_ID%TYPE
            , P_REFER4_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER4_ID%TYPE
            , P_REFER5_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER5_ID%TYPE
            , P_REFER6_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER6_ID%TYPE
            , P_REFER7_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER7_ID%TYPE
            , P_REFER8_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER8_ID%TYPE
            , P_REFER9_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER9_ID%TYPE
            , P_REFER_RATE_ID      IN GL_ACCOUNT_CONTROL_ITEM.REFER_RATE_ID%TYPE
            , P_REFER_AMOUNT_ID    IN GL_ACCOUNT_CONTROL_ITEM.REFER_AMOUNT_ID%TYPE
            , P_REFER_DATE1_ID     IN GL_ACCOUNT_CONTROL_ITEM.REFER_DATE1_ID%TYPE
            , P_REFER_DATE2_ID     IN GL_ACCOUNT_CONTROL_ITEM.REFER_DATE2_ID%TYPE
            , P_VOUCH_ID           IN GL_ACCOUNT_CONTROL_ITEM.VOUCH_ID%TYPE
            , P_MANAGEMENT1_YN     IN GL_ACCOUNT_CONTROL_ITEM.MANAGEMENT1_YN%TYPE
            , P_MANAGEMENT2_YN     IN GL_ACCOUNT_CONTROL_ITEM.MANAGEMENT2_YN%TYPE
            , P_REFER1_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER1_YN%TYPE
            , P_REFER2_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER2_YN%TYPE
            , P_REFER3_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER3_YN%TYPE
            , P_REFER4_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER4_YN%TYPE
            , P_REFER5_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER5_YN%TYPE
            , P_REFER6_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER6_YN%TYPE
            , P_REFER7_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER7_YN%TYPE
            , P_REFER8_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER8_YN%TYPE
            , P_REFER9_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER9_YN%TYPE
            , P_REFER_RATE_YN      IN GL_ACCOUNT_CONTROL_ITEM.REFER_RATE_YN%TYPE
            , P_REFER_AMOUNT_YN    IN GL_ACCOUNT_CONTROL_ITEM.REFER_AMOUNT_YN%TYPE
            , P_REFER_DATE1_YN     IN GL_ACCOUNT_CONTROL_ITEM.REFER_DATE1_YN%TYPE
            , P_REFER_DATE2_YN     IN GL_ACCOUNT_CONTROL_ITEM.REFER_DATE2_YN%TYPE
            , P_VOUCH_YN           IN GL_ACCOUNT_CONTROL_ITEM.VOUCH_YN%TYPE
            , P_USER_ID            IN GL_ACCOUNT_CONTROL_ITEM.CREATED_BY%TYPE
            );

-- 회계 계정통제관리 수정.
  PROCEDURE UPDATE_ACCOUNT_CONTROL_ITEM
            ( W_ACCOUNT_CONTROL_ID IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_CONTROL_ID%TYPE
            , W_ACCOUNT_DR_CR      IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_DR_CR%TYPE
            , P_MANAGEMENT1_ID     IN GL_ACCOUNT_CONTROL_ITEM.MANAGEMENT1_ID%TYPE
            , P_MANAGEMENT2_ID     IN GL_ACCOUNT_CONTROL_ITEM.MANAGEMENT2_ID%TYPE
            , P_REFER1_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER1_ID%TYPE
            , P_REFER2_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER2_ID%TYPE
            , P_REFER3_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER3_ID%TYPE
            , P_REFER4_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER4_ID%TYPE
            , P_REFER5_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER5_ID%TYPE
            , P_REFER6_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER6_ID%TYPE
            , P_REFER7_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER7_ID%TYPE
            , P_REFER8_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER8_ID%TYPE
            , P_REFER9_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER9_ID%TYPE
            , P_REFER_RATE_ID      IN GL_ACCOUNT_CONTROL_ITEM.REFER_RATE_ID%TYPE
            , P_REFER_AMOUNT_ID    IN GL_ACCOUNT_CONTROL_ITEM.REFER_AMOUNT_ID%TYPE
            , P_REFER_DATE1_ID     IN GL_ACCOUNT_CONTROL_ITEM.REFER_DATE1_ID%TYPE
            , P_REFER_DATE2_ID     IN GL_ACCOUNT_CONTROL_ITEM.REFER_DATE2_ID%TYPE
            , P_VOUCH_ID           IN GL_ACCOUNT_CONTROL_ITEM.VOUCH_ID%TYPE
            , P_MANAGEMENT1_YN     IN GL_ACCOUNT_CONTROL_ITEM.MANAGEMENT1_YN%TYPE
            , P_MANAGEMENT2_YN     IN GL_ACCOUNT_CONTROL_ITEM.MANAGEMENT2_YN%TYPE
            , P_REFER1_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER1_YN%TYPE
            , P_REFER2_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER2_YN%TYPE
            , P_REFER3_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER3_YN%TYPE
            , P_REFER4_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER4_YN%TYPE
            , P_REFER5_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER5_YN%TYPE
            , P_REFER6_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER6_YN%TYPE
            , P_REFER7_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER7_YN%TYPE
            , P_REFER8_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER8_YN%TYPE
            , P_REFER9_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER9_YN%TYPE
            , P_REFER_RATE_YN      IN GL_ACCOUNT_CONTROL_ITEM.REFER_RATE_YN%TYPE
            , P_REFER_AMOUNT_YN    IN GL_ACCOUNT_CONTROL_ITEM.REFER_AMOUNT_YN%TYPE
            , P_REFER_DATE1_YN     IN GL_ACCOUNT_CONTROL_ITEM.REFER_DATE1_YN%TYPE
            , P_REFER_DATE2_YN     IN GL_ACCOUNT_CONTROL_ITEM.REFER_DATE2_YN%TYPE
            , P_VOUCH_YN           IN GL_ACCOUNT_CONTROL_ITEM.VOUCH_YN%TYPE
            , P_USER_ID            IN GL_ACCOUNT_CONTROL_ITEM.CREATED_BY%TYPE
            );

-- 회계 계정통제관리 삭제.
  PROCEDURE DELETE_ACCOUNT_CONTROL_ITEM
            ( W_ACCOUNT_CONTROL_ID IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_CONTROL_ID%TYPE
            , W_ACCOUNT_DR_CR      IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_DR_CR%TYPE 
            );
            
-- 회계 계정통제관리 Prompt조회.
  PROCEDURE SELECT_CONTROL_ITEM_PROMPT
            ( P_CURSOR3              OUT TYPES.TCURSOR3
            , W_ACCOUNT_CONTROL_ID   IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_CONTROL_ID%TYPE
            , W_ACCOUNT_DR_CR        IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_DR_CR%TYPE
            , W_SOB_ID               IN GL_ACCOUNT_CONTROL_ITEM.SOB_ID%TYPE
            );

---------------------------------------------------------------------------------------------------
-- 계정 통제관리항목 Lookup Type.
  FUNCTION CONTROL_ITEM_LOOKUP_TYPE_F
          ( W_ACCOUNT_CONTROL_ID  IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_CONTROL_ID%TYPE
          , W_ACCOUNT_DR_CR       IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_DR_CR%TYPE
          , W_MANAGEMENT_FIELD    IN VARCHAR2
          , W_SOB_ID              IN GL_ACCOUNT_CONTROL_ITEM.SOB_ID%TYPE
          ) RETURN VARCHAR2;
                        
-- 계정 통제관리항목 Lookup.
  PROCEDURE LU_CONTROL_ITEM_MANAGEMENT
            ( P_CURSOR3             OUT TYPES.TCURSOR3
            , W_ACCOUNT_CONTROL_ID  IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_CONTROL_ID%TYPE
            , W_ACCOUNT_DR_CR       IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_DR_CR%TYPE
            , W_MANAGEMENT_FIELD    IN VARCHAR2
            , W_SOB_ID              IN GL_ACCOUNT_CONTROL_ITEM.SOB_ID%TYPE
            , W_ENABLED_YN          IN VARCHAR2
            );

-- 계정 통제관리항목 필드값 DESCRIPTION.
  FUNCTION CONTROL_ITEM_DESC_F
          ( W_ACCOUNT_CONTROL_ID  IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_CONTROL_ID%TYPE
          , W_ACCOUNT_DR_CR       IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_DR_CR%TYPE
          , W_MANAGEMENT_FIELD    IN VARCHAR2
          , W_MANAGEMENT_VAULE    IN VARCHAR2
          , W_SOB_ID              IN GL_ACCOUNT_CONTROL_ITEM.SOB_ID%TYPE
          ) RETURN VARCHAR2;
            
END GL_ACCOUNT_CONTROL_ITEM_G;
/
CREATE OR REPLACE PACKAGE BODY GL_ACCOUNT_CONTROL_ITEM_G
AS
/******************************************************************************/
/* Project      : FPCB ERP
/* Module       : HR
/* Program Name : GL_ACCOUNT_CONTROL_ITEM_G
/* Description  : 회계 계정통제관리 관리.
/*
/* Reference by :
/* Program History :
/*------------------------------------------------------------------------------
/*   Date       In Charge          Description
/*------------------------------------------------------------------------------
/* 07-JUN-2010  Jeon Ho Su          Initialize
/******************************************************************************/
-- 회계 계정통제관리 조회.
  PROCEDURE SELECT_ACCOUNT_CONTROL_ITEM
            ( P_CURSOR               OUT TYPES.TCURSOR
            , W_ACCOUNT_CONTROL_ID   IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_CONTROL_ID%TYPE
            , W_ACCOUNT_DR_CR        IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_DR_CR%TYPE
            )
  AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT ACI.ACCOUNT_CONTROL_ID
           , ACI.ACCOUNT_CODE
           , ACI.SOB_ID
           , ACI.ORG_ID
           , ACI.ACCOUNT_DR_CR
           , ACI.MANAGEMENT1_ID
           , FI_COMMON_G.ID_NAME_F(ACI.MANAGEMENT1_ID) AS MANAGEMENT1_NAME
           , ACI.MANAGEMENT2_ID
           , FI_COMMON_G.ID_NAME_F(ACI.MANAGEMENT2_ID) AS MANAGEMENT2_NAME
           , ACI.REFER1_ID
           , FI_COMMON_G.ID_NAME_F(ACI.REFER1_ID) AS REFER1_NAME
           , ACI.REFER2_ID
           , FI_COMMON_G.ID_NAME_F(ACI.REFER2_ID) AS REFER2_NAME
           , ACI.REFER3_ID
           , FI_COMMON_G.ID_NAME_F(ACI.REFER3_ID) AS REFER3_NAME
           , ACI.REFER4_ID
           , FI_COMMON_G.ID_NAME_F(ACI.REFER4_ID) AS REFER4_NAME
           , ACI.REFER5_ID
           , FI_COMMON_G.ID_NAME_F(ACI.REFER5_ID) AS REFER5_NAME
           , ACI.REFER6_ID
           , FI_COMMON_G.ID_NAME_F(ACI.REFER6_ID) AS REFER6_NAME
           , ACI.REFER7_ID
           , FI_COMMON_G.ID_NAME_F(ACI.REFER7_ID) AS REFER7_NAME
           , ACI.REFER8_ID
           , FI_COMMON_G.ID_NAME_F(ACI.REFER8_ID) AS REFER8_NAME
           , ACI.REFER9_ID
           , FI_COMMON_G.ID_NAME_F(ACI.REFER9_ID) AS REFER9_NAME
           , ACI.REFER_RATE_ID
           , FI_COMMON_G.ID_NAME_F(ACI.REFER_RATE_ID) AS REFER_RATE_NAME
           , ACI.REFER_AMOUNT_ID
           , FI_COMMON_G.ID_NAME_F(ACI.REFER_AMOUNT_ID) AS REFER_AMOUNT_NAME
           , ACI.REFER_DATE1_ID
           , FI_COMMON_G.ID_NAME_F(ACI.REFER_DATE1_ID) AS REFER_DATE1_NAME
           , ACI.REFER_DATE2_ID
           , FI_COMMON_G.ID_NAME_F(ACI.REFER_DATE2_ID) AS REFER_DATE2_NAME
           , ACI.VOUCH_ID
           , FI_COMMON_G.ID_NAME_F(ACI.VOUCH_ID) AS VOUCH_NAME
           
           , ACI.MANAGEMENT1_YN
           , ACI.MANAGEMENT2_YN
           , ACI.REFER1_YN
           , ACI.REFER2_YN
           , ACI.REFER3_YN
           , ACI.REFER4_YN
           , ACI.REFER5_YN
           , ACI.REFER6_YN
           , ACI.REFER7_YN
           , ACI.REFER8_YN
           , ACI.REFER9_YN
           , ACI.REFER_RATE_YN
           , ACI.REFER_AMOUNT_YN
           , ACI.REFER_DATE1_YN
           , ACI.REFER_DATE2_YN
           , ACI.VOUCH_YN
        FROM GL_ACCOUNT_CONTROL_ITEM ACI
       WHERE ACI.ACCOUNT_CONTROL_ID     = W_ACCOUNT_CONTROL_ID
         AND ACI.ACCOUNT_DR_CR          = W_ACCOUNT_DR_CR
      ;

  END SELECT_ACCOUNT_CONTROL_ITEM;

-- 회계 계정통제관리 삽입.
  PROCEDURE INSERT_ACCOUNT_CONTROL_ITEM
            ( P_ACCOUNT_CONTROL_ID IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_CONTROL_ID%TYPE
            , P_ACCOUNT_CODE       IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_CODE%TYPE
            , P_SOB_ID             IN GL_ACCOUNT_CONTROL_ITEM.SOB_ID%TYPE
            , P_ORG_ID             IN GL_ACCOUNT_CONTROL_ITEM.ORG_ID%TYPE
            , P_ACCOUNT_DR_CR      IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_DR_CR%TYPE
            , P_MANAGEMENT1_ID     IN GL_ACCOUNT_CONTROL_ITEM.MANAGEMENT1_ID%TYPE
            , P_MANAGEMENT2_ID     IN GL_ACCOUNT_CONTROL_ITEM.MANAGEMENT2_ID%TYPE
            , P_REFER1_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER1_ID%TYPE
            , P_REFER2_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER2_ID%TYPE
            , P_REFER3_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER3_ID%TYPE
            , P_REFER4_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER4_ID%TYPE
            , P_REFER5_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER5_ID%TYPE
            , P_REFER6_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER6_ID%TYPE
            , P_REFER7_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER7_ID%TYPE
            , P_REFER8_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER8_ID%TYPE
            , P_REFER9_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER9_ID%TYPE
            , P_REFER_RATE_ID      IN GL_ACCOUNT_CONTROL_ITEM.REFER_RATE_ID%TYPE
            , P_REFER_AMOUNT_ID    IN GL_ACCOUNT_CONTROL_ITEM.REFER_AMOUNT_ID%TYPE
            , P_REFER_DATE1_ID     IN GL_ACCOUNT_CONTROL_ITEM.REFER_DATE1_ID%TYPE
            , P_REFER_DATE2_ID     IN GL_ACCOUNT_CONTROL_ITEM.REFER_DATE2_ID%TYPE
            , P_VOUCH_ID           IN GL_ACCOUNT_CONTROL_ITEM.VOUCH_ID%TYPE
            , P_MANAGEMENT1_YN     IN GL_ACCOUNT_CONTROL_ITEM.MANAGEMENT1_YN%TYPE
            , P_MANAGEMENT2_YN     IN GL_ACCOUNT_CONTROL_ITEM.MANAGEMENT2_YN%TYPE
            , P_REFER1_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER1_YN%TYPE
            , P_REFER2_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER2_YN%TYPE
            , P_REFER3_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER3_YN%TYPE
            , P_REFER4_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER4_YN%TYPE
            , P_REFER5_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER5_YN%TYPE
            , P_REFER6_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER6_YN%TYPE
            , P_REFER7_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER7_YN%TYPE
            , P_REFER8_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER8_YN%TYPE
            , P_REFER9_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER9_YN%TYPE
            , P_REFER_RATE_YN      IN GL_ACCOUNT_CONTROL_ITEM.REFER_RATE_YN%TYPE
            , P_REFER_AMOUNT_YN    IN GL_ACCOUNT_CONTROL_ITEM.REFER_AMOUNT_YN%TYPE
            , P_REFER_DATE1_YN     IN GL_ACCOUNT_CONTROL_ITEM.REFER_DATE1_YN%TYPE
            , P_REFER_DATE2_YN     IN GL_ACCOUNT_CONTROL_ITEM.REFER_DATE2_YN%TYPE
            , P_VOUCH_YN           IN GL_ACCOUNT_CONTROL_ITEM.VOUCH_YN%TYPE
            , P_USER_ID            IN GL_ACCOUNT_CONTROL_ITEM.CREATED_BY%TYPE
            )
  AS
    V_SYSDATE                    GL_ACCOUNT_CONTROL_ITEM.CREATION_DATE%TYPE;
    V_RECORD_COUNT               NUMBER := 0;

  BEGIN
    V_SYSDATE := GET_LOCAL_DATE(P_SOB_ID);
    V_RECORD_COUNT := 0;
    BEGIN
      SELECT COUNT(ACI.ACCOUNT_CONTROL_ID) AS RECORD_COUNT
        INTO V_RECORD_COUNT
        FROM GL_ACCOUNT_CONTROL_ITEM ACI
       WHERE ACI.ACCOUNT_CONTROL_ID     = P_ACCOUNT_CONTROL_ID
         AND ACI.ACCOUNT_DR_CR          = P_ACCOUNT_DR_CR
      ;
    EXCEPTION WHEN OTHERS THEN
      V_RECORD_COUNT := 0;
    END;
    IF V_RECORD_COUNT > 0 THEN
     RAISE ERRNUMS.Exist_Data;
    END IF;
-------------------------------------------------
    INSERT INTO GL_ACCOUNT_CONTROL_ITEM
    ( ACCOUNT_CONTROL_ID
    , ACCOUNT_CODE 
    , SOB_ID 
    , ORG_ID 
    , ACCOUNT_DR_CR 
    , MANAGEMENT1_ID 
    , MANAGEMENT2_ID 
    , REFER1_ID 
    , REFER2_ID 
    , REFER3_ID 
    , REFER4_ID 
    , REFER5_ID 
    , REFER6_ID 
    , REFER7_ID 
    , REFER8_ID 
    , REFER9_ID 
    , REFER_RATE_ID 
    , REFER_AMOUNT_ID 
    , REFER_DATE1_ID 
    , REFER_DATE2_ID 
    , VOUCH_ID 
    , MANAGEMENT1_YN 
    , MANAGEMENT2_YN 
    , REFER1_YN 
    , REFER2_YN 
    , REFER3_YN 
    , REFER4_YN 
    , REFER5_YN 
    , REFER6_YN 
    , REFER7_YN 
    , REFER8_YN 
    , REFER9_YN 
    , REFER_RATE_YN 
    , REFER_AMOUNT_YN 
    , REFER_DATE1_YN 
    , REFER_DATE2_YN 
    , VOUCH_YN 
    , CREATION_DATE 
    , CREATED_BY 
    , LAST_UPDATE_DATE 
    , LAST_UPDATED_BY )
    VALUES
    ( P_ACCOUNT_CONTROL_ID
    , P_ACCOUNT_CODE
    , P_SOB_ID
    , P_ORG_ID
    , P_ACCOUNT_DR_CR
    , P_MANAGEMENT1_ID
    , P_MANAGEMENT2_ID
    , P_REFER1_ID
    , P_REFER2_ID
    , P_REFER3_ID
    , P_REFER4_ID
    , P_REFER5_ID
    , P_REFER6_ID
    , P_REFER7_ID
    , P_REFER8_ID
    , P_REFER9_ID
    , P_REFER_RATE_ID
    , P_REFER_AMOUNT_ID
    , P_REFER_DATE1_ID
    , P_REFER_DATE2_ID
    , P_VOUCH_ID
    , P_MANAGEMENT1_YN
    , P_MANAGEMENT2_YN
    , P_REFER1_YN
    , P_REFER2_YN
    , P_REFER3_YN
    , P_REFER4_YN
    , P_REFER5_YN
    , P_REFER6_YN
    , P_REFER7_YN
    , P_REFER8_YN
    , P_REFER9_YN
    , P_REFER_RATE_YN
    , P_REFER_AMOUNT_YN
    , P_REFER_DATE1_YN
    , P_REFER_DATE2_YN
    , P_VOUCH_YN
    , V_SYSDATE
    , P_USER_ID
    , V_SYSDATE
    , P_USER_ID );

  EXCEPTION
    WHEN ERRNUMS.Exist_Data THEN
    RAISE_APPLICATION_ERROR(ERRNUMS.Exist_Data_Code, ERRNUMS.Exist_Data_Desc);
  END INSERT_ACCOUNT_CONTROL_ITEM;

-- 회계 계정통제관리 수정.
  PROCEDURE UPDATE_ACCOUNT_CONTROL_ITEM
            ( W_ACCOUNT_CONTROL_ID IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_CONTROL_ID%TYPE
            , W_ACCOUNT_DR_CR      IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_DR_CR%TYPE
            , P_MANAGEMENT1_ID     IN GL_ACCOUNT_CONTROL_ITEM.MANAGEMENT1_ID%TYPE
            , P_MANAGEMENT2_ID     IN GL_ACCOUNT_CONTROL_ITEM.MANAGEMENT2_ID%TYPE
            , P_REFER1_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER1_ID%TYPE
            , P_REFER2_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER2_ID%TYPE
            , P_REFER3_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER3_ID%TYPE
            , P_REFER4_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER4_ID%TYPE
            , P_REFER5_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER5_ID%TYPE
            , P_REFER6_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER6_ID%TYPE
            , P_REFER7_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER7_ID%TYPE
            , P_REFER8_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER8_ID%TYPE
            , P_REFER9_ID          IN GL_ACCOUNT_CONTROL_ITEM.REFER9_ID%TYPE
            , P_REFER_RATE_ID      IN GL_ACCOUNT_CONTROL_ITEM.REFER_RATE_ID%TYPE
            , P_REFER_AMOUNT_ID    IN GL_ACCOUNT_CONTROL_ITEM.REFER_AMOUNT_ID%TYPE
            , P_REFER_DATE1_ID     IN GL_ACCOUNT_CONTROL_ITEM.REFER_DATE1_ID%TYPE
            , P_REFER_DATE2_ID     IN GL_ACCOUNT_CONTROL_ITEM.REFER_DATE2_ID%TYPE
            , P_VOUCH_ID           IN GL_ACCOUNT_CONTROL_ITEM.VOUCH_ID%TYPE
            , P_MANAGEMENT1_YN     IN GL_ACCOUNT_CONTROL_ITEM.MANAGEMENT1_YN%TYPE
            , P_MANAGEMENT2_YN     IN GL_ACCOUNT_CONTROL_ITEM.MANAGEMENT2_YN%TYPE
            , P_REFER1_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER1_YN%TYPE
            , P_REFER2_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER2_YN%TYPE
            , P_REFER3_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER3_YN%TYPE
            , P_REFER4_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER4_YN%TYPE
            , P_REFER5_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER5_YN%TYPE
            , P_REFER6_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER6_YN%TYPE
            , P_REFER7_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER7_YN%TYPE
            , P_REFER8_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER8_YN%TYPE
            , P_REFER9_YN          IN GL_ACCOUNT_CONTROL_ITEM.REFER9_YN%TYPE
            , P_REFER_RATE_YN      IN GL_ACCOUNT_CONTROL_ITEM.REFER_RATE_YN%TYPE
            , P_REFER_AMOUNT_YN    IN GL_ACCOUNT_CONTROL_ITEM.REFER_AMOUNT_YN%TYPE
            , P_REFER_DATE1_YN     IN GL_ACCOUNT_CONTROL_ITEM.REFER_DATE1_YN%TYPE
            , P_REFER_DATE2_YN     IN GL_ACCOUNT_CONTROL_ITEM.REFER_DATE2_YN%TYPE
            , P_VOUCH_YN           IN GL_ACCOUNT_CONTROL_ITEM.VOUCH_YN%TYPE
            , P_USER_ID            IN GL_ACCOUNT_CONTROL_ITEM.CREATED_BY%TYPE
            )
  AS
  BEGIN
    UPDATE GL_ACCOUNT_CONTROL_ITEM
      SET MANAGEMENT1_ID     = P_MANAGEMENT1_ID
        , MANAGEMENT2_ID     = P_MANAGEMENT2_ID
        , REFER1_ID          = P_REFER1_ID
        , REFER2_ID          = P_REFER2_ID
        , REFER3_ID          = P_REFER3_ID
        , REFER4_ID          = P_REFER4_ID
        , REFER5_ID          = P_REFER5_ID
        , REFER6_ID          = P_REFER6_ID
        , REFER7_ID          = P_REFER7_ID
        , REFER8_ID          = P_REFER8_ID
        , REFER9_ID          = P_REFER9_ID
        , REFER_RATE_ID      = P_REFER_RATE_ID
        , REFER_AMOUNT_ID    = P_REFER_AMOUNT_ID
        , REFER_DATE1_ID     = P_REFER_DATE1_ID
        , REFER_DATE2_ID     = P_REFER_DATE2_ID
        , VOUCH_ID           = P_VOUCH_ID
        , MANAGEMENT1_YN     = P_MANAGEMENT1_YN
        , MANAGEMENT2_YN     = P_MANAGEMENT2_YN
        , REFER1_YN          = P_REFER1_YN
        , REFER2_YN          = P_REFER2_YN
        , REFER3_YN          = P_REFER3_YN
        , REFER4_YN          = P_REFER4_YN
        , REFER5_YN          = P_REFER5_YN
        , REFER6_YN          = P_REFER6_YN
        , REFER7_YN          = P_REFER7_YN
        , REFER8_YN          = P_REFER8_YN
        , REFER9_YN          = P_REFER9_YN
        , REFER_RATE_YN      = P_REFER_RATE_YN
        , REFER_AMOUNT_YN    = P_REFER_AMOUNT_YN
        , REFER_DATE1_YN     = P_REFER_DATE1_YN
        , REFER_DATE2_YN     = P_REFER_DATE2_YN
        , VOUCH_YN           = P_VOUCH_YN
        , LAST_UPDATE_DATE   = GET_LOCAL_DATE(SOB_ID)
        , LAST_UPDATED_BY    = P_USER_ID
    WHERE ACCOUNT_CONTROL_ID = W_ACCOUNT_CONTROL_ID
      AND ACCOUNT_DR_CR      = W_ACCOUNT_DR_CR;
      
  END UPDATE_ACCOUNT_CONTROL_ITEM;

-- 회계 계정통제관리 삭제.
  PROCEDURE DELETE_ACCOUNT_CONTROL_ITEM
            ( W_ACCOUNT_CONTROL_ID IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_CONTROL_ID%TYPE
            , W_ACCOUNT_DR_CR      IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_DR_CR%TYPE 
            )
  AS
  BEGIN
    DELETE GL_ACCOUNT_CONTROL_ITEM
    WHERE ACCOUNT_CONTROL_ID = W_ACCOUNT_CONTROL_ID
      AND ACCOUNT_DR_CR      = W_ACCOUNT_DR_CR
   ;
  
  END DELETE_ACCOUNT_CONTROL_ITEM;

-- 회계 계정통제관리 Prompt조회.
  PROCEDURE SELECT_CONTROL_ITEM_PROMPT
            ( P_CURSOR3              OUT TYPES.TCURSOR3
            , W_ACCOUNT_CONTROL_ID   IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_CONTROL_ID%TYPE
            , W_ACCOUNT_DR_CR        IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_DR_CR%TYPE
            , W_SOB_ID               IN GL_ACCOUNT_CONTROL_ITEM.SOB_ID%TYPE
            )
  AS 
  BEGIN
    OPEN P_CURSOR3 FOR     
      SELECT ACI.MANAGEMENT1_ID
           , FI_COMMON_G.ID_NAME_F(ACI.MANAGEMENT1_ID) AS MANAGEMENT1_NAME
           , DECODE(ACI.MANAGEMENT1_ID, NULL, 'F', NVL(ACI.MANAGEMENT1_YN, 'N')) AS MANAGEMENT1_YN
           , NVL(FI_COMMON_G.ID_VALUE_F(ACI.MANAGEMENT1_ID, 'VALUE2'), 'N') AS MANAGEMENT1_LOOKUP_YN
           , ACI.MANAGEMENT2_ID
           , FI_COMMON_G.ID_NAME_F(ACI.MANAGEMENT2_ID) AS MANAGEMENT2_NAME
           , DECODE(ACI.MANAGEMENT2_ID, NULL, 'F', NVL(ACI.MANAGEMENT2_YN, 'N')) AS MANAGEMENT2_YN
           , NVL(FI_COMMON_G.ID_VALUE_F(ACI.MANAGEMENT2_ID, 'VALUE2'), 'N') AS MANAGEMENT2_LOOKUP_YN
           , ACI.REFER1_ID
           , FI_COMMON_G.ID_NAME_F(ACI.REFER1_ID) AS REFER1_NAME
           , DECODE(ACI.REFER1_ID, NULL, 'F', NVL(ACI.REFER1_YN, 'N')) AS REFER1_YN
           , NVL(FI_COMMON_G.ID_VALUE_F(ACI.REFER1_ID, 'VALUE2'), 'N') AS REFER1_LOOKUP_YN
           , ACI.REFER2_ID
           , FI_COMMON_G.ID_NAME_F(ACI.REFER2_ID) AS REFER2_NAME
           , DECODE(ACI.REFER2_ID, NULL, 'F', NVL(ACI.REFER2_YN, 'N')) AS REFER2_YN
           , NVL(FI_COMMON_G.ID_VALUE_F(ACI.REFER2_ID, 'VALUE2'), 'N') AS REFER2_LOOKUP_YN
           , ACI.REFER3_ID
           , FI_COMMON_G.ID_NAME_F(ACI.REFER3_ID) AS REFER3_NAME
           , DECODE(ACI.REFER3_ID, NULL, 'F', NVL(ACI.REFER3_YN, 'N')) AS REFER3_YN
           , NVL(FI_COMMON_G.ID_VALUE_F(ACI.REFER3_ID, 'VALUE2'), 'N') AS REFER3_LOOKUP_YN
           , ACI.REFER4_ID
           , FI_COMMON_G.ID_NAME_F(ACI.REFER4_ID) AS REFER4_NAME
           , DECODE(ACI.REFER4_ID, NULL, 'F', NVL(ACI.REFER4_YN, 'N')) AS REFER4_YN
           , NVL(FI_COMMON_G.ID_VALUE_F(ACI.REFER4_ID, 'VALUE2'), 'N') AS REFER4_LOOKUP_YN
           , ACI.REFER5_ID
           , FI_COMMON_G.ID_NAME_F(ACI.REFER5_ID) AS REFER5_NAME
           , DECODE(ACI.REFER5_ID, NULL, 'F', NVL(ACI.REFER5_YN, 'N')) AS REFER5_YN
           , NVL(FI_COMMON_G.ID_VALUE_F(ACI.REFER5_ID, 'VALUE2'), 'N') AS REFER5_LOOKUP_YN
           , ACI.REFER6_ID
           , FI_COMMON_G.ID_NAME_F(ACI.REFER6_ID) AS REFER6_NAME
           , DECODE(ACI.REFER6_ID, NULL, 'F', NVL(ACI.REFER6_YN, 'N')) AS REFER6_YN
           , NVL(FI_COMMON_G.ID_VALUE_F(ACI.REFER6_ID, 'VALUE2'), 'N') AS REFER6_LOOKUP_YN
           , ACI.REFER7_ID
           , FI_COMMON_G.ID_NAME_F(ACI.REFER7_ID) AS REFER7_NAME
           , DECODE(ACI.REFER7_ID, NULL, 'F', NVL(ACI.REFER7_YN, 'N')) AS REFER7_YN
           , NVL(FI_COMMON_G.ID_VALUE_F(ACI.REFER7_ID, 'VALUE2'), 'N') AS REFER7_LOOKUP_YN
           , ACI.REFER8_ID
           , FI_COMMON_G.ID_NAME_F(ACI.REFER8_ID) AS REFER8_NAME
           , DECODE(ACI.REFER8_ID, NULL, 'F', NVL(ACI.REFER8_YN, 'N')) AS REFER8_YN
           , NVL(FI_COMMON_G.ID_VALUE_F(ACI.REFER8_ID, 'VALUE2'), 'N') AS REFER8_LOOKUP_YN
           , ACI.REFER9_ID
           , FI_COMMON_G.ID_NAME_F(ACI.REFER9_ID) AS REFER9_NAME
           , DECODE(ACI.REFER9_ID, NULL, 'F', NVL(ACI.REFER9_YN, 'N')) AS REFER9_YN
           , NVL(FI_COMMON_G.ID_VALUE_F(ACI.REFER9_ID, 'VALUE2'), 'N') AS REFER9_LOOKUP_YN
           , ACI.REFER_RATE_ID
           , FI_COMMON_G.ID_NAME_F(ACI.REFER_RATE_ID) AS REFER_RATE_NAME
           , DECODE(ACI.REFER_RATE_ID, NULL, 'F', NVL(ACI.REFER_RATE_YN, 'N')) AS REFER_RATE_YN
           , ACI.REFER_AMOUNT_ID
           , FI_COMMON_G.ID_NAME_F(ACI.REFER_AMOUNT_ID) AS REFER_AMOUNT_NAME
           , DECODE(ACI.REFER_AMOUNT_ID, NULL, 'F', NVL(ACI.REFER_AMOUNT_YN, 'N')) AS REFER_AMOUNT_YN
           , ACI.REFER_DATE1_ID
           , FI_COMMON_G.ID_NAME_F(ACI.REFER_DATE1_ID) AS REFER_DATE1_NAME
           , DECODE(ACI.REFER_DATE1_ID, NULL, 'F', NVL(ACI.REFER_DATE1_YN, 'N')) AS REFER_DATE1_YN
           , ACI.REFER_DATE2_ID
           , FI_COMMON_G.ID_NAME_F(ACI.REFER_DATE2_ID) AS REFER_DATE2_NAME
           , DECODE(ACI.REFER_DATE2_ID, NULL, 'F', NVL(ACI.REFER_DATE2_YN, 'N')) AS REFER_DATE2_YN
           , ACI.VOUCH_ID
           , FI_COMMON_G.ID_NAME_F(ACI.VOUCH_ID) AS VOUCH_NAME
           , NVL(ACI.VOUCH_YN, 'F') AS VOUCH_YN
           , ACI.ACCOUNT_CONTROL_ID
           , ACI.ACCOUNT_CODE
           , ACI.ACCOUNT_DR_CR
        FROM GL_ACCOUNT_CONTROL_ITEM ACI
       WHERE ACI.ACCOUNT_CONTROL_ID         = W_ACCOUNT_CONTROL_ID
         AND ACI.ACCOUNT_DR_CR              = W_ACCOUNT_DR_CR
         AND ACI.SOB_ID                     = W_SOB_ID
      ;
  
  EXCEPTION WHEN OTHERS THEN
    NULL;
  END SELECT_CONTROL_ITEM_PROMPT;

---------------------------------------------------------------------------------------------------
-- 계정 잔액관리항목 Lookup Type.
  FUNCTION CONTROL_ITEM_LOOKUP_TYPE_F
          ( W_ACCOUNT_CONTROL_ID  IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_CONTROL_ID%TYPE
          , W_ACCOUNT_DR_CR       IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_DR_CR%TYPE
          , W_MANAGEMENT_FIELD    IN VARCHAR2
          , W_SOB_ID              IN GL_ACCOUNT_CONTROL_ITEM.SOB_ID%TYPE
          ) RETURN VARCHAR2
  AS
    V_LOOKUP_TYPE                   FI_COMMON.VALUE1%TYPE := NULL;
    V_STRING                        VARCHAR2(1000) := NULL;
    
  BEGIN
    -- LOOKUP 타입 조회.
    BEGIN
      V_STRING := ' SELECT FC.VALUE3
                      FROM FI_COMMON FC
                     WHERE FC.SOB_ID                  = ' || W_SOB_ID || '
                       AND EXISTS ( SELECT ''X''
                                      FROM GL_ACCOUNT_CONTROL_ITEM ACI
                                     WHERE ACI.' || W_MANAGEMENT_FIELD || '         = FC.COMMON_ID
                                       AND ACI.ACCOUNT_CONTROL_ID     = ' || W_ACCOUNT_CONTROL_ID || '
                                       AND ACI.ACCOUNT_DR_CR          = ''' || W_ACCOUNT_DR_CR || '''
                                       AND ACI.SOB_ID                 = ' || W_SOB_ID || '
                                  )';
      EXECUTE IMMEDIATE V_STRING
        INTO V_LOOKUP_TYPE;
    EXCEPTION WHEN OTHERS THEN
      V_LOOKUP_TYPE := NULL;
    END;
    RETURN V_LOOKUP_TYPE;
  
  END CONTROL_ITEM_LOOKUP_TYPE_F;
  
-- 계정 잔액관리항목 Lookup.
  PROCEDURE LU_CONTROL_ITEM_MANAGEMENT
            ( P_CURSOR3             OUT TYPES.TCURSOR3
            , W_ACCOUNT_CONTROL_ID  IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_CONTROL_ID%TYPE
            , W_ACCOUNT_DR_CR       IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_DR_CR%TYPE
            , W_MANAGEMENT_FIELD    IN VARCHAR2
            , W_SOB_ID              IN GL_ACCOUNT_CONTROL_ITEM.SOB_ID%TYPE
            , W_ENABLED_YN          IN VARCHAR2
            )
  AS
    V_STD_DATE                       DATE := NULL;
    V_LOOKUP_TYPE                   FI_COMMON.VALUE1%TYPE := NULL;
    
  BEGIN
    IF W_ENABLED_YN = 'Y' THEN
      V_STD_DATE := GET_LOCAL_DATE(W_SOB_ID);
    END IF;
    
    -- LOOKUP 타입 조회.
    V_LOOKUP_TYPE := CONTROL_ITEM_LOOKUP_TYPE_F ( W_ACCOUNT_CONTROL_ID => W_ACCOUNT_CONTROL_ID
                                                , W_ACCOUNT_DR_CR => W_ACCOUNT_DR_CR
                                                , W_MANAGEMENT_FIELD => W_MANAGEMENT_FIELD
                                                , W_SOB_ID => W_SOB_ID
                                                );
    IF V_LOOKUP_TYPE = 'BANK' THEN
      OPEN P_CURSOR3 FOR
        SELECT FB.BANK_NAME AS MANAGEMENT_NAME
             , FB.BANK_CODE AS MANAGEMENT_CODE
          FROM FI_BANK FB
         WHERE FB.BANK_GROUP              <> '-'
           AND FB.ENABLED_FLAG            = DECODE(W_ENABLED_YN, 'Y', 'Y', FB.ENABLED_FLAG)
           AND FB.EFFECTIVE_DATE_FR       <= NVL(V_STD_DATE, FB.EFFECTIVE_DATE_FR)
           AND (FB.EFFECTIVE_DATE_TO IS NULL OR FB.EFFECTIVE_DATE_TO >= NVL(V_STD_DATE, FB.EFFECTIVE_DATE_TO))
           AND FB.SOB_ID                  = W_SOB_ID
        ;
    
    ELSIF V_LOOKUP_TYPE = 'BANK_ACCOUNT' THEN
      OPEN P_CURSOR3 FOR
        SELECT BA.BANK_ACCOUNT_NAME || '(' || FB.BANK_NAME || ')' AS MANAGEMENT_NAME
             , BA.BANK_ACCOUNT_NUM AS MANAGEMENT_CODE
          FROM FI_BANK_ACCOUNT_TLV BA
             , FI_BANK FB
         WHERE BA.BANK_ID                 = FB.BANK_ID
           /*AND BA.BANK_ID                 = NVL(W_BANK_ID, BA.BANK_ID)*/
           AND BA.SOB_ID                  = W_SOB_ID
           AND BA.ENABLED_FLAG            = DECODE(W_ENABLED_YN, 'Y', 'Y', BA.ENABLED_FLAG)
           AND BA.EFFECTIVE_DATE_FR       <= NVL(V_STD_DATE, BA.EFFECTIVE_DATE_FR)
           AND (BA.EFFECTIVE_DATE_TO IS NULL OR BA.EFFECTIVE_DATE_TO >= NVL(V_STD_DATE, BA.EFFECTIVE_DATE_TO))
        ;
    ELSE
      OPEN P_CURSOR3 FOR
        SELECT NULL AS MANAGEMENT_NAME
             , NULL AS MANAGEMENT_CODE
          FROM DUAL
        ;
    END IF;

  END LU_CONTROL_ITEM_MANAGEMENT;

-- 계정 통제관리항목 필드값 DESCRIPTION.
  FUNCTION CONTROL_ITEM_DESC_F
          ( W_ACCOUNT_CONTROL_ID  IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_CONTROL_ID%TYPE
          , W_ACCOUNT_DR_CR       IN GL_ACCOUNT_CONTROL_ITEM.ACCOUNT_DR_CR%TYPE
          , W_MANAGEMENT_FIELD    IN VARCHAR2
          , W_MANAGEMENT_VAULE    IN VARCHAR2
          , W_SOB_ID              IN GL_ACCOUNT_CONTROL_ITEM.SOB_ID%TYPE
          ) RETURN VARCHAR2
  AS
    V_LOOKUP_TYPE                 FI_COMMON.VALUE1%TYPE := NULL;
    V_CONTROL_ITEM_DESC           VARCHAR2(200) := NULL;
    
  BEGIN
    -- LOOKUP 타입 조회.
    V_LOOKUP_TYPE := CONTROL_ITEM_LOOKUP_TYPE_F ( W_ACCOUNT_CONTROL_ID => W_ACCOUNT_CONTROL_ID
                                                , W_ACCOUNT_DR_CR => W_ACCOUNT_DR_CR
                                                , W_MANAGEMENT_FIELD => W_MANAGEMENT_FIELD
                                                , W_SOB_ID => W_SOB_ID
                                                );
     V_CONTROL_ITEM_DESC := NULL;
    IF V_LOOKUP_TYPE = 'BANK' THEN
      BEGIN
        SELECT FB.BANK_NAME AS MANAGEMENT_NAME
          INTO V_CONTROL_ITEM_DESC
          FROM FI_BANK FB
         WHERE FB.BANK_GROUP              <> '-'
           AND FB.BANK_CODE               = W_MANAGEMENT_VAULE
           AND FB.SOB_ID                  = W_SOB_ID
        ;
      EXCEPTION WHEN OTHERS THEN
        NULL;
      END;
    ELSIF V_LOOKUP_TYPE = 'BANK_ACCOUNT' THEN
      BEGIN
        SELECT BA.BANK_ACCOUNT_NAME || '(' || FB.BANK_NAME || ')' AS MANAGEMENT_NAME
          INTO V_CONTROL_ITEM_DESC
          FROM FI_BANK_ACCOUNT_TLV BA
             , FI_BANK FB
         WHERE BA.BANK_ID                 = FB.BANK_ID
           AND BA.BANK_ACCOUNT_NUM        = W_MANAGEMENT_VAULE
           AND BA.SOB_ID                  = W_SOB_ID
        ;
      EXCEPTION WHEN OTHERS THEN
        NULL;
      END;
    ELSE
      NULL;
    END IF;
    RETURN V_CONTROL_ITEM_DESC;
    
  END CONTROL_ITEM_DESC_F;
    
END GL_ACCOUNT_CONTROL_ITEM_G;
/
