CREATE OR REPLACE FUNCTION ISGETDATE
          ( P_VALUE               IN VARCHAR2
          ) RETURN VARCHAR2
AS
  V_STRING_DATE                   VARCHAR(100);
  V_DATE                          DATE;
BEGIN
  BEGIN
    V_STRING_DATE := SUBSTR(P_VALUE, 1, 10);
    SELECT TO_DATE(V_STRING_DATE, 'YYYY-MM-DD')
      INTO V_DATE
      FROM DUAL;
  EXCEPTION WHEN OTHERS THEN
    V_STRING_DATE := P_VALUE;
  END;
  RETURN V_STRING_DATE;
END ISGETDATE;
/
