-- 계정그룹 조회.
SELECT AG.ACCOUNT_GROUP_ID
     , AG.ACCOUNT_SET_ID
     , AG.SEGMENT1_CODE
     , AG.SEGMENT1_DESC
     , AG.SEGMENT2_CODE
     , AG.SEGMENT2_DESC
     , AG.SEGMENT3_CODE
     , AG.SEGMENT3_DESC
     , AG.SEGMENT4_CODE
     , AG.SEGMENT4_DESC
     , AG.SEGMENT5_CODE
     , AG.SEGMENT5_DESC
     , AG.SEGMENT6_CODE
     , AG.SEGMENT6_DESC
     , AG.SEGMENT7_CODE
     , AG.SEGMENT7_DESC
     , AG.SEGMENT8_CODE
     , AG.SEGMENT8_DESC
     , AG.SEGMENT9_CODE
     , AG.SEGMENT9_DESC
     , AG.SEGMENT10_CODE
     , AG.SEGMENT10_DESC
     , AG.ACCOUNT_CODE
     , AG.ACCOUNT_DESC
     , AG.ENABLED_FLAG
     , AG.EFFECTIVE_DATE_FR
     , AG.EFFECTIVE_DATE_TO
  FROM FI_ACCOUNT_GROUP AG
 WHERE AG.ACCOUNT_SET_ID          = &W_ACCOUNT_SET_ID
   AND AG.ACCOUNT_CODE            = NVL(&W_ACCOUNT_CODE, AG.ACCOUNT_CODE)
ORDER BY AG.ACCOUNT_CODE
;

-- 계정통제 조회.
SELECT AC.ACCOUNT_CONTROL_ID
     , AC.ACCOUNT_CODE
     , AC.ACCOUNT_DESC
     , AC.ACCOUNT_DESC_S
     , AC.ACCOUNT_SET_ID
     , AC.ACCOUNT_GROUP_ID
     , AC.ACCOUNT_DR_CR
     , FI_COMMON_G.CODE_NAME_F('ACCOUNT_DR_CR', AC.ACCOUNT_DR_CR, AC.SOB_ID) AS ACCOUNT_DR_CR_NAME
     , AC.ACCOUNT_GL_ID
     , FI_COMMON_G.ID_NAME_F(AC.ACCOUNT_GL_ID) AS ACCOUNT_GL_NAME
     , AC.ACCOUNT_FS_TYPE
     , FI_COMMON_G.CODE_NAME_F('FS_TYPE', AC.ACCOUNT_FS_TYPE, AC.SOB_ID) AS ACCOUNT_FS_TYPE_NAME
     , AC.CUSTOMER_ENABLED_FLAG
     , AC.ACCOUNT_ENABLED_FLAG
     , AC.BANK_ACCOUNT_FLAG
     , AC.CURRENCY_ENABLED_FLAG
     , AC.ACCOUNT_MICH_YN
     , AC.VAT_ENABLED_FLAG
     , AC.BUDGET_ENABLED_FLAG
     , AC.BUDGET_CONTROL_FLAG
     , AC.BUDGET_BELONG_FLAG
     , AC.COST_CENTER_FLAG
     , AC.LIQUIDATE_METHOD_TYPE
     , FI_COMMON_G.CODE_NAME_F('LIQUIDATE_METHOD_TYPE', AC.LIQUIDATE_METHOD_TYPE, AC.SOB_ID) AS LIQUIDATE_METHOD_TYPE_NAME
     , AC.ACCOUNT_CLASS_ID
     , FI_COMMON_G.ID_NAME_F(AC.ACCOUNT_CLASS_ID) AS ACCOUNT_CLASS_NAME
     , AC.REMARK
     , AC.ENABLED_FLAG 
     , AC.EFFECTIVE_DATE_FR
     , AC.EFFECTIVE_DATE_TO
  FROM FI_ACCOUNT_CONTROL AC
 WHERE AC.ACCOUNT_SET_ID          = &W_ACCOUNT_SET_ID
   AND AC.ACCOUNT_GROUP_ID        = NVL(&W_ACCOUNT_GROUP_ID, AC.ACCOUNT_GROUP_ID)
   AND AC.SOB_ID                  = &W_SOB_ID
ORDER BY AC.ACCOUNT_CODE   
;

-- 관리항목 조회.
SELECT ACI.ACCOUNT_CONTROL_ID
     , ACI.ACCOUNT_CODE
     , AC.ACCOUNT_DESC
     , ACI.SOB_ID
     , ACI.ORG_ID
     , ACI.ACCOUNT_DR_CR
     , ACI.MANAGEMENT1_ID
     , FI_COMMON_G.ID_NAME_F(ACI.MANAGEMENT1_ID) AS MANAGEMENT1_NAME
     , ACI.MANAGEMENT2_ID
     , FI_COMMON_G.ID_NAME_F(ACI.MANAGEMENT2_ID) AS MANAGEMENT2_NAME
     , ACI.REFER1_ID
     , FI_COMMON_G.ID_NAME_F(ACI.REFER1_ID) AS REFER1_NAME
     , ACI.REFER2_ID
     , FI_COMMON_G.ID_NAME_F(ACI.REFER2_ID) AS REFER2_NAME
     , ACI.REFER3_ID
     , FI_COMMON_G.ID_NAME_F(ACI.REFER3_ID) AS REFER3_NAME
     , ACI.REFER4_ID
     , FI_COMMON_G.ID_NAME_F(ACI.REFER4_ID) AS REFER4_NAME
     , ACI.REFER5_ID
     , FI_COMMON_G.ID_NAME_F(ACI.REFER5_ID) AS REFER5_NAME
     , ACI.REFER6_ID
     , FI_COMMON_G.ID_NAME_F(ACI.REFER6_ID) AS REFER6_NAME
     , ACI.REFER7_ID
     , FI_COMMON_G.ID_NAME_F(ACI.REFER7_ID) AS REFER7_NAME
     , ACI.REFER8_ID
     , FI_COMMON_G.ID_NAME_F(ACI.REFER8_ID) AS REFER8_NAME
     , ACI.REFER9_ID
     , FI_COMMON_G.ID_NAME_F(ACI.REFER9_ID) AS REFER9_NAME
     , ACI.REFER_RATE_ID
     , FI_COMMON_G.ID_NAME_F(ACI.REFER_RATE_ID) AS REFER_RATE_NAME
     , ACI.REFER_AMOUNT_ID
     , FI_COMMON_G.ID_NAME_F(ACI.REFER_AMOUNT_ID) AS REFER_AMOUNT_NAME
     , ACI.REFER_DATE1_ID
     , FI_COMMON_G.ID_NAME_F(ACI.REFER_DATE1_ID) AS REFER_DATE1_NAME
     , ACI.REFER_DATE2_ID
     , FI_COMMON_G.ID_NAME_F(ACI.REFER_DATE2_ID) AS REFER_DATE2_NAME
     , ACI.VOUCH_ID
     , FI_COMMON_G.ID_NAME_F(ACI.VOUCH_ID) AS VOUCH_NAME
     , ACI.MANAGEMENT1_YN
     , ACI.MANAGEMENT2_YN
     , ACI.REFER1_YN
     , ACI.REFER2_YN
     , ACI.REFER3_YN
     , ACI.REFER4_YN
     , ACI.REFER5_YN
     , ACI.REFER6_YN
     , ACI.REFER7_YN
     , ACI.REFER8_YN
     , ACI.REFER9_YN
     , ACI.REFER_RATE_YN
     , ACI.REFER_AMOUNT_YN
     , ACI.REFER_DATE1_YN
     , ACI.REFER_DATE2_YN
     , ACI.VOUCH_YN
  FROM FI_ACCOUNT_CONTROL_ITEM ACI
    , FI_ACCOUNT_CONTROL AC
  WHERE ACI.ACCOUNT_CONTROL_ID     = AC.ACCOUNT_CONTROL_ID
   AND ACI.SOB_ID                 = AC.SOB_ID
   AND AC.ACCOUNT_SET_ID          = &W_ACCOUNT_SET_ID
   AND ACI.SOB_ID                 = &W_SOB_ID
ORDER BY ACI.ACCOUNT_CODE
;
