CREATE OR REPLACE VIEW HRM_PAY_TYPE_V AS
SELECT HC.COMMON_ID AS PAY_TYPE_ID
     , HC.CODE AS PAY_TYPE
     , HC.CODE_NAME AS PAY_TYPE_NAME
     , HC.VALUE1 AS PAY_LEVEL
     , NVL(TO_NUMBER(HC.VALUE2), 0) AS GENERAL_HOURLY_TIME
     , HC.VALUE3 AS DAY_RATE_METHOD
     , HC.VALUE4
     , HC.VALUE5
     , HC.VALUE6
     , HC.VALUE7
     , HC.VALUE8
		 , HC.VALUE9
		 , HC.VALUE10
		 , HC.DEFAULT_FLAG
		 , HC.SORT_NUM
		 , HC.DESCRIPTION
		 , HC.ENABLED_FLAG
		 , HC.EFFECTIVE_DATE_FR
		 , HC.EFFECTIVE_DATE_TO
		 , HC.SOB_ID
		 , HC.ORG_ID
  FROM HRM_COMMON_TLV HC
 WHERE HC.GROUP_CODE            = 'PAY_TYPE';
