CREATE OR REPLACE PACKAGE HRT_PAYMENT_ADD_ALLOWANCE_G
AS

-- ADD_ALLOWANCE SELECT
  PROCEDURE DATA_SELECT
            ( P_CURSOR                            OUT TYPES.TCURSOR
            , W_CORP_ID                           IN HRT_PAYMENT_ADD_ALLOWANCE.CORP_ID%TYPE
            , W_PAY_YYYYMM                        IN HRT_PAYMENT_ADD_ALLOWANCE.PAY_YYYYMM%TYPE
            , W_WAGE_TYPE                         IN HRT_PAYMENT_ADD_ALLOWANCE.WAGE_TYPE%TYPE
            , W_ALLOWANCE_ID                      IN HRT_PAYMENT_ADD_ALLOWANCE.ALLOWANCE_ID%TYPE
            , W_PERSON_ID                         IN HRT_PAYMENT_ADD_ALLOWANCE.PERSON_ID%TYPE
            , W_SOB_ID                            IN HRT_PAYMENT_ADD_ALLOWANCE.SOB_ID%TYPE
            , W_ORG_ID                            IN HRT_PAYMENT_ADD_ALLOWANCE.ORG_ID%TYPE
            );

---------------------------------------------------------------------------------------------------
-- ADD_ALLOWANCE_INSERT
  PROCEDURE ADD_ALLOWANCE_INSERT
            ( P_ADD_ALLOWANCE_ID OUT HRT_PAYMENT_ADD_ALLOWANCE.ADD_ALLOWANCE_ID%TYPE
            , P_PERSON_ID        IN HRT_PAYMENT_ADD_ALLOWANCE.PERSON_ID%TYPE
            , P_CORP_ID          IN HRT_PAYMENT_ADD_ALLOWANCE.CORP_ID%TYPE
            , P_PAY_YYYYMM       IN HRT_PAYMENT_ADD_ALLOWANCE.PAY_YYYYMM%TYPE
            , P_WAGE_TYPE        IN HRT_PAYMENT_ADD_ALLOWANCE.WAGE_TYPE%TYPE
            , P_ALLOWANCE_ID     IN HRT_PAYMENT_ADD_ALLOWANCE.ALLOWANCE_ID%TYPE
            , P_ALLOWANCE_AMOUNT IN HRT_PAYMENT_ADD_ALLOWANCE.ALLOWANCE_AMOUNT%TYPE
            , P_TAX_YN           IN HRT_PAYMENT_ADD_ALLOWANCE.TAX_YN%TYPE
            , P_HIRE_INSUR_YN    IN HRT_PAYMENT_ADD_ALLOWANCE.HIRE_INSUR_YN%TYPE
            , P_CREATED_FLAG     IN HRT_PAYMENT_ADD_ALLOWANCE.CREATED_FLAG%TYPE
            , P_DESCRIPTION      IN HRT_PAYMENT_ADD_ALLOWANCE.DESCRIPTION%TYPE
            , P_SOB_ID           IN HRT_PAYMENT_ADD_ALLOWANCE.SOB_ID%TYPE
            , P_ORG_ID           IN HRT_PAYMENT_ADD_ALLOWANCE.ORG_ID%TYPE
            , P_USER_ID          IN HRT_PAYMENT_ADD_ALLOWANCE.CREATED_BY%TYPE 
            );

-- ADD_ALLOWANCE__UPDATE.
  PROCEDURE ADD_ALLOWANCE_UPDATE
            ( W_ADD_ALLOWANCE_ID IN HRT_PAYMENT_ADD_ALLOWANCE.ADD_ALLOWANCE_ID%TYPE
            , P_PERSON_ID        IN HRT_PAYMENT_ADD_ALLOWANCE.PERSON_ID%TYPE
            , P_CORP_ID          IN HRT_PAYMENT_ADD_ALLOWANCE.CORP_ID%TYPE
            , P_PAY_YYYYMM       IN HRT_PAYMENT_ADD_ALLOWANCE.PAY_YYYYMM%TYPE
            , P_WAGE_TYPE        IN HRT_PAYMENT_ADD_ALLOWANCE.WAGE_TYPE%TYPE
            , P_ALLOWANCE_ID     IN HRT_PAYMENT_ADD_ALLOWANCE.ALLOWANCE_ID%TYPE
            , P_ALLOWANCE_AMOUNT IN HRT_PAYMENT_ADD_ALLOWANCE.ALLOWANCE_AMOUNT%TYPE
            , P_TAX_YN           IN HRT_PAYMENT_ADD_ALLOWANCE.TAX_YN%TYPE
            , P_HIRE_INSUR_YN    IN HRT_PAYMENT_ADD_ALLOWANCE.HIRE_INSUR_YN%TYPE
            , P_CREATED_FLAG     IN HRT_PAYMENT_ADD_ALLOWANCE.CREATED_FLAG%TYPE
            , P_DESCRIPTION      IN HRT_PAYMENT_ADD_ALLOWANCE.DESCRIPTION%TYPE
            , P_SOB_ID           IN HRT_PAYMENT_ADD_ALLOWANCE.SOB_ID%TYPE
            , P_ORG_ID           IN HRT_PAYMENT_ADD_ALLOWANCE.ORG_ID%TYPE
            , P_USER_ID          IN HRT_PAYMENT_ADD_ALLOWANCE.CREATED_BY%TYPE
            );

-- ADD_ALLOWANCE_DELETE.
  PROCEDURE ADD_ALLOWANCE_DELETE
            ( W_ADD_ALLOWANCE_ID IN HRT_PAYMENT_ADD_ALLOWANCE.ADD_ALLOWANCE_ID%TYPE 
            );

---------------------------------------------------------------------------------------------------
-- ADD_ALLOWANCE SPREAD SELECT
  PROCEDURE PROMPT_SPREAD_SELECT
            ( P_CURSOR1           OUT TYPES.TCURSOR
            , W_PAY_YYYYMM        IN HRT_PAYMENT_ADD_ALLOWANCE.PAY_YYYYMM%TYPE
            , W_SOB_ID            IN HRT_PAYMENT_ADD_ALLOWANCE.SOB_ID%TYPE
            , W_ORG_ID            IN HRT_PAYMENT_ADD_ALLOWANCE.ORG_ID%TYPE
            );

-- ADD_ALLOWANCE SPREAD SELECT
  PROCEDURE ALLOWANCE_SPREAD_SELECT
            ( P_CURSOR2           OUT TYPES.TCURSOR2
            , W_CORP_ID           IN HRT_PAYMENT_ADD_ALLOWANCE.CORP_ID%TYPE
            , W_PAY_YYYYMM        IN HRT_PAYMENT_ADD_ALLOWANCE.PAY_YYYYMM%TYPE
            , W_WAGE_TYPE         IN HRT_PAYMENT_ADD_ALLOWANCE.WAGE_TYPE%TYPE
            , W_PERSON_ID         IN HRT_PAYMENT_ADD_ALLOWANCE.PERSON_ID%TYPE
            , W_SOB_ID            IN HRT_PAYMENT_ADD_ALLOWANCE.SOB_ID%TYPE
            , W_ORG_ID            IN HRT_PAYMENT_ADD_ALLOWANCE.ORG_ID%TYPE
            );
            
---------------------------------------------------------------------------------------------------
-- 급상여 대량 데이터 INSERT를 위한 ADD_ALLOWANCE SELECT
  PROCEDURE MASS_EXCEL_SELECT
            ( P_CURSOR1                           OUT TYPES.TCURSOR1
            , W_CORP_ID                           IN HRT_PAYMENT_ADD_ALLOWANCE.CORP_ID%TYPE
            , W_PAY_YYYYMM                        IN HRT_PAYMENT_ADD_ALLOWANCE.PAY_YYYYMM%TYPE
            , W_WAGE_TYPE                         IN HRT_PAYMENT_ADD_ALLOWANCE.WAGE_TYPE%TYPE
            , W_SOB_ID                            IN HRT_PAYMENT_ADD_ALLOWANCE.SOB_ID%TYPE
            , W_ORG_ID                            IN HRT_PAYMENT_ADD_ALLOWANCE.ORG_ID%TYPE
            );

-- 엑셀데이터 INSERT.
  PROCEDURE MASS_EXCEL_INSERT
            ( P_PAY_YYYYMM       IN HRT_PAYMENT_ADD_ALLOWANCE.PAY_YYYYMM%TYPE
            , P_WAGE_TYPE        IN HRT_PAYMENT_ADD_ALLOWANCE.WAGE_TYPE%TYPE
            , P_WAGE_TYPE_NAME   IN VARCHAR2
            , P_PERSON_NUM       IN VARCHAR2
            , P_NAME             IN VARCHAR2
            , P_ALLOWANCE_CODE   IN VARCHAR2
            , P_ALLOWANCE_NAME   IN VARCHAR2
            , P_ALLOWANCE_AMOUNT IN NUMBER
            , P_TAX_YN           IN HRT_PAYMENT_ADD_ALLOWANCE.TAX_YN%TYPE
            , P_HIRE_INSUR_YN    IN HRT_PAYMENT_ADD_ALLOWANCE.HIRE_INSUR_YN%TYPE
            , P_DESCRIPTION      IN HRT_PAYMENT_ADD_ALLOWANCE.DESCRIPTION%TYPE
            , P_SOB_ID           IN HRT_PAYMENT_ADD_ALLOWANCE.SOB_ID%TYPE
            , P_ORG_ID           IN HRT_PAYMENT_ADD_ALLOWANCE.ORG_ID%TYPE
            , P_USER_ID          IN HRT_PAYMENT_ADD_ALLOWANCE.CREATED_BY%TYPE 
            );
            
END HRT_PAYMENT_ADD_ALLOWANCE_G;


 
/
CREATE OR REPLACE PACKAGE BODY HRT_PAYMENT_ADD_ALLOWANCE_G
AS
/******************************************************************************/
/* PROJECT      : FPCB ERP
/* MODULE       : EAPP
/* PROGRAM NAME : HRT_PAYMENT_ADD_ALLOWANCE_G
/* DESCRIPTION  : 급상여 추가 지급 관리.
/* REFERENCE BY :
/* PROGRAM HISTORY : 신규 생성
/*------------------------------------------------------------------------------
/*   DATE       IN CHARGE          DESCRIPTION
/*------------------------------------------------------------------------------
/* 20-JUN-2010  JEON HO SU          INITIALIZE
/******************************************************************************/
-- ADD_ALLOWANCE SELECT
  PROCEDURE DATA_SELECT
            ( P_CURSOR                            OUT TYPES.TCURSOR
            , W_CORP_ID                           IN HRT_PAYMENT_ADD_ALLOWANCE.CORP_ID%TYPE
            , W_PAY_YYYYMM                        IN HRT_PAYMENT_ADD_ALLOWANCE.PAY_YYYYMM%TYPE
            , W_WAGE_TYPE                         IN HRT_PAYMENT_ADD_ALLOWANCE.WAGE_TYPE%TYPE
            , W_ALLOWANCE_ID                      IN HRT_PAYMENT_ADD_ALLOWANCE.ALLOWANCE_ID%TYPE
            , W_PERSON_ID                         IN HRT_PAYMENT_ADD_ALLOWANCE.PERSON_ID%TYPE
            , W_SOB_ID                            IN HRT_PAYMENT_ADD_ALLOWANCE.SOB_ID%TYPE
            , W_ORG_ID                            IN HRT_PAYMENT_ADD_ALLOWANCE.ORG_ID%TYPE
            )
  AS
    V_START_DATE                                  DATE := NULL;
    V_END_DATE                                    DATE := NULL;
    
  BEGIN
    BEGIN
      SELECT ADD_MONTHS(TO_DATE(W_PAY_YYYYMM || '-' || PT.START_DAY, 'YYYY-MM-DD') + PT.START_ADD_DAY, PT.START_ADD_MONTH) AS START_DATE
           , ADD_MONTHS(TO_DATE(W_PAY_YYYYMM || '-' || PT.END_DAY, 'YYYY-MM-DD') + PT.END_ADD_DAY, PT.END_ADD_MONTH) AS END_DATE
        INTO V_START_DATE, V_END_DATE
        FROM HRM_CLOSING_TYPE_V CT
          , HRM_PAYMENT_TERM_V PT
       WHERE CT.CLOSING_TYPE    = PT.WAGE_TYPE
         AND CT.SOB_ID          = PT.SOB_ID
         AND CT.ORG_ID          = PT.ORG_ID
         AND PT.WAGE_TYPE       = W_WAGE_TYPE
         AND PT.SOB_ID          = W_SOB_ID
         AND PT.ORG_ID          = W_ORG_ID
       ;
    EXCEPTION WHEN OTHERS THEN
      V_START_DATE := TRUNC(TO_DATE(W_PAY_YYYYMM, 'YYYY-MM'));
      V_END_DATE := LAST_DAY(V_START_DATE);
    END;
    
    OPEN P_CURSOR FOR
      SELECT PAA.PAY_YYYYMM
           , PAA.WAGE_TYPE
           , HRM_COMMON_G.CODE_NAME_F('CLOSING_TYPE', PAA.WAGE_TYPE, PAA.SOB_ID, PAA.ORG_ID) AS WAGE_TYPE_NAME
           , PM.NAME
           , PM.PERSON_NUM
           , HRM_DEPT_MASTER_G.DEPT_NAME_F(HL.DEPT_ID) AS DEPT_NAME
           , HRM_COMMON_G.ID_NAME_F(HL.POST_ID) AS POST_NAME
           , HRM_COMMON_G.ID_NAME_F(PAA.ALLOWANCE_ID) AS ALLOWANCE_NAME
           , PAA.ALLOWANCE_AMOUNT
           , PAA.TAX_YN
           , PAA.HIRE_INSUR_YN
           , PAA.CREATED_FLAG
           , PAA.DESCRIPTION
           , PAA.ADD_ALLOWANCE_ID
           , PAA.PERSON_ID
           , PAA.CORP_ID
           , PAA.ALLOWANCE_ID
        FROM HRM_HISTORY_LINE HL
          , HRM_PERSON_MASTER PM
          , HRT_PAYMENT_ADD_ALLOWANCE PAA
      WHERE HL.PERSON_ID        = PM.PERSON_ID
        AND PM.PERSON_ID        = PAA.PERSON_ID        
        AND HL.HISTORY_LINE_ID  IN ( SELECT MAX(S_HL.HISTORY_LINE_ID) AS HISTORY_LINE_ID
                                      FROM HRM_HISTORY_LINE S_HL
                                     WHERE S_HL.CHARGE_DATE            <= V_END_DATE
                                       AND S_HL.PERSON_ID              = HL.PERSON_ID
                                     GROUP BY S_HL.PERSON_ID
                                   )
        AND PAA.CORP_ID         = NVL(W_CORP_ID, PAA.CORP_ID)
        AND PAA.PAY_YYYYMM      = W_PAY_YYYYMM
        AND PAA.WAGE_TYPE       = W_WAGE_TYPE
        AND PAA.PERSON_ID       = NVL(W_PERSON_ID, PAA.PERSON_ID)
        AND PAA.ALLOWANCE_ID    = NVL(W_ALLOWANCE_ID, PAA.ALLOWANCE_ID)
        AND PAA.SOB_ID          = W_SOB_ID
        AND PAA.ORG_ID          = W_ORG_ID
        AND PM.ORI_JOIN_DATE    <= V_END_DATE
        AND (PM.RETIRE_DATE IS NULL OR PM.RETIRE_DATE >= V_START_DATE)
      ORDER BY HL.DEPT_ID, HL.POST_ID, HL.PERSON_ID
      ;

  END DATA_SELECT;

---------------------------------------------------------------------------------------------------
-- ADD_ALLOWANCE_INSERT
  PROCEDURE ADD_ALLOWANCE_INSERT
            ( P_ADD_ALLOWANCE_ID OUT HRT_PAYMENT_ADD_ALLOWANCE.ADD_ALLOWANCE_ID%TYPE
            , P_PERSON_ID        IN HRT_PAYMENT_ADD_ALLOWANCE.PERSON_ID%TYPE
            , P_CORP_ID          IN HRT_PAYMENT_ADD_ALLOWANCE.CORP_ID%TYPE
            , P_PAY_YYYYMM       IN HRT_PAYMENT_ADD_ALLOWANCE.PAY_YYYYMM%TYPE
            , P_WAGE_TYPE        IN HRT_PAYMENT_ADD_ALLOWANCE.WAGE_TYPE%TYPE
            , P_ALLOWANCE_ID     IN HRT_PAYMENT_ADD_ALLOWANCE.ALLOWANCE_ID%TYPE
            , P_ALLOWANCE_AMOUNT IN HRT_PAYMENT_ADD_ALLOWANCE.ALLOWANCE_AMOUNT%TYPE
            , P_TAX_YN           IN HRT_PAYMENT_ADD_ALLOWANCE.TAX_YN%TYPE
            , P_HIRE_INSUR_YN    IN HRT_PAYMENT_ADD_ALLOWANCE.HIRE_INSUR_YN%TYPE
            , P_CREATED_FLAG     IN HRT_PAYMENT_ADD_ALLOWANCE.CREATED_FLAG%TYPE
            , P_DESCRIPTION      IN HRT_PAYMENT_ADD_ALLOWANCE.DESCRIPTION%TYPE
            , P_SOB_ID           IN HRT_PAYMENT_ADD_ALLOWANCE.SOB_ID%TYPE
            , P_ORG_ID           IN HRT_PAYMENT_ADD_ALLOWANCE.ORG_ID%TYPE
            , P_USER_ID          IN HRT_PAYMENT_ADD_ALLOWANCE.CREATED_BY%TYPE 
            )
  AS
    V_SYSDATE                     DATE := GET_LOCAL_DATE(P_SOB_ID);

  BEGIN
    BEGIN
      SELECT HRT_PAYMENT_ADD_ALLOWANCE_S1.NEXTVAL
       INTO P_ADD_ALLOWANCE_ID
       FROM DUAL;
    EXCEPTION WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(ERRNUMS.Invalid_Sequence_Code, ERRNUMS.Invalid_Sequence_Desc);
      RETURN;
    END;

    INSERT INTO HRT_PAYMENT_ADD_ALLOWANCE
    ( ADD_ALLOWANCE_ID
    , PERSON_ID 
    , CORP_ID 
    , PAY_YYYYMM 
    , WAGE_TYPE 
    , ALLOWANCE_ID 
    , ALLOWANCE_AMOUNT 
    , TAX_YN 
    , HIRE_INSUR_YN 
    , CREATED_FLAG 
    , DESCRIPTION 
    , SOB_ID 
    , ORG_ID 
    , CREATION_DATE 
    , CREATED_BY 
    , LAST_UPDATE_DATE 
    , LAST_UPDATED_BY 
    ) VALUES
    ( P_ADD_ALLOWANCE_ID
    , P_PERSON_ID
    , P_CORP_ID
    , P_PAY_YYYYMM
    , P_WAGE_TYPE
    , P_ALLOWANCE_ID
    , P_ALLOWANCE_AMOUNT
    , P_TAX_YN
    , P_HIRE_INSUR_YN
    , P_CREATED_FLAG
    , P_DESCRIPTION
    , P_SOB_ID
    , P_ORG_ID
    , V_SYSDATE
    , P_USER_ID
    , V_SYSDATE
    , P_USER_ID 
    );
  END ADD_ALLOWANCE_INSERT;

-- ADD_ALLOWANCE__UPDATE.
  PROCEDURE ADD_ALLOWANCE_UPDATE
            ( W_ADD_ALLOWANCE_ID IN HRT_PAYMENT_ADD_ALLOWANCE.ADD_ALLOWANCE_ID%TYPE
            , P_PERSON_ID        IN HRT_PAYMENT_ADD_ALLOWANCE.PERSON_ID%TYPE
            , P_CORP_ID          IN HRT_PAYMENT_ADD_ALLOWANCE.CORP_ID%TYPE
            , P_PAY_YYYYMM       IN HRT_PAYMENT_ADD_ALLOWANCE.PAY_YYYYMM%TYPE
            , P_WAGE_TYPE        IN HRT_PAYMENT_ADD_ALLOWANCE.WAGE_TYPE%TYPE
            , P_ALLOWANCE_ID     IN HRT_PAYMENT_ADD_ALLOWANCE.ALLOWANCE_ID%TYPE
            , P_ALLOWANCE_AMOUNT IN HRT_PAYMENT_ADD_ALLOWANCE.ALLOWANCE_AMOUNT%TYPE
            , P_TAX_YN           IN HRT_PAYMENT_ADD_ALLOWANCE.TAX_YN%TYPE
            , P_HIRE_INSUR_YN    IN HRT_PAYMENT_ADD_ALLOWANCE.HIRE_INSUR_YN%TYPE
            , P_CREATED_FLAG     IN HRT_PAYMENT_ADD_ALLOWANCE.CREATED_FLAG%TYPE
            , P_DESCRIPTION      IN HRT_PAYMENT_ADD_ALLOWANCE.DESCRIPTION%TYPE
            , P_SOB_ID           IN HRT_PAYMENT_ADD_ALLOWANCE.SOB_ID%TYPE
            , P_ORG_ID           IN HRT_PAYMENT_ADD_ALLOWANCE.ORG_ID%TYPE
            , P_USER_ID          IN HRT_PAYMENT_ADD_ALLOWANCE.CREATED_BY%TYPE
            )
  AS
   V_SYSDATE DATE := GET_LOCAL_DATE(P_SOB_ID);

  BEGIN
      UPDATE HRT_PAYMENT_ADD_ALLOWANCE
        SET ALLOWANCE_ID     = P_ALLOWANCE_ID
          , ALLOWANCE_AMOUNT = P_ALLOWANCE_AMOUNT
          , TAX_YN           = P_TAX_YN
          , HIRE_INSUR_YN    = P_HIRE_INSUR_YN
          , CREATED_FLAG     = P_CREATED_FLAG
          , DESCRIPTION      = P_DESCRIPTION
          , LAST_UPDATE_DATE = V_SYSDATE
          , LAST_UPDATED_BY  = P_USER_ID
      WHERE ADD_ALLOWANCE_ID = W_ADD_ALLOWANCE_ID
      ;

  END ADD_ALLOWANCE_UPDATE;

-- ADD_ALLOWANCE_DELETE.
  PROCEDURE ADD_ALLOWANCE_DELETE
            ( W_ADD_ALLOWANCE_ID IN HRT_PAYMENT_ADD_ALLOWANCE.ADD_ALLOWANCE_ID%TYPE 
            )
  AS
  BEGIN
    DELETE HRT_PAYMENT_ADD_ALLOWANCE
     WHERE ADD_ALLOWANCE_ID = W_ADD_ALLOWANCE_ID;
  
  END ADD_ALLOWANCE_DELETE;

---------------------------------------------------------------------------------------------------
-- ADD_ALLOWANCE SPREAD SELECT
  PROCEDURE PROMPT_SPREAD_SELECT
            ( P_CURSOR1           OUT TYPES.TCURSOR
            , W_PAY_YYYYMM        IN HRT_PAYMENT_ADD_ALLOWANCE.PAY_YYYYMM%TYPE
            , W_SOB_ID            IN HRT_PAYMENT_ADD_ALLOWANCE.SOB_ID%TYPE
            , W_ORG_ID            IN HRT_PAYMENT_ADD_ALLOWANCE.ORG_ID%TYPE
            )
  AS
  BEGIN
    OPEN P_CURSOR1 FOR
      SELECT -- 추가지급 PROMPT.
             MAX(DECODE(HA.ALLOWANCE_CODE, 'A01', HA.ALLOWANCE_NAME)) AS A01
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A02', HA.ALLOWANCE_NAME)) AS A02
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A03', HA.ALLOWANCE_NAME)) AS A03
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A04', HA.ALLOWANCE_NAME)) AS A04
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A05', HA.ALLOWANCE_NAME)) AS A05
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A06', HA.ALLOWANCE_NAME)) AS A06
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A07', HA.ALLOWANCE_NAME)) AS A07
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A08', HA.ALLOWANCE_NAME)) AS A08
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A09', HA.ALLOWANCE_NAME)) AS A09
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A10', HA.ALLOWANCE_NAME)) AS A10
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A11', HA.ALLOWANCE_NAME)) AS A11
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A12', HA.ALLOWANCE_NAME)) AS A12
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A13', HA.ALLOWANCE_NAME)) AS A13
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A14', HA.ALLOWANCE_NAME)) AS A14
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A15', HA.ALLOWANCE_NAME)) AS A15
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A16', HA.ALLOWANCE_NAME)) AS A16
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A17', HA.ALLOWANCE_NAME)) AS A17
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A18', HA.ALLOWANCE_NAME)) AS A18
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A19', HA.ALLOWANCE_NAME)) AS A19
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A20', HA.ALLOWANCE_NAME)) AS A20
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A21', HA.ALLOWANCE_NAME)) AS A21
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A22', HA.ALLOWANCE_NAME)) AS A22
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A23', HA.ALLOWANCE_NAME)) AS A23
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A24', HA.ALLOWANCE_NAME)) AS A24
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A25', HA.ALLOWANCE_NAME)) AS A25
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A26', HA.ALLOWANCE_NAME)) AS A26
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A27', HA.ALLOWANCE_NAME)) AS A27
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A28', HA.ALLOWANCE_NAME)) AS A28
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A29', HA.ALLOWANCE_NAME)) AS A29
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A30', HA.ALLOWANCE_NAME)) AS A30
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A31', HA.ALLOWANCE_NAME)) AS A31
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A32', HA.ALLOWANCE_NAME)) AS A32
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A33', HA.ALLOWANCE_NAME)) AS A33
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A34', HA.ALLOWANCE_NAME)) AS A34
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A35', HA.ALLOWANCE_NAME)) AS A35
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A36', HA.ALLOWANCE_NAME)) AS A36
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A37', HA.ALLOWANCE_NAME)) AS A37
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A38', HA.ALLOWANCE_NAME)) AS A38
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A39', HA.ALLOWANCE_NAME)) AS A39
           -- 추가지급항목 여부.
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A01', HA.ALLOWANCE_YN, 'N')) AS A01_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A02', HA.ALLOWANCE_YN, 'N')) AS A02_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A03', HA.ALLOWANCE_YN, 'N')) AS A03_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A04', HA.ALLOWANCE_YN, 'N')) AS A04_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A05', HA.ALLOWANCE_YN, 'N')) AS A05_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A06', HA.ALLOWANCE_YN, 'N')) AS A06_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A07', HA.ALLOWANCE_YN, 'N')) AS A07_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A08', HA.ALLOWANCE_YN, 'N')) AS A08_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A09', HA.ALLOWANCE_YN, 'N')) AS A09_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A10', HA.ALLOWANCE_YN, 'N')) AS A10_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A11', HA.ALLOWANCE_YN, 'N')) AS A11_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A12', HA.ALLOWANCE_YN, 'N')) AS A12_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A13', HA.ALLOWANCE_YN, 'N')) AS A13_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A14', HA.ALLOWANCE_YN, 'N')) AS A14_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A15', HA.ALLOWANCE_YN, 'N')) AS A15_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A16', HA.ALLOWANCE_YN, 'N')) AS A16_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A17', HA.ALLOWANCE_YN, 'N')) AS A17_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A18', HA.ALLOWANCE_YN, 'N')) AS A18_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A19', HA.ALLOWANCE_YN, 'N')) AS A19_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A20', HA.ALLOWANCE_YN, 'N')) AS A20_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A21', HA.ALLOWANCE_YN, 'N')) AS A21_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A22', HA.ALLOWANCE_YN, 'N')) AS A22_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A23', HA.ALLOWANCE_YN, 'N')) AS A23_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A24', HA.ALLOWANCE_YN, 'N')) AS A24_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A25', HA.ALLOWANCE_YN, 'N')) AS A25_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A26', HA.ALLOWANCE_YN, 'N')) AS A26_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A27', HA.ALLOWANCE_YN, 'N')) AS A27_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A28', HA.ALLOWANCE_YN, 'N')) AS A28_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A29', HA.ALLOWANCE_YN, 'N')) AS A29_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A30', HA.ALLOWANCE_YN, 'N')) AS A30_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A31', HA.ALLOWANCE_YN, 'N')) AS A31_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A32', HA.ALLOWANCE_YN, 'N')) AS A32_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A33', HA.ALLOWANCE_YN, 'N')) AS A33_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A34', HA.ALLOWANCE_YN, 'N')) AS A34_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A35', HA.ALLOWANCE_YN, 'N')) AS A35_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A36', HA.ALLOWANCE_YN, 'N')) AS A36_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A37', HA.ALLOWANCE_YN, 'N')) AS A37_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A38', HA.ALLOWANCE_YN, 'N')) AS A38_YN
           , MAX(DECODE(HA.ALLOWANCE_CODE, 'A39', HA.ALLOWANCE_YN, 'N')) AS A39_YN
        FROM HRM_ALLOWANCE_V HA
      WHERE HA.SOB_ID                   = W_SOB_ID
        AND HA.ORG_ID                   = W_ORG_ID
        AND HA.ENABLED_FLAG             = 'Y'
        AND HA.EFFECTIVE_DATE_FR        <= LAST_DAY(TO_DATE(W_PAY_YYYYMM, 'YYYY-MM'))
        AND (HA.EFFECTIVE_DATE_TO IS NULL OR HA.EFFECTIVE_DATE_TO >= TRUNC(TO_DATE(W_PAY_YYYYMM, 'YYYY-MM')))
      GROUP BY HA.SOB_ID
           , HA.ORG_ID
      ;
  END PROMPT_SPREAD_SELECT;

-- ADD_ALLOWANCE SPREAD SELECT
  PROCEDURE ALLOWANCE_SPREAD_SELECT
            ( P_CURSOR2           OUT TYPES.TCURSOR2
            , W_CORP_ID           IN HRT_PAYMENT_ADD_ALLOWANCE.CORP_ID%TYPE
            , W_PAY_YYYYMM        IN HRT_PAYMENT_ADD_ALLOWANCE.PAY_YYYYMM%TYPE
            , W_WAGE_TYPE         IN HRT_PAYMENT_ADD_ALLOWANCE.WAGE_TYPE%TYPE
            , W_PERSON_ID         IN HRT_PAYMENT_ADD_ALLOWANCE.PERSON_ID%TYPE
            , W_SOB_ID            IN HRT_PAYMENT_ADD_ALLOWANCE.SOB_ID%TYPE
            , W_ORG_ID            IN HRT_PAYMENT_ADD_ALLOWANCE.ORG_ID%TYPE
            )
  AS
  BEGIN
    OPEN P_CURSOR2 FOR
      SELECT PAA.PAY_YYYYMM
           , PAA.WAGE_TYPE
           , HRM_COMMON_G.CODE_NAME_F('WAGE_TYPE', PAA.WAGE_TYPE, PAA.SOB_ID, PAA.ORG_ID) AS WAGE_TYPE_DESC
           , NVL(PAA.CORP_ID, NULL) AS CORP_ID
           , NVL(PAA.PERSON_ID, NULL) AS PERSON_ID
           , CASE
               WHEN GROUPING(PAA.PAY_YYYYMM) = 1 THEN EAPP_MESSAGE_G.RETURN_TEXT_F(USERENV_G.GET_TERRITORY_S_F, 'EAPP_10045', NULL)
               ELSE PM.NAME
             END AS NAME
           , PM.PERSON_NUM
           , DM.DEPT_NAME
           , PG.PAY_GRADE_NAME
           , TO_CHAR(PM.ORI_JOIN_DATE, 'YYYY-MM-DD') AS ORI_JOIN_DATE
           , TO_CHAR(PM.RETIRE_DATE, 'YYYY-MM-DD') AS RETIRE_DATE
           -- 추가지급.
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A01', PAA.ALLOWANCE_AMOUNT)) AS A01
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A02', PAA.ALLOWANCE_AMOUNT)) AS A02
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A03', PAA.ALLOWANCE_AMOUNT)) AS A03
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A04', PAA.ALLOWANCE_AMOUNT)) AS A04
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A05', PAA.ALLOWANCE_AMOUNT)) AS A05
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A06', PAA.ALLOWANCE_AMOUNT)) AS A06
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A07', PAA.ALLOWANCE_AMOUNT)) AS A07
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A08', PAA.ALLOWANCE_AMOUNT)) AS A08
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A09', PAA.ALLOWANCE_AMOUNT)) AS A09
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A10', PAA.ALLOWANCE_AMOUNT)) AS A10
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A11', PAA.ALLOWANCE_AMOUNT)) AS A11
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A12', PAA.ALLOWANCE_AMOUNT)) AS A12
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A13', PAA.ALLOWANCE_AMOUNT)) AS A13
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A14', PAA.ALLOWANCE_AMOUNT)) AS A14
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A15', PAA.ALLOWANCE_AMOUNT)) AS A15
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A16', PAA.ALLOWANCE_AMOUNT)) AS A16
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A17', PAA.ALLOWANCE_AMOUNT)) AS A17
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A18', PAA.ALLOWANCE_AMOUNT)) AS A18
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A19', PAA.ALLOWANCE_AMOUNT)) AS A19
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A20', PAA.ALLOWANCE_AMOUNT)) AS A20
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A21', PAA.ALLOWANCE_AMOUNT)) AS A21
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A22', PAA.ALLOWANCE_AMOUNT)) AS A22
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A23', PAA.ALLOWANCE_AMOUNT)) AS A23
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A24', PAA.ALLOWANCE_AMOUNT)) AS A24
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A25', PAA.ALLOWANCE_AMOUNT)) AS A25
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A26', PAA.ALLOWANCE_AMOUNT)) AS A26
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A27', PAA.ALLOWANCE_AMOUNT)) AS A27
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A28', PAA.ALLOWANCE_AMOUNT)) AS A28
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A29', PAA.ALLOWANCE_AMOUNT)) AS A29
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A30', PAA.ALLOWANCE_AMOUNT)) AS A30
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A31', PAA.ALLOWANCE_AMOUNT)) AS A31
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A32', PAA.ALLOWANCE_AMOUNT)) AS A32
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A33', PAA.ALLOWANCE_AMOUNT)) AS A33
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A34', PAA.ALLOWANCE_AMOUNT)) AS A34
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A35', PAA.ALLOWANCE_AMOUNT)) AS A35
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A36', PAA.ALLOWANCE_AMOUNT)) AS A36
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A37', PAA.ALLOWANCE_AMOUNT)) AS A37
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A38', PAA.ALLOWANCE_AMOUNT)) AS A38
           , SUM(DECODE(HA.ALLOWANCE_CODE, 'A39', PAA.ALLOWANCE_AMOUNT)) AS A39
           , SUM(PAA.ALLOWANCE_AMOUNT) AS TOTAL_AMOUNT
        FROM HRM_PERSON_MASTER PM
          , HRM_DEPT_MASTER DM
          , HRM_PAY_GRADE_V PG
          , HRT_PAYMENT_ADD_ALLOWANCE PAA
          , HRM_ALLOWANCE_V HA
      WHERE PM.PERSON_ID                = PAA.PERSON_ID
        AND PM.DEPT_ID                  = DM.DEPT_ID
        AND PM.PAY_GRADE_ID             = PG.PAY_GRADE_ID
        AND PAA.ALLOWANCE_ID            = HA.ALLOWANCE_ID
        AND PAA.SOB_ID                  = HA.SOB_ID
        AND PAA.ORG_ID                  = HA.ORG_ID
        AND PAA.PAY_YYYYMM              = W_PAY_YYYYMM
        AND PAA.WAGE_TYPE               = W_WAGE_TYPE
        AND PAA.CORP_ID                 = NVL(W_CORP_ID, PAA.CORP_ID)
        AND PAA.PERSON_ID               = NVL(W_PERSON_ID, PAA.PERSON_ID)
        AND PAA.SOB_ID                  = W_SOB_ID
        AND PAA.ORG_ID                  = W_ORG_ID
        AND HA.ENABLED_FLAG             = 'Y'
        AND HA.EFFECTIVE_DATE_FR        <= LAST_DAY(TO_DATE(W_PAY_YYYYMM, 'YYYY-MM'))
        AND (HA.EFFECTIVE_DATE_TO IS NULL OR HA.EFFECTIVE_DATE_TO >= TRUNC(TO_DATE(W_PAY_YYYYMM, 'YYYY-MM')))
      GROUP BY ROLLUP((DM.DEPT_CODE
           , PG.PAY_GRADE
           , PM.PERSON_NUM
           , PAA.PERSON_ID
           , PM.NAME
           , DM.DEPT_NAME
           , PG.PAY_GRADE_NAME
           , PM.ORI_JOIN_DATE
           , PM.RETIRE_DATE
           , PAA.CORP_ID
           , PAA.PAY_YYYYMM
           , PAA.WAGE_TYPE
           , HRM_COMMON_G.CODE_NAME_F('WAGE_TYPE', PAA.WAGE_TYPE, PAA.SOB_ID, PAA.ORG_ID)))
      ;
  END ALLOWANCE_SPREAD_SELECT;
    
---------------------------------------------------------------------------------------------------
-- 급상여 대량 데이터 INSERT를 위한 ADD_ALLOWANCE SELECT
  PROCEDURE MASS_EXCEL_SELECT
            ( P_CURSOR1                           OUT TYPES.TCURSOR1
            , W_CORP_ID                           IN HRT_PAYMENT_ADD_ALLOWANCE.CORP_ID%TYPE
            , W_PAY_YYYYMM                        IN HRT_PAYMENT_ADD_ALLOWANCE.PAY_YYYYMM%TYPE
            , W_WAGE_TYPE                         IN HRT_PAYMENT_ADD_ALLOWANCE.WAGE_TYPE%TYPE
            , W_SOB_ID                            IN HRT_PAYMENT_ADD_ALLOWANCE.SOB_ID%TYPE
            , W_ORG_ID                            IN HRT_PAYMENT_ADD_ALLOWANCE.ORG_ID%TYPE
            )
  AS
  BEGIN
    OPEN P_CURSOR1 FOR
      SELECT PAA.PAY_YYYYMM
           , PAA.WAGE_TYPE
           , TO_CHAR(NULL) AS WAGE_TYPE_NAME
           , TO_CHAR(NULL) AS PERSON_NUM
           , TO_CHAR(NULL) AS NAME
           , TO_CHAR(NULL) AS ALLOWANCE_CODE
           , TO_CHAR(NULL) AS ALLOWANCE_NAME
           , PAA.ALLOWANCE_AMOUNT
           , PAA.TAX_YN
           , PAA.HIRE_INSUR_YN
           , PAA.DESCRIPTION
           , PAA.SOB_ID
           , PAA.ORG_ID
        FROM HRT_PAYMENT_ADD_ALLOWANCE PAA
      WHERE PAA.CORP_ID           = NVL(W_CORP_ID, PAA.CORP_ID)
        AND PAA.PAY_YYYYMM        = W_PAY_YYYYMM
        AND PAA.WAGE_TYPE         = W_WAGE_TYPE
        AND PAA.SOB_ID            = W_SOB_ID
        AND PAA.ORG_ID            = W_ORG_ID
      ;
  END;

-- 엑셀데이터 INSERT.
  PROCEDURE MASS_EXCEL_INSERT
            ( P_PAY_YYYYMM       IN HRT_PAYMENT_ADD_ALLOWANCE.PAY_YYYYMM%TYPE
            , P_WAGE_TYPE        IN HRT_PAYMENT_ADD_ALLOWANCE.WAGE_TYPE%TYPE
            , P_WAGE_TYPE_NAME   IN VARCHAR2
            , P_PERSON_NUM       IN VARCHAR2
            , P_NAME             IN VARCHAR2
            , P_ALLOWANCE_CODE   IN VARCHAR2
            , P_ALLOWANCE_NAME   IN VARCHAR2
            , P_ALLOWANCE_AMOUNT IN NUMBER
            , P_TAX_YN           IN HRT_PAYMENT_ADD_ALLOWANCE.TAX_YN%TYPE
            , P_HIRE_INSUR_YN    IN HRT_PAYMENT_ADD_ALLOWANCE.HIRE_INSUR_YN%TYPE
            , P_DESCRIPTION      IN HRT_PAYMENT_ADD_ALLOWANCE.DESCRIPTION%TYPE
            , P_SOB_ID           IN HRT_PAYMENT_ADD_ALLOWANCE.SOB_ID%TYPE
            , P_ORG_ID           IN HRT_PAYMENT_ADD_ALLOWANCE.ORG_ID%TYPE
            , P_USER_ID          IN HRT_PAYMENT_ADD_ALLOWANCE.CREATED_BY%TYPE 
            )
  AS
    V_ADD_ALLOWANCE_ID           NUMBER;
    V_PERSON_ID                  NUMBER;
    V_CORP_ID                    NUMBER;
    V_ALLOWANCE_ID               NUMBER;
  BEGIN
    -- 사원정보-- 
    BEGIN
      SELECT PM.CORP_ID
           , PM.PERSON_ID
        INTO V_CORP_ID
           , V_PERSON_ID
        FROM HRM_PERSON_MASTER PM
      WHERE PM.PERSON_NUM         = P_PERSON_NUM
        AND PM.SOB_ID             = P_SOB_ID
        AND PM.ORG_ID             = P_ORG_ID
      ;
    EXCEPTION WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20001, 'Person Infomation Error : Person Num - ' || P_PERSON_NUM);
      RETURN;
    END;
    -- 지급항목ID-- 
    BEGIN
      SELECT HA.ALLOWANCE_ID
        INTO V_ALLOWANCE_ID
        FROM HRM_ALLOWANCE_V HA
      WHERE HA.ALLOWANCE_CODE     = P_ALLOWANCE_CODE
        AND HA.SOB_ID             = P_SOB_ID
        AND HA.ORG_ID             = P_ORG_ID
      ;
    EXCEPTION WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20001, 'Allowance ID Error : (' || P_PERSON_NUM || '), Allowance Code- ' || P_ALLOWANCE_CODE);
      RETURN;
    END;
    
    ADD_ALLOWANCE_INSERT( P_ADD_ALLOWANCE_ID => V_ADD_ALLOWANCE_ID
                        , P_PERSON_ID => V_PERSON_ID
                        , P_CORP_ID => V_CORP_ID
                        , P_PAY_YYYYMM => P_PAY_YYYYMM
                        , P_WAGE_TYPE => P_WAGE_TYPE
                        , P_ALLOWANCE_ID => V_ALLOWANCE_ID
                        , P_ALLOWANCE_AMOUNT => P_ALLOWANCE_AMOUNT
                        , P_TAX_YN => P_TAX_YN
                        , P_HIRE_INSUR_YN => P_HIRE_INSUR_YN
                        , P_CREATED_FLAG => 'M'
                        , P_DESCRIPTION => P_DESCRIPTION
                        , P_SOB_ID => P_SOB_ID
                        , P_ORG_ID => P_ORG_ID
                        , P_USER_ID => P_USER_ID
                        );  
  END MASS_EXCEL_INSERT;

END HRT_PAYMENT_ADD_ALLOWANCE_G;
/
