SELECT FP.FOOD_DATE AS FOOD_DATE
     , HRM_COMMON_G.WEEK_F( TO_CHAR(FP.FOOD_DATE, 'D'), FP.SOB_ID, FP.ORG_ID) AS WEEK_NAME
           , NVL(FP.FOOD_COUNT, 0) AS FOOD_SUM
           , NVL(FP.DED_COUNT, 0) AS DED_COUNT
        FROM HRF_FOOD_PERSON FP
       WHERE FP.FOOD_DATE             BETWEEN &W_START_DATE AND &W_END_DATE
			   AND FP.PERSON_ID             = &W_PERSON_ID
         AND FP.SOB_ID                = &W_SOB_ID
         AND FP.ORG_ID                = &W_ORG_ID
      ;

SELECT ROWNUM AS FOOD_ID
    , FPT.FOOD_PERSON_ID
    , FPT.FOOD_FLAG
		, FPT.FOOD_DATETIME
  FROM HRF_FOOD_PERSON_TIME FPT
 WHERE FPT.FOOD_PERSON_ID       = &W_FOOD_PERSON_ID
 ;
