-- 전체 조회.
SELECT 
     , PM.DEPT_NAME
		 , PM.POST_NAME
		 , PM.FLOOR_NAME
		 , DI.PERSON_ID
     , PM.DISPLAY_NAME
		 , DI.DUTY_ID
		 , HRM_COMMON_G.ID_NAME_F(DI.DUTY_ID) AS DUTY_NAME
		 , DI.HOLY_TYPE
		 , HRM_COMMON_G.CODE_NAME_F('HOLY_TYPE', DI.HOLY_TYPE, DI.SOB_ID, DI.ORG_ID) AS HOLY_TYPE_NAME
		 , CASE
		     WHEN &W_IO_FLAG = '1' THEN NVL(I_DM.MODIFY_TIME, DI.OPEN_TIME)
				 ELSE NVL(O_DM.MODIFY_TIME, DI.CLOSE_TIME)
		   END AS IO_TIME1
		 , CASE
		     WHEN &W_IO_FLAG = '1' THEN NVL(I_DM.MODIFY_TIME1, DI.OPEN_TIME1)
				 ELSE NVL(O_DM.MODIFY_TIME1, DI.CLOSE_TIME1) 
		   END AS IO_TIME2
		 , HRM_COMMON_G.ID_NAME_F(DECODE(&W_IO_FLAG, '1', I_DM.MODIFY_ID, O_DM.MODIFY_ID)) AS MODIFY_DESC
		 , DI.NEXT_DAY_YN
		 , DI.LEAVE_ID
		 , HRM_COMMON_G.ID_NAME_F(DI.LEAVE_ID) AS LEAVE_NAME
		 , DI.LEAVE_TIME_CODE
		 , HRM_COMMON_G.CODE_NAME_F('LEAVE_TIME', DI.LEAVE_TIME_CODE, DI.SOB_ID, DI.ORG_ID) AS LEAVE_TIME
		 , DI.MODIFY_YN
		 , DI.MODIFY_IN_YN
		 , DI.MODIFY_OUT_YN
		 , DI.MODIFY_FLAG AS MODIFY_FLAG
		 , DI.TRANS_YN AS TRANS_YN
		 , HRM_COMMON_G.CODE_NAME_F('DUTY_APPROVE_STATUS', DI.APPROVE_STATUS, DI.SOB_ID, DI.ORG_ID) AS APPROVE_STATUS_NAME
		 , HRM_PERSON_MASTER_G.NAME_F(DI.APPROVED_PERSON_ID) AS APPROVED_PERSON_NAME
		 , HRM_PERSON_MASTER_G.NAME_F(DI.CONFIRMED_PERSON_ID) AS CONFIRMED_PERSON_NAME
FROM HRD_DAY_INTERFACE_V DI 
  , HRM_PERSON_MASTER_V1 PM
	, HRD_DAY_MODIFY I_DM
	, HRD_DAY_MODIFY O_DM
WHERE DI.PERSON_ID                          = PM.PERSON_ID
  AND DI.CORP_ID                            = PM.CORP_ID
  AND DI.SOB_ID                             = PM.SOB_ID
  AND DI.ORG_ID                             = PM.ORG_ID
	AND DI.PERSON_ID                          = I_DM.PERSON_ID(+)
	AND DI.WORK_DATE                          = I_DM.WORK_DATE(+)
	AND '1'                                   = I_DM.IO_FLAG(+)
	AND DI.PERSON_ID                          = O_DM.PERSON_ID(+)
	AND DI.WORK_DATE                          = O_DM.WORK_DATE(+)
	AND '2'                                   = O_DM.IO_FLAG(+)	
  AND DI.WORK_DATE                          = &W_WORK_DATE
  AND DI.PERSON_ID                          = NVL(&W_PERSON_ID, DI.PERSON_ID)
  AND DI.CORP_ID                            = &W_CORP_ID
  AND DI.SOB_ID                             = &W_SOB_ID
  AND DI.ORG_ID                             = &W_ORG_ID
	AND DI.WORK_TYPE_ID                       = NVL(&W_WORK_TYPE_ID, DI.WORK_TYPE_ID)
	AND PM.DEPT_ID                            = NVL(&W_DEPT_ID, PM.DEPT_ID)
	AND NVL(&W_MODIFY_YN, DI.MODIFY_YN)       IN(DI.MODIFY_YN, DI.MODIFY_IN_YN, DI.MODIFY_OUT_YN)
	  
