SELECT *
  FROM HRP_TAX_STANDARD TS
 WHERE TS.START_DATE      < TO_DATE('2014-02-28', 'YYYY-MM-DD')
   AND (TS.END_DATE       > TO_DATE('2014-02-28', 'YYYY-MM-DD') OR TS.END_DATE IS NULL) 
;

-- 기간 업데이트 
UPDATE HRP_TAX_STANDARD TS
   SET TS.END_DATE        = TO_DATE('2014-01-31', 'YYYY-MM-DD')
 WHERE TS.START_DATE      <  TO_DATE('2014-02-28', 'YYYY-MM-DD')
   AND (TS.END_DATE       >  TO_DATE('2014-02-28', 'YYYY-MM-DD') OR TS.END_DATE IS NULL)
;

SELECT *
  FROM HRP_TAX_STANDARD TS
 WHERE TS.START_DATE      < TO_DATE('2014-02-28', 'YYYY-MM-DD')
   AND (TS.END_DATE       > TO_DATE('2014-02-28', 'YYYY-MM-DD') OR TS.END_DATE IS NULL)
 FOR UPDATE
;      
