SELECT PM.NAME
     , PM.REPRE_NUM
     , PM.PRSN_ADDR1 || ' ' || PM.PRSN_ADDR2 AS ADDRESS
     , CM.CORP_NAME AS CORP_NAME
     , OU.VAT_NUMBER
     , OU.CORP_ADDRESS
     , CM.TEL_NUMBER
     , CM.PRESIDENT_NAME
     , CM.LEGAL_NUMBER
     , HMP.PAY_YYYYMM_01
     , HMP.SUPPLY_AMOUNT_01
     , HMP.TAX_AMOUNT_01
     , HMP.SUPPLY_DATE_01
     , HMP.PAY_YYYYMM_02
     , HMP.SUPPLY_AMOUNT_02
     , HMP.TAX_AMOUNT_02
     , HMP.SUPPLY_DATE_02
     , HMP.PAY_YYYYMM_03
     , HMP.SUPPLY_AMOUNT_03
     , HMP.TAX_AMOUNT_03
     , HMP.SUPPLY_DATE_03
     , HMP.PAY_YYYYMM_04
     , HMP.SUPPLY_AMOUNT_04
     , HMP.TAX_AMOUNT_04
     , HMP.SUPPLY_DATE_04
     , HMP.PAY_YYYYMM_05
     , HMP.SUPPLY_AMOUNT_05
     , HMP.TAX_AMOUNT_05
     , HMP.SUPPLY_DATE_05
     , HMP.PAY_YYYYMM_06
     , HMP.SUPPLY_AMOUNT_06
     , HMP.TAX_AMOUNT_06
     , HMP.SUPPLY_DATE_06
     , HMP.PAY_YYYYMM_07
     , HMP.SUPPLY_AMOUNT_07
     , HMP.TAX_AMOUNT_07
     , HMP.SUPPLY_DATE_07
     , HMP.PAY_YYYYMM_08
     , HMP.SUPPLY_AMOUNT_08
     , HMP.TAX_AMOUNT_08
     , HMP.SUPPLY_DATE_08
     , HMP.PAY_YYYYMM_09
     , HMP.SUPPLY_AMOUNT_09
     , HMP.TAX_AMOUNT_09
     , HMP.SUPPLY_DATE_09
     , HMP.PAY_YYYYMM_10
     , HMP.SUPPLY_AMOUNT_10
     , HMP.TAX_AMOUNT_10
     , HMP.SUPPLY_DATE_10
     , HMP.PAY_YYYYMM_11
     , HMP.SUPPLY_AMOUNT_11
     , HMP.TAX_AMOUNT_11
     , HMP.SUPPLY_DATE_11
     , HMP.PAY_YYYYMM_12
     , HMP.SUPPLY_AMOUNT_12
     , HMP.TAX_AMOUNT_12
     , HMP.SUPPLY_DATE_12
  FROM HRM_PERSON_MASTER PM
    , HRM_CORP_MASTER CM
    , ( SELECT HOU.CORP_ID
             , HOU.VAT_NUMBER 
             , HOU.ADDR1 || ' ' || HOU.ADDR2 AS CORP_ADDRESS
          FROM HRM_OPERATING_UNIT HOU
        WHERE HOU.SOB_ID          = &W_SOB_ID
          AND HOU.ORG_ID          = &W_ORG_ID
          AND HOU.DEFAULT_FLAG    = 'Y'
      ) OU
    , ( SELECT MP.PERSON_ID
             , MAX(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '01', MP.PAY_YYYYMM, NULL)) AS PAY_YYYYMM_01
             , SUM(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '01', MP.TOT_SUPPLY_AMOUNT, 0)) AS SUPPLY_AMOUNT_01
             , SUM(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '01', MD.TAX_AMOUNT, 0)) AS TAX_AMOUNT_01
             , MAX(CASE
                     WHEN SUBSTR(MP.PAY_YYYYMM, 6, 2) = '01' THEN NVL(DECODE(MP.WAGE_TYPE, 'P1', MP.SUPPLY_DATE, NULL), MP.SUPPLY_DATE)
                     ELSE NULL
                   END) AS SUPPLY_DATE_01
             , MAX(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '02', MP.PAY_YYYYMM, NULL)) AS PAY_YYYYMM_02
             , SUM(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '02', MP.TOT_SUPPLY_AMOUNT, 0)) AS SUPPLY_AMOUNT_02
             , SUM(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '02', MD.TAX_AMOUNT, 0)) AS TAX_AMOUNT_02
             , MAX(CASE
                     WHEN SUBSTR(MP.PAY_YYYYMM, 6, 2) = '02' THEN NVL(DECODE(MP.WAGE_TYPE, 'P1', MP.SUPPLY_DATE, NULL), MP.SUPPLY_DATE)
                     ELSE NULL
                   END) AS SUPPLY_DATE_02
             , MAX(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '03', MP.PAY_YYYYMM, NULL)) AS PAY_YYYYMM_03
             , SUM(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '03', MP.TOT_SUPPLY_AMOUNT, 0)) AS SUPPLY_AMOUNT_03
             , SUM(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '03', MD.TAX_AMOUNT, 0)) AS TAX_AMOUNT_03
             , MAX(CASE
                     WHEN SUBSTR(MP.PAY_YYYYMM, 6, 2) = '03' THEN NVL(DECODE(MP.WAGE_TYPE, 'P1', MP.SUPPLY_DATE, NULL), MP.SUPPLY_DATE)
                     ELSE NULL
                   END) AS SUPPLY_DATE_03
             , MAX(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '04', MP.PAY_YYYYMM, NULL)) AS PAY_YYYYMM_04
             , SUM(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '04', MP.TOT_SUPPLY_AMOUNT, 0)) AS SUPPLY_AMOUNT_04
             , SUM(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '04', MD.TAX_AMOUNT, 0)) AS TAX_AMOUNT_04
             , MAX(CASE
                     WHEN SUBSTR(MP.PAY_YYYYMM, 6, 2) = '04' THEN NVL(DECODE(MP.WAGE_TYPE, 'P1', MP.SUPPLY_DATE, NULL), MP.SUPPLY_DATE)
                     ELSE NULL
                   END) AS SUPPLY_DATE_04
             , MAX(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '05', MP.PAY_YYYYMM, NULL)) AS PAY_YYYYMM_05
             , SUM(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '05', MP.TOT_SUPPLY_AMOUNT, 0)) AS SUPPLY_AMOUNT_05
             , SUM(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '05', MD.TAX_AMOUNT, 0)) AS TAX_AMOUNT_05
             , MAX(CASE
                     WHEN SUBSTR(MP.PAY_YYYYMM, 6, 2) = '05' THEN NVL(DECODE(MP.WAGE_TYPE, 'P1', MP.SUPPLY_DATE, NULL), MP.SUPPLY_DATE)
                     ELSE NULL
                   END) AS SUPPLY_DATE_05
             , MAX(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '06', MP.PAY_YYYYMM, NULL)) AS PAY_YYYYMM_06
             , SUM(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '06', MP.TOT_SUPPLY_AMOUNT, 0)) AS SUPPLY_AMOUNT_06
             , SUM(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '06', MD.TAX_AMOUNT, 0)) AS TAX_AMOUNT_06
             , MAX(CASE
                     WHEN SUBSTR(MP.PAY_YYYYMM, 6, 2) = '06' THEN NVL(DECODE(MP.WAGE_TYPE, 'P1', MP.SUPPLY_DATE, NULL), MP.SUPPLY_DATE)
                     ELSE NULL
                   END) AS SUPPLY_DATE_06
             , MAX(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '07', MP.PAY_YYYYMM, NULL)) AS PAY_YYYYMM_07
             , SUM(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '07', MP.TOT_SUPPLY_AMOUNT, 0)) AS SUPPLY_AMOUNT_07
             , SUM(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '07', MD.TAX_AMOUNT, 0)) AS TAX_AMOUNT_07
             , MAX(CASE
                     WHEN SUBSTR(MP.PAY_YYYYMM, 6, 2) = '07' THEN NVL(DECODE(MP.WAGE_TYPE, 'P1', MP.SUPPLY_DATE, NULL), MP.SUPPLY_DATE)
                     ELSE NULL
                   END) AS SUPPLY_DATE_07
             , MAX(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '08', MP.PAY_YYYYMM, NULL)) AS PAY_YYYYMM_08
             , SUM(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '08', MP.TOT_SUPPLY_AMOUNT, 0)) AS SUPPLY_AMOUNT_08
             , SUM(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '08', MD.TAX_AMOUNT, 0)) AS TAX_AMOUNT_08
             , MAX(CASE
                     WHEN SUBSTR(MP.PAY_YYYYMM, 6, 2) = '08' THEN NVL(DECODE(MP.WAGE_TYPE, 'P1', MP.SUPPLY_DATE, NULL), MP.SUPPLY_DATE)
                     ELSE NULL
                   END) AS SUPPLY_DATE_08
                   
             , MAX(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '09', MP.PAY_YYYYMM, NULL)) AS PAY_YYYYMM_09
             , SUM(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '09', MP.TOT_SUPPLY_AMOUNT, 0)) AS SUPPLY_AMOUNT_09
             , SUM(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '09', MD.TAX_AMOUNT, 0)) AS TAX_AMOUNT_09
             , MAX(CASE
                     WHEN SUBSTR(MP.PAY_YYYYMM, 6, 2) = '09' THEN NVL(DECODE(MP.WAGE_TYPE, 'P1', MP.SUPPLY_DATE, NULL), MP.SUPPLY_DATE)
                     ELSE NULL
                   END) AS SUPPLY_DATE_09
             , MAX(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '10', MP.PAY_YYYYMM, NULL)) AS PAY_YYYYMM_10
             , SUM(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '10', MP.TOT_SUPPLY_AMOUNT, 0)) AS SUPPLY_AMOUNT_10
             , SUM(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '10', MD.TAX_AMOUNT, 0)) AS TAX_AMOUNT_10
             , MAX(CASE
                     WHEN SUBSTR(MP.PAY_YYYYMM, 6, 2) = '10' THEN NVL(DECODE(MP.WAGE_TYPE, 'P1', MP.SUPPLY_DATE, NULL), MP.SUPPLY_DATE)
                     ELSE NULL
                   END) AS SUPPLY_DATE_10
             , MAX(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '11', MP.PAY_YYYYMM, NULL)) AS PAY_YYYYMM_11
             , SUM(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '11', MP.TOT_SUPPLY_AMOUNT, 0)) AS SUPPLY_AMOUNT_11
             , SUM(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '11', MD.TAX_AMOUNT, 0)) AS TAX_AMOUNT_11
             , MAX(CASE
                     WHEN SUBSTR(MP.PAY_YYYYMM, 6, 2) = '11' THEN NVL(DECODE(MP.WAGE_TYPE, 'P1', MP.SUPPLY_DATE, NULL), MP.SUPPLY_DATE)
                     ELSE NULL
                   END) AS SUPPLY_DATE_11
             , MAX(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '12', MP.PAY_YYYYMM, NULL)) AS PAY_YYYYMM_12
             , SUM(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '12', MP.TOT_SUPPLY_AMOUNT, 0)) AS SUPPLY_AMOUNT_12
             , SUM(DECODE(SUBSTR(MP.PAY_YYYYMM, 6, 2), '12', MD.TAX_AMOUNT, 0)) AS TAX_AMOUNT_12
             , MAX(CASE
                     WHEN SUBSTR(MP.PAY_YYYYMM, 6, 2) = '12' THEN NVL(DECODE(MP.WAGE_TYPE, 'P1', MP.SUPPLY_DATE, NULL), MP.SUPPLY_DATE)
                     ELSE NULL
                   END) AS SUPPLY_DATE_12
          FROM HRP_MONTH_PAYMENT MP
            , ( SELECT HMD.MONTH_PAYMENT_ID
                     , SUM(HMD.DEDUCTION_AMOUNT) AS TAX_AMOUNT
                  FROM HRP_MONTH_DEDUCTION HMD
                    , HRM_DEDUCTION_V HD
                WHERE HMD.DEDUCTION_ID  = HD.DEDUCTION_ID
                  AND HMD.PAY_YYYYMM    BETWEEN &W_PAY_YYYYMM_FR AND &W_PAY_YYYYMM_TO
                  AND HMD.PERSON_ID     = &W_PERSON_ID
                  AND HMD.SOB_ID        = &W_SOB_ID
                  AND HMD.ORG_ID        = &W_ORG_ID
                  AND HD.DEDUCTION_CODE = 'D01'
                GROUP BY HMD.MONTH_PAYMENT_ID
              ) MD
        WHERE MP.MONTH_PAYMENT_ID       = MD.MONTH_PAYMENT_ID(+)
          AND MP.PAY_YYYYMM             BETWEEN &W_PAY_YYYYMM_FR AND &W_PAY_YYYYMM_TO
          AND MP.PERSON_ID              = &W_PERSON_ID
          AND MP.SOB_ID                 = &W_SOB_ID
          AND MP.ORG_ID                 = &W_ORG_ID
        GROUP BY MP.PERSON_ID
        ) HMP
WHERE PM.CORP_ID                = CM.CORP_ID
  AND CM.CORP_ID                = OU.CORP_ID(+)
  AND PM.PERSON_ID              = HMP.PERSON_ID(+)
  AND PM.PERSON_ID              = &W_PERSON_ID

;
