SELECT PM.PERSON_ID
    , PM.PERSON_NUM
    , PM.NAME 
    , PM.NAME1 
    , PM.NAME2 
    , PM.CORP_ID
    , CM.CORP_NAME
    , PM.OPERATING_UNIT_ID
    , OU.OPERATING_UNIT_NAME 
    , PM.DEPT_ID
    , DM.DEPT_CODE
    , DM.DEPT_NAME
    , PM.NATION_ID 
    , HRM_COMMON_G.ID_NAME_F(PM.NATION_ID) NATION_NAME
    , PM.WORK_AREA_ID 
    , HRM_COMMON_G.ID_NAME_F(PM.WORK_AREA_ID) WORK_AREA_NAME
    , PM.WORK_TYPE_ID
    , HRM_COMMON_G.ID_NAME_F(PM.WORK_TYPE_ID) WORK_TYPE_NAME
    , PM.JOB_CLASS_ID
    , HRM_COMMON_G.ID_NAME_F(PM.JOB_CLASS_ID) JOB_CLASS_NAME
    , PM.JOB_ID
    , HRM_COMMON_G.ID_NAME_F(PM.JOB_ID) JOB_NAME
    , PM.POST_ID
    , HRM_COMMON_G.ID_NAME_F(PM.POST_ID) POST_NAME
    , PM.OCPT_ID
    , HRM_COMMON_G.ID_NAME_F(PM.OCPT_ID) OCPT_NAME
    , PM.ABIL_ID
    , HRM_COMMON_G.ID_NAME_F(PM.ABIL_ID) ABIL_NAME
    , PM.PAY_GRADE_ID
    , HRM_COMMON_G.ID_NAME_F(PM.PAY_GRADE_ID) PAY_GRADE_NAME
    , PM.REPRE_NUM
    , PM.SEX_TYPE
    , HRM_COMMON_G.CODE_NAME_F('SEX_TYPE', PM.SEX_TYPE, PM.SOB_ID, PM.ORG_ID) SEX_NAME
    , PM.BIRTHDAY
    , NVL(PM.BIRTHDAY_TYPE, 'N')BIRTHDAY_TYPE
    , HRM_COMMON_G.CODE_NAME_F('BIRTHDAY_TYPE', PM.BIRTHDAY_TYPE, PM.SOB_ID, PM.ORG_ID) BIRTHDAY_TYPE_NAME
    , PM.MARRY_YN
    , PM.MARRY_DATE
    , PM.JOIN_ID
    , HRM_COMMON_G.ID_NAME_F(PM.JOIN_ID) JOIN_NAME
    , PM.JOIN_ROUTE_ID
    , HRM_COMMON_G.ID_NAME_F(PM.JOIN_ROUTE_ID) JOIN_ROUTE_NAME
    , PM.ORI_JOIN_DATE
    , PM.JOIN_DATE
    , PM.PAY_DATE
    , PM.DEPT_DATE
    , PM.OFFICIALLY_DATE
    , PM.SHO_DATE
    , PM.EXPIRE_DATE
    , PM.PROMOTION_EXPECT_DATE
    , PM.RETIRE_DATE
    , PM.RETIRE_ID
    , HRM_COMMON_G.ID_NAME_F(PM.RETIRE_ID) RETIRE_NAME
    , PM.DIR_INDIR_TYPE
    , HRM_COMMON_G.CODE_NAME_F('DIR_INDIR_TYPE', PM.DIR_INDIR_TYPE, PM.SOB_ID, PM.ORG_ID) DIR_INDIR_TYPE_NAME
    , PM.EMPLOYE_TYPE
    , HRM_COMMON_G.CODE_NAME_F('EMPLOYE_TYPE', PM.EMPLOYE_TYPE, PM.SOB_ID, PM.ORG_ID) EMPLOYE_TYPE_NAME
    , PM.LEGAL_ZIP_CODE
    , PM.LEGAL_ADDR1
    , PM.LEGAL_ADDR2
    , PM.PRSN_ZIP_CODE
    , PM.PRSN_ADDR1
    , PM.PRSN_ADDR2
    , PM.LIVE_ZIP_CODE
    , PM.LIVE_ADDR1
    , PM.LIVE_ADDR2
    , PM.TELEPHON_NO
    , PM.HP_PHONE_NO
    , PM.EMAIL
    , PM.RELIGION_ID
    , HRM_COMMON_G.ID_NAME_F(PM.RELIGION_ID) RELIGION_NAME
    , PM.END_SCH_ID
    , HRM_COMMON_G.ID_NAME_F(PM.END_SCH_ID) END_SCH_NAME
    , PM.HOBBY
    , PM.TALENT
    , PM.JOB_CATEGORY_ID
    , HRM_COMMON_G.ID_NAME_F(PM.JOB_CATEGORY_ID) JOB_CATEGORY_NAME
    , PM.FLOOR_ID
    , HRM_COMMON_G.ID_NAME_F(PM.FLOOR_ID) FLOOR_NAME
    , PM.COST_CENTER_ID
    , HRM_COMMON_G.COST_CENTER_DESC_F(PM.COST_CENTER_ID) AS COST_CENTER
    , PM.IC_CARD_NO
    , PM.OLD_PERSON_NUM
    , PM.CORP_TYPE
    , PM.DESCRIPTION
    , PM.LAST_UPDATE_DATE
    , PM.LAST_UPDATED_BY
FROM HRM_PERSON_MASTER PM
  , HRM_CORP_MASTER CM
  , HRM_OPERATING_UNIT OU
  , HRM_DEPT_MASTER DM
WHERE PM.CORP_ID                                    = CM.CORP_ID  
  AND PM.OPERATING_UNIT_ID                          = OU.OPERATING_UNIT_ID(+)
  AND PM.DEPT_ID                                    = DM.DEPT_ID
  AND PM.CORP_ID                                    = NVL(&W_CORP_ID, PM.CORP_ID)
  AND PM.DEPT_ID                                    = NVL(&W_DEPT_ID, PM.DEPT_ID)
  AND PM.NAME                                       LIKE &W_NAME || '%'
  AND PM.EMPLOYE_TYPE                               = NVL(&W_EMPLOYE_TYPE, PM.EMPLOYE_TYPE)
  AND PM.SOB_ID                                     = &W_SOB_ID
  AND PM.ORG_ID                                     = &W_ORG_ID
  AND (PM.RETIRE_DATE IS NULL OR PM.RETIRE_DATE     >= LAST_DAY(&W_STD_DATE))
ORDER BY PM.PERSON_NUM, PM.NAME
;
