SELECT WOO.WORKCENTER_DESCRIPTION
     , WOO.OP_TYPE_DESCRIPTION
     , WOO.OPERATION_SEQ_NO
     , CASE
         WHEN GROUPING(WOO.WORKCENTER_DESCRIPTION) = 1 THEN '총합계'
         WHEN GROUPING(WOO.OPERATION_DESCRIPTION) = 1 THEN WOO.WORKCENTER_DESCRIPTION || ' 작업장소계'
         WHEN GROUPING(WOO.BOM_ITEM_CODE) = 1 THEN '공정소계'
         ELSE WOO.OPERATION_DESCRIPTION
       END AS OPERATION_DESCRIPTION
     , WOO.DESCRIPTION
     , WOO.BOM_ITEM_CODE AS ITEM_CODE
     , WOO.BOM_ITEM_DESCRIPTION AS ITEM_DESC
     , WOO.WORKING_SIZE
     , WOO.STORE_LOCATION
     , WOO.JOB_NO
     , WOO.ITEM_UOM_CODE
     , SUM(WOO.TOTAL_ONHAND_QTY) AS TOTAL_ONHAND_QTY
     , WOO.MTX_UOM_CODE
     , SUM(WOO.FACTOR_VALUE1) AS FACTOR_VALUE1
     , SUM(WOO.MTX_UOM_QTY1) AS MTX_UOM_QTY1
     , SUM(WOO.ACTUAL_ONHAND_QTY1) AS ACTUAL_ONHAND_QTY1
     , SUM(WOO.FACTOR_VALUE2) AS FACTOR_VALUE2
     , SUM(WOO.MTX_UOM_QTY2) AS MTX_UOM_QTY2
     , SUM(WOO.ACTUAL_ONHAND_QTY2) AS ACTUAL_ONHAND_QTY2
     , CASE
         WHEN GROUPING(WOO.WORKCENTER_DESCRIPTION) = 1 THEN 'T'
         WHEN GROUPING(WOO.OPERATION_DESCRIPTION) = 1 THEN 'W'
         WHEN GROUPING(WOO.BOM_ITEM_CODE) = 1 THEN 'O'
         ELSE 'L'
       END AS LINE_TYPE
  FROM WIP_OPERATION_ONHAND_V1 WOO
WHERE WOO.SOB_ID                  = &W_SOB_ID
  AND WOO.ORG_ID                  = &W_ORG_ID
GROUP BY ROLLUP((WOO.WORKCENTER_DESCRIPTION)
     , (WOO.OPERATION_DESCRIPTION)
     , (WOO.OPERATION_SEQ_NO
     , WOO.OP_TYPE_DESCRIPTION
     , WOO.DESCRIPTION
     , WOO.BOM_ITEM_CODE 
     , WOO.BOM_ITEM_DESCRIPTION 
     , WOO.WORKING_SIZE
     , WOO.STORE_LOCATION
     , WOO.JOB_NO
     , WOO.ITEM_UOM_CODE
     , WOO.MTX_UOM_CODE))
HAVING GROUPING(WOO.WORKCENTER_DESCRIPTION) <> 1
;
