-- 원자재 현장창고 재고실사 : PAGE SKIP => 창고코드 
SELECT CASE
         WHEN GROUPING (FWO.WAREHOUSE_CODE) = 1 THEN TO_CHAR(NULL)
         WHEN GROUPING (FWO.ITEM_CODE) = 1 THEN TO_CHAR(NULL)
         ELSE FWO.WAREHOUSE_NAME 
       END AS WAREHOUSE_NAME  -- 창고명
     , FWO.CATEGORY_DESC -- 범주
     , FWO.SUMMARY_GROUP --중분류
     , FWO.DESCRIPTION -- 소분류
     , FWO.ITEM_CODE -- 품목코드
     , CASE
         WHEN GROUPING (FWO.WAREHOUSE_CODE) = 1 THEN EAPP_MESSAGE_G.RETURN_TEXT_F(USERENV_G.GET_TERRITORY_S_F, 'EAPP_10062', NULL)
         WHEN GROUPING (FWO.ITEM_CODE) = 1 THEN FWO.WAREHOUSE_NAME || ' '|| EAPP_MESSAGE_G.RETURN_TEXT_F(USERENV_G.GET_TERRITORY_S_F, 'EAPP_10063', NULL)
         ELSE FWO.ITEM_DESCRIPTION 
       END AS ITEM_DESCRIPTION-- 품목명
     , FWO.MAKER_CODE -- 제조사코드
     , FWO.MAKER_DESCRIPTION -- 제조사명
     , FWO.UOM_CODE -- 단위
     , SUM(FWO.PRIMARY_QTY) AS PRIMARY_QTY -- 정상재고량
     , NULL AS ACTUAL_PRIMARY_QTY -- 실사량(정상)
     , SUM(FWO.OVER_STOCK_QTY) AS OVER_STOCK_QTY -- 과출재고량
     , NULL AS ACTUAL_OVER_QTY -- 실사량(과출고)
     , SUM(FWO.ONHAND_QTY) AS ONHAND_QTY  -- 재고량
     , NULL AS ACTUAL_QTY -- 실사량
     , FWO.WAREHOUSE_CODE -- 창고코드
  FROM INV_FIELD_WAREHOUSE_ONHAND_V2 FWO
WHERE FWO.SOB_ID                  = &W_SOB_ID
  AND FWO.ORG_ID                  = &W_ORG_ID
  AND FWO.WAREHOUSE_CODE          = NVL(&W_WAREHOUSE_CODE, FWO.WAREHOUSE_CODE)
GROUP BY ROLLUP((FWO.WAREHOUSE_CODE
     , FWO.WAREHOUSE_NAME)
     , (FWO.ENTRY_CODE
     , FWO.MAKER_CODE
     , FWO.ITEM_CODE
     , FWO.DESCRIPTION
     , FWO.CATEGORY_DESC
     , FWO.SUMMARY_GROUP
     , FWO.ITEM_DESCRIPTION
     , FWO.MAKER_DESCRIPTION
     , FWO.UOM_CODE))
HAVING GROUPING (FWO.WAREHOUSE_CODE) <> 1
;  
